# Top-level configuration
"$schema" = "../../node_modules/wrangler/config-schema.json"
name = "viberatr"
main = "./.output/server/index.mjs"
compatibility_date = "2025-07-01"
compatibility_flags = [ "nodejs_compat" ]

# TanStack Start static assets
[assets]
directory = "./.output/public"

[observability]
enabled = true

# Build configuration for optimized output
[build]
command = "bun run build"

# Enable automatic compression for responses
# Cloudflare automatically compresses certain content types
# This works in conjunction with our worker-compression middleware
[browser]
cache_control = "public, max-age=31536000, immutable"

# Production Environment
[env.production]
name = "viberatr-production-frontend"
# Secrets should be set via `npx wrangler secret put --env production`

# Development Environment
[env.development]
name = "viberatr-development-frontend"
# Secrets should be set via `npx wrangler secret put --env development`
