# Top-level configuration
# Note: The actual worker name is set dynamically during deployment
# based on the APP_NAME environment variable
"$schema" = "../../node_modules/wrangler/config-schema.json"
name = "vibechecc"
main = "./.output/server/index.mjs"
compatibility_date = "2025-07-01"
compatibility_flags = [ "nodejs_compat", "nodejs_compat_populate_process_env" ]

# TanStack Start static assets
[assets]
directory = "./.output/public"

[observability]
enabled = true

# Compiled during CI/CD, uncomment for local builds 

# Production Environment
# [env.production]
# name = "vibechecc-production-web"
# Secrets should be set via `npx wrangler secret put --env production`

# Production Alt Environment (for A/B testing name)
# [env.production-alt]
# name = "vibechecc-alt-production-alt-web"
# Secrets should be set via `npx wrangler secret put --env production-alt`

# Development Environment
# [env.development]
# name = "vibechecc-development-web"
# Secrets should be set via `npx wrangler secret put --env development`
