# Top-level configuration
main = "./dist/server/index.mjs"
compatibility_date = "2024-01-01"
nodejs_compat = true

[site]
bucket = "./dist/client"

# Production Environment
[env.production]
name = "vibechecc-production"
# Secrets should be set via `npx wrangler secret put --env production`

# Development Environment
[env.development]
name = "vibechecc-development"
# Secrets should be set via `npx wrangler secret put --env development`
