/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VibesIndexRouteImport } from './routes/vibes/index'
import { Route as VibesMyVibesRouteImport } from './routes/vibes/my-vibes'
import { Route as VibesCreateRouteImport } from './routes/vibes/create'
import { Route as VibesVibeIdRouteImport } from './routes/vibes/$vibeId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VibesIndexRoute = VibesIndexRouteImport.update({
  id: '/vibes/',
  path: '/vibes/',
  getParentRoute: () => rootRouteImport,
} as any)
const VibesMyVibesRoute = VibesMyVibesRouteImport.update({
  id: '/vibes/my-vibes',
  path: '/vibes/my-vibes',
  getParentRoute: () => rootRouteImport,
} as any)
const VibesCreateRoute = VibesCreateRouteImport.update({
  id: '/vibes/create',
  path: '/vibes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const VibesVibeIdRoute = VibesVibeIdRouteImport.update({
  id: '/vibes/$vibeId',
  path: '/vibes/$vibeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/vibes/$vibeId': typeof VibesVibeIdRoute
  '/vibes/create': typeof VibesCreateRoute
  '/vibes/my-vibes': typeof VibesMyVibesRoute
  '/vibes': typeof VibesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/vibes/$vibeId': typeof VibesVibeIdRoute
  '/vibes/create': typeof VibesCreateRoute
  '/vibes/my-vibes': typeof VibesMyVibesRoute
  '/vibes': typeof VibesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/vibes/$vibeId': typeof VibesVibeIdRoute
  '/vibes/create': typeof VibesCreateRoute
  '/vibes/my-vibes': typeof VibesMyVibesRoute
  '/vibes/': typeof VibesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/vibes/$vibeId'
    | '/vibes/create'
    | '/vibes/my-vibes'
    | '/vibes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/vibes/$vibeId'
    | '/vibes/create'
    | '/vibes/my-vibes'
    | '/vibes'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/vibes/$vibeId'
    | '/vibes/create'
    | '/vibes/my-vibes'
    | '/vibes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  VibesVibeIdRoute: typeof VibesVibeIdRoute
  VibesCreateRoute: typeof VibesCreateRoute
  VibesMyVibesRoute: typeof VibesMyVibesRoute
  VibesIndexRoute: typeof VibesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vibes/': {
      id: '/vibes/'
      path: '/vibes'
      fullPath: '/vibes'
      preLoaderRoute: typeof VibesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vibes/my-vibes': {
      id: '/vibes/my-vibes'
      path: '/vibes/my-vibes'
      fullPath: '/vibes/my-vibes'
      preLoaderRoute: typeof VibesMyVibesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vibes/create': {
      id: '/vibes/create'
      path: '/vibes/create'
      fullPath: '/vibes/create'
      preLoaderRoute: typeof VibesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vibes/$vibeId': {
      id: '/vibes/$vibeId'
      path: '/vibes/$vibeId'
      fullPath: '/vibes/$vibeId'
      preLoaderRoute: typeof VibesVibeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  VibesVibeIdRoute: VibesVibeIdRoute,
  VibesCreateRoute: VibesCreateRoute,
  VibesMyVibesRoute: VibesMyVibesRoute,
  VibesIndexRoute: VibesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
