/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as IndexImport } from './routes/index'
import { Route as VibesIndexImport } from './routes/vibes/index'
import { Route as VibesMyVibesImport } from './routes/vibes/my-vibes'
import { Route as VibesCreateImport } from './routes/vibes/create'
import { Route as VibesVibeIdImport } from './routes/vibes/$vibeId'
import { Route as BoardsBoardIdImport } from './routes/boards.$boardId'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VibesIndexRoute = VibesIndexImport.update({
  id: '/vibes/',
  path: '/vibes/',
  getParentRoute: () => rootRoute,
} as any)

const VibesMyVibesRoute = VibesMyVibesImport.update({
  id: '/vibes/my-vibes',
  path: '/vibes/my-vibes',
  getParentRoute: () => rootRoute,
} as any)

const VibesCreateRoute = VibesCreateImport.update({
  id: '/vibes/create',
  path: '/vibes/create',
  getParentRoute: () => rootRoute,
} as any)

const VibesVibeIdRoute = VibesVibeIdImport.update({
  id: '/vibes/$vibeId',
  path: '/vibes/$vibeId',
  getParentRoute: () => rootRoute,
} as any)

const BoardsBoardIdRoute = BoardsBoardIdImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdImport
      parentRoute: typeof rootRoute
    }
    '/vibes/$vibeId': {
      id: '/vibes/$vibeId'
      path: '/vibes/$vibeId'
      fullPath: '/vibes/$vibeId'
      preLoaderRoute: typeof VibesVibeIdImport
      parentRoute: typeof rootRoute
    }
    '/vibes/create': {
      id: '/vibes/create'
      path: '/vibes/create'
      fullPath: '/vibes/create'
      preLoaderRoute: typeof VibesCreateImport
      parentRoute: typeof rootRoute
    }
    '/vibes/my-vibes': {
      id: '/vibes/my-vibes'
      path: '/vibes/my-vibes'
      fullPath: '/vibes/my-vibes'
      preLoaderRoute: typeof VibesMyVibesImport
      parentRoute: typeof rootRoute
    }
    '/vibes/': {
      id: '/vibes/'
      path: '/vibes'
      fullPath: '/vibes'
      preLoaderRoute: typeof VibesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/vibes/$vibeId': typeof VibesVibeIdRoute
  '/vibes/create': typeof VibesCreateRoute
  '/vibes/my-vibes': typeof VibesMyVibesRoute
  '/vibes': typeof VibesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/vibes/$vibeId': typeof VibesVibeIdRoute
  '/vibes/create': typeof VibesCreateRoute
  '/vibes/my-vibes': typeof VibesMyVibesRoute
  '/vibes': typeof VibesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/vibes/$vibeId': typeof VibesVibeIdRoute
  '/vibes/create': typeof VibesCreateRoute
  '/vibes/my-vibes': typeof VibesMyVibesRoute
  '/vibes/': typeof VibesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/boards/$boardId'
    | '/vibes/$vibeId'
    | '/vibes/create'
    | '/vibes/my-vibes'
    | '/vibes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/boards/$boardId'
    | '/vibes/$vibeId'
    | '/vibes/create'
    | '/vibes/my-vibes'
    | '/vibes'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/boards/$boardId'
    | '/vibes/$vibeId'
    | '/vibes/create'
    | '/vibes/my-vibes'
    | '/vibes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
  VibesVibeIdRoute: typeof VibesVibeIdRoute
  VibesCreateRoute: typeof VibesCreateRoute
  VibesMyVibesRoute: typeof VibesMyVibesRoute
  VibesIndexRoute: typeof VibesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  BoardsBoardIdRoute: BoardsBoardIdRoute,
  VibesVibeIdRoute: VibesVibeIdRoute,
  VibesCreateRoute: VibesCreateRoute,
  VibesMyVibesRoute: VibesMyVibesRoute,
  VibesIndexRoute: VibesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profile",
        "/boards/$boardId",
        "/vibes/$vibeId",
        "/vibes/create",
        "/vibes/my-vibes",
        "/vibes/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/boards/$boardId": {
      "filePath": "boards.$boardId.tsx"
    },
    "/vibes/$vibeId": {
      "filePath": "vibes/$vibeId.tsx"
    },
    "/vibes/create": {
      "filePath": "vibes/create.tsx"
    },
    "/vibes/my-vibes": {
      "filePath": "vibes/my-vibes.tsx"
    },
    "/vibes/": {
      "filePath": "vibes/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
