import type { Emoji } from '../../schema';

// Generated from OpenMoji dataset - 85 emojis
// Unicode versions up to 15.1 + OpenMoji extras
export const activitiesEmojisAll: Emoji[] = [
  {
    emoji: '🎃',
    name: 'jack-o-lantern',
    keywords: ['celebration', 'halloween', 'jack', 'lantern', 'pumpkin'],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F383',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎄',
    name: 'christmas tree',
    keywords: ['celebration', 'christmas', 'tree'],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F384',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎆',
    name: 'fireworks',
    keywords: ['boom', 'celebration', 'entertainment', 'yolo'],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F386',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎇',
    name: 'sparkler',
    keywords: ['boom', 'celebration', 'fireworks', 'sparkle'],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F387',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🧨',
    name: 'firecracker',
    keywords: [
      'dynamite',
      'explosive',
      'fire',
      'fireworks',
      'light',
      'pop',
      'popping',
      'spark',
    ],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F9E8',
    version: '11',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '✨️',
    name: 'sparkles',
    keywords: ['*', 'magic', 'sparkle', 'star'],
    category: 'activities',
    subcategory: 'event',
    unicode: '2728',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎈',
    name: 'balloon',
    keywords: ['birthday', 'celebrate', 'celebration'],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F388',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎉',
    name: 'party popper',
    keywords: [
      'awesome',
      'birthday',
      'celebrate',
      'celebration',
      'excited',
      'hooray',
      'party',
      'popper',
      'tada',
      'woohoo',
    ],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F389',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎊',
    name: 'confetti ball',
    keywords: [
      'ball',
      'celebrate',
      'celebration',
      'confetti',
      'party',
      'woohoo',
    ],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F38A',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎋',
    name: 'tanabata tree',
    keywords: ['banner', 'celebration', 'japanese', 'tanabata', 'tree'],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F38B',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎍',
    name: 'pine decoration',
    keywords: [
      'bamboo',
      'celebration',
      'decoration',
      'japanese',
      'pine',
      'plant',
    ],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F38D',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎎',
    name: 'japanese dolls',
    keywords: ['celebration', 'doll', 'dolls', 'festival', 'japanese'],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F38E',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎏',
    name: 'carp streamer',
    keywords: ['carp', 'celebration', 'streamer'],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F38F',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎐',
    name: 'wind chime',
    keywords: ['bell', 'celebration', 'chime', 'wind'],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F390',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎑',
    name: 'moon viewing ceremony',
    keywords: ['celebration', 'ceremony', 'moon', 'viewing'],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F391',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🧧',
    name: 'red envelope',
    keywords: [
      'envelope',
      'gift',
      'good',
      'hóngbāo',
      'lai',
      'luck',
      'money',
      'red',
      'see',
    ],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F9E7',
    version: '11',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎀',
    name: 'ribbon',
    keywords: ['celebration'],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F380',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎁',
    name: 'wrapped gift',
    keywords: [
      'birthday',
      'bow',
      'box',
      'celebration',
      'christmas',
      'gift',
      'present',
      'surprise',
      'wrapped',
    ],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F381',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎗️',
    name: 'reminder ribbon',
    keywords: ['celebration', 'reminder', 'ribbon'],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F397',
    version: '0.7',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎟️',
    name: 'admission tickets',
    keywords: ['admission', 'ticket', 'tickets'],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F39F',
    version: '0.7',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎫',
    name: 'ticket',
    keywords: ['admission', 'stub'],
    category: 'activities',
    subcategory: 'event',
    unicode: '1F3AB',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎖️',
    name: 'military medal',
    keywords: ['award', 'celebration', 'medal', 'military'],
    category: 'activities',
    subcategory: 'award-medal',
    unicode: '1F396',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🏆️',
    name: 'trophy',
    keywords: [
      'champion',
      'champs',
      'prize',
      'slay',
      'sport',
      'victory',
      'win',
      'winning',
    ],
    category: 'activities',
    subcategory: 'award-medal',
    unicode: '1F3C6',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏅',
    name: 'sports medal',
    keywords: ['award', 'gold', 'medal', 'sports', 'winner'],
    category: 'activities',
    subcategory: 'award-medal',
    unicode: '1F3C5',
    version: '1',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥇',
    name: '1st place medal',
    keywords: ['1st', 'first', 'gold', 'medal', 'place'],
    category: 'activities',
    subcategory: 'award-medal',
    unicode: '1F947',
    version: '3',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥈',
    name: '2nd place medal',
    keywords: ['2nd', 'medal', 'place', 'second', 'silver'],
    category: 'activities',
    subcategory: 'award-medal',
    unicode: '1F948',
    version: '3',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥉',
    name: '3rd place medal',
    keywords: ['3rd', 'bronze', 'medal', 'place', 'third'],
    category: 'activities',
    subcategory: 'award-medal',
    unicode: '1F949',
    version: '3',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚽️',
    name: 'soccer ball',
    keywords: ['ball', 'football', 'futbol', 'soccer', 'sport'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '26BD',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚾️',
    name: 'baseball',
    keywords: ['ball', 'sport'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '26BE',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥎',
    name: 'softball',
    keywords: ['ball', 'glove', 'sports', 'underarm'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F94E',
    version: '11',
    color: '#FF6347',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🏀',
    name: 'basketball',
    keywords: ['ball', 'hoop', 'sport'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F3C0',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏐',
    name: 'volleyball',
    keywords: ['ball', 'game'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F3D0',
    version: '1',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏈',
    name: 'american football',
    keywords: ['american', 'ball', 'bowl', 'football', 'sport', 'super'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F3C8',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏉',
    name: 'rugby football',
    keywords: ['ball', 'football', 'rugby', 'sport'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F3C9',
    version: '1',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎾',
    name: 'tennis',
    keywords: ['ball', 'racquet', 'sport'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F3BE',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥏',
    name: 'flying disc',
    keywords: ['disc', 'flying', 'ultimate'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F94F',
    version: '11',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎳',
    name: 'bowling',
    keywords: ['ball', 'game', 'sport', 'strike'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F3B3',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏏',
    name: 'cricket game',
    keywords: ['ball', 'bat', 'cricket', 'game'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F3CF',
    version: '1',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏑',
    name: 'field hockey',
    keywords: ['ball', 'field', 'game', 'hockey', 'stick'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F3D1',
    version: '1',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏒',
    name: 'ice hockey',
    keywords: ['game', 'hockey', 'ice', 'puck', 'stick'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F3D2',
    version: '1',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥍',
    name: 'lacrosse',
    keywords: ['ball', 'goal', 'sports', 'stick'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F94D',
    version: '11',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏓',
    name: 'ping pong',
    keywords: [
      'ball',
      'bat',
      'game',
      'paddle',
      'ping',
      'pingpong',
      'pong',
      'table',
      'tennis',
    ],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F3D3',
    version: '1',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏸',
    name: 'badminton',
    keywords: ['birdie', 'game', 'racquet', 'shuttlecock'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F3F8',
    version: '1',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥊',
    name: 'boxing glove',
    keywords: ['boxing', 'glove'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F94A',
    version: '3',
    color: '#FF6347',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🥋',
    name: 'martial arts uniform',
    keywords: ['arts', 'judo', 'karate', 'martial', 'taekwondo', 'uniform'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F94B',
    version: '3',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥅',
    name: 'goal net',
    keywords: ['goal', 'net'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F945',
    version: '3',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛳️',
    name: 'flag in hole',
    keywords: ['flag', 'golf', 'hole', 'sport'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '26F3',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛸️',
    name: 'ice skate',
    keywords: ['ice', 'skate', 'skating'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '26F8',
    version: '0.7',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎣',
    name: 'fishing pole',
    keywords: ['entertainment', 'fish', 'fishing', 'pole', 'sport'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F3A3',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🤿',
    name: 'diving mask',
    keywords: ['diving', 'mask', 'scuba', 'snorkeling'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F93F',
    version: '12',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎽',
    name: 'running shirt',
    keywords: ['athletics', 'running', 'sash', 'shirt'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F3BD',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎿',
    name: 'skis',
    keywords: ['ski', 'snow', 'sport'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F3BF',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛷',
    name: 'sled',
    keywords: ['luge', 'sledge', 'sleigh', 'snow', 'toboggan'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F6F7',
    version: '5',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥌',
    name: 'curling stone',
    keywords: ['curling', 'game', 'rock', 'stone'],
    category: 'activities',
    subcategory: 'sport',
    unicode: '1F94C',
    version: '5',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎯',
    name: 'bullseye',
    keywords: [
      'bull',
      'dart',
      'direct',
      'entertainment',
      'game',
      'hit',
      'target',
    ],
    category: 'activities',
    subcategory: 'game',
    unicode: '1F3AF',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪀',
    name: 'yo-yo',
    keywords: ['fluctuate', 'toy'],
    category: 'activities',
    subcategory: 'game',
    unicode: '1FA80',
    version: '12',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪁',
    name: 'kite',
    keywords: ['fly', 'soar'],
    category: 'activities',
    subcategory: 'game',
    unicode: '1FA81',
    version: '12',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔫',
    name: 'water pistol',
    keywords: [
      'gun',
      'handgun',
      'pistol',
      'revolver',
      'tool',
      'water',
      'weapon',
    ],
    category: 'activities',
    subcategory: 'game',
    unicode: '1F52B',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎱',
    name: 'pool 8 ball',
    keywords: ['8', '8ball', 'ball', 'billiard', 'eight', 'game', 'pool'],
    category: 'activities',
    subcategory: 'game',
    unicode: '1F3B1',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔮',
    name: 'crystal ball',
    keywords: [
      'ball',
      'crystal',
      'fairy',
      'fairytale',
      'fantasy',
      'fortune',
      'future',
      'magic',
      'tale',
      'tool',
    ],
    category: 'activities',
    subcategory: 'game',
    unicode: '1F52E',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🪄',
    name: 'magic wand',
    keywords: ['magic', 'magician', 'wand', 'witch', 'wizard'],
    category: 'activities',
    subcategory: 'game',
    unicode: '1FA84',
    version: '13',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎮️',
    name: 'video game',
    keywords: ['controller', 'entertainment', 'game', 'video'],
    category: 'activities',
    subcategory: 'game',
    unicode: '1F3AE',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕹️',
    name: 'joystick',
    keywords: ['game', 'video', 'videogame'],
    category: 'activities',
    subcategory: 'game',
    unicode: '1F579',
    version: '0.7',
    color: '#9370DB',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎰',
    name: 'slot machine',
    keywords: [
      'casino',
      'gamble',
      'gambling',
      'game',
      'machine',
      'slot',
      'slots',
    ],
    category: 'activities',
    subcategory: 'game',
    unicode: '1F3B0',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎲',
    name: 'game die',
    keywords: ['dice', 'die', 'entertainment', 'game'],
    category: 'activities',
    subcategory: 'game',
    unicode: '1F3B2',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧩',
    name: 'puzzle piece',
    keywords: ['clue', 'interlocking', 'jigsaw', 'piece', 'puzzle'],
    category: 'activities',
    subcategory: 'game',
    unicode: '1F9E9',
    version: '11',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧸',
    name: 'teddy bear',
    keywords: ['bear', 'plaything', 'plush', 'stuffed', 'teddy', 'toy'],
    category: 'activities',
    subcategory: 'game',
    unicode: '1F9F8',
    version: '11',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪅',
    name: 'piñata',
    keywords: [
      'candy',
      'celebrate',
      'celebration',
      'cinco',
      'de',
      'festive',
      'mayo',
      'party',
      'pinada',
      'pinata',
    ],
    category: 'activities',
    subcategory: 'game',
    unicode: '1FA85',
    version: '13',
    color: '#9370DB',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🪩',
    name: 'mirror ball',
    keywords: ['ball', 'dance', 'disco', 'glitter', 'mirror', 'party'],
    category: 'activities',
    subcategory: 'game',
    unicode: '1FAA9',
    version: '14',
    color: '#9370DB',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🪆',
    name: 'nesting dolls',
    keywords: [
      'babooshka',
      'baboushka',
      'babushka',
      'doll',
      'dolls',
      'matryoshka',
      'nesting',
      'russia',
    ],
    category: 'activities',
    subcategory: 'game',
    unicode: '1FA86',
    version: '13',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♠️',
    name: 'spade suit',
    keywords: ['card', 'game', 'spade', 'suit'],
    category: 'activities',
    subcategory: 'game',
    unicode: '2660',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♥️',
    name: 'heart suit',
    keywords: ['card', 'emotion', 'game', 'heart', 'hearts', 'suit'],
    category: 'activities',
    subcategory: 'game',
    unicode: '2665',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'positive' as const,
  },
  {
    emoji: '♦️',
    name: 'diamond suit',
    keywords: ['card', 'diamond', 'game', 'suit'],
    category: 'activities',
    subcategory: 'game',
    unicode: '2666',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♣️',
    name: 'club suit',
    keywords: ['card', 'club', 'clubs', 'game', 'suit'],
    category: 'activities',
    subcategory: 'game',
    unicode: '2663',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♟️',
    name: 'chess pawn',
    keywords: ['chess', 'dupe', 'expendable', 'pawn'],
    category: 'activities',
    subcategory: 'game',
    unicode: '265F',
    version: '11',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🃏',
    name: 'joker',
    keywords: ['card', 'game', 'wildcard'],
    category: 'activities',
    subcategory: 'game',
    unicode: '1F0CF',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🀄️',
    name: 'mahjong red dragon',
    keywords: ['dragon', 'game', 'mahjong', 'red'],
    category: 'activities',
    subcategory: 'game',
    unicode: '1F004',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎴',
    name: 'flower playing cards',
    keywords: ['card', 'cards', 'flower', 'game', 'japanese', 'playing'],
    category: 'activities',
    subcategory: 'game',
    unicode: '1F3B4',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎭️',
    name: 'performing arts',
    keywords: [
      'actor',
      'actress',
      'art',
      'arts',
      'entertainment',
      'mask',
      'performing',
      'theater',
      'theatre',
      'thespian',
    ],
    category: 'activities',
    subcategory: 'arts-crafts',
    unicode: '1F3AD',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🖼️',
    name: 'framed picture',
    keywords: ['art', 'frame', 'framed', 'museum', 'painting', 'picture'],
    category: 'activities',
    subcategory: 'arts-crafts',
    unicode: '1F5BC',
    version: '0.7',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎨',
    name: 'artist palette',
    keywords: [
      'art',
      'artist',
      'artsy',
      'arty',
      'colorful',
      'creative',
      'entertainment',
      'museum',
      'painter',
      'painting',
      'palette',
    ],
    category: 'activities',
    subcategory: 'arts-crafts',
    unicode: '1F3A8',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧵',
    name: 'thread',
    keywords: ['needle', 'sewing', 'spool', 'string'],
    category: 'activities',
    subcategory: 'arts-crafts',
    unicode: '1F9F5',
    version: '11',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪡',
    name: 'sewing needle',
    keywords: [
      'embroidery',
      'needle',
      'sew',
      'sewing',
      'stitches',
      'sutures',
      'tailoring',
      'thread',
    ],
    category: 'activities',
    subcategory: 'arts-crafts',
    unicode: '1FAA1',
    version: '13',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧶',
    name: 'yarn',
    keywords: ['ball', 'crochet', 'knit'],
    category: 'activities',
    subcategory: 'arts-crafts',
    unicode: '1F9F6',
    version: '11',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪢',
    name: 'knot',
    keywords: ['cord', 'rope', 'tangled', 'tie', 'twine', 'twist'],
    category: 'activities',
    subcategory: 'arts-crafts',
    unicode: '1FAA2',
    version: '13',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
];
