import type { Emoji } from '../../schema';

export const activityEmojis: Omit<Emoji, 'sentiment'>[] = [
  // Sports - Ball sports
  {
    emoji: '⚽',
    name: 'soccer ball',
    keywords: ['sports', 'football', 'soccer'],
    category: 'activities',
    color: '#000000',
    tags: ['soccer', 'football', 'sports'],
  },
  {
    emoji: '🏀',
    name: 'basketball',
    keywords: ['sports', 'balls', 'basketball'],
    category: 'activities',
    color: '#FF8C00',
    tags: ['basketball', 'sports', 'nba'],
  },
  {
    emoji: '🏈',
    name: 'american football',
    keywords: ['sports', 'balls', 'football'],
    category: 'activities',
    color: '#8B4513',
    tags: ['football', 'american', 'nfl'],
  },
  {
    emoji: '⚾',
    name: 'baseball',
    keywords: ['sports', 'balls', 'baseball'],
    category: 'activities',
    color: '#F5F5F5',
    tags: ['baseball', 'sports', 'mlb'],
  },
  {
    emoji: '🥎',
    name: 'softball',
    keywords: ['sports', 'balls', 'softball'],
    category: 'activities',
    color: '#FFFF00',
    tags: ['softball', 'sports', 'ball'],
  },
  {
    emoji: '🎾',
    name: 'tennis',
    keywords: ['sports', 'balls', 'tennis'],
    category: 'activities',
    color: '#ADFF2F',
    tags: ['tennis', 'sports', 'racket'],
  },
  {
    emoji: '🏐',
    name: 'volleyball',
    keywords: ['sports', 'balls', 'volleyball'],
    category: 'activities',
    color: '#F5F5F5',
    tags: ['volleyball', 'sports', 'beach'],
  },
  {
    emoji: '🏉',
    name: 'rugby football',
    keywords: ['sports', 'team', 'rugby'],
    category: 'activities',
    color: '#8B4513',
    tags: ['rugby', 'sports', 'ball'],
  },
  {
    emoji: '🥏',
    name: 'flying disc',
    keywords: ['frisbee', 'ultimate', 'disc'],
    category: 'activities',
    color: '#4169E1',
    tags: ['frisbee', 'disc', 'ultimate'],
  },
  {
    emoji: '🎱',
    name: 'pool 8 ball',
    keywords: ['pool', 'hobby', '8ball'],
    category: 'activities',
    color: '#000000',
    tags: ['pool', 'billiards', '8ball'],
  },

  // Sports equipment
  {
    emoji: '🏓',
    name: 'ping pong',
    keywords: ['sports', 'pingpong', 'table tennis'],
    category: 'activities',
    color: '#DC143C',
    tags: ['ping-pong', 'table-tennis', 'paddle'],
  },
  {
    emoji: '🏸',
    name: 'badminton',
    keywords: ['sports', 'racquet', 'badminton'],
    category: 'activities',
    color: '#F5F5F5',
    tags: ['badminton', 'racket', 'shuttlecock'],
  },
  {
    emoji: '🏒',
    name: 'ice hockey',
    keywords: ['sports', 'hockey', 'ice'],
    category: 'activities',
    color: '#8B4513',
    tags: ['hockey', 'ice', 'stick'],
  },
  {
    emoji: '🏑',
    name: 'field hockey',
    keywords: ['sports', 'hockey', 'field'],
    category: 'activities',
    color: '#8B4513',
    tags: ['hockey', 'field', 'stick'],
  },
  {
    emoji: '🥍',
    name: 'lacrosse',
    keywords: ['sports', 'ball', 'stick'],
    category: 'activities',
    color: '#8B4513',
    tags: ['lacrosse', 'sports', 'stick'],
  },
  {
    emoji: '🏏',
    name: 'cricket game',
    keywords: ['sports', 'cricket', 'bat'],
    category: 'activities',
    color: '#8B4513',
    tags: ['cricket', 'sports', 'bat'],
  },
  {
    emoji: '🪃',
    name: 'boomerang',
    keywords: ['weapon', 'australia', 'rebound'],
    category: 'activities',
    color: '#8B4513',
    tags: ['boomerang', 'australia', 'throw'],
  },
  {
    emoji: '🥅',
    name: 'goal net',
    keywords: ['sports', 'goal', 'net'],
    category: 'activities',
    color: '#F5F5F5',
    tags: ['goal', 'net', 'sports'],
  },
  {
    emoji: '⛳',
    name: 'flag in hole',
    keywords: ['sports', 'business', 'golf'],
    category: 'activities',
    color: '#DC143C',
    tags: ['golf', 'flag', 'hole'],
  },
  {
    emoji: '🪁',
    name: 'kite',
    keywords: ['wind', 'fly', 'soar'],
    category: 'activities',
    color: '#FF69B4',
    tags: ['kite', 'flying', 'wind'],
  },

  // Winter sports
  {
    emoji: '🛷',
    name: 'sled',
    keywords: ['sledge', 'sleigh', 'luge'],
    category: 'activities',
    color: '#8B4513',
    tags: ['sled', 'winter', 'snow'],
  },
  {
    emoji: '⛸️',
    name: 'ice skate',
    keywords: ['sports', 'skating', 'ice'],
    category: 'activities',
    color: '#C0C0C0',
    tags: ['ice-skate', 'skating', 'winter'],
  },
  {
    emoji: '🎿',
    name: 'ski',
    keywords: ['sports', 'winter', 'cold'],
    category: 'activities',
    color: '#4169E1',
    tags: ['ski', 'skiing', 'winter'],
  },
  {
    emoji: '🥌',
    name: 'curling stone',
    keywords: ['sports', 'curling', 'stone'],
    category: 'activities',
    color: '#696969',
    tags: ['curling', 'ice', 'stone'],
  },

  // Target sports
  {
    emoji: '🏹',
    name: 'bow and arrow',
    keywords: ['sports', 'archery', 'bow'],
    category: 'activities',
    color: '#8B4513',
    tags: ['archery', 'bow', 'arrow'],
  },
  {
    emoji: '🎯',
    name: 'bullseye',
    keywords: ['target', 'archery', 'game'],
    category: 'activities',
    color: '#DC143C',
    tags: ['target', 'bullseye', 'darts'],
  },

  // Games
  {
    emoji: '🎮',
    name: 'video game',
    keywords: ['play', 'controller', 'console'],
    category: 'activities',
    color: '#000000',
    tags: ['gaming', 'controller', 'video-game'],
  },
  {
    emoji: '🕹️',
    name: 'joystick',
    keywords: ['game', 'play', 'arcade'],
    category: 'activities',
    color: '#DC143C',
    tags: ['joystick', 'arcade', 'gaming'],
  },
  {
    emoji: '🎲',
    name: 'game die',
    keywords: ['dice', 'random', 'tabletop'],
    category: 'activities',
    color: '#F5F5F5',
    tags: ['dice', 'game', 'chance'],
  },
  {
    emoji: '🧩',
    name: 'puzzle piece',
    keywords: ['interlocking', 'puzzle', 'piece'],
    category: 'activities',
    color: '#4169E1',
    tags: ['puzzle', 'piece', 'game'],
  },
  {
    emoji: '♟️',
    name: 'chess pawn',
    keywords: ['chess', 'expendable', 'pawn'],
    category: 'activities',
    color: '#000000',
    tags: ['chess', 'pawn', 'game'],
  },
  {
    emoji: '🎰',
    name: 'slot machine',
    keywords: ['slot', 'machine', 'gambling'],
    category: 'activities',
    color: '#FFD700',
    tags: ['slots', 'casino', 'gambling'],
  },
  {
    emoji: '🎳',
    name: 'bowling',
    keywords: ['sports', 'fun', 'bowling'],
    category: 'activities',
    color: '#F5F5F5',
    tags: ['bowling', 'pins', 'strike'],
  },

  // Arts and crafts
  {
    emoji: '🎨',
    name: 'artist palette',
    keywords: ['art', 'colors', 'paint'],
    category: 'activities',
    color: '#8B4513',
    tags: ['art', 'palette', 'painting'],
  },
  {
    emoji: '🧵',
    name: 'thread',
    keywords: ['needle', 'sewing', 'spool'],
    category: 'activities',
    color: '#DC143C',
    tags: ['thread', 'sewing', 'craft'],
  },
  {
    emoji: '🧶',
    name: 'yarn',
    keywords: ['ball', 'crochet', 'knit'],
    category: 'activities',
    color: '#FF69B4',
    tags: ['yarn', 'knitting', 'craft'],
  },
  {
    emoji: '🎭',
    name: 'performing arts',
    keywords: ['theater', 'drama', 'masks'],
    category: 'activities',
    color: '#FFD700',
    tags: ['theater', 'drama', 'masks'],
  },
  {
    emoji: '🖼️',
    name: 'framed picture',
    keywords: ['art', 'museum', 'painting'],
    category: 'activities',
    color: '#8B4513',
    tags: ['picture', 'art', 'frame'],
  },
  {
    emoji: '🎬',
    name: 'clapper board',
    keywords: ['movie', 'film', 'record'],
    category: 'activities',
    color: '#000000',
    tags: ['movie', 'film', 'action'],
  },
  {
    emoji: '🎤',
    name: 'microphone',
    keywords: ['music', 'sound', 'karaoke'],
    category: 'activities',
    color: '#C0C0C0',
    tags: ['microphone', 'singing', 'karaoke'],
  },
  {
    emoji: '🎧',
    name: 'headphone',
    keywords: ['music', 'earphones', 'headphones'],
    category: 'activities',
    color: '#000000',
    tags: ['headphones', 'music', 'audio'],
  },
  {
    emoji: '🎼',
    name: 'musical score',
    keywords: ['music', 'clef', 'compose'],
    category: 'activities',
    color: '#000000',
    tags: ['music', 'score', 'notes'],
  },
  {
    emoji: '🎵',
    name: 'musical note',
    keywords: ['music', 'note', 'tone'],
    category: 'activities',
    color: '#000000',
    tags: ['music', 'note', 'sound'],
  },
  {
    emoji: '🎶',
    name: 'musical notes',
    keywords: ['music', 'notes', 'score'],
    category: 'activities',
    color: '#000000',
    tags: ['music', 'notes', 'melody'],
  },

  // Musical instruments
  {
    emoji: '🎹',
    name: 'musical keyboard',
    keywords: ['piano', 'instrument', 'compose'],
    category: 'activities',
    color: '#000000',
    tags: ['piano', 'keyboard', 'music'],
  },
  {
    emoji: '🥁',
    name: 'drum',
    keywords: ['music', 'instrument', 'drumsticks'],
    category: 'activities',
    color: '#DC143C',
    tags: ['drum', 'percussion', 'music'],
  },
  {
    emoji: '🪘',
    name: 'long drum',
    keywords: ['beat', 'conga', 'rhythm'],
    category: 'activities',
    color: '#8B4513',
    tags: ['drum', 'conga', 'percussion'],
  },
  {
    emoji: '🎷',
    name: 'saxophone',
    keywords: ['music', 'instrument', 'jazz'],
    category: 'activities',
    color: '#FFD700',
    tags: ['saxophone', 'jazz', 'music'],
  },
  {
    emoji: '🎺',
    name: 'trumpet',
    keywords: ['music', 'brass', 'instrument'],
    category: 'activities',
    color: '#FFD700',
    tags: ['trumpet', 'brass', 'music'],
  },
  {
    emoji: '🎸',
    name: 'guitar',
    keywords: ['music', 'instrument', 'rock'],
    category: 'activities',
    color: '#8B4513',
    tags: ['guitar', 'rock', 'music'],
  },
  {
    emoji: '🪕',
    name: 'banjo',
    keywords: ['music', 'stringed', 'instrument'],
    category: 'activities',
    color: '#8B4513',
    tags: ['banjo', 'country', 'music'],
  },
  {
    emoji: '🎻',
    name: 'violin',
    keywords: ['music', 'instrument', 'orchestra'],
    category: 'activities',
    color: '#8B4513',
    tags: ['violin', 'classical', 'music'],
  },
  {
    emoji: '🪗',
    name: 'accordion',
    keywords: ['music', 'concertina', 'squeeze'],
    category: 'activities',
    color: '#DC143C',
    tags: ['accordion', 'music', 'folk'],
  },

  // Events
  {
    emoji: '🎫',
    name: 'ticket',
    keywords: ['event', 'concert', 'pass'],
    category: 'activities',
    color: '#FFD700',
    tags: ['ticket', 'event', 'admission'],
  },
  {
    emoji: '🎟️',
    name: 'admission tickets',
    keywords: ['sports', 'concert', 'ticket'],
    category: 'activities',
    color: '#DC143C',
    tags: ['tickets', 'admission', 'event'],
  },
  {
    emoji: '🎪',
    name: 'circus tent',
    keywords: ['festival', 'carnival', 'party'],
    category: 'activities',
    color: '#DC143C',
    tags: ['circus', 'tent', 'carnival'],
  },
  {
    emoji: '🤹',
    name: 'person juggling',
    keywords: ['juggle', 'balance', 'skill'],
    category: 'activities',
    color: '#FFD700',
    tags: ['juggling', 'circus', 'performance'],
  },
  {
    emoji: '🤹‍♂️',
    name: 'man juggling',
    keywords: ['juggle', 'balance', 'skill'],
    category: 'activities',
    color: '#FFD700',
    tags: ['juggling', 'man', 'circus'],
  },
  {
    emoji: '🤹‍♀️',
    name: 'woman juggling',
    keywords: ['juggle', 'balance', 'skill'],
    category: 'activities',
    color: '#FFD700',
    tags: ['juggling', 'woman', 'circus'],
  },

  // Awards and competitions
  {
    emoji: '🏆',
    name: 'trophy',
    keywords: ['award', 'contest', 'winner'],
    category: 'activities',
    color: '#FFD700',
    tags: ['trophy', 'winner', 'champion'],
  },
  {
    emoji: '🏅',
    name: 'sports medal',
    keywords: ['gold', 'winner', 'medal'],
    category: 'activities',
    color: '#FFD700',
    tags: ['medal', 'gold', 'winner'],
  },
  {
    emoji: '🥇',
    name: '1st place medal',
    keywords: ['gold', 'first', 'medal'],
    category: 'activities',
    color: '#FFD700',
    tags: ['first', 'gold', 'winner'],
  },
  {
    emoji: '🥈',
    name: '2nd place medal',
    keywords: ['silver', 'second', 'medal'],
    category: 'activities',
    color: '#C0C0C0',
    tags: ['second', 'silver', 'medal'],
  },
  {
    emoji: '🥉',
    name: '3rd place medal',
    keywords: ['bronze', 'third', 'medal'],
    category: 'activities',
    color: '#CD7F32',
    tags: ['third', 'bronze', 'medal'],
  },

  // Martial arts
  {
    emoji: '🥊',
    name: 'boxing glove',
    keywords: ['sports', 'fighting', 'boxing'],
    category: 'activities',
    color: '#DC143C',
    tags: ['boxing', 'glove', 'fighting'],
  },
  {
    emoji: '🥋',
    name: 'martial arts uniform',
    keywords: ['judo', 'karate', 'taekwondo'],
    category: 'activities',
    color: '#F5F5F5',
    tags: ['martial-arts', 'uniform', 'karate'],
  },

  // Other activities
  {
    emoji: '🎣',
    name: 'fishing pole',
    keywords: ['food', 'hobby', 'fishing'],
    category: 'activities',
    color: '#8B4513',
    tags: ['fishing', 'pole', 'hobby'],
  },
  {
    emoji: '🤿',
    name: 'diving mask',
    keywords: ['sports', 'ocean', 'scuba'],
    category: 'activities',
    color: '#4169E1',
    tags: ['diving', 'snorkel', 'mask'],
  },
  {
    emoji: '🎽',
    name: 'running shirt',
    keywords: ['sports', 'running', 'athletics'],
    category: 'activities',
    color: '#4169E1',
    tags: ['running', 'shirt', 'athletics'],
  },
  {
    emoji: '🛹',
    name: 'skateboard',
    keywords: ['board', 'skateboard', 'sport'],
    category: 'activities',
    color: '#8B4513',
    tags: ['skateboard', 'skating', 'sport'],
  },
  {
    emoji: '🛼',
    name: 'roller skate',
    keywords: ['sports', 'footwear', 'skate'],
    category: 'activities',
    color: '#FF69B4',
    tags: ['roller-skate', 'skating', 'retro'],
  },
  {
    emoji: '🪀',
    name: 'yo-yo',
    keywords: ['toy', 'fluctuate', 'yoyo'],
    category: 'activities',
    color: '#DC143C',
    tags: ['yo-yo', 'toy', 'trick'],
  },
  {
    emoji: '🪁',
    name: 'kite',
    keywords: ['wind', 'fly', 'soar'],
    category: 'activities',
    color: '#FF69B4',
    tags: ['kite', 'flying', 'wind'],
  },

  // Exercise and fitness
  {
    emoji: '🏋️',
    name: 'person lifting weights',
    keywords: ['sports', 'training', 'exercise'],
    category: 'activities',
    color: '#696969',
    tags: ['weightlifting', 'gym', 'exercise'],
  },
  {
    emoji: '🏋️‍♂️',
    name: 'man lifting weights',
    keywords: ['sports', 'training', 'exercise'],
    category: 'activities',
    color: '#696969',
    tags: ['weightlifting', 'man', 'gym'],
  },
  {
    emoji: '🏋️‍♀️',
    name: 'woman lifting weights',
    keywords: ['sports', 'training', 'exercise'],
    category: 'activities',
    color: '#696969',
    tags: ['weightlifting', 'woman', 'gym'],
  },
  {
    emoji: '🤸',
    name: 'person cartwheeling',
    keywords: ['gymnastics', 'cartwheel', 'person'],
    category: 'activities',
    color: '#FF69B4',
    tags: ['gymnastics', 'cartwheel', 'flexible'],
  },
  {
    emoji: '🤸‍♂️',
    name: 'man cartwheeling',
    keywords: ['gymnastics', 'cartwheel', 'man'],
    category: 'activities',
    color: '#87CEEB',
    tags: ['gymnastics', 'man', 'cartwheel'],
  },
  {
    emoji: '🤸‍♀️',
    name: 'woman cartwheeling',
    keywords: ['gymnastics', 'cartwheel', 'woman'],
    category: 'activities',
    color: '#FF69B4',
    tags: ['gymnastics', 'woman', 'cartwheel'],
  },
  {
    emoji: '⛹️',
    name: 'person bouncing ball',
    keywords: ['sports', 'human', 'basketball'],
    category: 'activities',
    color: '#FF8C00',
    tags: ['basketball', 'dribbling', 'sport'],
  },
  {
    emoji: '⛹️‍♂️',
    name: 'man bouncing ball',
    keywords: ['sports', 'human', 'basketball'],
    category: 'activities',
    color: '#FF8C00',
    tags: ['basketball', 'man', 'dribbling'],
  },
  {
    emoji: '⛹️‍♀️',
    name: 'woman bouncing ball',
    keywords: ['sports', 'human', 'basketball'],
    category: 'activities',
    color: '#FF8C00',
    tags: ['basketball', 'woman', 'dribbling'],
  },
  {
    emoji: '🤺',
    name: 'person fencing',
    keywords: ['sports', 'fencing', 'sword'],
    category: 'activities',
    color: '#C0C0C0',
    tags: ['fencing', 'sword', 'sport'],
  },
  {
    emoji: '🤼',
    name: 'people wrestling',
    keywords: ['sports', 'wrestling', 'wrestle'],
    category: 'activities',
    color: '#DAA520',
    tags: ['wrestling', 'sport', 'grappling'],
  },
  {
    emoji: '🤼‍♂️',
    name: 'men wrestling',
    keywords: ['sports', 'wrestling', 'men'],
    category: 'activities',
    color: '#DAA520',
    tags: ['wrestling', 'men', 'sport'],
  },
  {
    emoji: '🤼‍♀️',
    name: 'women wrestling',
    keywords: ['sports', 'wrestling', 'women'],
    category: 'activities',
    color: '#DAA520',
    tags: ['wrestling', 'women', 'sport'],
  },
  {
    emoji: '🤽',
    name: 'person playing water polo',
    keywords: ['sports', 'water', 'polo'],
    category: 'activities',
    color: '#00CED1',
    tags: ['water-polo', 'swimming', 'sport'],
  },
  {
    emoji: '🤽‍♂️',
    name: 'man playing water polo',
    keywords: ['sports', 'water', 'polo'],
    category: 'activities',
    color: '#00CED1',
    tags: ['water-polo', 'man', 'swimming'],
  },
  {
    emoji: '🤽‍♀️',
    name: 'woman playing water polo',
    keywords: ['sports', 'water', 'polo'],
    category: 'activities',
    color: '#00CED1',
    tags: ['water-polo', 'woman', 'swimming'],
  },
  {
    emoji: '🤾',
    name: 'person playing handball',
    keywords: ['sports', 'handball', 'ball'],
    category: 'activities',
    color: '#FF4500',
    tags: ['handball', 'sport', 'throwing'],
  },
  {
    emoji: '🤾‍♂️',
    name: 'man playing handball',
    keywords: ['sports', 'handball', 'man'],
    category: 'activities',
    color: '#FF4500',
    tags: ['handball', 'man', 'sport'],
  },
  {
    emoji: '🤾‍♀️',
    name: 'woman playing handball',
    keywords: ['sports', 'handball', 'woman'],
    category: 'activities',
    color: '#FF4500',
    tags: ['handball', 'woman', 'sport'],
  },
  {
    emoji: '🧘',
    name: 'person in lotus position',
    keywords: ['yoga', 'meditation', 'zen'],
    category: 'activities',
    color: '#DDA0DD',
    tags: ['yoga', 'meditation', 'lotus'],
  },
  {
    emoji: '🧘‍♂️',
    name: 'man in lotus position',
    keywords: ['yoga', 'meditation', 'man'],
    category: 'activities',
    color: '#87CEEB',
    tags: ['yoga', 'man', 'meditation'],
  },
  {
    emoji: '🧘‍♀️',
    name: 'woman in lotus position',
    keywords: ['yoga', 'meditation', 'woman'],
    category: 'activities',
    color: '#DDA0DD',
    tags: ['yoga', 'woman', 'meditation'],
  },

  // Outdoor activities
  {
    emoji: '🏕️',
    name: 'camping',
    keywords: ['photo', 'camping', 'tent'],
    category: 'activities',
    color: '#228B22',
    tags: ['camping', 'outdoors', 'tent'],
  },
  {
    emoji: '🧗',
    name: 'person climbing',
    keywords: ['sports', 'human', 'athletics'],
    category: 'activities',
    color: '#696969',
    tags: ['climbing', 'rock-climbing', 'sport'],
  },
  {
    emoji: '🧗‍♂️',
    name: 'man climbing',
    keywords: ['sports', 'human', 'athletics'],
    category: 'activities',
    color: '#696969',
    tags: ['climbing', 'man', 'rock-climbing'],
  },
  {
    emoji: '🧗‍♀️',
    name: 'woman climbing',
    keywords: ['sports', 'human', 'athletics'],
    category: 'activities',
    color: '#696969',
    tags: ['climbing', 'woman', 'rock-climbing'],
  },
  {
    emoji: '🏇',
    name: 'horse racing',
    keywords: ['animal', 'betting', 'competition'],
    category: 'activities',
    color: '#8B4513',
    tags: ['horse-racing', 'jockey', 'sport'],
  },
  {
    emoji: '🏊',
    name: 'person swimming',
    keywords: ['sports', 'exercise', 'human'],
    category: 'activities',
    color: '#00CED1',
    tags: ['swimming', 'pool', 'sport'],
  },
  {
    emoji: '🏊‍♂️',
    name: 'man swimming',
    keywords: ['sports', 'exercise', 'human'],
    category: 'activities',
    color: '#00CED1',
    tags: ['swimming', 'man', 'pool'],
  },
  {
    emoji: '🏊‍♀️',
    name: 'woman swimming',
    keywords: ['sports', 'exercise', 'human'],
    category: 'activities',
    color: '#00CED1',
    tags: ['swimming', 'woman', 'pool'],
  },
  {
    emoji: '🏄',
    name: 'person surfing',
    keywords: ['sports', 'human', 'beach'],
    category: 'activities',
    color: '#00CED1',
    tags: ['surfing', 'ocean', 'sport'],
  },
  {
    emoji: '🏄‍♂️',
    name: 'man surfing',
    keywords: ['sports', 'human', 'beach'],
    category: 'activities',
    color: '#00CED1',
    tags: ['surfing', 'man', 'ocean'],
  },
  {
    emoji: '🏄‍♀️',
    name: 'woman surfing',
    keywords: ['sports', 'human', 'beach'],
    category: 'activities',
    color: '#00CED1',
    tags: ['surfing', 'woman', 'ocean'],
  },
  {
    emoji: '🚣',
    name: 'person rowing boat',
    keywords: ['sports', 'hobby', 'water'],
    category: 'activities',
    color: '#8B4513',
    tags: ['rowing', 'boat', 'sport'],
  },
  {
    emoji: '🚣‍♂️',
    name: 'man rowing boat',
    keywords: ['sports', 'hobby', 'water'],
    category: 'activities',
    color: '#8B4513',
    tags: ['rowing', 'man', 'boat'],
  },
  {
    emoji: '🚣‍♀️',
    name: 'woman rowing boat',
    keywords: ['sports', 'hobby', 'water'],
    category: 'activities',
    color: '#8B4513',
    tags: ['rowing', 'woman', 'boat'],
  },
  {
    emoji: '🚴',
    name: 'person biking',
    keywords: ['sports', 'bike', 'exercise'],
    category: 'activities',
    color: '#4169E1',
    tags: ['cycling', 'bike', 'sport'],
  },
  {
    emoji: '🚴‍♂️',
    name: 'man biking',
    keywords: ['sports', 'bike', 'exercise'],
    category: 'activities',
    color: '#4169E1',
    tags: ['cycling', 'man', 'bike'],
  },
  {
    emoji: '🚴‍♀️',
    name: 'woman biking',
    keywords: ['sports', 'bike', 'exercise'],
    category: 'activities',
    color: '#4169E1',
    tags: ['cycling', 'woman', 'bike'],
  },
  {
    emoji: '🚵',
    name: 'person mountain biking',
    keywords: ['sports', 'human', 'race'],
    category: 'activities',
    color: '#228B22',
    tags: ['mountain-biking', 'extreme', 'sport'],
  },
  {
    emoji: '🚵‍♂️',
    name: 'man mountain biking',
    keywords: ['sports', 'human', 'race'],
    category: 'activities',
    color: '#228B22',
    tags: ['mountain-biking', 'man', 'extreme'],
  },
  {
    emoji: '🚵‍♀️',
    name: 'woman mountain biking',
    keywords: ['sports', 'human', 'race'],
    category: 'activities',
    color: '#228B22',
    tags: ['mountain-biking', 'woman', 'extreme'],
  },

  // Seasonal and celebrations
  {
    emoji: '🎃',
    name: 'jack-o-lantern',
    keywords: ['halloween', 'pumpkin', 'creepy'],
    category: 'activities',
    color: '#FF8C00',
    tags: ['halloween', 'pumpkin', 'spooky'],
  },
  {
    emoji: '🎄',
    name: 'christmas tree',
    keywords: ['festival', 'vacation', 'december'],
    category: 'activities',
    color: '#228B22',
    tags: ['christmas', 'tree', 'holiday'],
  },
  {
    emoji: '🎆',
    name: 'fireworks',
    keywords: ['photo', 'festival', 'carnival'],
    category: 'activities',
    color: '#FFD700',
    tags: ['fireworks', 'celebration', 'new-year'],
  },
  {
    emoji: '🎇',
    name: 'sparkler',
    keywords: ['stars', 'night', 'shine'],
    category: 'activities',
    color: '#FFD700',
    tags: ['sparkler', 'firework', 'celebration'],
  },
  {
    emoji: '🧨',
    name: 'firecracker',
    keywords: ['dynamite', 'boom', 'explode'],
    category: 'activities',
    color: '#DC143C',
    tags: ['firecracker', 'explosive', 'celebration'],
  },
  {
    emoji: '✨',
    name: 'sparkles',
    keywords: ['stars', 'shine', 'shiny'],
    category: 'activities',
    color: '#FFD700',
    tags: ['sparkle', 'magic', 'shiny'],
  },
  {
    emoji: '🎈',
    name: 'balloon',
    keywords: ['party', 'celebration', 'birthday'],
    category: 'activities',
    color: '#DC143C',
    tags: ['balloon', 'party', 'celebration'],
  },
  {
    emoji: '🎉',
    name: 'party popper',
    keywords: ['party', 'congratulations', 'birthday'],
    category: 'activities',
    color: '#FFD700',
    tags: ['party', 'celebration', 'confetti'],
  },
  {
    emoji: '🎊',
    name: 'confetti ball',
    keywords: ['festival', 'party', 'birthday'],
    category: 'activities',
    color: '#FF69B4',
    tags: ['confetti', 'party', 'celebration'],
  },
  {
    emoji: '🎋',
    name: 'tanabata tree',
    keywords: ['plant', 'nature', 'branch'],
    category: 'activities',
    color: '#228B22',
    tags: ['tanabata', 'japanese', 'wish'],
  },
  {
    emoji: '🎍',
    name: 'pine decoration',
    keywords: ['festival', 'plant', 'nature'],
    category: 'activities',
    color: '#228B22',
    tags: ['decoration', 'japanese', 'new-year'],
  },
  {
    emoji: '🎎',
    name: 'japanese dolls',
    keywords: ['japanese', 'toy', 'kimono'],
    category: 'activities',
    color: '#DC143C',
    tags: ['dolls', 'japanese', 'festival'],
  },
  {
    emoji: '🎏',
    name: 'carp streamer',
    keywords: ['fish', 'japanese', 'koinobori'],
    category: 'activities',
    color: '#4169E1',
    tags: ['koinobori', 'japanese', 'festival'],
  },
  {
    emoji: '🎐',
    name: 'wind chime',
    keywords: ['nature', 'ding', 'spring'],
    category: 'activities',
    color: '#87CEEB',
    tags: ['wind-chime', 'summer', 'japanese'],
  },
  {
    emoji: '🎑',
    name: 'moon viewing ceremony',
    keywords: ['photo', 'japan', 'asia'],
    category: 'activities',
    color: '#4169E1',
    tags: ['moon-viewing', 'japanese', 'autumn'],
  },
  {
    emoji: '🧧',
    name: 'red envelope',
    keywords: ['gift', 'money', 'luck'],
    category: 'activities',
    color: '#DC143C',
    tags: ['red-envelope', 'chinese', 'luck'],
  },
  {
    emoji: '🎀',
    name: 'ribbon',
    keywords: ['decoration', 'pink', 'gift'],
    category: 'activities',
    color: '#FF69B4',
    tags: ['ribbon', 'bow', 'gift'],
  },
  {
    emoji: '🎁',
    name: 'wrapped gift',
    keywords: ['present', 'birthday', 'christmas'],
    category: 'activities',
    color: '#DC143C',
    tags: ['gift', 'present', 'wrapped'],
  },
  {
    emoji: '🪅',
    name: 'piñata',
    keywords: ['celebration', 'party', 'candy'],
    category: 'activities',
    color: '#FF69B4',
    tags: ['pinata', 'party', 'mexican'],
  },
  {
    emoji: '🪆',
    name: 'nesting dolls',
    keywords: ['matryoshka', 'russia', 'doll'],
    category: 'activities',
    color: '#DC143C',
    tags: ['matryoshka', 'russian', 'dolls'],
  },
];

