import type { Emoji } from '../../schema';

export const activityEmojis = [
  // Sports - Ball sports
  {
    emoji: '⚽',
    name: 'soccer ball',
    keywords: ['sports', 'football', 'soccer'],
    category: 'activities',
    color: '#000000',
  },
  {
    emoji: '🏀',
    name: 'basketball',
    keywords: ['sports', 'balls', 'basketball'],
    category: 'activities',
    color: '#FF8C00',
  },
  {
    emoji: '🏈',
    name: 'american football',
    keywords: ['sports', 'balls', 'football'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '⚾',
    name: 'baseball',
    keywords: ['sports', 'balls', 'baseball'],
    category: 'activities',
    color: '#F5F5F5',
  },
  {
    emoji: '🥎',
    name: 'softball',
    keywords: ['sports', 'balls', 'softball'],
    category: 'activities',
    color: '#FFFF00',
  },
  {
    emoji: '🎾',
    name: 'tennis',
    keywords: ['sports', 'balls', 'tennis'],
    category: 'activities',
    color: '#ADFF2F',
  },
  {
    emoji: '🏐',
    name: 'volleyball',
    keywords: ['sports', 'balls', 'volleyball'],
    category: 'activities',
    color: '#F5F5F5',
  },
  {
    emoji: '🏉',
    name: 'rugby football',
    keywords: ['sports', 'team', 'rugby'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🥏',
    name: 'flying disc',
    keywords: ['frisbee', 'ultimate', 'disc'],
    category: 'activities',
    color: '#4169E1',
  },
  {
    emoji: '🎱',
    name: 'pool 8 ball',
    keywords: ['pool', 'hobby', '8ball'],
    category: 'activities',
    color: '#000000',
  },

  // Sports equipment
  {
    emoji: '🏓',
    name: 'ping pong',
    keywords: ['sports', 'pingpong', 'table tennis'],
    category: 'activities',
    color: '#DC143C',
  },
  {
    emoji: '🏸',
    name: 'badminton',
    keywords: ['sports', 'racquet', 'badminton'],
    category: 'activities',
    color: '#F5F5F5',
  },
  {
    emoji: '🏒',
    name: 'ice hockey',
    keywords: ['sports', 'hockey', 'ice'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🏑',
    name: 'field hockey',
    keywords: ['sports', 'hockey', 'field'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🥍',
    name: 'lacrosse',
    keywords: ['sports', 'ball', 'stick'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🏏',
    name: 'cricket game',
    keywords: ['sports', 'cricket', 'bat'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🪃',
    name: 'boomerang',
    keywords: ['weapon', 'australia', 'rebound'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🥅',
    name: 'goal net',
    keywords: ['sports', 'goal', 'net'],
    category: 'activities',
    color: '#F5F5F5',
  },
  {
    emoji: '⛳',
    name: 'flag in hole',
    keywords: ['sports', 'business', 'golf'],
    category: 'activities',
    color: '#DC143C',
  },
  {
    emoji: '🪁',
    name: 'kite',
    keywords: ['wind', 'fly', 'soar'],
    category: 'activities',
    color: '#FF69B4',
  },

  // Winter sports
  {
    emoji: '🛷',
    name: 'sled',
    keywords: ['sledge', 'sleigh', 'luge'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '⛸️',
    name: 'ice skate',
    keywords: ['sports', 'skating', 'ice'],
    category: 'activities',
    color: '#C0C0C0',
  },
  {
    emoji: '🎿',
    name: 'ski',
    keywords: ['sports', 'winter', 'cold'],
    category: 'activities',
    color: '#4169E1',
  },
  {
    emoji: '🥌',
    name: 'curling stone',
    keywords: ['sports', 'curling', 'stone'],
    category: 'activities',
    color: '#696969',
  },

  // Target sports
  {
    emoji: '🏹',
    name: 'bow and arrow',
    keywords: ['sports', 'archery', 'bow'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🎯',
    name: 'bullseye',
    keywords: ['target', 'archery', 'game'],
    category: 'activities',
    color: '#DC143C',
  },

  // Games
  {
    emoji: '🎮',
    name: 'video game',
    keywords: ['play', 'controller', 'console'],
    category: 'activities',
    color: '#000000',
  },
  {
    emoji: '🕹️',
    name: 'joystick',
    keywords: ['game', 'play', 'arcade'],
    category: 'activities',
    color: '#DC143C',
  },
  {
    emoji: '🎲',
    name: 'game die',
    keywords: ['dice', 'random', 'tabletop'],
    category: 'activities',
    color: '#F5F5F5',
  },
  {
    emoji: '🧩',
    name: 'puzzle piece',
    keywords: ['interlocking', 'puzzle', 'piece'],
    category: 'activities',
    color: '#4169E1',
  },
  {
    emoji: '♟️',
    name: 'chess pawn',
    keywords: ['chess', 'expendable', 'pawn'],
    category: 'activities',
    color: '#000000',
  },
  {
    emoji: '🎰',
    name: 'slot machine',
    keywords: ['slot', 'machine', 'gambling'],
    category: 'activities',
    color: '#FFD700',
  },
  {
    emoji: '🎳',
    name: 'bowling',
    keywords: ['sports', 'fun', 'bowling'],
    category: 'activities',
    color: '#F5F5F5',
  },

  // Arts and crafts
  {
    emoji: '🎨',
    name: 'artist palette',
    keywords: ['art', 'colors', 'paint'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🧵',
    name: 'thread',
    keywords: ['needle', 'sewing', 'spool'],
    category: 'activities',
    color: '#DC143C',
  },
  {
    emoji: '🧶',
    name: 'yarn',
    keywords: ['ball', 'crochet', 'knit'],
    category: 'activities',
    color: '#FF69B4',
  },
  {
    emoji: '🎭',
    name: 'performing arts',
    keywords: ['theater', 'drama', 'masks'],
    category: 'activities',
    color: '#FFD700',
  },
  {
    emoji: '🖼️',
    name: 'framed picture',
    keywords: ['art', 'museum', 'painting'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🎬',
    name: 'clapper board',
    keywords: ['movie', 'film', 'record'],
    category: 'activities',
    color: '#000000',
  },
  {
    emoji: '🎤',
    name: 'microphone',
    keywords: ['music', 'sound', 'karaoke'],
    category: 'activities',
    color: '#C0C0C0',
  },
  {
    emoji: '🎧',
    name: 'headphone',
    keywords: ['music', 'earphones', 'headphones'],
    category: 'activities',
    color: '#000000',
  },
  {
    emoji: '🎼',
    name: 'musical score',
    keywords: ['music', 'clef', 'compose'],
    category: 'activities',
    color: '#000000',
  },
  {
    emoji: '🎵',
    name: 'musical note',
    keywords: ['music', 'note', 'tone'],
    category: 'activities',
    color: '#000000',
  },
  {
    emoji: '🎶',
    name: 'musical notes',
    keywords: ['music', 'notes', 'score'],
    category: 'activities',
    color: '#000000',
  },

  // Musical instruments
  {
    emoji: '🎹',
    name: 'musical keyboard',
    keywords: ['piano', 'instrument', 'compose'],
    category: 'activities',
    color: '#000000',
  },
  {
    emoji: '🥁',
    name: 'drum',
    keywords: ['music', 'instrument', 'drumsticks'],
    category: 'activities',
    color: '#DC143C',
  },
  {
    emoji: '🪘',
    name: 'long drum',
    keywords: ['beat', 'conga', 'rhythm'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🎷',
    name: 'saxophone',
    keywords: ['music', 'instrument', 'jazz'],
    category: 'activities',
    color: '#FFD700',
  },
  {
    emoji: '🎺',
    name: 'trumpet',
    keywords: ['music', 'brass', 'instrument'],
    category: 'activities',
    color: '#FFD700',
  },
  {
    emoji: '🎸',
    name: 'guitar',
    keywords: ['music', 'instrument', 'rock'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🪕',
    name: 'banjo',
    keywords: ['music', 'stringed', 'instrument'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🎻',
    name: 'violin',
    keywords: ['music', 'instrument', 'orchestra'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🪗',
    name: 'accordion',
    keywords: ['music', 'concertina', 'squeeze'],
    category: 'activities',
    color: '#DC143C',
  },

  // Events
  {
    emoji: '🎫',
    name: 'ticket',
    keywords: ['event', 'concert', 'pass'],
    category: 'activities',
    color: '#FFD700',
  },
  {
    emoji: '🎟️',
    name: 'admission tickets',
    keywords: ['sports', 'concert', 'ticket'],
    category: 'activities',
    color: '#DC143C',
  },
  {
    emoji: '🎪',
    name: 'circus tent',
    keywords: ['festival', 'carnival', 'party'],
    category: 'activities',
    color: '#DC143C',
  },
  {
    emoji: '🤹',
    name: 'person juggling',
    keywords: ['juggle', 'balance', 'skill'],
    category: 'activities',
    color: '#FFD700',
  },
  {
    emoji: '🤹‍♂️',
    name: 'man juggling',
    keywords: ['juggle', 'balance', 'skill'],
    category: 'activities',
    color: '#FFD700',
  },
  {
    emoji: '🤹‍♀️',
    name: 'woman juggling',
    keywords: ['juggle', 'balance', 'skill'],
    category: 'activities',
    color: '#FFD700',
  },

  // Awards and competitions
  {
    emoji: '🏆',
    name: 'trophy',
    keywords: ['award', 'contest', 'winner'],
    category: 'activities',
    color: '#FFD700',
  },
  {
    emoji: '🏅',
    name: 'sports medal',
    keywords: ['gold', 'winner', 'medal'],
    category: 'activities',
    color: '#FFD700',
  },
  {
    emoji: '🥇',
    name: '1st place medal',
    keywords: ['gold', 'first', 'medal'],
    category: 'activities',
    color: '#FFD700',
  },
  {
    emoji: '🥈',
    name: '2nd place medal',
    keywords: ['silver', 'second', 'medal'],
    category: 'activities',
    color: '#C0C0C0',
  },
  {
    emoji: '🥉',
    name: '3rd place medal',
    keywords: ['bronze', 'third', 'medal'],
    category: 'activities',
    color: '#CD7F32',
  },

  // Martial arts
  {
    emoji: '🥊',
    name: 'boxing glove',
    keywords: ['sports', 'fighting', 'boxing'],
    category: 'activities',
    color: '#DC143C',
  },
  {
    emoji: '🥋',
    name: 'martial arts uniform',
    keywords: ['judo', 'karate', 'taekwondo'],
    category: 'activities',
    color: '#F5F5F5',
  },

  // Other activities
  {
    emoji: '🎣',
    name: 'fishing pole',
    keywords: ['food', 'hobby', 'fishing'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🤿',
    name: 'diving mask',
    keywords: ['sports', 'ocean', 'scuba'],
    category: 'activities',
    color: '#4169E1',
  },
  {
    emoji: '🎽',
    name: 'running shirt',
    keywords: ['sports', 'running', 'athletics'],
    category: 'activities',
    color: '#4169E1',
  },
  {
    emoji: '🛹',
    name: 'skateboard',
    keywords: ['board', 'skateboard', 'sport'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🛼',
    name: 'roller skate',
    keywords: ['sports', 'footwear', 'skate'],
    category: 'activities',
    color: '#FF69B4',
  },
  {
    emoji: '🪀',
    name: 'yo-yo',
    keywords: ['toy', 'fluctuate', 'yoyo'],
    category: 'activities',
    color: '#DC143C',
  },

  // Exercise and fitness
  {
    emoji: '🏋️',
    name: 'person lifting weights',
    keywords: ['sports', 'training', 'exercise'],
    category: 'activities',
    color: '#696969',
  },
  {
    emoji: '🏋️‍♂️',
    name: 'man lifting weights',
    keywords: ['sports', 'training', 'exercise'],
    category: 'activities',
    color: '#696969',
  },
  {
    emoji: '🏋️‍♀️',
    name: 'woman lifting weights',
    keywords: ['sports', 'training', 'exercise'],
    category: 'activities',
    color: '#696969',
  },
  {
    emoji: '🤸',
    name: 'person cartwheeling',
    keywords: ['gymnastics', 'cartwheel', 'person'],
    category: 'activities',
    color: '#FF69B4',
  },
  {
    emoji: '🤸‍♂️',
    name: 'man cartwheeling',
    keywords: ['gymnastics', 'cartwheel', 'man'],
    category: 'activities',
    color: '#87CEEB',
  },
  {
    emoji: '🤸‍♀️',
    name: 'woman cartwheeling',
    keywords: ['gymnastics', 'cartwheel', 'woman'],
    category: 'activities',
    color: '#FF69B4',
  },
  {
    emoji: '⛹️',
    name: 'person bouncing ball',
    keywords: ['sports', 'human', 'basketball'],
    category: 'activities',
    color: '#FF8C00',
  },
  {
    emoji: '⛹️‍♂️',
    name: 'man bouncing ball',
    keywords: ['sports', 'human', 'basketball'],
    category: 'activities',
    color: '#FF8C00',
  },
  {
    emoji: '⛹️‍♀️',
    name: 'woman bouncing ball',
    keywords: ['sports', 'human', 'basketball'],
    category: 'activities',
    color: '#FF8C00',
  },
  {
    emoji: '🤺',
    name: 'person fencing',
    keywords: ['sports', 'fencing', 'sword'],
    category: 'activities',
    color: '#C0C0C0',
  },
  {
    emoji: '🤼',
    name: 'people wrestling',
    keywords: ['sports', 'wrestling', 'wrestle'],
    category: 'activities',
    color: '#DAA520',
  },
  {
    emoji: '🤼‍♂️',
    name: 'men wrestling',
    keywords: ['sports', 'wrestling', 'men'],
    category: 'activities',
    color: '#DAA520',
  },
  {
    emoji: '🤼‍♀️',
    name: 'women wrestling',
    keywords: ['sports', 'wrestling', 'women'],
    category: 'activities',
    color: '#DAA520',
  },
  {
    emoji: '🤽',
    name: 'person playing water polo',
    keywords: ['sports', 'water', 'polo'],
    category: 'activities',
    color: '#00CED1',
  },
  {
    emoji: '🤽‍♂️',
    name: 'man playing water polo',
    keywords: ['sports', 'water', 'polo'],
    category: 'activities',
    color: '#00CED1',
  },
  {
    emoji: '🤽‍♀️',
    name: 'woman playing water polo',
    keywords: ['sports', 'water', 'polo'],
    category: 'activities',
    color: '#00CED1',
  },
  {
    emoji: '🤾',
    name: 'person playing handball',
    keywords: ['sports', 'handball', 'ball'],
    category: 'activities',
    color: '#FF4500',
  },
  {
    emoji: '🤾‍♂️',
    name: 'man playing handball',
    keywords: ['sports', 'handball', 'man'],
    category: 'activities',
    color: '#FF4500',
  },
  {
    emoji: '🤾‍♀️',
    name: 'woman playing handball',
    keywords: ['sports', 'handball', 'woman'],
    category: 'activities',
    color: '#FF4500',
  },
  {
    emoji: '🧘',
    name: 'person in lotus position',
    keywords: ['yoga', 'meditation', 'zen'],
    category: 'activities',
    color: '#DDA0DD',
  },
  {
    emoji: '🧘‍♂️',
    name: 'man in lotus position',
    keywords: ['yoga', 'meditation', 'man'],
    category: 'activities',
    color: '#87CEEB',
  },
  {
    emoji: '🧘‍♀️',
    name: 'woman in lotus position',
    keywords: ['yoga', 'meditation', 'woman'],
    category: 'activities',
    color: '#DDA0DD',
  },

  // Outdoor activities
  {
    emoji: '🏕️',
    name: 'camping',
    keywords: ['photo', 'camping', 'tent'],
    category: 'activities',
    color: '#228B22',
  },
  {
    emoji: '🧗',
    name: 'person climbing',
    keywords: ['sports', 'human', 'athletics'],
    category: 'activities',
    color: '#696969',
  },
  {
    emoji: '🧗‍♂️',
    name: 'man climbing',
    keywords: ['sports', 'human', 'athletics'],
    category: 'activities',
    color: '#696969',
  },
  {
    emoji: '🧗‍♀️',
    name: 'woman climbing',
    keywords: ['sports', 'human', 'athletics'],
    category: 'activities',
    color: '#696969',
  },
  {
    emoji: '🏇',
    name: 'horse racing',
    keywords: ['animal', 'betting', 'competition'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🏊',
    name: 'person swimming',
    keywords: ['sports', 'exercise', 'human'],
    category: 'activities',
    color: '#00CED1',
  },
  {
    emoji: '🏊‍♂️',
    name: 'man swimming',
    keywords: ['sports', 'exercise', 'human'],
    category: 'activities',
    color: '#00CED1',
  },
  {
    emoji: '🏊‍♀️',
    name: 'woman swimming',
    keywords: ['sports', 'exercise', 'human'],
    category: 'activities',
    color: '#00CED1',
  },
  {
    emoji: '🏄',
    name: 'person surfing',
    keywords: ['sports', 'human', 'beach'],
    category: 'activities',
    color: '#00CED1',
  },
  {
    emoji: '🏄‍♂️',
    name: 'man surfing',
    keywords: ['sports', 'human', 'beach'],
    category: 'activities',
    color: '#00CED1',
  },
  {
    emoji: '🏄‍♀️',
    name: 'woman surfing',
    keywords: ['sports', 'human', 'beach'],
    category: 'activities',
    color: '#00CED1',
  },
  {
    emoji: '🚣',
    name: 'person rowing boat',
    keywords: ['sports', 'hobby', 'water'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🚣‍♂️',
    name: 'man rowing boat',
    keywords: ['sports', 'hobby', 'water'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🚣‍♀️',
    name: 'woman rowing boat',
    keywords: ['sports', 'hobby', 'water'],
    category: 'activities',
    color: '#8B4513',
  },
  {
    emoji: '🚴',
    name: 'person biking',
    keywords: ['sports', 'bike', 'exercise'],
    category: 'activities',
    color: '#4169E1',
  },
  {
    emoji: '🚴‍♂️',
    name: 'man biking',
    keywords: ['sports', 'bike', 'exercise'],
    category: 'activities',
    color: '#4169E1',
  },
  {
    emoji: '🚴‍♀️',
    name: 'woman biking',
    keywords: ['sports', 'bike', 'exercise'],
    category: 'activities',
    color: '#4169E1',
  },
  {
    emoji: '🚵',
    name: 'person mountain biking',
    keywords: ['sports', 'human', 'race'],
    category: 'activities',
    color: '#228B22',
  },
  {
    emoji: '🚵‍♂️',
    name: 'man mountain biking',
    keywords: ['sports', 'human', 'race'],
    category: 'activities',
    color: '#228B22',
  },
  {
    emoji: '🚵‍♀️',
    name: 'woman mountain biking',
    keywords: ['sports', 'human', 'race'],
    category: 'activities',
    color: '#228B22',
  },

  // Seasonal and celebrations
  {
    emoji: '🎃',
    name: 'jack-o-lantern',
    keywords: ['halloween', 'pumpkin', 'creepy'],
    category: 'activities',
    color: '#FF8C00',
  },
  {
    emoji: '🎄',
    name: 'christmas tree',
    keywords: ['festival', 'vacation', 'december'],
    category: 'activities',
    color: '#228B22',
  },
  {
    emoji: '🎆',
    name: 'fireworks',
    keywords: ['photo', 'festival', 'carnival'],
    category: 'activities',
    color: '#FFD700',
  },
  {
    emoji: '🎇',
    name: 'sparkler',
    keywords: ['stars', 'night', 'shine'],
    category: 'activities',
    color: '#FFD700',
  },
  {
    emoji: '🧨',
    name: 'firecracker',
    keywords: ['dynamite', 'boom', 'explode'],
    category: 'activities',
    color: '#DC143C',
  },
  {
    emoji: '✨',
    name: 'sparkles',
    keywords: ['stars', 'shine', 'shiny'],
    category: 'activities',
    color: '#FFD700',
  },
  {
    emoji: '🎈',
    name: 'balloon',
    keywords: ['party', 'celebration', 'birthday'],
    category: 'activities',
    color: '#DC143C',
  },
  {
    emoji: '🎉',
    name: 'party popper',
    keywords: ['party', 'congratulations', 'birthday'],
    category: 'activities',
    color: '#FFD700',
  },
  {
    emoji: '🎊',
    name: 'confetti ball',
    keywords: ['festival', 'party', 'birthday'],
    category: 'activities',
    color: '#FF69B4',
  },
  {
    emoji: '🎋',
    name: 'tanabata tree',
    keywords: ['plant', 'nature', 'branch'],
    category: 'activities',
    color: '#228B22',
  },
  {
    emoji: '🎍',
    name: 'pine decoration',
    keywords: ['festival', 'plant', 'nature'],
    category: 'activities',
    color: '#228B22',
  },
  {
    emoji: '🎎',
    name: 'japanese dolls',
    keywords: ['japanese', 'toy', 'kimono'],
    category: 'activities',
    color: '#DC143C',
  },
  {
    emoji: '🎏',
    name: 'carp streamer',
    keywords: ['fish', 'japanese', 'koinobori'],
    category: 'activities',
    color: '#4169E1',
  },
  {
    emoji: '🎐',
    name: 'wind chime',
    keywords: ['nature', 'ding', 'spring'],
    category: 'activities',
    color: '#87CEEB',
  },
  {
    emoji: '🎑',
    name: 'moon viewing ceremony',
    keywords: ['photo', 'japan', 'asia'],
    category: 'activities',
    color: '#4169E1',
  },
  {
    emoji: '🧧',
    name: 'red envelope',
    keywords: ['gift', 'money', 'luck'],
    category: 'activities',
    color: '#DC143C',
  },
  {
    emoji: '🎀',
    name: 'ribbon',
    keywords: ['decoration', 'pink', 'gift'],
    category: 'activities',
    color: '#FF69B4',
  },
  {
    emoji: '🎁',
    name: 'wrapped gift',
    keywords: ['present', 'birthday', 'christmas'],
    category: 'activities',
    color: '#DC143C',
  },
  {
    emoji: '🪅',
    name: 'piñata',
    keywords: ['celebration', 'party', 'candy'],
    category: 'activities',
    color: '#FF69B4',
  },
  {
    emoji: '🪆',
    name: 'nesting dolls',
    keywords: ['matryoshka', 'russia', 'doll'],
    category: 'activities',
    color: '#DC143C',
  },
] as const satisfies readonly Omit<Emoji, 'sentiment'>[];
