import type { Emoji } from '../../schema';

// Generated from OpenMoji dataset - 159 emojis
// Unicode versions up to 15.1 + OpenMoji extras
export const animalsEmojisAll: Emoji[] = [
  {
    emoji: '🐵',
    name: 'monkey face',
    keywords: ['animal', 'banana', 'face', 'monkey'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F435',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐒',
    name: 'monkey',
    keywords: ['animal', 'banana'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F412',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦍',
    name: 'gorilla',
    keywords: ['animal'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F98D',
    version: '3',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦧',
    name: 'orangutan',
    keywords: ['animal', 'ape', 'monkey'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F9A7',
    version: '12',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐶',
    name: 'dog face',
    keywords: ['adorbs', 'animal', 'dog', 'face', 'pet', 'puppies', 'puppy'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F436',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐕️',
    name: 'dog',
    keywords: ['animal', 'animals', 'dogs', 'pet'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F415',
    version: '0.7',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦮',
    name: 'guide dog',
    keywords: ['accessibility', 'animal', 'blind', 'dog', 'guide'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F9AE',
    version: '12',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐕‍🦺',
    name: 'service dog',
    keywords: ['accessibility', 'animal', 'assistance', 'dog', 'service'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F415 200D 1F9BA',
    version: '12',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐩',
    name: 'poodle',
    keywords: ['animal', 'dog', 'fluffy'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F429',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐺',
    name: 'wolf',
    keywords: ['animal', 'face'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F43A',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦊',
    name: 'fox',
    keywords: ['animal', 'face'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F98A',
    version: '3',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦝',
    name: 'raccoon',
    keywords: ['animal', 'curious', 'sly'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F99D',
    version: '11',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐱',
    name: 'cat face',
    keywords: ['animal', 'cat', 'face', 'kitten', 'kitty', 'pet'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F431',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐈️',
    name: 'cat',
    keywords: ['animal', 'animals', 'cats', 'kitten', 'pet'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F408',
    version: '0.7',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐈‍⬛',
    name: 'black cat',
    keywords: [
      'animal',
      'black',
      'cat',
      'feline',
      'halloween',
      'meow',
      'unlucky',
    ],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F408 200D 2B1B',
    version: '13',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦁',
    name: 'lion',
    keywords: [
      'alpha',
      'animal',
      'face',
      'leo',
      'mane',
      'order',
      'rawr',
      'roar',
      'safari',
      'strong',
      'zodiac',
    ],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F981',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐯',
    name: 'tiger face',
    keywords: ['animal', 'big', 'cat', 'face', 'predator', 'tiger'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F42F',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐅',
    name: 'tiger',
    keywords: ['animal', 'big', 'cat', 'predator', 'zoo'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F405',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐆',
    name: 'leopard',
    keywords: ['animal', 'big', 'cat', 'predator', 'zoo'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F406',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐴',
    name: 'horse face',
    keywords: [
      'animal',
      'dressage',
      'equine',
      'face',
      'farm',
      'horse',
      'horses',
    ],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F434',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫎',
    name: 'moose',
    keywords: ['alces', 'animal', 'antlers', 'elk', 'mammal'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1FACE',
    version: '15',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫏',
    name: 'donkey',
    keywords: ['animal', 'ass', 'burro', 'hinny', 'mammal', 'mule', 'stubborn'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1FACF',
    version: '15',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐎',
    name: 'horse',
    keywords: ['animal', 'equestrian', 'farm', 'racehorse', 'racing'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F40E',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦄',
    name: 'unicorn',
    keywords: ['face'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F984',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦓',
    name: 'zebra',
    keywords: ['animal', 'stripe'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F993',
    version: '5',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦌',
    name: 'deer',
    keywords: ['animal'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F98C',
    version: '3',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦬',
    name: 'bison',
    keywords: ['animal', 'buffalo', 'herd', 'wisent'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F9AC',
    version: '13',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐮',
    name: 'cow face',
    keywords: ['animal', 'cow', 'face', 'farm', 'milk', 'moo'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F42E',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐂',
    name: 'ox',
    keywords: ['animal', 'animals', 'bull', 'farm', 'taurus', 'zodiac'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F402',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐃',
    name: 'water buffalo',
    keywords: ['animal', 'buffalo', 'water', 'zoo'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F403',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐄',
    name: 'cow',
    keywords: ['animal', 'animals', 'farm', 'milk', 'moo'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F404',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐷',
    name: 'pig face',
    keywords: ['animal', 'bacon', 'face', 'farm', 'pig', 'pork'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F437',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐖',
    name: 'pig',
    keywords: ['animal', 'bacon', 'farm', 'pork', 'sow'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F416',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐗',
    name: 'boar',
    keywords: ['animal', 'pig'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F417',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐽',
    name: 'pig nose',
    keywords: ['animal', 'face', 'farm', 'nose', 'pig', 'smell', 'snout'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F43D',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐏',
    name: 'ram',
    keywords: ['animal', 'aries', 'horns', 'male', 'sheep', 'zodiac', 'zoo'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F40F',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐑',
    name: 'ewe',
    keywords: [
      'animal',
      'baa',
      'farm',
      'female',
      'fluffy',
      'lamb',
      'sheep',
      'wool',
    ],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F411',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐐',
    name: 'goat',
    keywords: ['animal', 'capricorn', 'farm', 'milk', 'zodiac'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F410',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐪',
    name: 'camel',
    keywords: ['animal', 'desert', 'dromedary', 'hump', 'one'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F42A',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐫',
    name: 'two-hump camel',
    keywords: [
      'animal',
      'bactrian',
      'camel',
      'desert',
      'hump',
      'two',
      'two-hump',
    ],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F42B',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦙',
    name: 'llama',
    keywords: ['alpaca', 'animal', 'guanaco', 'vicuña', 'wool'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F999',
    version: '11',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦒',
    name: 'giraffe',
    keywords: ['animal', 'spots'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F992',
    version: '5',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐘',
    name: 'elephant',
    keywords: ['animal'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F418',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦣',
    name: 'mammoth',
    keywords: ['animal', 'extinction', 'large', 'tusk', 'wooly'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F9A3',
    version: '13',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦏',
    name: 'rhinoceros',
    keywords: ['animal'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F98F',
    version: '3',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦛',
    name: 'hippopotamus',
    keywords: ['animal', 'hippo'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F99B',
    version: '11',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐭',
    name: 'mouse face',
    keywords: ['animal', 'face', 'mouse'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F42D',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐁',
    name: 'mouse',
    keywords: ['animal', 'animals'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F401',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐀',
    name: 'rat',
    keywords: ['animal'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F400',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐹',
    name: 'hamster',
    keywords: ['animal', 'face', 'pet'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F439',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐰',
    name: 'rabbit face',
    keywords: ['animal', 'bunny', 'face', 'pet', 'rabbit'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F430',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐇',
    name: 'rabbit',
    keywords: ['animal', 'bunny', 'pet'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F407',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐿️',
    name: 'chipmunk',
    keywords: ['animal', 'squirrel'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F43F',
    version: '0.7',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦫',
    name: 'beaver',
    keywords: ['animal', 'dam', 'teeth'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F9AB',
    version: '13',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦔',
    name: 'hedgehog',
    keywords: ['animal', 'spiny'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F994',
    version: '5',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦇',
    name: 'bat',
    keywords: ['animal', 'vampire'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F987',
    version: '3',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐻',
    name: 'bear',
    keywords: ['animal', 'face', 'grizzly', 'growl', 'honey'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F43B',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐻‍❄️',
    name: 'polar bear',
    keywords: ['animal', 'arctic', 'bear', 'polar', 'white'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F43B 200D 2744 FE0F',
    version: '13',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐨',
    name: 'koala',
    keywords: [
      'animal',
      'australia',
      'bear',
      'down',
      'face',
      'marsupial',
      'under',
    ],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F428',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐼',
    name: 'panda',
    keywords: ['animal', 'bamboo', 'face'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F43C',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦥',
    name: 'sloth',
    keywords: ['lazy', 'slow'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F9A5',
    version: '12',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦦',
    name: 'otter',
    keywords: ['animal', 'fishing', 'playful'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F9A6',
    version: '12',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦨',
    name: 'skunk',
    keywords: ['animal', 'stink'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F9A8',
    version: '12',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦘',
    name: 'kangaroo',
    keywords: ['animal', 'joey', 'jump', 'marsupial'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F998',
    version: '11',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦡',
    name: 'badger',
    keywords: ['animal', 'honey', 'pester'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F9A1',
    version: '11',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐾',
    name: 'paw prints',
    keywords: ['feet', 'paw', 'paws', 'print', 'prints'],
    category: 'animals',
    subcategory: 'animal-mammal',
    unicode: '1F43E',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦃',
    name: 'turkey',
    keywords: ['bird', 'gobble', 'thanksgiving'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F983',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐔',
    name: 'chicken',
    keywords: ['animal', 'bird', 'ornithology'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F414',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐓',
    name: 'rooster',
    keywords: ['animal', 'bird', 'ornithology'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F413',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐣',
    name: 'hatching chick',
    keywords: ['animal', 'baby', 'bird', 'chick', 'egg', 'hatching'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F423',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐤',
    name: 'baby chick',
    keywords: ['animal', 'baby', 'bird', 'chick', 'ornithology'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F424',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐥',
    name: 'front-facing baby chick',
    keywords: [
      'animal',
      'baby',
      'bird',
      'chick',
      'front-facing',
      'newborn',
      'ornithology',
    ],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F425',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐦️',
    name: 'bird',
    keywords: ['animal', 'ornithology'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F426',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐧',
    name: 'penguin',
    keywords: ['animal', 'antarctica', 'bird', 'ornithology'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F427',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕊️',
    name: 'dove',
    keywords: ['bird', 'fly', 'ornithology', 'peace'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F54A',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦅',
    name: 'eagle',
    keywords: ['animal', 'bird', 'ornithology'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F985',
    version: '3',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦆',
    name: 'duck',
    keywords: ['animal', 'bird', 'ornithology'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F986',
    version: '3',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦢',
    name: 'swan',
    keywords: ['animal', 'bird', 'cygnet', 'duckling', 'ornithology', 'ugly'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F9A2',
    version: '11',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦉',
    name: 'owl',
    keywords: ['animal', 'bird', 'ornithology', 'wise'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F989',
    version: '3',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦤',
    name: 'dodo',
    keywords: ['animal', 'bird', 'extinction', 'large', 'ornithology'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F9A4',
    version: '13',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪶',
    name: 'feather',
    keywords: ['bird', 'flight', 'light', 'plumage'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1FAB6',
    version: '13',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦩',
    name: 'flamingo',
    keywords: ['animal', 'bird', 'flamboyant', 'ornithology', 'tropical'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F9A9',
    version: '12',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦚',
    name: 'peacock',
    keywords: [
      'animal',
      'bird',
      'colorful',
      'ornithology',
      'ostentatious',
      'peahen',
      'pretty',
      'proud',
    ],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F99A',
    version: '11',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦜',
    name: 'parrot',
    keywords: ['animal', 'bird', 'ornithology', 'pirate', 'talk'],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F99C',
    version: '11',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪽',
    name: 'wing',
    keywords: [
      'angelic',
      'ascend',
      'aviation',
      'bird',
      'fly',
      'flying',
      'heavenly',
      'mythology',
      'soar',
    ],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1FABD',
    version: '15',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐦‍⬛',
    name: 'black bird',
    keywords: [
      'animal',
      'beak',
      'bird',
      'black',
      'caw',
      'corvid',
      'crow',
      'ornithology',
      'raven',
      'rook',
    ],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F426 200D 2B1B',
    version: '15',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪿',
    name: 'goose',
    keywords: [
      'animal',
      'bird',
      'duck',
      'flock',
      'fowl',
      'gaggle',
      'gander',
      'geese',
      'honk',
      'ornithology',
      'silly',
    ],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1FABF',
    version: '15',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐦‍🔥',
    name: 'phoenix',
    keywords: [
      'ascend',
      'ascension',
      'emerge',
      'fantasy',
      'firebird',
      'glory',
      'immortal',
      'rebirth',
      'reincarnation',
      'reinvent',
      'renewal',
      'revival',
      'revive',
      'rise',
      'transform',
    ],
    category: 'animals',
    subcategory: 'animal-bird',
    unicode: '1F426 200D 1F525',
    version: '15.1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐸',
    name: 'frog',
    keywords: ['animal', 'face'],
    category: 'animals',
    subcategory: 'animal-amphibian',
    unicode: '1F438',
    version: '0.6',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐊',
    name: 'crocodile',
    keywords: ['animal', 'zoo'],
    category: 'animals',
    subcategory: 'animal-reptile',
    unicode: '1F40A',
    version: '1',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐢',
    name: 'turtle',
    keywords: ['animal', 'terrapin', 'tortoise'],
    category: 'animals',
    subcategory: 'animal-reptile',
    unicode: '1F422',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦎',
    name: 'lizard',
    keywords: ['animal', 'reptile'],
    category: 'animals',
    subcategory: 'animal-reptile',
    unicode: '1F98E',
    version: '3',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐍',
    name: 'snake',
    keywords: ['animal', 'bearer', 'ophiuchus', 'serpent', 'zodiac'],
    category: 'animals',
    subcategory: 'animal-reptile',
    unicode: '1F40D',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐲',
    name: 'dragon face',
    keywords: ['animal', 'dragon', 'face', 'fairy', 'fairytale', 'tale'],
    category: 'animals',
    subcategory: 'animal-reptile',
    unicode: '1F432',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐉',
    name: 'dragon',
    keywords: ['animal', 'fairy', 'fairytale', 'knights', 'tale'],
    category: 'animals',
    subcategory: 'animal-reptile',
    unicode: '1F409',
    version: '1',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦕',
    name: 'sauropod',
    keywords: ['brachiosaurus', 'brontosaurus', 'dinosaur', 'diplodocus'],
    category: 'animals',
    subcategory: 'animal-reptile',
    unicode: '1F995',
    version: '5',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦖',
    name: 't-rex',
    keywords: ['dinosaur', 'rex', 't', 't-rex', 'tyrannosaurus'],
    category: 'animals',
    subcategory: 'animal-reptile',
    unicode: '1F996',
    version: '5',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐳',
    name: 'spouting whale',
    keywords: ['animal', 'beach', 'face', 'ocean', 'spouting', 'whale'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F433',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐋',
    name: 'whale',
    keywords: ['animal', 'beach', 'ocean'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F40B',
    version: '1',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐬',
    name: 'dolphin',
    keywords: ['animal', 'beach', 'flipper', 'ocean'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F42C',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦭',
    name: 'seal',
    keywords: ['animal', 'lion', 'ocean', 'sea'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F9AD',
    version: '13',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐟️',
    name: 'fish',
    keywords: ['animal', 'dinner', 'fishes', 'fishing', 'pisces', 'zodiac'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F41F',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐠',
    name: 'tropical fish',
    keywords: ['animal', 'fish', 'fishes', 'tropical'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F420',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐡',
    name: 'blowfish',
    keywords: ['animal', 'fish'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F421',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦈',
    name: 'shark',
    keywords: ['animal', 'fish'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F988',
    version: '3',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐙',
    name: 'octopus',
    keywords: ['animal', 'creature', 'ocean'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F419',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐚',
    name: 'spiral shell',
    keywords: ['animal', 'beach', 'conch', 'sea', 'shell', 'spiral'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F41A',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪸',
    name: 'coral',
    keywords: ['change', 'climate', 'ocean', 'reef', 'sea'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1FAB8',
    version: '14',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪼',
    name: 'jellyfish',
    keywords: [
      'animal',
      'aquarium',
      'burn',
      'invertebrate',
      'jelly',
      'life',
      'marine',
      'ocean',
      'ouch',
      'plankton',
      'sea',
      'sting',
      'stinger',
      'tentacles',
    ],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1FABC',
    version: '15',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦀',
    name: 'crab',
    keywords: ['cancer', 'zodiac'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F980',
    version: '1',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦞',
    name: 'lobster',
    keywords: ['animal', 'bisque', 'claws', 'seafood'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F99E',
    version: '11',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦐',
    name: 'shrimp',
    keywords: ['food', 'shellfish', 'small'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F990',
    version: '3',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦑',
    name: 'squid',
    keywords: ['animal', 'food', 'mollusk'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F991',
    version: '3',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦪',
    name: 'oyster',
    keywords: ['diving', 'pearl'],
    category: 'animals',
    subcategory: 'animal-marine',
    unicode: '1F9AA',
    version: '12',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐌',
    name: 'snail',
    keywords: ['animal', 'escargot', 'garden', 'nature', 'slug'],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1F40C',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦋',
    name: 'butterfly',
    keywords: ['insect', 'pretty'],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1F98B',
    version: '3',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐛',
    name: 'bug',
    keywords: ['animal', 'garden', 'insect'],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1F41B',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐜',
    name: 'ant',
    keywords: ['animal', 'garden', 'insect'],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1F41C',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐝',
    name: 'honeybee',
    keywords: [
      'animal',
      'bee',
      'bumblebee',
      'honey',
      'insect',
      'nature',
      'spring',
    ],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1F41D',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪲',
    name: 'beetle',
    keywords: ['animal', 'bug', 'insect'],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1FAB2',
    version: '13',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🐞',
    name: 'lady beetle',
    keywords: [
      'animal',
      'beetle',
      'garden',
      'insect',
      'lady',
      'ladybird',
      'ladybug',
      'nature',
    ],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1F41E',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦗',
    name: 'cricket',
    keywords: ['animal', 'bug', 'grasshopper', 'insect', 'orthoptera'],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1F997',
    version: '5',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪳',
    name: 'cockroach',
    keywords: ['animal', 'insect', 'pest', 'roach'],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1FAB3',
    version: '13',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕷️',
    name: 'spider',
    keywords: ['animal', 'insect'],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1F577',
    version: '0.7',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕸️',
    name: 'spider web',
    keywords: ['spider', 'web'],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1F578',
    version: '0.7',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦂',
    name: 'scorpion',
    keywords: ['scorpio', 'scorpius', 'zodiac'],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1F982',
    version: '1',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦟',
    name: 'mosquito',
    keywords: [
      'bite',
      'disease',
      'fever',
      'insect',
      'malaria',
      'pest',
      'virus',
    ],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1F99F',
    version: '11',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪰',
    name: 'fly',
    keywords: ['animal', 'disease', 'insect', 'maggot', 'pest', 'rotting'],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1FAB0',
    version: '13',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪱',
    name: 'worm',
    keywords: ['animal', 'annelid', 'earthworm', 'parasite'],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1FAB1',
    version: '13',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦠',
    name: 'microbe',
    keywords: ['amoeba', 'bacteria', 'science', 'virus'],
    category: 'animals',
    subcategory: 'animal-bug',
    unicode: '1F9A0',
    version: '11',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💐',
    name: 'bouquet',
    keywords: [
      'anniversary',
      'birthday',
      'date',
      'flower',
      'love',
      'plant',
      'romance',
    ],
    category: 'animals',
    subcategory: 'plant-flower',
    unicode: '1F490',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🌸',
    name: 'cherry blossom',
    keywords: ['blossom', 'cherry', 'flower', 'plant', 'spring', 'springtime'],
    category: 'animals',
    subcategory: 'plant-flower',
    unicode: '1F338',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💮',
    name: 'white flower',
    keywords: ['flower', 'white'],
    category: 'animals',
    subcategory: 'plant-flower',
    unicode: '1F4AE',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪷',
    name: 'lotus',
    keywords: [
      'beauty',
      'buddhism',
      'calm',
      'flower',
      'hinduism',
      'peace',
      'purity',
      'serenity',
    ],
    category: 'animals',
    subcategory: 'plant-flower',
    unicode: '1FAB7',
    version: '14',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏵️',
    name: 'rosette',
    keywords: ['plant'],
    category: 'animals',
    subcategory: 'plant-flower',
    unicode: '1F3F5',
    version: '0.7',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌹',
    name: 'rose',
    keywords: [
      'beauty',
      'elegant',
      'flower',
      'love',
      'plant',
      'red',
      'valentine',
    ],
    category: 'animals',
    subcategory: 'plant-flower',
    unicode: '1F339',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🥀',
    name: 'wilted flower',
    keywords: ['dying', 'flower', 'wilted'],
    category: 'animals',
    subcategory: 'plant-flower',
    unicode: '1F940',
    version: '3',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌺',
    name: 'hibiscus',
    keywords: ['flower', 'plant'],
    category: 'animals',
    subcategory: 'plant-flower',
    unicode: '1F33A',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌻',
    name: 'sunflower',
    keywords: ['flower', 'outdoors', 'plant', 'sun'],
    category: 'animals',
    subcategory: 'plant-flower',
    unicode: '1F33B',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌼',
    name: 'blossom',
    keywords: ['buttercup', 'dandelion', 'flower', 'plant'],
    category: 'animals',
    subcategory: 'plant-flower',
    unicode: '1F33C',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌷',
    name: 'tulip',
    keywords: ['blossom', 'flower', 'growth', 'plant'],
    category: 'animals',
    subcategory: 'plant-flower',
    unicode: '1F337',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪻',
    name: 'hyacinth',
    keywords: [
      'bloom',
      'bluebonnet',
      'flower',
      'indigo',
      'lavender',
      'lilac',
      'lupine',
      'plant',
      'purple',
      'shrub',
      'snapdragon',
      'spring',
      'violet',
    ],
    category: 'animals',
    subcategory: 'plant-flower',
    unicode: '1FABB',
    version: '15',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌱',
    name: 'seedling',
    keywords: ['plant', 'sapling', 'sprout', 'young'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1F331',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪴',
    name: 'potted plant',
    keywords: ['decor', 'grow', 'house', 'nurturing', 'plant', 'pot', 'potted'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1FAB4',
    version: '13',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌲',
    name: 'evergreen tree',
    keywords: ['christmas', 'evergreen', 'forest', 'pine', 'tree'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1F332',
    version: '1',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌳',
    name: 'deciduous tree',
    keywords: ['deciduous', 'forest', 'green', 'habitat', 'shedding', 'tree'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1F333',
    version: '1',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌴',
    name: 'palm tree',
    keywords: ['beach', 'palm', 'plant', 'tree', 'tropical'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1F334',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌵',
    name: 'cactus',
    keywords: ['desert', 'drought', 'nature', 'plant'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1F335',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌾',
    name: 'sheaf of rice',
    keywords: ['ear', 'grain', 'grains', 'plant', 'rice', 'sheaf'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1F33E',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌿',
    name: 'herb',
    keywords: ['leaf', 'plant'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1F33F',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '☘️',
    name: 'shamrock',
    keywords: ['irish', 'plant'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '2618',
    version: '1',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍀',
    name: 'four leaf clover',
    keywords: [
      '4',
      'clover',
      'four',
      'four-leaf',
      'irish',
      'leaf',
      'lucky',
      'plant',
    ],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1F340',
    version: '0.6',
    color: '#228B22',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🍁',
    name: 'maple leaf',
    keywords: ['falling', 'leaf', 'maple'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1F341',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍂',
    name: 'fallen leaf',
    keywords: ['autumn', 'fall', 'fallen', 'falling', 'leaf'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1F342',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍃',
    name: 'leaf fluttering in wind',
    keywords: ['blow', 'flutter', 'fluttering', 'leaf', 'wind'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1F343',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪹',
    name: 'empty nest',
    keywords: ['branch', 'empty', 'home', 'nest', 'nesting'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1FAB9',
    version: '14',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪺',
    name: 'nest with eggs',
    keywords: ['bird', 'branch', 'egg', 'eggs', 'nest', 'nesting'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1FABA',
    version: '14',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍄',
    name: 'mushroom',
    keywords: ['fungus', 'toadstool'],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1F344',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪾',
    name: 'leafless tree',
    keywords: [
      'bare',
      'barren',
      'branches',
      'dead',
      'drought',
      'leafless',
      'tree',
      'trunk',
      'winter',
      'wood',
    ],
    category: 'animals',
    subcategory: 'plant-other',
    unicode: '1FABE',
    version: '16',
    color: '#228B22',
    sentiment: 'negative' as const,
  },
];
