import type { Emoji } from '../../schema';

export const animalEmojis: Omit<Emoji, 'sentiment'>[] = [
  // Mammals - Pets
  {
    emoji: '🐶',
    name: 'dog face',
    keywords: ['dog', 'puppy', 'pet'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🐕',
    name: 'dog',
    keywords: ['dog', 'doggo', 'puppy'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🦮',
    name: 'guide dog',
    keywords: ['blind', 'guide', 'dog'],
    category: 'animals',
    color: '#FFD700',
  },
  {
    emoji: '🐕‍🦺',
    name: 'service dog',
    keywords: ['service', 'support', 'dog'],
    category: 'animals',
    color: '#FF4500',
  },
  {
    emoji: '🐩',
    name: 'poodle',
    keywords: ['dog', 'poodle', 'fluffy'],
    category: 'animals',
    color: '#F5F5F5',
  },
  {
    emoji: '🐺',
    name: 'wolf',
    keywords: ['wolf', 'howl', 'wild'],
    category: 'animals',
    color: '#696969',
  },
  {
    emoji: '🦊',
    name: 'fox',
    keywords: ['fox', 'face', 'clever'],
    category: 'animals',
    color: '#FF8C00',
  },
  {
    emoji: '🦝',
    name: 'raccoon',
    keywords: ['raccoon', 'trash panda', 'curious'],
    category: 'animals',
    color: '#696969',
  },
  {
    emoji: '🐱',
    name: 'cat face',
    keywords: ['cat', 'kitten', 'pet'],
    category: 'animals',
    color: '#FFD700',
  },
  {
    emoji: '🐈',
    name: 'cat',
    keywords: ['cat', 'feline', 'pet'],
    category: 'animals',
    color: '#FFD700',
  },
  {
    emoji: '🐈‍⬛',
    name: 'black cat',
    keywords: ['black', 'cat', 'superstition'],
    category: 'animals',
    color: '#000000',
  },
  {
    emoji: '🦁',
    name: 'lion',
    keywords: ['lion', 'face', 'king'],
    category: 'animals',
    color: '#FFD700',
  },
  {
    emoji: '🐯',
    name: 'tiger face',
    keywords: ['tiger', 'face', 'cute'],
    category: 'animals',
    color: '#FF8C00',
  },
  {
    emoji: '🐅',
    name: 'tiger',
    keywords: ['tiger', 'nature', 'stripes'],
    category: 'animals',
    color: '#FF8C00',
  },
  {
    emoji: '🐆',
    name: 'leopard',
    keywords: ['leopard', 'nature', 'spots'],
    category: 'animals',
    color: '#FFD700',
  },

  // Horses and farm animals
  {
    emoji: '🐴',
    name: 'horse face',
    keywords: ['horse', 'face', 'animal'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🐎',
    name: 'horse',
    keywords: ['horse', 'racehorse', 'speed'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🦄',
    name: 'unicorn',
    keywords: ['unicorn', 'fantasy', 'magic'],
    category: 'animals',
    color: '#FFB6C1',
  },
  {
    emoji: '🦓',
    name: 'zebra',
    keywords: ['zebra', 'stripes', 'safari'],
    category: 'animals',
    color: '#000000',
  },
  {
    emoji: '🦌',
    name: 'deer',
    keywords: ['deer', 'nature', 'bambi'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🦬',
    name: 'bison',
    keywords: ['bison', 'buffalo', 'ox'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🐮',
    name: 'cow face',
    keywords: ['cow', 'face', 'moo'],
    category: 'animals',
    color: '#000000',
  },
  {
    emoji: '🐄',
    name: 'cow',
    keywords: ['cow', 'milk', 'moo'],
    category: 'animals',
    color: '#000000',
  },
  {
    emoji: '🐂',
    name: 'ox',
    keywords: ['ox', 'bull', 'cow'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🐃',
    name: 'water buffalo',
    keywords: ['buffalo', 'water', 'ox'],
    category: 'animals',
    color: '#696969',
  },
  {
    emoji: '🐷',
    name: 'pig face',
    keywords: ['pig', 'face', 'oink'],
    category: 'animals',
    color: '#FFB6C1',
  },
  {
    emoji: '🐖',
    name: 'pig',
    keywords: ['pig', 'hog', 'oink'],
    category: 'animals',
    color: '#FFB6C1',
  },
  {
    emoji: '🐗',
    name: 'boar',
    keywords: ['boar', 'wild', 'pig'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🐽',
    name: 'pig nose',
    keywords: ['pig', 'nose', 'snout'],
    category: 'animals',
    color: '#FFB6C1',
  },
  {
    emoji: '🐏',
    name: 'ram',
    keywords: ['sheep', 'ram', 'male'],
    category: 'animals',
    color: '#F5F5F5',
  },
  {
    emoji: '🐑',
    name: 'ewe',
    keywords: ['sheep', 'wool', 'lamb'],
    category: 'animals',
    color: '#F5F5F5',
  },
  {
    emoji: '🐐',
    name: 'goat',
    keywords: ['goat', 'animal', 'nature'],
    category: 'animals',
    color: '#D3D3D3',
  },
  {
    emoji: '🐪',
    name: 'dromedary camel',
    keywords: ['camel', 'desert', 'hump'],
    category: 'animals',
    color: '#DEB887',
  },
  {
    emoji: '🐫',
    name: 'bactrian camel',
    keywords: ['camel', 'desert', 'two humps'],
    category: 'animals',
    color: '#DEB887',
  },
  {
    emoji: '🦙',
    name: 'llama',
    keywords: ['llama', 'alpaca', 'animal'],
    category: 'animals',
    color: '#F5DEB3',
  },
  {
    emoji: '🦒',
    name: 'giraffe',
    keywords: ['giraffe', 'spots', 'safari'],
    category: 'animals',
    color: '#FFD700',
  },
  {
    emoji: '🐘',
    name: 'elephant',
    keywords: ['elephant', 'trunk', 'safari'],
    category: 'animals',
    color: '#696969',
  },
  {
    emoji: '🦣',
    name: 'mammoth',
    keywords: ['mammoth', 'extinct', 'elephant'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🦏',
    name: 'rhinoceros',
    keywords: ['rhino', 'horn', 'safari'],
    category: 'animals',
    color: '#696969',
  },
  {
    emoji: '🦛',
    name: 'hippopotamus',
    keywords: ['hippo', 'water', 'nature'],
    category: 'animals',
    color: '#9370DB',
  },

  // Small mammals
  {
    emoji: '🐭',
    name: 'mouse face',
    keywords: ['mouse', 'face', 'rodent'],
    category: 'animals',
    color: '#D3D3D3',
  },
  {
    emoji: '🐁',
    name: 'mouse',
    keywords: ['mouse', 'rodent', 'nature'],
    category: 'animals',
    color: '#D3D3D3',
  },
  {
    emoji: '🐀',
    name: 'rat',
    keywords: ['rat', 'rodent', 'mouse'],
    category: 'animals',
    color: '#696969',
  },
  {
    emoji: '🐹',
    name: 'hamster',
    keywords: ['hamster', 'face', 'pet'],
    category: 'animals',
    color: '#FFD700',
  },
  {
    emoji: '🐰',
    name: 'rabbit face',
    keywords: ['bunny', 'rabbit', 'face'],
    category: 'animals',
    color: '#F5F5F5',
  },
  {
    emoji: '🐇',
    name: 'rabbit',
    keywords: ['bunny', 'rabbit', 'animal'],
    category: 'animals',
    color: '#F5F5F5',
  },
  {
    emoji: '🐿️',
    name: 'chipmunk',
    keywords: ['chipmunk', 'squirrel', 'animal'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🦫',
    name: 'beaver',
    keywords: ['beaver', 'dam', 'animal'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🦔',
    name: 'hedgehog',
    keywords: ['hedgehog', 'spiny', 'nature'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🦇',
    name: 'bat',
    keywords: ['bat', 'vampire', 'batman'],
    category: 'animals',
    color: '#000000',
  },

  // Bears
  {
    emoji: '🐻',
    name: 'bear',
    keywords: ['bear', 'face', 'teddy'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🐻‍❄️',
    name: 'polar bear',
    keywords: ['bear', 'white', 'arctic'],
    category: 'animals',
    color: '#F5F5F5',
  },
  {
    emoji: '🐨',
    name: 'koala',
    keywords: ['koala', 'nature', 'animal'],
    category: 'animals',
    color: '#D3D3D3',
  },
  {
    emoji: '🐼',
    name: 'panda',
    keywords: ['panda', 'face', 'nature'],
    category: 'animals',
    color: '#000000',
  },

  // Marsupials and others
  {
    emoji: '🦥',
    name: 'sloth',
    keywords: ['sloth', 'slow', 'lazy'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🦦',
    name: 'otter',
    keywords: ['otter', 'playful', 'fishing'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🦨',
    name: 'skunk',
    keywords: ['skunk', 'stink', 'smelly'],
    category: 'animals',
    color: '#000000',
  },
  {
    emoji: '🦘',
    name: 'kangaroo',
    keywords: ['kangaroo', 'marsupial', 'joey'],
    category: 'animals',
    color: '#DEB887',
  },
  {
    emoji: '🦡',
    name: 'badger',
    keywords: ['badger', 'honey badger', 'pester'],
    category: 'animals',
    color: '#696969',
  },

  // Birds
  {
    emoji: '🐔',
    name: 'chicken',
    keywords: ['chicken', 'cluck', 'bird'],
    category: 'animals',
    color: '#F5F5F5',
  },
  {
    emoji: '🐓',
    name: 'rooster',
    keywords: ['rooster', 'crow', 'chicken'],
    category: 'animals',
    color: '#DC143C',
  },
  {
    emoji: '🐣',
    name: 'hatching chick',
    keywords: ['chick', 'hatching', 'egg'],
    category: 'animals',
    color: '#FFD700',
  },
  {
    emoji: '🐤',
    name: 'baby chick',
    keywords: ['chick', 'baby', 'bird'],
    category: 'animals',
    color: '#FFD700',
  },
  {
    emoji: '🐥',
    name: 'front-facing baby chick',
    keywords: ['chick', 'baby', 'bird'],
    category: 'animals',
    color: '#FFD700',
  },
  {
    emoji: '🐦',
    name: 'bird',
    keywords: ['bird', 'nature', 'tweet'],
    category: 'animals',
    color: '#87CEEB',
  },
  {
    emoji: '🐧',
    name: 'penguin',
    keywords: ['penguin', 'nature', 'animal'],
    category: 'animals',
    color: '#000000',
  },
  {
    emoji: '🕊️',
    name: 'dove',
    keywords: ['peace', 'dove', 'bird'],
    category: 'animals',
    color: '#F5F5F5',
  },
  {
    emoji: '🦅',
    name: 'eagle',
    keywords: ['eagle', 'bird', 'america'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🦆',
    name: 'duck',
    keywords: ['duck', 'quack', 'nature'],
    category: 'animals',
    color: '#FFD700',
  },
  {
    emoji: '🦢',
    name: 'swan',
    keywords: ['swan', 'cygnet', 'ugly duckling'],
    category: 'animals',
    color: '#F5F5F5',
  },
  {
    emoji: '🦉',
    name: 'owl',
    keywords: ['owl', 'wise', 'hoot'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🦤',
    name: 'dodo',
    keywords: ['dodo', 'extinct', 'mauritius'],
    category: 'animals',
    color: '#D3D3D3',
  },
  {
    emoji: '🪶',
    name: 'feather',
    keywords: ['feather', 'bird', 'fly'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🦩',
    name: 'flamingo',
    keywords: ['flamingo', 'flamboyant', 'tropical'],
    category: 'animals',
    color: '#FF69B4',
  },
  {
    emoji: '🦚',
    name: 'peacock',
    keywords: ['peacock', 'proud', 'bird'],
    category: 'animals',
    color: '#4169E1',
  },
  {
    emoji: '🦜',
    name: 'parrot',
    keywords: ['parrot', 'pirate', 'talk'],
    category: 'animals',
    color: '#FF0000',
  },

  // Amphibians
  {
    emoji: '🐸',
    name: 'frog',
    keywords: ['frog', 'toad', 'nature'],
    category: 'animals',
    color: '#90EE90',
  },

  // Reptiles
  {
    emoji: '🐊',
    name: 'crocodile',
    keywords: ['crocodile', 'nature', 'alligator'],
    category: 'animals',
    color: '#228B22',
  },
  {
    emoji: '🐢',
    name: 'turtle',
    keywords: ['turtle', 'slow', 'nature'],
    category: 'animals',
    color: '#228B22',
  },
  {
    emoji: '🦎',
    name: 'lizard',
    keywords: ['lizard', 'nature', 'reptile'],
    category: 'animals',
    color: '#228B22',
  },
  {
    emoji: '🐍',
    name: 'snake',
    keywords: ['snake', 'serpent', 'python'],
    category: 'animals',
    color: '#228B22',
  },
  {
    emoji: '🐲',
    name: 'dragon face',
    keywords: ['dragon', 'face', 'nature'],
    category: 'animals',
    color: '#228B22',
  },
  {
    emoji: '🐉',
    name: 'dragon',
    keywords: ['dragon', 'myth', 'nature'],
    category: 'animals',
    color: '#DC143C',
  },
  {
    emoji: '🦕',
    name: 'sauropod',
    keywords: ['dinosaur', 'brachiosaurus', 'extinct'],
    category: 'animals',
    color: '#228B22',
  },
  {
    emoji: '🦖',
    name: 't-rex',
    keywords: ['dinosaur', 'tyrannosaurus', 'extinct'],
    category: 'animals',
    color: '#8B4513',
  },

  // Sea animals
  {
    emoji: '🐳',
    name: 'spouting whale',
    keywords: ['whale', 'sea', 'ocean'],
    category: 'animals',
    color: '#4682B4',
  },
  {
    emoji: '🐋',
    name: 'whale',
    keywords: ['whale', 'nature', 'sea'],
    category: 'animals',
    color: '#4682B4',
  },
  {
    emoji: '🐬',
    name: 'dolphin',
    keywords: ['dolphin', 'flipper', 'fins'],
    category: 'animals',
    color: '#87CEEB',
  },
  {
    emoji: '🦭',
    name: 'seal',
    keywords: ['seal', 'sea lion', 'animal'],
    category: 'animals',
    color: '#696969',
  },
  {
    emoji: '🐟',
    name: 'fish',
    keywords: ['fish', 'swim', 'sea'],
    category: 'animals',
    color: '#4169E1',
  },
  {
    emoji: '🐠',
    name: 'tropical fish',
    keywords: ['fish', 'tropical', 'swim'],
    category: 'animals',
    color: '#FFD700',
  },
  {
    emoji: '🐡',
    name: 'blowfish',
    keywords: ['fish', 'pufferfish', 'nature'],
    category: 'animals',
    color: '#FFD700',
  },
  {
    emoji: '🦈',
    name: 'shark',
    keywords: ['shark', 'jaws', 'fin'],
    category: 'animals',
    color: '#696969',
  },
  {
    emoji: '🐙',
    name: 'octopus',
    keywords: ['octopus', 'animal', 'creature'],
    category: 'animals',
    color: '#FF69B4',
  },
  {
    emoji: '🐚',
    name: 'spiral shell',
    keywords: ['shell', 'sea', 'beach'],
    category: 'animals',
    color: '#FFB6C1',
  },

  // Invertebrates
  {
    emoji: '🐌',
    name: 'snail',
    keywords: ['snail', 'slow', 'shell'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🦋',
    name: 'butterfly',
    keywords: ['butterfly', 'insect', 'nature'],
    category: 'animals',
    color: '#9370DB',
  },
  {
    emoji: '🐛',
    name: 'bug',
    keywords: ['bug', 'insect', 'worm'],
    category: 'animals',
    color: '#90EE90',
  },
  {
    emoji: '🐜',
    name: 'ant',
    keywords: ['ant', 'insect', 'nature'],
    category: 'animals',
    color: '#000000',
  },
  {
    emoji: '🐝',
    name: 'honeybee',
    keywords: ['bee', 'honeybee', 'insect'],
    category: 'animals',
    color: '#FFD700',
  },
  {
    emoji: '🪲',
    name: 'beetle',
    keywords: ['beetle', 'bug', 'insect'],
    category: 'animals',
    color: '#000000',
  },
  {
    emoji: '🐞',
    name: 'lady beetle',
    keywords: ['ladybug', 'insect', 'nature'],
    category: 'animals',
    color: '#DC143C',
  },
  {
    emoji: '🦗',
    name: 'cricket',
    keywords: ['cricket', 'grasshopper', 'chirp'],
    category: 'animals',
    color: '#228B22',
  },
  {
    emoji: '🪳',
    name: 'cockroach',
    keywords: ['cockroach', 'pest', 'pests'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🕷️',
    name: 'spider',
    keywords: ['spider', 'arachnid', 'insect'],
    category: 'animals',
    color: '#000000',
  },
  {
    emoji: '🕸️',
    name: 'spider web',
    keywords: ['web', 'spider', 'cobweb'],
    category: 'animals',
    color: '#D3D3D3',
  },
  {
    emoji: '🦂',
    name: 'scorpion',
    keywords: ['scorpion', 'zodiac', 'sting'],
    category: 'animals',
    color: '#8B4513',
  },
  {
    emoji: '🦟',
    name: 'mosquito',
    keywords: ['mosquito', 'insect', 'malaria'],
    category: 'animals',
    color: '#696969',
  },
  {
    emoji: '🪰',
    name: 'fly',
    keywords: ['fly', 'insect', 'pest'],
    category: 'animals',
    color: '#000000',
  },
  {
    emoji: '🪱',
    name: 'worm',
    keywords: ['worm', 'parasite', 'annelid'],
    category: 'animals',
    color: '#FFB6C1',
  },
  {
    emoji: '🦠',
    name: 'microbe',
    keywords: ['germ', 'coronavirus', 'bacteria'],
    category: 'animals',
    color: '#90EE90',
  },

  // Marine invertebrates
  {
    emoji: '🦀',
    name: 'crab',
    keywords: ['crab', 'crustacean', 'cancer'],
    category: 'animals',
    color: '#DC143C',
  },
  {
    emoji: '🦞',
    name: 'lobster',
    keywords: ['lobster', 'seafood', 'bisque'],
    category: 'animals',
    color: '#DC143C',
  },
  {
    emoji: '🦐',
    name: 'shrimp',
    keywords: ['shrimp', 'seafood', 'small'],
    category: 'animals',
    color: '#FF69B4',
  },
  {
    emoji: '🦑',
    name: 'squid',
    keywords: ['squid', 'animal', 'nature'],
    category: 'animals',
    color: '#FF69B4',
  },
  {
    emoji: '🦪',
    name: 'oyster',
    keywords: ['oyster', 'food', 'pearl'],
    category: 'animals',
    color: '#D3D3D3',
  },

  // Footprints
  {
    emoji: '🐾',
    name: 'paw prints',
    keywords: ['paw', 'feet', 'footprints'],
    category: 'animals',
    color: '#8B4513',
  },
];
