import type { Emoji } from '../../schema';

export const flagEmojis: Omit<Emoji, 'sentiment'>[] = [
  // Common country flags
  {
    emoji: '🇺🇸',
    name: 'flag: United States',
    keywords: ['usa', 'america', 'united states', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇬🇧',
    name: 'flag: United Kingdom',
    keywords: ['uk', 'britain', 'england', 'united kingdom', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇨🇦',
    name: 'flag: Canada',
    keywords: ['canada', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇦🇺',
    name: 'flag: Australia',
    keywords: ['australia', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇩🇪',
    name: 'flag: Germany',
    keywords: ['germany', 'deutschland', 'flag', 'country'],
    category: 'flags',
    color: '#000000',
  },
  {
    emoji: '🇫🇷',
    name: 'flag: France',
    keywords: ['france', 'french', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇮🇹',
    name: 'flag: Italy',
    keywords: ['italy', 'italian', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇪🇸',
    name: 'flag: Spain',
    keywords: ['spain', 'spanish', 'flag', 'country'],
    category: 'flags',
    color: '#FFD700',
  },
  {
    emoji: '🇯🇵',
    name: 'flag: Japan',
    keywords: ['japan', 'japanese', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇰🇷',
    name: 'flag: South Korea',
    keywords: ['korea', 'south korea', 'flag', 'country'],
    category: 'flags',
    color: '#003478',
  },
  {
    emoji: '🇨🇳',
    name: 'flag: China',
    keywords: ['china', 'chinese', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇮🇳',
    name: 'flag: India',
    keywords: ['india', 'indian', 'flag', 'country'],
    category: 'flags',
    color: '#FF9933',
  },
  {
    emoji: '🇧🇷',
    name: 'flag: Brazil',
    keywords: ['brazil', 'brazilian', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇲🇽',
    name: 'flag: Mexico',
    keywords: ['mexico', 'mexican', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇦🇷',
    name: 'flag: Argentina',
    keywords: ['argentina', 'argentinian', 'flag', 'country'],
    category: 'flags',
    color: '#87CEEB',
  },
  {
    emoji: '🇷🇺',
    name: 'flag: Russia',
    keywords: ['russia', 'russian', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇳🇱',
    name: 'flag: Netherlands',
    keywords: ['netherlands', 'dutch', 'holland', 'flag', 'country'],
    category: 'flags',
    color: '#FF9933',
  },
  {
    emoji: '🇧🇪',
    name: 'flag: Belgium',
    keywords: ['belgium', 'belgian', 'flag', 'country'],
    category: 'flags',
    color: '#000000',
  },
  {
    emoji: '🇨🇭',
    name: 'flag: Switzerland',
    keywords: ['switzerland', 'swiss', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇸🇪',
    name: 'flag: Sweden',
    keywords: ['sweden', 'swedish', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇳🇴',
    name: 'flag: Norway',
    keywords: ['norway', 'norwegian', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇩🇰',
    name: 'flag: Denmark',
    keywords: ['denmark', 'danish', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇫🇮',
    name: 'flag: Finland',
    keywords: ['finland', 'finnish', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇮🇸',
    name: 'flag: Iceland',
    keywords: ['iceland', 'icelandic', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇮🇪',
    name: 'flag: Ireland',
    keywords: ['ireland', 'irish', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇵🇱',
    name: 'flag: Poland',
    keywords: ['poland', 'polish', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇺🇦',
    name: 'flag: Ukraine',
    keywords: ['ukraine', 'ukrainian', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇬🇷',
    name: 'flag: Greece',
    keywords: ['greece', 'greek', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇹🇷',
    name: 'flag: Turkey',
    keywords: ['turkey', 'turkish', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇮🇱',
    name: 'flag: Israel',
    keywords: ['israel', 'israeli', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇸🇦',
    name: 'flag: Saudi Arabia',
    keywords: ['saudi arabia', 'saudi', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇦🇪',
    name: 'flag: United Arab Emirates',
    keywords: ['uae', 'emirates', 'dubai', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇪🇬',
    name: 'flag: Egypt',
    keywords: ['egypt', 'egyptian', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇿🇦',
    name: 'flag: South Africa',
    keywords: ['south africa', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇳🇬',
    name: 'flag: Nigeria',
    keywords: ['nigeria', 'nigerian', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇰🇪',
    name: 'flag: Kenya',
    keywords: ['kenya', 'kenyan', 'flag', 'country'],
    category: 'flags',
    color: '#000000',
  },
  {
    emoji: '🇦🇹',
    name: 'flag: Austria',
    keywords: ['austria', 'austrian', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇵🇹',
    name: 'flag: Portugal',
    keywords: ['portugal', 'portuguese', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇨🇿',
    name: 'flag: Czechia',
    keywords: ['czech', 'czechia', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇭🇺',
    name: 'flag: Hungary',
    keywords: ['hungary', 'hungarian', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇷🇴',
    name: 'flag: Romania',
    keywords: ['romania', 'romanian', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇧🇬',
    name: 'flag: Bulgaria',
    keywords: ['bulgaria', 'bulgarian', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇸🇰',
    name: 'flag: Slovakia',
    keywords: ['slovakia', 'slovak', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇸🇮',
    name: 'flag: Slovenia',
    keywords: ['slovenia', 'slovenian', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇭🇷',
    name: 'flag: Croatia',
    keywords: ['croatia', 'croatian', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇷🇸',
    name: 'flag: Serbia',
    keywords: ['serbia', 'serbian', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇳🇿',
    name: 'flag: New Zealand',
    keywords: ['new zealand', 'kiwi', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇸🇬',
    name: 'flag: Singapore',
    keywords: ['singapore', 'singaporean', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇲🇾',
    name: 'flag: Malaysia',
    keywords: ['malaysia', 'malaysian', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇹🇭',
    name: 'flag: Thailand',
    keywords: ['thailand', 'thai', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇻🇳',
    name: 'flag: Vietnam',
    keywords: ['vietnam', 'vietnamese', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇵🇭',
    name: 'flag: Philippines',
    keywords: ['philippines', 'filipino', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇮🇩',
    name: 'flag: Indonesia',
    keywords: ['indonesia', 'indonesian', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇵🇰',
    name: 'flag: Pakistan',
    keywords: ['pakistan', 'pakistani', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇧🇩',
    name: 'flag: Bangladesh',
    keywords: ['bangladesh', 'bangladeshi', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇱🇰',
    name: 'flag: Sri Lanka',
    keywords: ['sri lanka', 'sri lankan', 'flag', 'country'],
    category: 'flags',
    color: '#FFD700',
  },
  {
    emoji: '🇹🇼',
    name: 'flag: Taiwan',
    keywords: ['taiwan', 'taiwanese', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇭🇰',
    name: 'flag: Hong Kong SAR China',
    keywords: ['hong kong', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇲🇴',
    name: 'flag: Macao SAR China',
    keywords: ['macao', 'macau', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇨🇱',
    name: 'flag: Chile',
    keywords: ['chile', 'chilean', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇵🇪',
    name: 'flag: Peru',
    keywords: ['peru', 'peruvian', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇨🇴',
    name: 'flag: Colombia',
    keywords: ['colombia', 'colombian', 'flag', 'country'],
    category: 'flags',
    color: '#FFD700',
  },
  {
    emoji: '🇻🇪',
    name: 'flag: Venezuela',
    keywords: ['venezuela', 'venezuelan', 'flag', 'country'],
    category: 'flags',
    color: '#FFD700',
  },
  {
    emoji: '🇪🇨',
    name: 'flag: Ecuador',
    keywords: ['ecuador', 'ecuadorian', 'flag', 'country'],
    category: 'flags',
    color: '#FFD700',
  },
  {
    emoji: '🇺🇾',
    name: 'flag: Uruguay',
    keywords: ['uruguay', 'uruguayan', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🇵🇾',
    name: 'flag: Paraguay',
    keywords: ['paraguay', 'paraguayan', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇧🇴',
    name: 'flag: Bolivia',
    keywords: ['bolivia', 'bolivian', 'flag', 'country'],
    category: 'flags',
    color: '#FFD700',
  },
  {
    emoji: '🇨🇺',
    name: 'flag: Cuba',
    keywords: ['cuba', 'cuban', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇯🇲',
    name: 'flag: Jamaica',
    keywords: ['jamaica', 'jamaican', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇵🇷',
    name: 'flag: Puerto Rico',
    keywords: ['puerto rico', 'puerto rican', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇲🇦',
    name: 'flag: Morocco',
    keywords: ['morocco', 'moroccan', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇹🇳',
    name: 'flag: Tunisia',
    keywords: ['tunisia', 'tunisian', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇩🇿',
    name: 'flag: Algeria',
    keywords: ['algeria', 'algerian', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇱🇾',
    name: 'flag: Libya',
    keywords: ['libya', 'libyan', 'flag', 'country'],
    category: 'flags',
    color: '#000000',
  },
  {
    emoji: '🇪🇹',
    name: 'flag: Ethiopia',
    keywords: ['ethiopia', 'ethiopian', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇬🇭',
    name: 'flag: Ghana',
    keywords: ['ghana', 'ghanaian', 'flag', 'country'],
    category: 'flags',
    color: '#FFD700',
  },
  {
    emoji: '🇨🇮',
    name: "flag: Côte d'Ivoire",
    keywords: ['ivory coast', 'flag', 'country'],
    category: 'flags',
    color: '#FF9933',
  },
  {
    emoji: '🇸🇳',
    name: 'flag: Senegal',
    keywords: ['senegal', 'senegalese', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇹🇿',
    name: 'flag: Tanzania',
    keywords: ['tanzania', 'tanzanian', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇺🇬',
    name: 'flag: Uganda',
    keywords: ['uganda', 'ugandan', 'flag', 'country'],
    category: 'flags',
    color: '#FFD700',
  },
  {
    emoji: '🇿🇼',
    name: 'flag: Zimbabwe',
    keywords: ['zimbabwe', 'zimbabwean', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇿🇲',
    name: 'flag: Zambia',
    keywords: ['zambia', 'zambian', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇦🇴',
    name: 'flag: Angola',
    keywords: ['angola', 'angolan', 'flag', 'country'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🇲🇿',
    name: 'flag: Mozambique',
    keywords: ['mozambique', 'mozambican', 'flag', 'country'],
    category: 'flags',
    color: '#008C45',
  },
  {
    emoji: '🇧🇼',
    name: 'flag: Botswana',
    keywords: ['botswana', 'flag', 'country'],
    category: 'flags',
    color: '#87CEEB',
  },
  {
    emoji: '🇳🇦',
    name: 'flag: Namibia',
    keywords: ['namibia', 'namibian', 'flag', 'country'],
    category: 'flags',
    color: '#0000FF',
  },
  
  // Special flags
  {
    emoji: '🏳️',
    name: 'white flag',
    keywords: ['white', 'flag', 'surrender', 'peace'],
    category: 'flags',
    color: '#FFFFFF',
  },
  {
    emoji: '🏴',
    name: 'black flag',
    keywords: ['black', 'flag', 'pirate'],
    category: 'flags',
    color: '#000000',
  },
  {
    emoji: '🏁',
    name: 'chequered flag',
    keywords: ['checkered', 'racing', 'finish', 'flag'],
    category: 'flags',
    color: '#000000',
  },
  {
    emoji: '🚩',
    name: 'triangular flag',
    keywords: ['red', 'flag', 'warning', 'triangular'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🏳️‍🌈',
    name: 'rainbow flag',
    keywords: ['rainbow', 'pride', 'lgbtq', 'flag'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🏳️‍⚧️',
    name: 'transgender flag',
    keywords: ['transgender', 'trans', 'pride', 'flag'],
    category: 'flags',
    color: '#87CEEB',
  },
  {
    emoji: '🏴‍☠️',
    name: 'pirate flag',
    keywords: ['pirate', 'skull', 'crossbones', 'flag'],
    category: 'flags',
    color: '#000000',
  },
  {
    emoji: '🇺🇳',
    name: 'flag: United Nations',
    keywords: ['un', 'united nations', 'flag', 'international'],
    category: 'flags',
    color: '#87CEEB',
  },
  {
    emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    name: 'flag: England',
    keywords: ['england', 'english', 'flag'],
    category: 'flags',
    color: '#FF0000',
  },
  {
    emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    name: 'flag: Scotland',
    keywords: ['scotland', 'scottish', 'flag'],
    category: 'flags',
    color: '#0000FF',
  },
  {
    emoji: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    name: 'flag: Wales',
    keywords: ['wales', 'welsh', 'flag'],
    category: 'flags',
    color: '#FF0000',
  },
];