import type { Emoji } from '../../schema';

// Generated from OpenMoji dataset - 270 emojis
// Unicode versions up to 15.1 + OpenMoji extras
export const flagsEmojisAll: Omit<Emoji, 'sentiment'>[] = [
  {
    emoji: '🏁',
    name: 'chequered flag',
    keywords: ['checkered', 'chequered', 'finish', 'flag', 'flags', 'game', 'race', 'racing', 'sport', 'win'],
    category: 'flags',
    subcategory: 'flag',
    unicode: '1F3C1',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚩',
    name: 'triangular flag',
    keywords: ['construction', 'flag', 'golf', 'post', 'triangular'],
    category: 'flags',
    subcategory: 'flag',
    unicode: '1F6A9',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎌',
    name: 'crossed flags',
    keywords: ['celebration', 'cross', 'crossed', 'flags', 'japanese'],
    category: 'flags',
    subcategory: 'flag',
    unicode: '1F38C',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🏴',
    name: 'black flag',
    keywords: ['black', 'flag', 'waving'],
    category: 'flags',
    subcategory: 'flag',
    unicode: '1F3F4',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏳️',
    name: 'white flag',
    keywords: ['flag', 'waving', 'white'],
    category: 'flags',
    subcategory: 'flag',
    unicode: '1F3F3',
    version: '0.7',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏳️‍🌈',
    name: 'rainbow flag',
    keywords: ['bisexual', 'flag', 'gay', 'genderqueer', 'glbt', 'glbtq', 'lesbian', 'lgbt', 'lgbtq', 'lgbtqia', 'pride', 'queer', 'rainbow', 'trans', 'transgender'],
    category: 'flags',
    subcategory: 'flag',
    unicode: '1F3F3 FE0F 200D 1F308',
    version: '4',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏳️‍⚧️',
    name: 'transgender flag',
    keywords: ['blue', 'flag', 'light', 'pink', 'transgender', 'white'],
    category: 'flags',
    subcategory: 'flag',
    unicode: '1F3F3 FE0F 200D 26A7 FE0F',
    version: '13',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏴‍☠️',
    name: 'pirate flag',
    keywords: ['flag', 'jolly', 'pirate', 'plunder', 'roger', 'treasure'],
    category: 'flags',
    subcategory: 'flag',
    unicode: '1F3F4 200D 2620 FE0F',
    version: '11',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇨',
    name: 'flag: ascension island',
    keywords: ['AC', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1E8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇩',
    name: 'flag: andorra',
    keywords: ['AD', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1E9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇪',
    name: 'flag: united arab emirates',
    keywords: ['AE', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1EA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇫',
    name: 'flag: afghanistan',
    keywords: ['AF', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1EB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇬',
    name: 'flag: antigua & barbuda',
    keywords: ['AG', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1EC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇮',
    name: 'flag: anguilla',
    keywords: ['AI', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1EE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇱',
    name: 'flag: albania',
    keywords: ['AL', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1F1',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇲',
    name: 'flag: armenia',
    keywords: ['AM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇴',
    name: 'flag: angola',
    keywords: ['AO', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1F4',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇶',
    name: 'flag: antarctica',
    keywords: ['AQ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1F6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇷',
    name: 'flag: argentina',
    keywords: ['AR', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1F7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇸',
    name: 'flag: american samoa',
    keywords: ['AS', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1F8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇹',
    name: 'flag: austria',
    keywords: ['AT', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1F9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇺',
    name: 'flag: australia',
    keywords: ['AU', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1FA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇼',
    name: 'flag: aruba',
    keywords: ['AW', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1FC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇽',
    name: 'flag: åland islands',
    keywords: ['AX', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1FD',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇦🇿',
    name: 'flag: azerbaijan',
    keywords: ['AZ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E6 1F1FF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇦',
    name: 'flag: bosnia & herzegovina',
    keywords: ['BA', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1E6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇧',
    name: 'flag: barbados',
    keywords: ['BB', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1E7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇩',
    name: 'flag: bangladesh',
    keywords: ['BD', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1E9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇪',
    name: 'flag: belgium',
    keywords: ['BE', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1EA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇫',
    name: 'flag: burkina faso',
    keywords: ['BF', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1EB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇬',
    name: 'flag: bulgaria',
    keywords: ['BG', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1EC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇭',
    name: 'flag: bahrain',
    keywords: ['BH', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1ED',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇮',
    name: 'flag: burundi',
    keywords: ['BI', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1EE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇯',
    name: 'flag: benin',
    keywords: ['BJ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1EF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇱',
    name: 'flag: st. barthélemy',
    keywords: ['BL', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1F1',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇲',
    name: 'flag: bermuda',
    keywords: ['BM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇳',
    name: 'flag: brunei',
    keywords: ['BN', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1F3',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇴',
    name: 'flag: bolivia',
    keywords: ['BO', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1F4',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇶',
    name: 'flag: caribbean netherlands',
    keywords: ['BQ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1F6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇷',
    name: 'flag: brazil',
    keywords: ['BR', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1F7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇸',
    name: 'flag: bahamas',
    keywords: ['BS', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1F8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇹',
    name: 'flag: bhutan',
    keywords: ['BT', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1F9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇻',
    name: 'flag: bouvet island',
    keywords: ['BV', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1FB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇼',
    name: 'flag: botswana',
    keywords: ['BW', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1FC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇾',
    name: 'flag: belarus',
    keywords: ['BY', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1FE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇧🇿',
    name: 'flag: belize',
    keywords: ['BZ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E7 1F1FF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇦',
    name: 'flag: canada',
    keywords: ['CA', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1E6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇨',
    name: 'flag: cocos (keeling) islands',
    keywords: ['CC', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1E8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇩',
    name: 'flag: congo - kinshasa',
    keywords: ['CD', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1E9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇫',
    name: 'flag: central african republic',
    keywords: ['CF', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1EB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇬',
    name: 'flag: congo - brazzaville',
    keywords: ['CG', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1EC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇭',
    name: 'flag: switzerland',
    keywords: ['CH', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1ED',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇮',
    name: 'flag: côte d’ivoire',
    keywords: ['CI', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1EE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇰',
    name: 'flag: cook islands',
    keywords: ['CK', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1F0',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇱',
    name: 'flag: chile',
    keywords: ['CL', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1F1',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇲',
    name: 'flag: cameroon',
    keywords: ['CM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇳',
    name: 'flag: china',
    keywords: ['CN', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1F3',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇴',
    name: 'flag: colombia',
    keywords: ['CO', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1F4',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇵',
    name: 'flag: clipperton island',
    keywords: ['CP', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1F5',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇶',
    name: 'flag: sark',
    keywords: ['CQ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1F6',
    version: '16',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇷',
    name: 'flag: costa rica',
    keywords: ['CR', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1F7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇺',
    name: 'flag: cuba',
    keywords: ['CU', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1FA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇻',
    name: 'flag: cape verde',
    keywords: ['CV', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1FB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇼',
    name: 'flag: curaçao',
    keywords: ['CW', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1FC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇽',
    name: 'flag: christmas island',
    keywords: ['CX', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1FD',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇾',
    name: 'flag: cyprus',
    keywords: ['CY', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1FE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇨🇿',
    name: 'flag: czechia',
    keywords: ['CZ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E8 1F1FF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇩🇪',
    name: 'flag: germany',
    keywords: ['DE', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E9 1F1EA',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇩🇬',
    name: 'flag: diego garcia',
    keywords: ['DG', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E9 1F1EC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇩🇯',
    name: 'flag: djibouti',
    keywords: ['DJ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E9 1F1EF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇩🇰',
    name: 'flag: denmark',
    keywords: ['DK', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E9 1F1F0',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇩🇲',
    name: 'flag: dominica',
    keywords: ['DM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E9 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇩🇴',
    name: 'flag: dominican republic',
    keywords: ['DO', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E9 1F1F4',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇩🇿',
    name: 'flag: algeria',
    keywords: ['DZ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1E9 1F1FF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇪🇦',
    name: 'flag: ceuta & melilla',
    keywords: ['EA', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EA 1F1E6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇪🇨',
    name: 'flag: ecuador',
    keywords: ['EC', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EA 1F1E8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇪🇪',
    name: 'flag: estonia',
    keywords: ['EE', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EA 1F1EA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇪🇬',
    name: 'flag: egypt',
    keywords: ['EG', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EA 1F1EC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇪🇭',
    name: 'flag: western sahara',
    keywords: ['EH', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EA 1F1ED',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇪🇷',
    name: 'flag: eritrea',
    keywords: ['ER', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EA 1F1F7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇪🇸',
    name: 'flag: spain',
    keywords: ['ES', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EA 1F1F8',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇪🇹',
    name: 'flag: ethiopia',
    keywords: ['ET', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EA 1F1F9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇪🇺',
    name: 'flag: european union',
    keywords: ['EU', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EA 1F1FA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇫🇮',
    name: 'flag: finland',
    keywords: ['FI', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EB 1F1EE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇫🇯',
    name: 'flag: fiji',
    keywords: ['FJ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EB 1F1EF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇫🇰',
    name: 'flag: falkland islands',
    keywords: ['FK', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EB 1F1F0',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇫🇲',
    name: 'flag: micronesia',
    keywords: ['FM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EB 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇫🇴',
    name: 'flag: faroe islands',
    keywords: ['FO', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EB 1F1F4',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇫🇷',
    name: 'flag: france',
    keywords: ['FR', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EB 1F1F7',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇦',
    name: 'flag: gabon',
    keywords: ['GA', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1E6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇧',
    name: 'flag: united kingdom',
    keywords: ['GB', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1E7',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇩',
    name: 'flag: grenada',
    keywords: ['GD', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1E9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇪',
    name: 'flag: georgia',
    keywords: ['GE', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1EA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇫',
    name: 'flag: french guiana',
    keywords: ['GF', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1EB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇬',
    name: 'flag: guernsey',
    keywords: ['GG', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1EC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇭',
    name: 'flag: ghana',
    keywords: ['GH', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1ED',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇮',
    name: 'flag: gibraltar',
    keywords: ['GI', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1EE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇱',
    name: 'flag: greenland',
    keywords: ['GL', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1F1',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇲',
    name: 'flag: gambia',
    keywords: ['GM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇳',
    name: 'flag: guinea',
    keywords: ['GN', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1F3',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇵',
    name: 'flag: guadeloupe',
    keywords: ['GP', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1F5',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇶',
    name: 'flag: equatorial guinea',
    keywords: ['GQ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1F6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇷',
    name: 'flag: greece',
    keywords: ['GR', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1F7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇸',
    name: 'flag: south georgia & south sandwich islands',
    keywords: ['GS', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1F8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇹',
    name: 'flag: guatemala',
    keywords: ['GT', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1F9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇺',
    name: 'flag: guam',
    keywords: ['GU', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1FA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇼',
    name: 'flag: guinea-bissau',
    keywords: ['GW', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1FC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇬🇾',
    name: 'flag: guyana',
    keywords: ['GY', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EC 1F1FE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇭🇰',
    name: 'flag: hong kong sar china',
    keywords: ['HK', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1ED 1F1F0',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇭🇲',
    name: 'flag: heard & mcdonald islands',
    keywords: ['HM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1ED 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇭🇳',
    name: 'flag: honduras',
    keywords: ['HN', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1ED 1F1F3',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇭🇷',
    name: 'flag: croatia',
    keywords: ['HR', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1ED 1F1F7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇭🇹',
    name: 'flag: haiti',
    keywords: ['HT', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1ED 1F1F9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇭🇺',
    name: 'flag: hungary',
    keywords: ['HU', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1ED 1F1FA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇮🇨',
    name: 'flag: canary islands',
    keywords: ['IC', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EE 1F1E8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇮🇩',
    name: 'flag: indonesia',
    keywords: ['ID', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EE 1F1E9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇮🇪',
    name: 'flag: ireland',
    keywords: ['IE', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EE 1F1EA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇮🇱',
    name: 'flag: israel',
    keywords: ['IL', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EE 1F1F1',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇮🇲',
    name: 'flag: isle of man',
    keywords: ['IM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EE 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇮🇳',
    name: 'flag: india',
    keywords: ['IN', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EE 1F1F3',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇮🇴',
    name: 'flag: british indian ocean territory',
    keywords: ['IO', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EE 1F1F4',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇮🇶',
    name: 'flag: iraq',
    keywords: ['IQ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EE 1F1F6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇮🇷',
    name: 'flag: iran',
    keywords: ['IR', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EE 1F1F7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇮🇸',
    name: 'flag: iceland',
    keywords: ['IS', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EE 1F1F8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇮🇹',
    name: 'flag: italy',
    keywords: ['IT', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EE 1F1F9',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇯🇪',
    name: 'flag: jersey',
    keywords: ['JE', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EF 1F1EA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇯🇲',
    name: 'flag: jamaica',
    keywords: ['JM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EF 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇯🇴',
    name: 'flag: jordan',
    keywords: ['JO', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EF 1F1F4',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇯🇵',
    name: 'flag: japan',
    keywords: ['JP', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1EF 1F1F5',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇰🇪',
    name: 'flag: kenya',
    keywords: ['KE', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F0 1F1EA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇰🇬',
    name: 'flag: kyrgyzstan',
    keywords: ['KG', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F0 1F1EC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇰🇭',
    name: 'flag: cambodia',
    keywords: ['KH', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F0 1F1ED',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇰🇮',
    name: 'flag: kiribati',
    keywords: ['KI', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F0 1F1EE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇰🇲',
    name: 'flag: comoros',
    keywords: ['KM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F0 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇰🇳',
    name: 'flag: st. kitts & nevis',
    keywords: ['KN', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F0 1F1F3',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇰🇵',
    name: 'flag: north korea',
    keywords: ['KP', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F0 1F1F5',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇰🇷',
    name: 'flag: south korea',
    keywords: ['KR', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F0 1F1F7',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇰🇼',
    name: 'flag: kuwait',
    keywords: ['KW', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F0 1F1FC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇰🇾',
    name: 'flag: cayman islands',
    keywords: ['KY', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F0 1F1FE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇰🇿',
    name: 'flag: kazakhstan',
    keywords: ['KZ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F0 1F1FF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇱🇦',
    name: 'flag: laos',
    keywords: ['LA', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F1 1F1E6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇱🇧',
    name: 'flag: lebanon',
    keywords: ['LB', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F1 1F1E7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇱🇨',
    name: 'flag: st. lucia',
    keywords: ['LC', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F1 1F1E8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇱🇮',
    name: 'flag: liechtenstein',
    keywords: ['LI', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F1 1F1EE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇱🇰',
    name: 'flag: sri lanka',
    keywords: ['LK', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F1 1F1F0',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇱🇷',
    name: 'flag: liberia',
    keywords: ['LR', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F1 1F1F7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇱🇸',
    name: 'flag: lesotho',
    keywords: ['LS', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F1 1F1F8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇱🇹',
    name: 'flag: lithuania',
    keywords: ['LT', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F1 1F1F9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇱🇺',
    name: 'flag: luxembourg',
    keywords: ['LU', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F1 1F1FA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇱🇻',
    name: 'flag: latvia',
    keywords: ['LV', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F1 1F1FB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇱🇾',
    name: 'flag: libya',
    keywords: ['LY', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F1 1F1FE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇦',
    name: 'flag: morocco',
    keywords: ['MA', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1E6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇨',
    name: 'flag: monaco',
    keywords: ['MC', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1E8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇩',
    name: 'flag: moldova',
    keywords: ['MD', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1E9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇪',
    name: 'flag: montenegro',
    keywords: ['ME', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1EA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇫',
    name: 'flag: st. martin',
    keywords: ['MF', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1EB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇬',
    name: 'flag: madagascar',
    keywords: ['MG', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1EC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇭',
    name: 'flag: marshall islands',
    keywords: ['MH', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1ED',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇰',
    name: 'flag: north macedonia',
    keywords: ['MK', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1F0',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇱',
    name: 'flag: mali',
    keywords: ['ML', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1F1',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇲',
    name: 'flag: myanmar (burma)',
    keywords: ['MM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇳',
    name: 'flag: mongolia',
    keywords: ['MN', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1F3',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇴',
    name: 'flag: macao sar china',
    keywords: ['MO', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1F4',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇵',
    name: 'flag: northern mariana islands',
    keywords: ['MP', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1F5',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇶',
    name: 'flag: martinique',
    keywords: ['MQ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1F6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇷',
    name: 'flag: mauritania',
    keywords: ['MR', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1F7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇸',
    name: 'flag: montserrat',
    keywords: ['MS', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1F8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇹',
    name: 'flag: malta',
    keywords: ['MT', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1F9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇺',
    name: 'flag: mauritius',
    keywords: ['MU', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1FA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇻',
    name: 'flag: maldives',
    keywords: ['MV', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1FB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇼',
    name: 'flag: malawi',
    keywords: ['MW', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1FC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇽',
    name: 'flag: mexico',
    keywords: ['MX', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1FD',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇾',
    name: 'flag: malaysia',
    keywords: ['MY', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1FE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇲🇿',
    name: 'flag: mozambique',
    keywords: ['MZ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F2 1F1FF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇳🇦',
    name: 'flag: namibia',
    keywords: ['NA', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F3 1F1E6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇳🇨',
    name: 'flag: new caledonia',
    keywords: ['NC', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F3 1F1E8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇳🇪',
    name: 'flag: niger',
    keywords: ['NE', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F3 1F1EA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇳🇫',
    name: 'flag: norfolk island',
    keywords: ['NF', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F3 1F1EB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇳🇬',
    name: 'flag: nigeria',
    keywords: ['NG', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F3 1F1EC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇳🇮',
    name: 'flag: nicaragua',
    keywords: ['NI', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F3 1F1EE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇳🇱',
    name: 'flag: netherlands',
    keywords: ['NL', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F3 1F1F1',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇳🇴',
    name: 'flag: norway',
    keywords: ['NO', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F3 1F1F4',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇳🇵',
    name: 'flag: nepal',
    keywords: ['NP', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F3 1F1F5',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇳🇷',
    name: 'flag: nauru',
    keywords: ['NR', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F3 1F1F7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇳🇺',
    name: 'flag: niue',
    keywords: ['NU', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F3 1F1FA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇳🇿',
    name: 'flag: new zealand',
    keywords: ['NZ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F3 1F1FF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇴🇲',
    name: 'flag: oman',
    keywords: ['OM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F4 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇵🇦',
    name: 'flag: panama',
    keywords: ['PA', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F5 1F1E6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇵🇪',
    name: 'flag: peru',
    keywords: ['PE', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F5 1F1EA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇵🇫',
    name: 'flag: french polynesia',
    keywords: ['PF', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F5 1F1EB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇵🇬',
    name: 'flag: papua new guinea',
    keywords: ['PG', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F5 1F1EC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇵🇭',
    name: 'flag: philippines',
    keywords: ['PH', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F5 1F1ED',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇵🇰',
    name: 'flag: pakistan',
    keywords: ['PK', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F5 1F1F0',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇵🇱',
    name: 'flag: poland',
    keywords: ['PL', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F5 1F1F1',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇵🇲',
    name: 'flag: st. pierre & miquelon',
    keywords: ['PM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F5 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇵🇳',
    name: 'flag: pitcairn islands',
    keywords: ['PN', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F5 1F1F3',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇵🇷',
    name: 'flag: puerto rico',
    keywords: ['PR', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F5 1F1F7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇵🇸',
    name: 'flag: palestinian territories',
    keywords: ['PS', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F5 1F1F8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇵🇹',
    name: 'flag: portugal',
    keywords: ['PT', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F5 1F1F9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇵🇼',
    name: 'flag: palau',
    keywords: ['PW', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F5 1F1FC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇵🇾',
    name: 'flag: paraguay',
    keywords: ['PY', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F5 1F1FE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇶🇦',
    name: 'flag: qatar',
    keywords: ['QA', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F6 1F1E6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇷🇪',
    name: 'flag: réunion',
    keywords: ['RE', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F7 1F1EA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇷🇴',
    name: 'flag: romania',
    keywords: ['RO', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F7 1F1F4',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇷🇸',
    name: 'flag: serbia',
    keywords: ['RS', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F7 1F1F8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇷🇺',
    name: 'flag: russia',
    keywords: ['RU', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F7 1F1FA',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇷🇼',
    name: 'flag: rwanda',
    keywords: ['RW', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F7 1F1FC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇦',
    name: 'flag: saudi arabia',
    keywords: ['SA', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1E6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇧',
    name: 'flag: solomon islands',
    keywords: ['SB', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1E7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇨',
    name: 'flag: seychelles',
    keywords: ['SC', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1E8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇩',
    name: 'flag: sudan',
    keywords: ['SD', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1E9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇪',
    name: 'flag: sweden',
    keywords: ['SE', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1EA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇬',
    name: 'flag: singapore',
    keywords: ['SG', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1EC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇭',
    name: 'flag: st. helena',
    keywords: ['SH', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1ED',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇮',
    name: 'flag: slovenia',
    keywords: ['SI', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1EE',
    version: '2',
    color: '#0000FF',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🇸🇯',
    name: 'flag: svalbard & jan mayen',
    keywords: ['SJ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1EF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇰',
    name: 'flag: slovakia',
    keywords: ['SK', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1F0',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇱',
    name: 'flag: sierra leone',
    keywords: ['SL', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1F1',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇲',
    name: 'flag: san marino',
    keywords: ['SM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇳',
    name: 'flag: senegal',
    keywords: ['SN', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1F3',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇴',
    name: 'flag: somalia',
    keywords: ['SO', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1F4',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇷',
    name: 'flag: suriname',
    keywords: ['SR', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1F7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇸',
    name: 'flag: south sudan',
    keywords: ['SS', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1F8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇹',
    name: 'flag: são tomé & príncipe',
    keywords: ['ST', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1F9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇻',
    name: 'flag: el salvador',
    keywords: ['SV', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1FB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇽',
    name: 'flag: sint maarten',
    keywords: ['SX', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1FD',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇾',
    name: 'flag: syria',
    keywords: ['SY', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1FE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇸🇿',
    name: 'flag: eswatini',
    keywords: ['SZ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F8 1F1FF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇦',
    name: 'flag: tristan da cunha',
    keywords: ['TA', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1E6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇨',
    name: 'flag: turks & caicos islands',
    keywords: ['TC', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1E8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇩',
    name: 'flag: chad',
    keywords: ['TD', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1E9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇫',
    name: 'flag: french southern territories',
    keywords: ['TF', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1EB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇬',
    name: 'flag: togo',
    keywords: ['TG', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1EC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇭',
    name: 'flag: thailand',
    keywords: ['TH', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1ED',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇯',
    name: 'flag: tajikistan',
    keywords: ['TJ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1EF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇰',
    name: 'flag: tokelau',
    keywords: ['TK', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1F0',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇱',
    name: 'flag: timor-leste',
    keywords: ['TL', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1F1',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇲',
    name: 'flag: turkmenistan',
    keywords: ['TM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇳',
    name: 'flag: tunisia',
    keywords: ['TN', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1F3',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇴',
    name: 'flag: tonga',
    keywords: ['TO', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1F4',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇷',
    name: 'flag: türkiye',
    keywords: ['TR', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1F7',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇹',
    name: 'flag: trinidad & tobago',
    keywords: ['TT', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1F9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇻',
    name: 'flag: tuvalu',
    keywords: ['TV', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1FB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇼',
    name: 'flag: taiwan',
    keywords: ['TW', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1FC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇹🇿',
    name: 'flag: tanzania',
    keywords: ['TZ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1F9 1F1FF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇺🇦',
    name: 'flag: ukraine',
    keywords: ['UA', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FA 1F1E6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇺🇬',
    name: 'flag: uganda',
    keywords: ['UG', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FA 1F1EC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇺🇲',
    name: 'flag: u.s. outlying islands',
    keywords: ['UM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FA 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇺🇳',
    name: 'flag: united nations',
    keywords: ['UN', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FA 1F1F3',
    version: '4',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇺🇸',
    name: 'flag: united states',
    keywords: ['US', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FA 1F1F8',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇺🇾',
    name: 'flag: uruguay',
    keywords: ['UY', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FA 1F1FE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇺🇿',
    name: 'flag: uzbekistan',
    keywords: ['UZ', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FA 1F1FF',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇻🇦',
    name: 'flag: vatican city',
    keywords: ['VA', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FB 1F1E6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇻🇨',
    name: 'flag: st. vincent & grenadines',
    keywords: ['VC', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FB 1F1E8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇻🇪',
    name: 'flag: venezuela',
    keywords: ['VE', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FB 1F1EA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇻🇬',
    name: 'flag: british virgin islands',
    keywords: ['VG', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FB 1F1EC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇻🇮',
    name: 'flag: u.s. virgin islands',
    keywords: ['VI', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FB 1F1EE',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇻🇳',
    name: 'flag: vietnam',
    keywords: ['VN', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FB 1F1F3',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇻🇺',
    name: 'flag: vanuatu',
    keywords: ['VU', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FB 1F1FA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇼🇫',
    name: 'flag: wallis & futuna',
    keywords: ['WF', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FC 1F1EB',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇼🇸',
    name: 'flag: samoa',
    keywords: ['WS', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FC 1F1F8',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇽🇰',
    name: 'flag: kosovo',
    keywords: ['XK', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FD 1F1F0',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇾🇪',
    name: 'flag: yemen',
    keywords: ['YE', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FE 1F1EA',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇾🇹',
    name: 'flag: mayotte',
    keywords: ['YT', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FE 1F1F9',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇿🇦',
    name: 'flag: south africa',
    keywords: ['ZA', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FF 1F1E6',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇿🇲',
    name: 'flag: zambia',
    keywords: ['ZM', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FF 1F1F2',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🇿🇼',
    name: 'flag: zimbabwe',
    keywords: ['ZW', 'flag'],
    category: 'flags',
    subcategory: 'country-flag',
    unicode: '1F1FF 1F1FC',
    version: '2',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    name: 'flag: england',
    keywords: ['flag', 'gbeng'],
    category: 'flags',
    subcategory: 'subdivision-flag',
    unicode: '1F3F4 E0067 E0062 E0065 E006E E0067 E007F',
    version: '5',
    color: '#008000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    name: 'flag: scotland',
    keywords: ['flag', 'gbsct'],
    category: 'flags',
    subcategory: 'subdivision-flag',
    unicode: '1F3F4 E0067 E0062 E0073 E0063 E0074 E007F',
    version: '5',
    color: '#008000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    name: 'flag: wales',
    keywords: ['flag', 'gbwls'],
    category: 'flags',
    subcategory: 'subdivision-flag',
    unicode: '1F3F4 E0067 E0062 E0077 E006C E0073 E007F',
    version: '5',
    color: '#008000',
    sentiment: 'neutral' as const,
  }
];