import type { Emoji } from '../../schema';

export const foodEmojis: Omit<Emoji, 'sentiment'>[] = [
  // Fruits
  {
    emoji: '🍏',
    name: 'green apple',
    keywords: ['apple', 'fruit', 'green'],
    category: 'food',
    color: '#90EE90',
    tags: ['fruit', 'healthy', 'apple'],
  },
  {
    emoji: '🍎',
    name: 'red apple',
    keywords: ['apple', 'fruit', 'red'],
    category: 'food',
    color: '#DC143C',
    tags: ['fruit', 'healthy', 'apple'],
  },
  {
    emoji: '🍐',
    name: 'pear',
    keywords: ['pear', 'fruit', 'nature'],
    category: 'food',
    color: '#90EE90',
    tags: ['fruit', 'pear', 'sweet'],
  },
  {
    emoji: '🍊',
    name: 'tangerine',
    keywords: ['orange', 'fruit', 'tangerine'],
    category: 'food',
    color: '#FFA500',
    tags: ['fruit', 'citrus', 'orange'],
  },
  {
    emoji: '🍋',
    name: 'lemon',
    keywords: ['lemon', 'fruit', 'citrus'],
    category: 'food',
    color: '#FFD700',
    tags: ['fruit', 'citrus', 'sour'],
  },
  {
    emoji: '🍌',
    name: 'banana',
    keywords: ['banana', 'fruit', 'food'],
    category: 'food',
    color: '#FFD700',
    tags: ['fruit', 'banana', 'potassium'],
  },
  {
    emoji: '🍉',
    name: 'watermelon',
    keywords: ['watermelon', 'fruit', 'summer'],
    category: 'food',
    color: '#FF69B4',
    tags: ['fruit', 'summer', 'refreshing'],
  },
  {
    emoji: '🍇',
    name: 'grapes',
    keywords: ['grapes', 'fruit', 'wine'],
    category: 'food',
    color: '#9370DB',
    tags: ['fruit', 'grapes', 'bunch'],
  },
  {
    emoji: '🍓',
    name: 'strawberry',
    keywords: ['strawberry', 'fruit', 'food'],
    category: 'food',
    color: '#DC143C',
    tags: ['fruit', 'berry', 'sweet'],
  },
  {
    emoji: '🫐',
    name: 'blueberries',
    keywords: ['blueberries', 'fruit', 'berry'],
    category: 'food',
    color: '#4169E1',
    tags: ['fruit', 'berry', 'healthy'],
  },
  {
    emoji: '🍈',
    name: 'melon',
    keywords: ['melon', 'fruit', 'cantaloupe'],
    category: 'food',
    color: '#F0E68C',
    tags: ['fruit', 'melon', 'sweet'],
  },
  {
    emoji: '🍒',
    name: 'cherries',
    keywords: ['cherry', 'fruit', 'cherries'],
    category: 'food',
    color: '#DC143C',
    tags: ['fruit', 'cherry', 'sweet'],
  },
  {
    emoji: '🍑',
    name: 'peach',
    keywords: ['peach', 'fruit', 'nature'],
    category: 'food',
    color: '#FFDAB9',
    tags: ['fruit', 'peach', 'juicy'],
  },
  {
    emoji: '🥭',
    name: 'mango',
    keywords: ['mango', 'fruit', 'tropical'],
    category: 'food',
    color: '#FFD700',
    tags: ['fruit', 'tropical', 'mango'],
  },
  {
    emoji: '🍍',
    name: 'pineapple',
    keywords: ['pineapple', 'fruit', 'tropical'],
    category: 'food',
    color: '#FFD700',
    tags: ['fruit', 'tropical', 'pineapple'],
  },
  {
    emoji: '🥥',
    name: 'coconut',
    keywords: ['coconut', 'palm', 'piña colada'],
    category: 'food',
    color: '#8B4513',
    tags: ['fruit', 'tropical', 'coconut'],
  },
  {
    emoji: '🥝',
    name: 'kiwi fruit',
    keywords: ['kiwi', 'fruit', 'food'],
    category: 'food',
    color: '#8B4513',
    tags: ['fruit', 'kiwi', 'fuzzy'],
  },
  {
    emoji: '🍅',
    name: 'tomato',
    keywords: ['tomato', 'fruit', 'vegetable'],
    category: 'food',
    color: '#FF6347',
    tags: ['fruit', 'vegetable', 'tomato'],
  },

  // Vegetables
  {
    emoji: '🍆',
    name: 'eggplant',
    keywords: ['eggplant', 'vegetable', 'nature'],
    category: 'food',
    color: '#9370DB',
    tags: ['vegetable', 'eggplant', 'purple'],
  },
  {
    emoji: '🥑',
    name: 'avocado',
    keywords: ['avocado', 'fruit', 'food'],
    category: 'food',
    color: '#228B22',
    tags: ['fruit', 'avocado', 'healthy'],
  },
  {
    emoji: '🥦',
    name: 'broccoli',
    keywords: ['broccoli', 'vegetable', 'food'],
    category: 'food',
    color: '#228B22',
    tags: ['vegetable', 'broccoli', 'healthy'],
  },
  {
    emoji: '🥬',
    name: 'leafy green',
    keywords: ['kale', 'lettuce', 'bok choy'],
    category: 'food',
    color: '#228B22',
    tags: ['vegetable', 'greens', 'salad'],
  },
  {
    emoji: '🥒',
    name: 'cucumber',
    keywords: ['cucumber', 'pickle', 'vegetable'],
    category: 'food',
    color: '#228B22',
    tags: ['vegetable', 'cucumber', 'fresh'],
  },
  {
    emoji: '🌶️',
    name: 'hot pepper',
    keywords: ['chili', 'spicy', 'hot'],
    category: 'food',
    color: '#DC143C',
    tags: ['spicy', 'pepper', 'hot'],
  },
  {
    emoji: '🫑',
    name: 'bell pepper',
    keywords: ['pepper', 'paprika', 'vegetable'],
    category: 'food',
    color: '#228B22',
    tags: ['vegetable', 'pepper', 'bell'],
  },
  {
    emoji: '🌽',
    name: 'ear of corn',
    keywords: ['corn', 'ear', 'maize'],
    category: 'food',
    color: '#FFD700',
    tags: ['vegetable', 'corn', 'cob'],
  },
  {
    emoji: '🥕',
    name: 'carrot',
    keywords: ['carrot', 'food', 'vegetable'],
    category: 'food',
    color: '#FF8C00',
    tags: ['vegetable', 'carrot', 'orange'],
  },
  {
    emoji: '🫒',
    name: 'olive',
    keywords: ['olive', 'food', 'mediterranean'],
    category: 'food',
    color: '#556B2F',
    tags: ['olive', 'mediterranean', 'oil'],
  },
  {
    emoji: '🧄',
    name: 'garlic',
    keywords: ['garlic', 'flavoring', 'cook'],
    category: 'food',
    color: '#F5F5F5',
    tags: ['garlic', 'cooking', 'flavor'],
  },
  {
    emoji: '🧅',
    name: 'onion',
    keywords: ['onion', 'cook', 'tear'],
    category: 'food',
    color: '#DDA0DD',
    tags: ['onion', 'cooking', 'vegetable'],
  },
  {
    emoji: '🥔',
    name: 'potato',
    keywords: ['potato', 'food', 'tuber'],
    category: 'food',
    color: '#DEB887',
    tags: ['potato', 'vegetable', 'starch'],
  },
  {
    emoji: '🍠',
    name: 'roasted sweet potato',
    keywords: ['sweet potato', 'roasted', 'food'],
    category: 'food',
    color: '#FF8C00',
    tags: ['sweet-potato', 'roasted', 'yam'],
  },

  // Prepared foods
  {
    emoji: '🥐',
    name: 'croissant',
    keywords: ['croissant', 'food', 'bread'],
    category: 'food',
    color: '#DEB887',
    tags: ['pastry', 'french', 'breakfast'],
  },
  {
    emoji: '🥖',
    name: 'baguette bread',
    keywords: ['baguette', 'food', 'bread'],
    category: 'food',
    color: '#DEB887',
    tags: ['bread', 'french', 'baguette'],
  },
  {
    emoji: '🍞',
    name: 'bread',
    keywords: ['bread', 'loaf', 'carbs'],
    category: 'food',
    color: '#DEB887',
    tags: ['bread', 'loaf', 'carbs'],
  },
  {
    emoji: '🥜',
    name: 'peanuts',
    keywords: ['peanut', 'nut', 'food'],
    category: 'food',
    color: '#DEB887',
    tags: ['nut', 'peanut', 'snack'],
  },
  {
    emoji: '🌰',
    name: 'chestnut',
    keywords: ['chestnut', 'food', 'squirrel'],
    category: 'food',
    color: '#8B4513',
    tags: ['nut', 'chestnut', 'roasted'],
  },
  {
    emoji: '🍯',
    name: 'honey pot',
    keywords: ['honey', 'honeypot', 'bees'],
    category: 'food',
    color: '#FFD700',
    tags: ['honey', 'sweet', 'bee'],
  },
  {
    emoji: '🧈',
    name: 'butter',
    keywords: ['butter', 'dairy', 'spread'],
    category: 'food',
    color: '#F0E68C',
    tags: ['butter', 'dairy', 'spread'],
  },
  {
    emoji: '🥛',
    name: 'glass of milk',
    keywords: ['milk', 'drink', 'glass'],
    category: 'food',
    color: '#F5F5F5',
    tags: ['milk', 'dairy', 'drink'],
  },
  {
    emoji: '🧀',
    name: 'cheese wedge',
    keywords: ['cheese', 'wedge', 'swiss'],
    category: 'food',
    color: '#FFD700',
    tags: ['cheese', 'dairy', 'wedge'],
  },
  {
    emoji: '🥚',
    name: 'egg',
    keywords: ['egg', 'chicken', 'easter'],
    category: 'food',
    color: '#F5F5F5',
    tags: ['egg', 'breakfast', 'protein'],
  },
  {
    emoji: '🍳',
    name: 'cooking',
    keywords: ['eggs', 'frying', 'pan'],
    category: 'food',
    color: '#FFD700',
    tags: ['cooking', 'eggs', 'frying'],
  },
  {
    emoji: '🥓',
    name: 'bacon',
    keywords: ['bacon', 'breakfast', 'pork'],
    category: 'food',
    color: '#DC143C',
    tags: ['bacon', 'meat', 'breakfast'],
  },
  {
    emoji: '🥩',
    name: 'cut of meat',
    keywords: ['steak', 'meat', 'chop'],
    category: 'food',
    color: '#DC143C',
    tags: ['meat', 'steak', 'beef'],
  },
  {
    emoji: '🍗',
    name: 'poultry leg',
    keywords: ['chicken', 'drumstick', 'leg'],
    category: 'food',
    color: '#8B4513',
    tags: ['chicken', 'meat', 'drumstick'],
  },
  {
    emoji: '🍖',
    name: 'meat on bone',
    keywords: ['meat', 'bone', 'drumstick'],
    category: 'food',
    color: '#8B4513',
    tags: ['meat', 'bone', 'bbq'],
  },
  {
    emoji: '🌭',
    name: 'hot dog',
    keywords: ['hotdog', 'frankfurter', 'america'],
    category: 'food',
    color: '#8B4513',
    tags: ['hotdog', 'sausage', 'american'],
  },
  {
    emoji: '🍔',
    name: 'hamburger',
    keywords: ['burger', 'cheeseburger', 'mcdonalds'],
    category: 'food',
    color: '#8B4513',
    tags: ['burger', 'american', 'fast-food'],
  },
  {
    emoji: '🍟',
    name: 'french fries',
    keywords: ['fries', 'chips', 'mcdonalds'],
    category: 'food',
    color: '#FFD700',
    tags: ['fries', 'potato', 'fast-food'],
  },
  {
    emoji: '🍕',
    name: 'pizza',
    keywords: ['pizza', 'party', 'italy'],
    category: 'food',
    color: '#DC143C',
    tags: ['pizza', 'italian', 'slice'],
  },
  {
    emoji: '🥪',
    name: 'sandwich',
    keywords: ['sandwich', 'bread', 'toast'],
    category: 'food',
    color: '#DEB887',
    tags: ['sandwich', 'lunch', 'bread'],
  },
  {
    emoji: '🥙',
    name: 'stuffed flatbread',
    keywords: ['flatbread', 'gyro', 'sandwich'],
    category: 'food',
    color: '#DEB887',
    tags: ['flatbread', 'gyro', 'wrap'],
  },
  {
    emoji: '🧆',
    name: 'falafel',
    keywords: ['falafel', 'chickpea', 'meatball'],
    category: 'food',
    color: '#8B4513',
    tags: ['falafel', 'middle-eastern', 'vegetarian'],
  },
  {
    emoji: '🌮',
    name: 'taco',
    keywords: ['taco', 'mexican', 'food'],
    category: 'food',
    color: '#FFD700',
    tags: ['taco', 'mexican', 'food'],
  },
  {
    emoji: '🌯',
    name: 'burrito',
    keywords: ['burrito', 'mexican', 'wrap'],
    category: 'food',
    color: '#F5DEB3',
    tags: ['burrito', 'mexican', 'wrap'],
  },
  {
    emoji: '🫔',
    name: 'tamale',
    keywords: ['tamale', 'mexican', 'wrapped'],
    category: 'food',
    color: '#90EE90',
    tags: ['tamale', 'mexican', 'corn'],
  },
  {
    emoji: '🥗',
    name: 'green salad',
    keywords: ['salad', 'food', 'green'],
    category: 'food',
    color: '#90EE90',
    tags: ['salad', 'healthy', 'greens'],
  },
  {
    emoji: '🥘',
    name: 'shallow pan of food',
    keywords: ['paella', 'curry', 'casserole'],
    category: 'food',
    color: '#FF8C00',
    tags: ['paella', 'pan', 'food'],
  },
  {
    emoji: '🫕',
    name: 'fondue',
    keywords: ['fondue', 'cheese', 'pot'],
    category: 'food',
    color: '#FFD700',
    tags: ['fondue', 'cheese', 'melted'],
  },
  {
    emoji: '🥫',
    name: 'canned food',
    keywords: ['can', 'soup', 'preserve'],
    category: 'food',
    color: '#DC143C',
    tags: ['canned', 'preserved', 'soup'],
  },

  // Asian foods
  {
    emoji: '🍱',
    name: 'bento box',
    keywords: ['bento', 'box', 'japanese'],
    category: 'food',
    color: '#8B4513',
    tags: ['bento', 'japanese', 'lunch'],
  },
  {
    emoji: '🍘',
    name: 'rice cracker',
    keywords: ['rice', 'cracker', 'japanese'],
    category: 'food',
    color: '#F5DEB3',
    tags: ['rice-cracker', 'japanese', 'snack'],
  },
  {
    emoji: '🍙',
    name: 'rice ball',
    keywords: ['rice', 'ball', 'japanese'],
    category: 'food',
    color: '#F5F5F5',
    tags: ['onigiri', 'japanese', 'rice'],
  },
  {
    emoji: '🍚',
    name: 'cooked rice',
    keywords: ['rice', 'cook', 'food'],
    category: 'food',
    color: '#F5F5F5',
    tags: ['rice', 'asian', 'cooked'],
  },
  {
    emoji: '🍛',
    name: 'curry rice',
    keywords: ['curry', 'rice', 'food'],
    category: 'food',
    color: '#FFD700',
    tags: ['curry', 'rice', 'indian'],
  },
  {
    emoji: '🍜',
    name: 'steaming bowl',
    keywords: ['noodle', 'chopsticks', 'ramen'],
    category: 'food',
    color: '#FFD700',
    tags: ['ramen', 'noodles', 'soup'],
  },
  {
    emoji: '🍝',
    name: 'spaghetti',
    keywords: ['pasta', 'noodle', 'italian'],
    category: 'food',
    color: '#FFD700',
    tags: ['pasta', 'italian', 'spaghetti'],
  },
  {
    emoji: '🍢',
    name: 'oden',
    keywords: ['oden', 'skewer', 'seafood'],
    category: 'food',
    color: '#DEB887',
    tags: ['oden', 'japanese', 'skewer'],
  },
  {
    emoji: '🍣',
    name: 'sushi',
    keywords: ['sushi', 'fish', 'japanese'],
    category: 'food',
    color: '#FF69B4',
    tags: ['sushi', 'japanese', 'fish'],
  },
  {
    emoji: '🍤',
    name: 'fried shrimp',
    keywords: ['shrimp', 'tempura', 'prawn'],
    category: 'food',
    color: '#FF8C00',
    tags: ['shrimp', 'tempura', 'fried'],
  },
  {
    emoji: '🍥',
    name: 'fish cake with swirl',
    keywords: ['fish', 'cake', 'swirl'],
    category: 'food',
    color: '#FFB6C1',
    tags: ['naruto', 'fish-cake', 'japanese'],
  },
  {
    emoji: '🥮',
    name: 'moon cake',
    keywords: ['mooncake', 'festival', 'autumn'],
    category: 'food',
    color: '#DEB887',
    tags: ['mooncake', 'chinese', 'festival'],
  },
  {
    emoji: '🍡',
    name: 'dango',
    keywords: ['dango', 'dessert', 'sweet'],
    category: 'food',
    color: '#FFB6C1',
    tags: ['dango', 'japanese', 'sweet'],
  },
  {
    emoji: '🥟',
    name: 'dumpling',
    keywords: ['dumpling', 'potsticker', 'pierogi'],
    category: 'food',
    color: '#F5DEB3',
    tags: ['dumpling', 'asian', 'steamed'],
  },
  {
    emoji: '🥠',
    name: 'fortune cookie',
    keywords: ['fortune', 'cookie', 'food'],
    category: 'food',
    color: '#DEB887',
    tags: ['fortune-cookie', 'chinese', 'dessert'],
  },
  {
    emoji: '🥡',
    name: 'takeout box',
    keywords: ['takeout', 'chinese', 'food'],
    category: 'food',
    color: '#F5F5F5',
    tags: ['takeout', 'chinese', 'box'],
  },

  // Sweets
  {
    emoji: '🦀',
    name: 'crab',
    keywords: ['crab', 'crustacean', 'seafood'],
    category: 'food',
    color: '#DC143C',
    tags: ['crab', 'seafood', 'shellfish'],
  },
  {
    emoji: '🦞',
    name: 'lobster',
    keywords: ['lobster', 'seafood', 'bisque'],
    category: 'food',
    color: '#DC143C',
    tags: ['lobster', 'seafood', 'fancy'],
  },
  {
    emoji: '🦐',
    name: 'shrimp',
    keywords: ['shrimp', 'seafood', 'ocean'],
    category: 'food',
    color: '#FF69B4',
    tags: ['shrimp', 'seafood', 'prawn'],
  },
  {
    emoji: '🦑',
    name: 'squid',
    keywords: ['squid', 'seafood', 'food'],
    category: 'food',
    color: '#FFB6C1',
    tags: ['squid', 'seafood', 'calamari'],
  },
  {
    emoji: '🦪',
    name: 'oyster',
    keywords: ['oyster', 'food', 'pearl'],
    category: 'food',
    color: '#D3D3D3',
    tags: ['oyster', 'seafood', 'shellfish'],
  },

  // Desserts and sweets
  {
    emoji: '🍦',
    name: 'soft ice cream',
    keywords: ['icecream', 'soft', 'dessert'],
    category: 'food',
    color: '#F5F5F5',
    tags: ['ice-cream', 'soft-serve', 'dessert'],
  },
  {
    emoji: '🍧',
    name: 'shaved ice',
    keywords: ['shaved', 'ice', 'dessert'],
    category: 'food',
    color: '#87CEEB',
    tags: ['shaved-ice', 'dessert', 'cold'],
  },
  {
    emoji: '🍨',
    name: 'ice cream',
    keywords: ['ice', 'cream', 'dessert'],
    category: 'food',
    color: '#FFB6C1',
    tags: ['ice-cream', 'dessert', 'sundae'],
  },
  {
    emoji: '🍩',
    name: 'doughnut',
    keywords: ['donut', 'dessert', 'snack'],
    category: 'food',
    color: '#D2691E',
    tags: ['donut', 'dessert', 'sweet'],
  },
  {
    emoji: '🍪',
    name: 'cookie',
    keywords: ['cookie', 'snack', 'chocolate'],
    category: 'food',
    color: '#D2691E',
    tags: ['cookie', 'dessert', 'biscuit'],
  },
  {
    emoji: '🎂',
    name: 'birthday cake',
    keywords: ['cake', 'birthday', 'dessert'],
    category: 'food',
    color: '#FFB6C1',
    tags: ['cake', 'birthday', 'celebration'],
  },
  {
    emoji: '🍰',
    name: 'shortcake',
    keywords: ['cake', 'dessert', 'slice'],
    category: 'food',
    color: '#FFE4E1',
    tags: ['cake', 'slice', 'dessert'],
  },
  {
    emoji: '🧁',
    name: 'cupcake',
    keywords: ['cupcake', 'food', 'dessert'],
    category: 'food',
    color: '#FFB6C1',
    tags: ['cupcake', 'dessert', 'sweet'],
  },
  {
    emoji: '🥧',
    name: 'pie',
    keywords: ['pie', 'filling', 'thanksgiving'],
    category: 'food',
    color: '#DEB887',
    tags: ['pie', 'dessert', 'baked'],
  },
  {
    emoji: '🍫',
    name: 'chocolate bar',
    keywords: ['chocolate', 'sweet', 'dessert'],
    category: 'food',
    color: '#D2691E',
    tags: ['chocolate', 'candy', 'sweet'],
  },
  {
    emoji: '🍬',
    name: 'candy',
    keywords: ['candy', 'snack', 'dessert'],
    category: 'food',
    color: '#FF69B4',
    tags: ['candy', 'sweet', 'wrapped'],
  },
  {
    emoji: '🍭',
    name: 'lollipop',
    keywords: ['lollipop', 'candy', 'snack'],
    category: 'food',
    color: '#FF69B4',
    tags: ['lollipop', 'candy', 'sweet'],
  },
  {
    emoji: '🍮',
    name: 'custard',
    keywords: ['custard', 'pudding', 'dessert'],
    category: 'food',
    color: '#F0E68C',
    tags: ['custard', 'pudding', 'dessert'],
  },

  // Beverages
  {
    emoji: '☕',
    name: 'hot beverage',
    keywords: ['coffee', 'cafe', 'espresso'],
    category: 'food',
    color: '#8B4513',
    tags: ['coffee', 'hot', 'beverage'],
  },
  {
    emoji: '🍵',
    name: 'teacup without handle',
    keywords: ['tea', 'green', 'breakfast'],
    category: 'food',
    color: '#90EE90',
    tags: ['tea', 'green-tea', 'japanese'],
  },
  {
    emoji: '🫖',
    name: 'teapot',
    keywords: ['teapot', 'tea', 'drink'],
    category: 'food',
    color: '#8B4513',
    tags: ['teapot', 'tea', 'brewing'],
  },
  {
    emoji: '🍶',
    name: 'sake',
    keywords: ['sake', 'wine', 'drink'],
    category: 'food',
    color: '#F5F5F5',
    tags: ['sake', 'japanese', 'alcohol'],
  },
  {
    emoji: '🍾',
    name: 'bottle with popping cork',
    keywords: ['champagne', 'bottle', 'bubbly'],
    category: 'food',
    color: '#FFD700',
    tags: ['champagne', 'celebration', 'popping'],
  },
  {
    emoji: '🍷',
    name: 'wine glass',
    keywords: ['wine', 'drink', 'drunk'],
    category: 'food',
    color: '#8B0000',
    tags: ['wine', 'red-wine', 'glass'],
  },
  {
    emoji: '🍸',
    name: 'cocktail glass',
    keywords: ['drink', 'drunk', 'alcohol'],
    category: 'food',
    color: '#FF69B4',
    tags: ['cocktail', 'martini', 'drink'],
  },
  {
    emoji: '🍹',
    name: 'tropical drink',
    keywords: ['tropical', 'drink', 'mojito'],
    category: 'food',
    color: '#FF69B4',
    tags: ['tropical', 'cocktail', 'vacation'],
  },
  {
    emoji: '🍺',
    name: 'beer mug',
    keywords: ['beer', 'drink', 'stein'],
    category: 'food',
    color: '#FFD700',
    tags: ['beer', 'mug', 'alcohol'],
  },
  {
    emoji: '🍻',
    name: 'clinking beer mugs',
    keywords: ['beers', 'drinks', 'cheers'],
    category: 'food',
    color: '#FFD700',
    tags: ['cheers', 'beer', 'celebration'],
  },
  {
    emoji: '🥂',
    name: 'clinking glasses',
    keywords: ['cheers', 'champagne', 'glass'],
    category: 'food',
    color: '#FFD700',
    tags: ['cheers', 'champagne', 'toast'],
  },
  {
    emoji: '🥃',
    name: 'tumbler glass',
    keywords: ['whisky', 'liquor', 'shot'],
    category: 'food',
    color: '#8B4513',
    tags: ['whiskey', 'tumbler', 'alcohol'],
  },
  {
    emoji: '🥤',
    name: 'cup with straw',
    keywords: ['drink', 'soda', 'soft drink'],
    category: 'food',
    color: '#DC143C',
    tags: ['soda', 'drink', 'straw'],
  },
  {
    emoji: '🧋',
    name: 'bubble tea',
    keywords: ['bubble', 'tea', 'pearl'],
    category: 'food',
    color: '#DEB887',
    tags: ['bubble-tea', 'boba', 'drink'],
  },
  {
    emoji: '🧃',
    name: 'beverage box',
    keywords: ['juice', 'straw', 'drink'],
    category: 'food',
    color: '#FFA500',
    tags: ['juice-box', 'drink', 'kids'],
  },
  {
    emoji: '🧉',
    name: 'mate',
    keywords: ['mate', 'drink', 'tea'],
    category: 'food',
    color: '#8B4513',
    tags: ['mate', 'tea', 'south-american'],
  },
  {
    emoji: '🧊',
    name: 'ice',
    keywords: ['ice', 'cube', 'iceberg'],
    category: 'food',
    color: '#87CEEB',
    tags: ['ice', 'cube', 'cold'],
  },

  // Utensils
  {
    emoji: '🥢',
    name: 'chopsticks',
    keywords: ['chopsticks', 'food', 'hashi'],
    category: 'food',
    color: '#8B4513',
    tags: ['chopsticks', 'asian', 'utensils'],
  },
  {
    emoji: '🍴',
    name: 'fork and knife',
    keywords: ['cutlery', 'fork', 'knife'],
    category: 'food',
    color: '#C0C0C0',
    tags: ['cutlery', 'dining', 'utensils'],
  },
  {
    emoji: '🥄',
    name: 'spoon',
    keywords: ['spoon', 'tableware', 'cutlery'],
    category: 'food',
    color: '#C0C0C0',
    tags: ['spoon', 'utensil', 'eating'],
  },
  {
    emoji: '🔪',
    name: 'kitchen knife',
    keywords: ['knife', 'blade', 'cutlery'],
    category: 'food',
    color: '#C0C0C0',
    tags: ['knife', 'kitchen', 'cooking'],
  },
  {
    emoji: '🏺',
    name: 'amphora',
    keywords: ['jar', 'vase', 'amphora'],
    category: 'food',
    color: '#8B4513',
    tags: ['amphora', 'jar', 'ancient'],
  },
];
