import type { Emoji } from '../../schema';

// Generated from OpenMoji dataset - 131 emojis
// Unicode versions up to 15.1 + OpenMoji extras
export const foodEmojisAll: Emoji[] = [
  {
    emoji: '🍇',
    name: 'grapes',
    keywords: ['dionysus', 'fruit', 'grape'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F347',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍈',
    name: 'melon',
    keywords: ['cantaloupe', 'fruit'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F348',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍉',
    name: 'watermelon',
    keywords: ['fruit'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F349',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍊',
    name: 'tangerine',
    keywords: ['c', 'citrus', 'fruit', 'nectarine', 'orange', 'vitamin'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F34A',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍋',
    name: 'lemon',
    keywords: ['citrus', 'fruit', 'sour'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F34B',
    version: '1',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍋‍🟩',
    name: 'lime',
    keywords: [
      'acidity',
      'citrus',
      'cocktail',
      'fruit',
      'garnish',
      'key',
      'margarita',
      'mojito',
      'refreshing',
      'salsa',
      'sour',
      'tangy',
      'tequila',
      'tropical',
      'zest',
    ],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F34B 200D 1F7E9',
    version: '15.1',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍌',
    name: 'banana',
    keywords: ['fruit', 'potassium'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F34C',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍍',
    name: 'pineapple',
    keywords: ['colada', 'fruit', 'pina', 'tropical'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F34D',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥭',
    name: 'mango',
    keywords: ['food', 'fruit', 'tropical'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F96D',
    version: '11',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍎',
    name: 'red apple',
    keywords: ['apple', 'diet', 'food', 'fruit', 'health', 'red', 'ripe'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F34E',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍏',
    name: 'green apple',
    keywords: ['apple', 'fruit', 'green'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F34F',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍐',
    name: 'pear',
    keywords: ['fruit'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F350',
    version: '1',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍑',
    name: 'peach',
    keywords: ['fruit'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F351',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍒',
    name: 'cherries',
    keywords: ['berries', 'cherry', 'fruit', 'red'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F352',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍓',
    name: 'strawberry',
    keywords: ['berry', 'fruit'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F353',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫐',
    name: 'blueberries',
    keywords: [
      'berries',
      'berry',
      'bilberry',
      'blue',
      'blueberry',
      'food',
      'fruit',
    ],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1FAD0',
    version: '13',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥝',
    name: 'kiwi fruit',
    keywords: ['food', 'fruit', 'kiwi'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F95D',
    version: '3',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍅',
    name: 'tomato',
    keywords: ['food', 'fruit', 'vegetable'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F345',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫒',
    name: 'olive',
    keywords: ['food'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1FAD2',
    version: '13',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥥',
    name: 'coconut',
    keywords: ['colada', 'palm', 'piña'],
    category: 'food',
    subcategory: 'food-fruit',
    unicode: '1F965',
    version: '5',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥑',
    name: 'avocado',
    keywords: ['food', 'fruit'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1F951',
    version: '3',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍆',
    name: 'eggplant',
    keywords: ['aubergine', 'vegetable'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1F346',
    version: '0.6',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥔',
    name: 'potato',
    keywords: ['food', 'vegetable'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1F954',
    version: '3',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥕',
    name: 'carrot',
    keywords: ['food', 'vegetable'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1F955',
    version: '3',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌽',
    name: 'ear of corn',
    keywords: ['corn', 'crops', 'ear', 'farm', 'maize', 'maze'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1F33D',
    version: '0.6',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌶️',
    name: 'hot pepper',
    keywords: ['hot', 'pepper'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1F336',
    version: '0.7',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫑',
    name: 'bell pepper',
    keywords: ['bell', 'capsicum', 'food', 'pepper', 'vegetable'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1FAD1',
    version: '13',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥒',
    name: 'cucumber',
    keywords: ['food', 'pickle', 'vegetable'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1F952',
    version: '3',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥬',
    name: 'leafy green',
    keywords: [
      'bok',
      'burgers',
      'cabbage',
      'choy',
      'green',
      'kale',
      'leafy',
      'lettuce',
      'salad',
    ],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1F96C',
    version: '11',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥦',
    name: 'broccoli',
    keywords: ['cabbage', 'wild'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1F966',
    version: '5',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧄',
    name: 'garlic',
    keywords: ['flavoring'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1F9C4',
    version: '12',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧅',
    name: 'onion',
    keywords: ['flavoring'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1F9C5',
    version: '12',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥜',
    name: 'peanuts',
    keywords: ['food', 'nut', 'peanut', 'vegetable'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1F95C',
    version: '3',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫘',
    name: 'beans',
    keywords: ['food', 'kidney', 'legume', 'small'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1FAD8',
    version: '14',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌰',
    name: 'chestnut',
    keywords: ['almond', 'plant'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1F330',
    version: '0.6',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫚',
    name: 'ginger root',
    keywords: ['beer', 'ginger', 'health', 'herb', 'natural', 'root', 'spice'],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1FADA',
    version: '15',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫛',
    name: 'pea pod',
    keywords: [
      'beans',
      'beanstalk',
      'edamame',
      'legume',
      'pea',
      'pod',
      'soybean',
      'vegetable',
      'veggie',
    ],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1FADB',
    version: '15',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍄‍🟫',
    name: 'brown mushroom',
    keywords: [
      'food',
      'fungi',
      'fungus',
      'mushroom',
      'nature',
      'pizza',
      'portobello',
      'shiitake',
      'shroom',
      'spore',
      'sprout',
      'toppings',
      'truffle',
      'vegetable',
      'vegetarian',
      'veggie',
    ],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1F344 200D 1F7EB',
    version: '15.1',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫜',
    name: 'root vegetable',
    keywords: [
      'beet',
      'food',
      'garden',
      'radish',
      'root',
      'salad',
      'turnip',
      'vegetable',
      'vegetarian',
    ],
    category: 'food',
    subcategory: 'food-vegetable',
    unicode: '1FADC',
    version: '16',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍞',
    name: 'bread',
    keywords: [
      'carbs',
      'food',
      'grain',
      'loaf',
      'restaurant',
      'toast',
      'wheat',
    ],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F35E',
    version: '0.6',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥐',
    name: 'croissant',
    keywords: ['bread', 'breakfast', 'crescent', 'food', 'french', 'roll'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F950',
    version: '3',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥖',
    name: 'baguette bread',
    keywords: ['baguette', 'bread', 'food', 'french'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F956',
    version: '3',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫓',
    name: 'flatbread',
    keywords: ['arepa', 'bread', 'food', 'gordita', 'lavash', 'naan', 'pita'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1FAD3',
    version: '13',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥨',
    name: 'pretzel',
    keywords: ['convoluted', 'twisted'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F968',
    version: '5',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥯',
    name: 'bagel',
    keywords: ['bakery', 'bread', 'breakfast', 'schmear'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F96F',
    version: '11',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥞',
    name: 'pancakes',
    keywords: ['breakfast', 'crêpe', 'food', 'hotcake', 'pancake'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F95E',
    version: '3',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧇',
    name: 'waffle',
    keywords: ['breakfast', 'indecisive', 'iron'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F9C7',
    version: '12',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧀',
    name: 'cheese wedge',
    keywords: ['cheese', 'wedge'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F9C0',
    version: '1',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍖',
    name: 'meat on bone',
    keywords: ['bone', 'meat'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F356',
    version: '0.6',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍗',
    name: 'poultry leg',
    keywords: [
      'bone',
      'chicken',
      'drumstick',
      'hungry',
      'leg',
      'poultry',
      'turkey',
    ],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F357',
    version: '0.6',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥩',
    name: 'cut of meat',
    keywords: ['chop', 'cut', 'lambchop', 'meat', 'porkchop', 'red', 'steak'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F969',
    version: '5',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥓',
    name: 'bacon',
    keywords: ['breakfast', 'food', 'meat'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F953',
    version: '3',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍔',
    name: 'hamburger',
    keywords: ['burger', 'eat', 'fast', 'food', 'hungry'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F354',
    version: '0.6',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍟',
    name: 'french fries',
    keywords: ['fast', 'food', 'french', 'fries'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F35F',
    version: '0.6',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍕',
    name: 'pizza',
    keywords: ['cheese', 'food', 'hungry', 'pepperoni', 'slice'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F355',
    version: '0.6',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌭',
    name: 'hot dog',
    keywords: ['dog', 'frankfurter', 'hot', 'hotdog', 'sausage'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F32D',
    version: '1',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥪',
    name: 'sandwich',
    keywords: ['bread'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F96A',
    version: '5',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌮',
    name: 'taco',
    keywords: ['mexican'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F32E',
    version: '1',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌯',
    name: 'burrito',
    keywords: ['mexican', 'wrap'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F32F',
    version: '1',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫔',
    name: 'tamale',
    keywords: ['food', 'mexican', 'pamonha', 'wrapped'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1FAD4',
    version: '13',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥙',
    name: 'stuffed flatbread',
    keywords: ['falafel', 'flatbread', 'food', 'gyro', 'kebab', 'stuffed'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F959',
    version: '3',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧆',
    name: 'falafel',
    keywords: ['chickpea', 'meatball'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F9C6',
    version: '12',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥚',
    name: 'egg',
    keywords: ['breakfast', 'food'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F95A',
    version: '3',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍳',
    name: 'cooking',
    keywords: [
      'breakfast',
      'easy',
      'egg',
      'fry',
      'frying',
      'over',
      'pan',
      'restaurant',
      'side',
      'sunny',
      'up',
    ],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F373',
    version: '0.6',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥘',
    name: 'shallow pan of food',
    keywords: ['casserole', 'food', 'paella', 'pan', 'shallow'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F958',
    version: '3',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍲',
    name: 'pot of food',
    keywords: ['food', 'pot', 'soup', 'stew'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F372',
    version: '0.6',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫕',
    name: 'fondue',
    keywords: ['cheese', 'chocolate', 'food', 'melted', 'pot', 'ski'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1FAD5',
    version: '13',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥣',
    name: 'bowl with spoon',
    keywords: [
      'bowl',
      'breakfast',
      'cereal',
      'congee',
      'oatmeal',
      'porridge',
      'spoon',
    ],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F963',
    version: '5',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥗',
    name: 'green salad',
    keywords: ['food', 'green', 'salad'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F957',
    version: '3',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍿',
    name: 'popcorn',
    keywords: ['corn', 'movie', 'pop'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F37F',
    version: '1',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧈',
    name: 'butter',
    keywords: ['dairy'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F9C8',
    version: '12',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧂',
    name: 'salt',
    keywords: [
      'condiment',
      'flavor',
      'mad',
      'salty',
      'shaker',
      'taste',
      'upset',
    ],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F9C2',
    version: '11',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥫',
    name: 'canned food',
    keywords: ['can', 'canned', 'food'],
    category: 'food',
    subcategory: 'food-prepared',
    unicode: '1F96B',
    version: '5',
    color: '#FFA500',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍱',
    name: 'bento box',
    keywords: ['bento', 'box', 'food'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F371',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍘',
    name: 'rice cracker',
    keywords: ['cracker', 'food', 'rice'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F358',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍙',
    name: 'rice ball',
    keywords: ['ball', 'food', 'japanese', 'rice'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F359',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍚',
    name: 'cooked rice',
    keywords: ['cooked', 'food', 'rice'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F35A',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍛',
    name: 'curry rice',
    keywords: ['curry', 'food', 'rice'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F35B',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍜',
    name: 'steaming bowl',
    keywords: [
      'bowl',
      'chopsticks',
      'food',
      'noodle',
      'pho',
      'ramen',
      'soup',
      'steaming',
    ],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F35C',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍝',
    name: 'spaghetti',
    keywords: ['food', 'meatballs', 'pasta', 'restaurant'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F35D',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍠',
    name: 'roasted sweet potato',
    keywords: ['food', 'potato', 'roasted', 'sweet'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F360',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍢',
    name: 'oden',
    keywords: ['food', 'kebab', 'restaurant', 'seafood', 'skewer', 'stick'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F362',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍣',
    name: 'sushi',
    keywords: ['food'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F363',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍤',
    name: 'fried shrimp',
    keywords: ['fried', 'prawn', 'shrimp', 'tempura'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F364',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍥',
    name: 'fish cake with swirl',
    keywords: ['cake', 'fish', 'food', 'pastry', 'restaurant', 'swirl'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F365',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥮',
    name: 'moon cake',
    keywords: ['autumn', 'cake', 'festival', 'moon', 'yuèbǐng'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F96E',
    version: '11',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍡',
    name: 'dango',
    keywords: ['dessert', 'japanese', 'skewer', 'stick', 'sweet'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F361',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥟',
    name: 'dumpling',
    keywords: ['empanada', 'gyōza', 'jiaozi', 'pierogi', 'potsticker'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F95F',
    version: '5',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥠',
    name: 'fortune cookie',
    keywords: ['cookie', 'fortune', 'prophecy'],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F960',
    version: '5',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥡',
    name: 'takeout box',
    keywords: [
      'box',
      'chopsticks',
      'delivery',
      'food',
      'oyster',
      'pail',
      'takeout',
    ],
    category: 'food',
    subcategory: 'food-asian',
    unicode: '1F961',
    version: '5',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍦',
    name: 'soft ice cream',
    keywords: [
      'cream',
      'dessert',
      'food',
      'ice',
      'icecream',
      'restaurant',
      'serve',
      'soft',
      'sweet',
    ],
    category: 'food',
    subcategory: 'food-sweet',
    unicode: '1F366',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍧',
    name: 'shaved ice',
    keywords: ['dessert', 'ice', 'restaurant', 'shaved', 'sweet'],
    category: 'food',
    subcategory: 'food-sweet',
    unicode: '1F367',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍨',
    name: 'ice cream',
    keywords: ['cream', 'dessert', 'food', 'ice', 'restaurant', 'sweet'],
    category: 'food',
    subcategory: 'food-sweet',
    unicode: '1F368',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍩',
    name: 'doughnut',
    keywords: ['breakfast', 'dessert', 'donut', 'food', 'sweet'],
    category: 'food',
    subcategory: 'food-sweet',
    unicode: '1F369',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍪',
    name: 'cookie',
    keywords: ['chip', 'chocolate', 'dessert', 'sweet'],
    category: 'food',
    subcategory: 'food-sweet',
    unicode: '1F36A',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎂',
    name: 'birthday cake',
    keywords: [
      'bday',
      'birthday',
      'cake',
      'celebration',
      'dessert',
      'happy',
      'pastry',
      'sweet',
    ],
    category: 'food',
    subcategory: 'food-sweet',
    unicode: '1F382',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🍰',
    name: 'shortcake',
    keywords: ['cake', 'dessert', 'pastry', 'slice', 'sweet'],
    category: 'food',
    subcategory: 'food-sweet',
    unicode: '1F370',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧁',
    name: 'cupcake',
    keywords: ['bakery', 'dessert', 'sprinkles', 'sugar', 'sweet', 'treat'],
    category: 'food',
    subcategory: 'food-sweet',
    unicode: '1F9C1',
    version: '11',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥧',
    name: 'pie',
    keywords: [
      'apple',
      'filling',
      'fruit',
      'meat',
      'pastry',
      'pumpkin',
      'slice',
    ],
    category: 'food',
    subcategory: 'food-sweet',
    unicode: '1F967',
    version: '5',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍫',
    name: 'chocolate bar',
    keywords: [
      'bar',
      'candy',
      'chocolate',
      'dessert',
      'halloween',
      'sweet',
      'tooth',
    ],
    category: 'food',
    subcategory: 'food-sweet',
    unicode: '1F36B',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍬',
    name: 'candy',
    keywords: [
      'cavities',
      'dessert',
      'halloween',
      'restaurant',
      'sweet',
      'tooth',
      'wrapper',
    ],
    category: 'food',
    subcategory: 'food-sweet',
    unicode: '1F36C',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍭',
    name: 'lollipop',
    keywords: ['candy', 'dessert', 'food', 'restaurant', 'sweet'],
    category: 'food',
    subcategory: 'food-sweet',
    unicode: '1F36D',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍮',
    name: 'custard',
    keywords: ['dessert', 'pudding', 'sweet'],
    category: 'food',
    subcategory: 'food-sweet',
    unicode: '1F36E',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🍯',
    name: 'honey pot',
    keywords: [
      'barrel',
      'bear',
      'food',
      'honey',
      'honeypot',
      'jar',
      'pot',
      'sweet',
    ],
    category: 'food',
    subcategory: 'food-sweet',
    unicode: '1F36F',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍼',
    name: 'baby bottle',
    keywords: [
      'babies',
      'baby',
      'birth',
      'born',
      'bottle',
      'drink',
      'infant',
      'milk',
      'newborn',
    ],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F37C',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥛',
    name: 'glass of milk',
    keywords: ['drink', 'glass', 'milk'],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F95B',
    version: '3',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '☕️',
    name: 'hot beverage',
    keywords: [
      'beverage',
      'cafe',
      'caffeine',
      'chai',
      'coffee',
      'drink',
      'hot',
      'morning',
      'steaming',
      'tea',
    ],
    category: 'food',
    subcategory: 'drink',
    unicode: '2615',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🫖',
    name: 'teapot',
    keywords: ['brew', 'drink', 'food', 'pot', 'tea'],
    category: 'food',
    subcategory: 'drink',
    unicode: '1FAD6',
    version: '13',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍵',
    name: 'teacup without handle',
    keywords: ['beverage', 'cup', 'drink', 'handle', 'oolong', 'tea', 'teacup'],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F375',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🍶',
    name: 'sake',
    keywords: ['bar', 'beverage', 'bottle', 'cup', 'drink', 'restaurant'],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F376',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🍾',
    name: 'bottle with popping cork',
    keywords: ['bar', 'bottle', 'cork', 'drink', 'popping'],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F37E',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍷',
    name: 'wine glass',
    keywords: [
      'alcohol',
      'bar',
      'beverage',
      'booze',
      'club',
      'drink',
      'drinking',
      'drinks',
      'glass',
      'restaurant',
      'wine',
    ],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F377',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🍸️',
    name: 'cocktail glass',
    keywords: [
      'alcohol',
      'bar',
      'booze',
      'club',
      'cocktail',
      'drink',
      'drinking',
      'drinks',
      'glass',
      'mad',
      'martini',
      'men',
    ],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F378',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍹',
    name: 'tropical drink',
    keywords: [
      'alcohol',
      'bar',
      'booze',
      'club',
      'cocktail',
      'drink',
      'drinking',
      'drinks',
      'drunk',
      'mai',
      'party',
      'tai',
      'tropical',
      'tropics',
    ],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F379',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🍺',
    name: 'beer mug',
    keywords: [
      'alcohol',
      'ale',
      'bar',
      'beer',
      'booze',
      'drink',
      'drinking',
      'drinks',
      'mug',
      'octoberfest',
      'oktoberfest',
      'pint',
      'stein',
      'summer',
    ],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F37A',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍻',
    name: 'clinking beer mugs',
    keywords: [
      'alcohol',
      'bar',
      'beer',
      'booze',
      'bottoms',
      'cheers',
      'clink',
      'clinking',
      'drinking',
      'drinks',
      'mugs',
    ],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F37B',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥂',
    name: 'clinking glasses',
    keywords: ['celebrate', 'clink', 'clinking', 'drink', 'glass', 'glasses'],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F942',
    version: '3',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥃',
    name: 'tumbler glass',
    keywords: [
      'glass',
      'liquor',
      'scotch',
      'shot',
      'tumbler',
      'whiskey',
      'whisky',
    ],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F943',
    version: '3',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫗',
    name: 'pouring liquid',
    keywords: [
      'accident',
      'drink',
      'empty',
      'glass',
      'liquid',
      'oops',
      'pour',
      'pouring',
      'spill',
      'water',
    ],
    category: 'food',
    subcategory: 'drink',
    unicode: '1FAD7',
    version: '14',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥤',
    name: 'cup with straw',
    keywords: [
      'cup',
      'drink',
      'juice',
      'malt',
      'soda',
      'soft',
      'straw',
      'water',
    ],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F964',
    version: '5',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧋',
    name: 'bubble tea',
    keywords: ['boba', 'bubble', 'food', 'milk', 'pearl', 'tea'],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F9CB',
    version: '13',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧃',
    name: 'beverage box',
    keywords: ['beverage', 'box', 'juice', 'straw', 'sweet'],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F9C3',
    version: '12',
    color: '#87CEEB',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🧉',
    name: 'mate',
    keywords: ['drink'],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F9C9',
    version: '12',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧊',
    name: 'ice',
    keywords: ['cold', 'cube', 'iceberg'],
    category: 'food',
    subcategory: 'drink',
    unicode: '1F9CA',
    version: '12',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥢',
    name: 'chopsticks',
    keywords: ['hashi', 'jeotgarak', 'kuaizi'],
    category: 'food',
    subcategory: 'dishware',
    unicode: '1F962',
    version: '5',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍽️',
    name: 'fork and knife with plate',
    keywords: ['cooking', 'dinner', 'eat', 'fork', 'knife', 'plate'],
    category: 'food',
    subcategory: 'dishware',
    unicode: '1F37D',
    version: '0.7',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🍴',
    name: 'fork and knife',
    keywords: [
      'breakfast',
      'breaky',
      'cooking',
      'cutlery',
      'delicious',
      'dinner',
      'eat',
      'feed',
      'food',
      'fork',
      'hungry',
      'knife',
      'lunch',
      'restaurant',
      'yum',
      'yummy',
    ],
    category: 'food',
    subcategory: 'dishware',
    unicode: '1F374',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🥄',
    name: 'spoon',
    keywords: ['eat', 'tableware'],
    category: 'food',
    subcategory: 'dishware',
    unicode: '1F944',
    version: '3',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔪',
    name: 'kitchen knife',
    keywords: [
      'chef',
      'cooking',
      'hocho',
      'kitchen',
      'knife',
      'tool',
      'weapon',
    ],
    category: 'food',
    subcategory: 'dishware',
    unicode: '1F52A',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫙',
    name: 'jar',
    keywords: ['condiment', 'container', 'empty', 'nothing', 'sauce', 'store'],
    category: 'food',
    subcategory: 'dishware',
    unicode: '1FAD9',
    version: '14',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏺',
    name: 'amphora',
    keywords: [
      'aquarius',
      'cooking',
      'drink',
      'jug',
      'tool',
      'weapon',
      'zodiac',
    ],
    category: 'food',
    subcategory: 'dishware',
    unicode: '1F3FA',
    version: '1',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
];
