import type { Emoji } from '../../schema';

export const foodEmojis: Emoji[] = [
  // Fruits
  {
    emoji: '🍏',
    name: 'green apple',
    keywords: ['apple', 'fruit', 'green'],
    category: 'food',
    color: '#90EE90',
  },
  {
    emoji: '🍎',
    name: 'red apple',
    keywords: ['apple', 'fruit', 'red'],
    category: 'food',
    color: '#DC143C',
  },
  {
    emoji: '🍐',
    name: 'pear',
    keywords: ['pear', 'fruit', 'nature'],
    category: 'food',
    color: '#90EE90',
  },
  {
    emoji: '🍊',
    name: 'tangerine',
    keywords: ['orange', 'fruit', 'tangerine'],
    category: 'food',
    color: '#FFA500',
  },
  {
    emoji: '🍋',
    name: 'lemon',
    keywords: ['lemon', 'fruit', 'citrus'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🍌',
    name: 'banana',
    keywords: ['banana', 'fruit', 'food'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🍉',
    name: 'watermelon',
    keywords: ['watermelon', 'fruit', 'summer'],
    category: 'food',
    color: '#FF69B4',
  },
  {
    emoji: '🍇',
    name: 'grapes',
    keywords: ['grapes', 'fruit', 'wine'],
    category: 'food',
    color: '#9370DB',
  },
  {
    emoji: '🍓',
    name: 'strawberry',
    keywords: ['strawberry', 'fruit', 'food'],
    category: 'food',
    color: '#DC143C',
  },
  {
    emoji: '🫐',
    name: 'blueberries',
    keywords: ['blueberries', 'fruit', 'berry'],
    category: 'food',
    color: '#4169E1',
  },
  {
    emoji: '🍈',
    name: 'melon',
    keywords: ['melon', 'fruit', 'cantaloupe'],
    category: 'food',
    color: '#F0E68C',
  },
  {
    emoji: '🍒',
    name: 'cherries',
    keywords: ['cherry', 'fruit', 'cherries'],
    category: 'food',
    color: '#DC143C',
  },
  {
    emoji: '🍑',
    name: 'peach',
    keywords: ['peach', 'fruit', 'nature'],
    category: 'food',
    color: '#FFDAB9',
  },
  {
    emoji: '🥭',
    name: 'mango',
    keywords: ['mango', 'fruit', 'tropical'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🍍',
    name: 'pineapple',
    keywords: ['pineapple', 'fruit', 'tropical'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🥥',
    name: 'coconut',
    keywords: ['coconut', 'palm', 'piña colada'],
    category: 'food',
    color: '#8B4513',
  },
  {
    emoji: '🥝',
    name: 'kiwi fruit',
    keywords: ['kiwi', 'fruit', 'food'],
    category: 'food',
    color: '#8B4513',
  },
  {
    emoji: '🍅',
    name: 'tomato',
    keywords: ['tomato', 'fruit', 'vegetable'],
    category: 'food',
    color: '#FF6347',
  },

  // Vegetables
  {
    emoji: '🍆',
    name: 'eggplant',
    keywords: ['eggplant', 'vegetable', 'nature'],
    category: 'food',
    color: '#9370DB',
  },
  {
    emoji: '🥑',
    name: 'avocado',
    keywords: ['avocado', 'fruit', 'food'],
    category: 'food',
    color: '#228B22',
  },
  {
    emoji: '🥦',
    name: 'broccoli',
    keywords: ['broccoli', 'vegetable', 'food'],
    category: 'food',
    color: '#228B22',
  },
  {
    emoji: '🥬',
    name: 'leafy green',
    keywords: ['kale', 'lettuce', 'bok choy'],
    category: 'food',
    color: '#228B22',
  },
  {
    emoji: '🥒',
    name: 'cucumber',
    keywords: ['cucumber', 'pickle', 'vegetable'],
    category: 'food',
    color: '#228B22',
  },
  {
    emoji: '🌶️',
    name: 'hot pepper',
    keywords: ['chili', 'spicy', 'hot'],
    category: 'food',
    color: '#DC143C',
  },
  {
    emoji: '🫑',
    name: 'bell pepper',
    keywords: ['pepper', 'paprika', 'vegetable'],
    category: 'food',
    color: '#228B22',
  },
  {
    emoji: '🌽',
    name: 'ear of corn',
    keywords: ['corn', 'ear', 'maize'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🥕',
    name: 'carrot',
    keywords: ['carrot', 'food', 'vegetable'],
    category: 'food',
    color: '#FF8C00',
  },
  {
    emoji: '🫒',
    name: 'olive',
    keywords: ['olive', 'food', 'mediterranean'],
    category: 'food',
    color: '#556B2F',
  },
  {
    emoji: '🧄',
    name: 'garlic',
    keywords: ['garlic', 'flavoring', 'cook'],
    category: 'food',
    color: '#F5F5F5',
  },
  {
    emoji: '🧅',
    name: 'onion',
    keywords: ['onion', 'cook', 'tear'],
    category: 'food',
    color: '#DDA0DD',
  },
  {
    emoji: '🥔',
    name: 'potato',
    keywords: ['potato', 'food', 'tuber'],
    category: 'food',
    color: '#DEB887',
  },
  {
    emoji: '🍠',
    name: 'roasted sweet potato',
    keywords: ['sweet potato', 'roasted', 'food'],
    category: 'food',
    color: '#FF8C00',
  },

  // Prepared foods
  {
    emoji: '🥐',
    name: 'croissant',
    keywords: ['croissant', 'food', 'bread'],
    category: 'food',
    color: '#DEB887',
  },
  {
    emoji: '🥖',
    name: 'baguette bread',
    keywords: ['baguette', 'food', 'bread'],
    category: 'food',
    color: '#DEB887',
  },
  {
    emoji: '🍞',
    name: 'bread',
    keywords: ['bread', 'loaf', 'carbs'],
    category: 'food',
    color: '#DEB887',
  },
  {
    emoji: '🥜',
    name: 'peanuts',
    keywords: ['peanut', 'nut', 'food'],
    category: 'food',
    color: '#DEB887',
  },
  {
    emoji: '🌰',
    name: 'chestnut',
    keywords: ['chestnut', 'food', 'squirrel'],
    category: 'food',
    color: '#8B4513',
  },
  {
    emoji: '🍯',
    name: 'honey pot',
    keywords: ['honey', 'honeypot', 'bees'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🧈',
    name: 'butter',
    keywords: ['butter', 'dairy', 'spread'],
    category: 'food',
    color: '#F0E68C',
  },
  {
    emoji: '🥛',
    name: 'glass of milk',
    keywords: ['milk', 'drink', 'glass'],
    category: 'food',
    color: '#F5F5F5',
  },
  {
    emoji: '🧀',
    name: 'cheese wedge',
    keywords: ['cheese', 'wedge', 'swiss'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🥚',
    name: 'egg',
    keywords: ['egg', 'chicken', 'easter'],
    category: 'food',
    color: '#F5F5F5',
  },
  {
    emoji: '🍳',
    name: 'cooking',
    keywords: ['eggs', 'frying', 'pan'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🥓',
    name: 'bacon',
    keywords: ['bacon', 'breakfast', 'pork'],
    category: 'food',
    color: '#DC143C',
  },
  {
    emoji: '🥩',
    name: 'cut of meat',
    keywords: ['steak', 'meat', 'chop'],
    category: 'food',
    color: '#DC143C',
  },
  {
    emoji: '🍗',
    name: 'poultry leg',
    keywords: ['chicken', 'drumstick', 'leg'],
    category: 'food',
    color: '#8B4513',
  },
  {
    emoji: '🍖',
    name: 'meat on bone',
    keywords: ['meat', 'bone', 'drumstick'],
    category: 'food',
    color: '#8B4513',
  },
  {
    emoji: '🌭',
    name: 'hot dog',
    keywords: ['hotdog', 'frankfurter', 'america'],
    category: 'food',
    color: '#8B4513',
  },
  {
    emoji: '🍔',
    name: 'hamburger',
    keywords: ['burger', 'cheeseburger', 'mcdonalds'],
    category: 'food',
    color: '#8B4513',
  },
  {
    emoji: '🍟',
    name: 'french fries',
    keywords: ['fries', 'chips', 'mcdonalds'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🍕',
    name: 'pizza',
    keywords: ['pizza', 'party', 'italy'],
    category: 'food',
    color: '#DC143C',
  },
  {
    emoji: '🥪',
    name: 'sandwich',
    keywords: ['sandwich', 'bread', 'toast'],
    category: 'food',
    color: '#DEB887',
  },
  {
    emoji: '🥙',
    name: 'stuffed flatbread',
    keywords: ['flatbread', 'gyro', 'sandwich'],
    category: 'food',
    color: '#DEB887',
  },
  {
    emoji: '🧆',
    name: 'falafel',
    keywords: ['falafel', 'chickpea', 'meatball'],
    category: 'food',
    color: '#8B4513',
  },
  {
    emoji: '🌮',
    name: 'taco',
    keywords: ['taco', 'mexican', 'food'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🌯',
    name: 'burrito',
    keywords: ['burrito', 'mexican', 'wrap'],
    category: 'food',
    color: '#F5DEB3',
  },
  {
    emoji: '🫔',
    name: 'tamale',
    keywords: ['tamale', 'mexican', 'wrapped'],
    category: 'food',
    color: '#90EE90',
  },
  {
    emoji: '🥗',
    name: 'green salad',
    keywords: ['salad', 'food', 'green'],
    category: 'food',
    color: '#90EE90',
  },
  {
    emoji: '🥘',
    name: 'shallow pan of food',
    keywords: ['paella', 'curry', 'casserole'],
    category: 'food',
    color: '#FF8C00',
  },
  {
    emoji: '🫕',
    name: 'fondue',
    keywords: ['fondue', 'cheese', 'pot'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🥫',
    name: 'canned food',
    keywords: ['can', 'soup', 'preserve'],
    category: 'food',
    color: '#DC143C',
  },

  // Asian foods
  {
    emoji: '🍱',
    name: 'bento box',
    keywords: ['bento', 'box', 'japanese'],
    category: 'food',
    color: '#8B4513',
  },
  {
    emoji: '🍘',
    name: 'rice cracker',
    keywords: ['rice', 'cracker', 'japanese'],
    category: 'food',
    color: '#F5DEB3',
  },
  {
    emoji: '🍙',
    name: 'rice ball',
    keywords: ['rice', 'ball', 'japanese'],
    category: 'food',
    color: '#F5F5F5',
  },
  {
    emoji: '🍚',
    name: 'cooked rice',
    keywords: ['rice', 'cook', 'food'],
    category: 'food',
    color: '#F5F5F5',
  },
  {
    emoji: '🍛',
    name: 'curry rice',
    keywords: ['curry', 'rice', 'food'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🍜',
    name: 'steaming bowl',
    keywords: ['noodle', 'chopsticks', 'ramen'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🍝',
    name: 'spaghetti',
    keywords: ['pasta', 'noodle', 'italian'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🍢',
    name: 'oden',
    keywords: ['oden', 'skewer', 'seafood'],
    category: 'food',
    color: '#DEB887',
  },
  {
    emoji: '🍣',
    name: 'sushi',
    keywords: ['sushi', 'fish', 'japanese'],
    category: 'food',
    color: '#FF69B4',
  },
  {
    emoji: '🍤',
    name: 'fried shrimp',
    keywords: ['shrimp', 'tempura', 'prawn'],
    category: 'food',
    color: '#FF8C00',
  },
  {
    emoji: '🍥',
    name: 'fish cake with swirl',
    keywords: ['fish', 'cake', 'swirl'],
    category: 'food',
    color: '#FFB6C1',
  },
  {
    emoji: '🥮',
    name: 'moon cake',
    keywords: ['mooncake', 'festival', 'autumn'],
    category: 'food',
    color: '#DEB887',
  },
  {
    emoji: '🍡',
    name: 'dango',
    keywords: ['dango', 'dessert', 'sweet'],
    category: 'food',
    color: '#FFB6C1',
  },
  {
    emoji: '🥟',
    name: 'dumpling',
    keywords: ['dumpling', 'potsticker', 'pierogi'],
    category: 'food',
    color: '#F5DEB3',
  },
  {
    emoji: '🥠',
    name: 'fortune cookie',
    keywords: ['fortune', 'cookie', 'food'],
    category: 'food',
    color: '#DEB887',
  },
  {
    emoji: '🥡',
    name: 'takeout box',
    keywords: ['takeout', 'chinese', 'food'],
    category: 'food',
    color: '#F5F5F5',
  },

  // Sweets

  // Desserts and sweets
  {
    emoji: '🍦',
    name: 'soft ice cream',
    keywords: ['icecream', 'soft', 'dessert'],
    category: 'food',
    color: '#F5F5F5',
  },
  {
    emoji: '🍧',
    name: 'shaved ice',
    keywords: ['shaved', 'ice', 'dessert'],
    category: 'food',
    color: '#87CEEB',
  },
  {
    emoji: '🍨',
    name: 'ice cream',
    keywords: ['ice', 'cream', 'dessert'],
    category: 'food',
    color: '#FFB6C1',
  },
  {
    emoji: '🍩',
    name: 'doughnut',
    keywords: ['donut', 'dessert', 'snack'],
    category: 'food',
    color: '#D2691E',
  },
  {
    emoji: '🍪',
    name: 'cookie',
    keywords: ['cookie', 'snack', 'chocolate'],
    category: 'food',
    color: '#D2691E',
  },
  {
    emoji: '🎂',
    name: 'birthday cake',
    keywords: ['cake', 'birthday', 'dessert'],
    category: 'food',
    color: '#FFB6C1',
  },
  {
    emoji: '🍰',
    name: 'shortcake',
    keywords: ['cake', 'dessert', 'slice'],
    category: 'food',
    color: '#FFE4E1',
  },
  {
    emoji: '🧁',
    name: 'cupcake',
    keywords: ['cupcake', 'food', 'dessert'],
    category: 'food',
    color: '#FFB6C1',
  },
  {
    emoji: '🥧',
    name: 'pie',
    keywords: ['pie', 'filling', 'thanksgiving'],
    category: 'food',
    color: '#DEB887',
  },
  {
    emoji: '🍫',
    name: 'chocolate bar',
    keywords: ['chocolate', 'sweet', 'dessert'],
    category: 'food',
    color: '#D2691E',
  },
  {
    emoji: '🍬',
    name: 'candy',
    keywords: ['candy', 'snack', 'dessert'],
    category: 'food',
    color: '#FF69B4',
  },
  {
    emoji: '🍭',
    name: 'lollipop',
    keywords: ['lollipop', 'candy', 'snack'],
    category: 'food',
    color: '#FF69B4',
  },
  {
    emoji: '🍮',
    name: 'custard',
    keywords: ['custard', 'pudding', 'dessert'],
    category: 'food',
    color: '#F0E68C',
  },

  // Beverages
  {
    emoji: '☕',
    name: 'hot beverage',
    keywords: ['coffee', 'cafe', 'espresso'],
    category: 'food',
    color: '#8B4513',
  },
  {
    emoji: '🍵',
    name: 'teacup without handle',
    keywords: ['tea', 'green', 'breakfast'],
    category: 'food',
    color: '#90EE90',
  },
  {
    emoji: '🫖',
    name: 'teapot',
    keywords: ['teapot', 'tea', 'drink'],
    category: 'food',
    color: '#8B4513',
  },
  {
    emoji: '🍶',
    name: 'sake',
    keywords: ['sake', 'wine', 'drink'],
    category: 'food',
    color: '#F5F5F5',
  },
  {
    emoji: '🍾',
    name: 'bottle with popping cork',
    keywords: ['champagne', 'bottle', 'bubbly'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🍷',
    name: 'wine glass',
    keywords: ['wine', 'drink', 'drunk'],
    category: 'food',
    color: '#8B0000',
  },
  {
    emoji: '🍸',
    name: 'cocktail glass',
    keywords: ['drink', 'drunk', 'alcohol'],
    category: 'food',
    color: '#FF69B4',
  },
  {
    emoji: '🍹',
    name: 'tropical drink',
    keywords: ['tropical', 'drink', 'mojito'],
    category: 'food',
    color: '#FF69B4',
  },
  {
    emoji: '🍺',
    name: 'beer mug',
    keywords: ['beer', 'drink', 'stein'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🍻',
    name: 'clinking beer mugs',
    keywords: ['beers', 'drinks', 'cheers'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🥂',
    name: 'clinking glasses',
    keywords: ['cheers', 'champagne', 'glass'],
    category: 'food',
    color: '#FFD700',
  },
  {
    emoji: '🥃',
    name: 'tumbler glass',
    keywords: ['whisky', 'liquor', 'shot'],
    category: 'food',
    color: '#8B4513',
  },
  {
    emoji: '🥤',
    name: 'cup with straw',
    keywords: ['drink', 'soda', 'soft drink'],
    category: 'food',
    color: '#DC143C',
  },
  {
    emoji: '🧋',
    name: 'bubble tea',
    keywords: ['bubble', 'tea', 'pearl'],
    category: 'food',
    color: '#DEB887',
  },
  {
    emoji: '🧃',
    name: 'beverage box',
    keywords: ['juice', 'straw', 'drink'],
    category: 'food',
    color: '#FFA500',
  },
  {
    emoji: '🧉',
    name: 'mate',
    keywords: ['mate', 'drink', 'tea'],
    category: 'food',
    color: '#8B4513',
  },
  {
    emoji: '🧊',
    name: 'ice',
    keywords: ['ice', 'cube', 'iceberg'],
    category: 'food',
    color: '#87CEEB',
  },

  // Utensils
  {
    emoji: '🥢',
    name: 'chopsticks',
    keywords: ['chopsticks', 'food', 'hashi'],
    category: 'food',
    color: '#8B4513',
  },
  {
    emoji: '🍴',
    name: 'fork and knife',
    keywords: ['cutlery', 'fork', 'knife'],
    category: 'food',
    color: '#C0C0C0',
  },
  {
    emoji: '🥄',
    name: 'spoon',
    keywords: ['spoon', 'tableware', 'cutlery'],
    category: 'food',
    color: '#C0C0C0',
  },
  {
    emoji: '🔪',
    name: 'kitchen knife',
    keywords: ['knife', 'blade', 'cutlery'],
    category: 'food',
    color: '#C0C0C0',
  },
  {
    emoji: '🏺',
    name: 'amphora',
    keywords: ['jar', 'vase', 'amphora'],
    category: 'food',
    color: '#8B4513',
  },
];
