import type { Emoji } from '../../schema';

export const objectEmojis: Omit<Emoji, 'sentiment'>[] = [
  // Glasses and optical
  {
    emoji: '👓',
    name: 'glasses',
    keywords: ['fashion', 'accessories', 'eyesight'],
    category: 'objects',
    color: '#696969',
    tags: ['glasses', 'eyewear', 'vision'],
  },
  {
    emoji: '🕶️',
    name: 'sunglasses',
    keywords: ['face', 'cool', 'accessories'],
    category: 'objects',
    color: '#000000',
    tags: ['sunglasses', 'cool', 'shade'],
  },
  {
    emoji: '🥽',
    name: 'goggles',
    keywords: ['eyes', 'protection', 'safety'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['goggles', 'safety', 'swimming'],
  },
  {
    emoji: '🥼',
    name: 'lab coat',
    keywords: ['doctor', 'experiment', 'scientist'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['lab-coat', 'scientist', 'doctor'],
  },
  {
    emoji: '🦺',
    name: 'safety vest',
    keywords: ['safety', 'orange', 'warning'],
    category: 'objects',
    color: '#FF8C00',
    tags: ['safety-vest', 'construction', 'visibility'],
  },
  {
    emoji: '👔',
    name: 'necktie',
    keywords: ['shirt', 'suitup', 'formal'],
    category: 'objects',
    color: '#4169E1',
    tags: ['tie', 'formal', 'business'],
  },
  {
    emoji: '👕',
    name: 't-shirt',
    keywords: ['fashion', 'cloth', 'casual'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['t-shirt', 'casual', 'clothing'],
  },
  {
    emoji: '👖',
    name: 'jeans',
    keywords: ['fashion', 'shopping', 'pants'],
    category: 'objects',
    color: '#4169E1',
    tags: ['jeans', 'pants', 'denim'],
  },
  {
    emoji: '🧣',
    name: 'scarf',
    keywords: ['neck', 'winter', 'clothes'],
    category: 'objects',
    color: '#DC143C',
    tags: ['scarf', 'winter', 'warm'],
  },
  {
    emoji: '🧤',
    name: 'gloves',
    keywords: ['hands', 'winter', 'clothes'],
    category: 'objects',
    color: '#8B4513',
    tags: ['gloves', 'winter', 'hands'],
  },
  {
    emoji: '🧥',
    name: 'coat',
    keywords: ['jacket', 'coat', 'clothes'],
    category: 'objects',
    color: '#8B4513',
    tags: ['coat', 'jacket', 'winter'],
  },
  {
    emoji: '🧦',
    name: 'socks',
    keywords: ['stocking', 'clothes', 'feet'],
    category: 'objects',
    color: '#DC143C',
    tags: ['socks', 'feet', 'clothing'],
  },
  {
    emoji: '👗',
    name: 'dress',
    keywords: ['clothes', 'fashion', 'shopping'],
    category: 'objects',
    color: '#FF69B4',
    tags: ['dress', 'fashion', 'clothing'],
  },
  {
    emoji: '👘',
    name: 'kimono',
    keywords: ['dress', 'fashion', 'women'],
    category: 'objects',
    color: '#FF69B4',
    tags: ['kimono', 'japanese', 'traditional'],
  },
  {
    emoji: '🥻',
    name: 'sari',
    keywords: ['dress', 'fashion', 'indian'],
    category: 'objects',
    color: '#FF69B4',
    tags: ['sari', 'indian', 'traditional'],
  },
  {
    emoji: '🩱',
    name: 'one-piece swimsuit',
    keywords: ['fashion', 'swim', 'bathing'],
    category: 'objects',
    color: '#4169E1',
    tags: ['swimsuit', 'swimming', 'beach'],
  },
  {
    emoji: '🩲',
    name: 'briefs',
    keywords: ['clothing', 'underwear', 'pants'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['underwear', 'briefs', 'clothing'],
  },
  {
    emoji: '🩳',
    name: 'shorts',
    keywords: ['clothing', 'pants', 'fashion'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['shorts', 'summer', 'clothing'],
  },
  {
    emoji: '👙',
    name: 'bikini',
    keywords: ['swimming', 'female', 'woman'],
    category: 'objects',
    color: '#FF69B4',
    tags: ['bikini', 'swimsuit', 'beach'],
  },
  {
    emoji: '👚',
    name: `woman's clothes`,
    keywords: ['fashion', 'shopping', 'female'],
    category: 'objects',
    color: '#FFB6C1',
    tags: ['blouse', 'woman', 'clothing'],
  },
  {
    emoji: '👛',
    name: 'purse',
    keywords: ['fashion', 'accessories', 'money'],
    category: 'objects',
    color: '#FF69B4',
    tags: ['purse', 'wallet', 'accessory'],
  },
  {
    emoji: '👜',
    name: 'handbag',
    keywords: ['fashion', 'accessory', 'accessories'],
    category: 'objects',
    color: '#8B4513',
    tags: ['handbag', 'purse', 'fashion'],
  },
  {
    emoji: '👝',
    name: 'clutch bag',
    keywords: ['bag', 'accessories', 'shopping'],
    category: 'objects',
    color: '#FFD700',
    tags: ['clutch', 'bag', 'evening'],
  },
  {
    emoji: '🛍️',
    name: 'shopping bags',
    keywords: ['mall', 'buy', 'purchase'],
    category: 'objects',
    color: '#FF69B4',
    tags: ['shopping', 'bags', 'retail'],
  },
  {
    emoji: '🎒',
    name: 'backpack',
    keywords: ['student', 'education', 'bag'],
    category: 'objects',
    color: '#DC143C',
    tags: ['backpack', 'school', 'bag'],
  },
  {
    emoji: '🩴',
    name: 'thong sandal',
    keywords: ['footwear', 'summer', 'flip flop'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['flip-flop', 'sandal', 'summer'],
  },
  {
    emoji: '👞',
    name: `man's shoe`,
    keywords: ['fashion', 'male', 'formal'],
    category: 'objects',
    color: '#8B4513',
    tags: ['shoe', 'formal', 'men'],
  },
  {
    emoji: '👟',
    name: 'running shoe',
    keywords: ['shoes', 'sports', 'sneakers'],
    category: 'objects',
    color: '#DC143C',
    tags: ['sneaker', 'running', 'athletic'],
  },
  {
    emoji: '🥾',
    name: 'hiking boot',
    keywords: ['backpacking', 'camping', 'hiking'],
    category: 'objects',
    color: '#8B4513',
    tags: ['boot', 'hiking', 'outdoor'],
  },
  {
    emoji: '🥿',
    name: 'flat shoe',
    keywords: ['ballet flat', 'slip-on', 'slipper'],
    category: 'objects',
    color: '#FFB6C1',
    tags: ['flat', 'shoe', 'ballet'],
  },
  {
    emoji: '👠',
    name: 'high-heeled shoe',
    keywords: ['fashion', 'shoes', 'female'],
    category: 'objects',
    color: '#DC143C',
    tags: ['high-heel', 'shoe', 'fashion'],
  },
  {
    emoji: '👡',
    name: `woman's sandal`,
    keywords: ['shoes', 'fashion', 'flip flops'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['sandal', 'woman', 'summer'],
  },
  {
    emoji: '🩰',
    name: 'ballet shoes',
    keywords: ['dance', 'ballet', 'shoes'],
    category: 'objects',
    color: '#FFB6C1',
    tags: ['ballet', 'dance', 'shoes'],
  },
  {
    emoji: '👢',
    name: `woman's boot`,
    keywords: ['shoes', 'fashion', 'boot'],
    category: 'objects',
    color: '#8B4513',
    tags: ['boot', 'woman', 'fashion'],
  },
  {
    emoji: '👑',
    name: 'crown',
    keywords: ['king', 'kod', 'leader'],
    category: 'objects',
    color: '#FFD700',
    tags: ['crown', 'royal', 'king'],
  },
  {
    emoji: '👒',
    name: `woman's hat`,
    keywords: ['fashion', 'accessories', 'female'],
    category: 'objects',
    color: '#F5DEB3',
    tags: ['hat', 'woman', 'sun'],
  },
  {
    emoji: '🎩',
    name: 'top hat',
    keywords: ['magic', 'gentleman', 'classy'],
    category: 'objects',
    color: '#000000',
    tags: ['top-hat', 'formal', 'magician'],
  },
  {
    emoji: '🎓',
    name: 'graduation cap',
    keywords: ['school', 'college', 'degree'],
    category: 'objects',
    color: '#000000',
    tags: ['graduation', 'cap', 'education'],
  },
  {
    emoji: '🧢',
    name: 'billed cap',
    keywords: ['cap', 'baseball', 'hat'],
    category: 'objects',
    color: '#DC143C',
    tags: ['baseball-cap', 'hat', 'casual'],
  },
  {
    emoji: '🪖',
    name: 'military helmet',
    keywords: ['army', 'protection', 'soldier'],
    category: 'objects',
    color: '#556B2F',
    tags: ['helmet', 'military', 'army'],
  },
  {
    emoji: '⛑️',
    name: `rescue worker's helmet`,
    keywords: ['construction', 'build', 'safety'],
    category: 'objects',
    color: '#DC143C',
    tags: ['helmet', 'rescue', 'safety'],
  },
  {
    emoji: '📿',
    name: 'prayer beads',
    keywords: ['dhikr', 'religious', 'rosary'],
    category: 'objects',
    color: '#8B4513',
    tags: ['beads', 'prayer', 'religious'],
  },
  {
    emoji: '💄',
    name: 'lipstick',
    keywords: ['female', 'girl', 'fashion'],
    category: 'objects',
    color: '#DC143C',
    tags: ['lipstick', 'makeup', 'cosmetic'],
  },
  {
    emoji: '💍',
    name: 'ring',
    keywords: ['wedding', 'propose', 'marriage'],
    category: 'objects',
    color: '#FFD700',
    tags: ['ring', 'diamond', 'engagement'],
  },
  {
    emoji: '💎',
    name: 'gem stone',
    keywords: ['blue', 'ruby', 'diamond'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['diamond', 'gem', 'jewelry'],
  },

  // Sound
  {
    emoji: '🔇',
    name: 'muted speaker',
    keywords: ['sound', 'volume', 'silence'],
    category: 'objects',
    color: '#696969',
    tags: ['mute', 'silent', 'speaker'],
  },
  {
    emoji: '🔈',
    name: 'speaker low volume',
    keywords: ['sound', 'volume', 'silence'],
    category: 'objects',
    color: '#696969',
    tags: ['speaker', 'low', 'volume'],
  },
  {
    emoji: '🔉',
    name: 'speaker medium volume',
    keywords: ['volume', 'speaker', 'broadcast'],
    category: 'objects',
    color: '#696969',
    tags: ['speaker', 'medium', 'volume'],
  },
  {
    emoji: '🔊',
    name: 'speaker high volume',
    keywords: ['volume', 'noise', 'noisy'],
    category: 'objects',
    color: '#696969',
    tags: ['speaker', 'loud', 'volume'],
  },
  {
    emoji: '📢',
    name: 'loudspeaker',
    keywords: ['volume', 'sound', 'announcement'],
    category: 'objects',
    color: '#696969',
    tags: ['loudspeaker', 'announcement', 'megaphone'],
  },
  {
    emoji: '📣',
    name: 'megaphone',
    keywords: ['sound', 'speaker', 'volume'],
    category: 'objects',
    color: '#4169E1',
    tags: ['megaphone', 'cheer', 'loud'],
  },
  {
    emoji: '📯',
    name: 'postal horn',
    keywords: ['instrument', 'music', 'horn'],
    category: 'objects',
    color: '#FFD700',
    tags: ['horn', 'postal', 'announcement'],
  },
  {
    emoji: '🔔',
    name: 'bell',
    keywords: ['sound', 'notification', 'christmas'],
    category: 'objects',
    color: '#FFD700',
    tags: ['bell', 'ring', 'notification'],
  },
  {
    emoji: '🔕',
    name: 'bell with slash',
    keywords: ['sound', 'volume', 'mute'],
    category: 'objects',
    color: '#DC143C',
    tags: ['bell', 'mute', 'silent'],
  },

  // Technology
  {
    emoji: '📱',
    name: 'mobile phone',
    keywords: ['technology', 'apple', 'gadgets'],
    category: 'objects',
    color: '#000000',
    tags: ['phone', 'mobile', 'smartphone'],
  },
  {
    emoji: '📲',
    name: 'mobile phone with arrow',
    keywords: ['iphone', 'incoming', 'call'],
    category: 'objects',
    color: '#000000',
    tags: ['phone', 'incoming', 'call'],
  },
  {
    emoji: '☎️',
    name: 'telephone',
    keywords: ['technology', 'communication', 'dial'],
    category: 'objects',
    color: '#DC143C',
    tags: ['telephone', 'phone', 'landline'],
  },
  {
    emoji: '📞',
    name: 'telephone receiver',
    keywords: ['technology', 'communication', 'dial'],
    category: 'objects',
    color: '#000000',
    tags: ['phone', 'receiver', 'call'],
  },
  {
    emoji: '📟',
    name: 'pager',
    keywords: ['bbcall', 'oldschool', '90s'],
    category: 'objects',
    color: '#000000',
    tags: ['pager', 'beeper', 'retro'],
  },
  {
    emoji: '📠',
    name: 'fax machine',
    keywords: ['communication', 'technology', 'fax'],
    category: 'objects',
    color: '#696969',
    tags: ['fax', 'machine', 'office'],
  },
  {
    emoji: '🔋',
    name: 'battery',
    keywords: ['power', 'energy', 'sustain'],
    category: 'objects',
    color: '#90EE90',
    tags: ['battery', 'power', 'energy'],
  },
  {
    emoji: '🔌',
    name: 'electric plug',
    keywords: ['charger', 'power', 'electricity'],
    category: 'objects',
    color: '#000000',
    tags: ['plug', 'electric', 'power'],
  },
  {
    emoji: '💻',
    name: 'laptop',
    keywords: ['technology', 'laptop', 'screen'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['laptop', 'computer', 'technology'],
  },
  {
    emoji: '🖥️',
    name: 'desktop computer',
    keywords: ['technology', 'computing', 'screen'],
    category: 'objects',
    color: '#696969',
    tags: ['desktop', 'computer', 'monitor'],
  },
  {
    emoji: '🖨️',
    name: 'printer',
    keywords: ['paper', 'ink', 'office'],
    category: 'objects',
    color: '#696969',
    tags: ['printer', 'print', 'office'],
  },
  {
    emoji: '⌨️',
    name: 'keyboard',
    keywords: ['technology', 'computer', 'type'],
    category: 'objects',
    color: '#696969',
    tags: ['keyboard', 'typing', 'computer'],
  },
  {
    emoji: '🖱️',
    name: 'computer mouse',
    keywords: ['click', 'button', 'pointer'],
    category: 'objects',
    color: '#696969',
    tags: ['mouse', 'computer', 'click'],
  },
  {
    emoji: '🖲️',
    name: 'trackball',
    keywords: ['technology', 'trackball', 'computer'],
    category: 'objects',
    color: '#000000',
    tags: ['trackball', 'mouse', 'computer'],
  },
  {
    emoji: '💽',
    name: 'computer disk',
    keywords: ['technology', 'record', 'data'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['minidisc', 'disk', 'storage'],
  },
  {
    emoji: '💾',
    name: 'floppy disk',
    keywords: ['oldschool', 'technology', 'save'],
    category: 'objects',
    color: '#000000',
    tags: ['floppy', 'save', 'disk'],
  },
  {
    emoji: '💿',
    name: 'optical disk',
    keywords: ['technology', 'dvd', 'disk'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['cd', 'dvd', 'disk'],
  },
  {
    emoji: '📀',
    name: 'dvd',
    keywords: ['cd', 'disk', 'disc'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['dvd', 'disk', 'movie'],
  },
  {
    emoji: '🧮',
    name: 'abacus',
    keywords: ['calculation', 'math', 'count'],
    category: 'objects',
    color: '#8B4513',
    tags: ['abacus', 'calculator', 'math'],
  },

  // Media
  {
    emoji: '🎥',
    name: 'movie camera',
    keywords: ['film', 'record', 'movie'],
    category: 'objects',
    color: '#000000',
    tags: ['camera', 'movie', 'film'],
  },
  {
    emoji: '🎞️',
    name: 'film frames',
    keywords: ['movie', 'film', 'frames'],
    category: 'objects',
    color: '#000000',
    tags: ['film', 'frames', 'movie'],
  },
  {
    emoji: '📽️',
    name: 'film projector',
    keywords: ['movie', 'film', 'projector'],
    category: 'objects',
    color: '#696969',
    tags: ['projector', 'film', 'movie'],
  },
  {
    emoji: '🎬',
    name: 'clapper board',
    keywords: ['movie', 'film', 'record'],
    category: 'objects',
    color: '#000000',
    tags: ['clapper', 'movie', 'action'],
  },
  {
    emoji: '📺',
    name: 'television',
    keywords: ['technology', 'program', 'oldschool'],
    category: 'objects',
    color: '#696969',
    tags: ['tv', 'television', 'screen'],
  },
  {
    emoji: '📷',
    name: 'camera',
    keywords: ['gadgets', 'photography', 'camera'],
    category: 'objects',
    color: '#000000',
    tags: ['camera', 'photo', 'photography'],
  },
  {
    emoji: '📸',
    name: 'camera with flash',
    keywords: ['photography', 'gadgets', 'flash'],
    category: 'objects',
    color: '#000000',
    tags: ['camera', 'flash', 'photo'],
  },
  {
    emoji: '📹',
    name: 'video camera',
    keywords: ['film', 'record', 'video'],
    category: 'objects',
    color: '#000000',
    tags: ['video', 'camera', 'record'],
  },
  {
    emoji: '📼',
    name: 'videocassette',
    keywords: ['record', 'video', 'oldschool'],
    category: 'objects',
    color: '#000000',
    tags: ['vhs', 'video', 'cassette'],
  },
  {
    emoji: '🔍',
    name: 'magnifying glass tilted left',
    keywords: ['search', 'zoom', 'find'],
    category: 'objects',
    color: '#4169E1',
    tags: ['magnifying', 'search', 'zoom'],
  },
  {
    emoji: '🔎',
    name: 'magnifying glass tilted right',
    keywords: ['search', 'zoom', 'find'],
    category: 'objects',
    color: '#4169E1',
    tags: ['magnifying', 'search', 'detective'],
  },
  {
    emoji: '🕯️',
    name: 'candle',
    keywords: ['fire', 'wax', 'light'],
    category: 'objects',
    color: '#F0E68C',
    tags: ['candle', 'light', 'flame'],
  },
  {
    emoji: '💡',
    name: 'light bulb',
    keywords: ['light', 'electricity', 'idea'],
    category: 'objects',
    color: '#FFD700',
    tags: ['lightbulb', 'idea', 'bright'],
  },
  {
    emoji: '🔦',
    name: 'flashlight',
    keywords: ['dark', 'camping', 'sight'],
    category: 'objects',
    color: '#FFD700',
    tags: ['flashlight', 'torch', 'light'],
  },
  {
    emoji: '🏮',
    name: 'red paper lantern',
    keywords: ['light', 'paper', 'halloween'],
    category: 'objects',
    color: '#DC143C',
    tags: ['lantern', 'paper', 'chinese'],
  },
  {
    emoji: '🪔',
    name: 'diya lamp',
    keywords: ['lighting', 'candle', 'diwali'],
    category: 'objects',
    color: '#FF8C00',
    tags: ['diya', 'lamp', 'diwali'],
  },

  // Books and paper
  {
    emoji: '📔',
    name: 'notebook with decorative cover',
    keywords: ['classroom', 'notes', 'record'],
    category: 'objects',
    color: '#DEB887',
    tags: ['notebook', 'journal', 'decorative'],
  },
  {
    emoji: '📕',
    name: 'closed book',
    keywords: ['read', 'library', 'knowledge'],
    category: 'objects',
    color: '#DC143C',
    tags: ['book', 'closed', 'red'],
  },
  {
    emoji: '📖',
    name: 'open book',
    keywords: ['book', 'read', 'open'],
    category: 'objects',
    color: '#4169E1',
    tags: ['book', 'open', 'reading'],
  },
  {
    emoji: '📗',
    name: 'green book',
    keywords: ['read', 'library', 'knowledge'],
    category: 'objects',
    color: '#90EE90',
    tags: ['book', 'green', 'textbook'],
  },
  {
    emoji: '📘',
    name: 'blue book',
    keywords: ['read', 'library', 'knowledge'],
    category: 'objects',
    color: '#4169E1',
    tags: ['book', 'blue', 'textbook'],
  },
  {
    emoji: '📙',
    name: 'orange book',
    keywords: ['read', 'library', 'knowledge'],
    category: 'objects',
    color: '#FF8C00',
    tags: ['book', 'orange', 'textbook'],
  },
  {
    emoji: '📚',
    name: 'books',
    keywords: ['literature', 'library', 'study'],
    category: 'objects',
    color: '#8B4513',
    tags: ['books', 'library', 'stack'],
  },
  {
    emoji: '📓',
    name: 'notebook',
    keywords: ['stationery', 'record', 'notes'],
    category: 'objects',
    color: '#000000',
    tags: ['notebook', 'notes', 'journal'],
  },
  {
    emoji: '📒',
    name: 'ledger',
    keywords: ['notes', 'paper', 'notebook'],
    category: 'objects',
    color: '#FFD700',
    tags: ['ledger', 'notebook', 'accounting'],
  },
  {
    emoji: '📃',
    name: 'page with curl',
    keywords: ['documents', 'office', 'paper'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['page', 'document', 'curl'],
  },
  {
    emoji: '📜',
    name: 'scroll',
    keywords: ['documents', 'ancient', 'history'],
    category: 'objects',
    color: '#DEB887',
    tags: ['scroll', 'ancient', 'document'],
  },
  {
    emoji: '📄',
    name: 'page facing up',
    keywords: ['documents', 'office', 'paper'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['page', 'document', 'paper'],
  },
  {
    emoji: '📰',
    name: 'newspaper',
    keywords: ['press', 'headline', 'news'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['newspaper', 'news', 'press'],
  },
  {
    emoji: '🗞️',
    name: 'rolled-up newspaper',
    keywords: ['press', 'headline', 'delivery'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['newspaper', 'rolled', 'delivery'],
  },
  {
    emoji: '📑',
    name: 'bookmark tabs',
    keywords: ['favorite', 'save', 'order'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['bookmarks', 'tabs', 'organize'],
  },
  {
    emoji: '🔖',
    name: 'bookmark',
    keywords: ['favorite', 'label', 'save'],
    category: 'objects',
    color: '#DC143C',
    tags: ['bookmark', 'save', 'mark'],
  },
  {
    emoji: '🏷️',
    name: 'label',
    keywords: ['sale', 'tag', 'price'],
    category: 'objects',
    color: '#F0E68C',
    tags: ['label', 'tag', 'price'],
  },

  // Money
  {
    emoji: '💰',
    name: 'money bag',
    keywords: ['dollar', 'payment', 'coins'],
    category: 'objects',
    color: '#F0E68C',
    tags: ['money', 'bag', 'wealth'],
  },
  {
    emoji: '🪙',
    name: 'coin',
    keywords: ['money', 'currency', 'gold'],
    category: 'objects',
    color: '#FFD700',
    tags: ['coin', 'money', 'currency'],
  },
  {
    emoji: '💴',
    name: 'yen banknote',
    keywords: ['money', 'sales', 'japanese'],
    category: 'objects',
    color: '#F0E68C',
    tags: ['yen', 'money', 'japanese'],
  },
  {
    emoji: '💵',
    name: 'dollar banknote',
    keywords: ['money', 'sales', 'bill'],
    category: 'objects',
    color: '#90EE90',
    tags: ['dollar', 'money', 'cash'],
  },
  {
    emoji: '💶',
    name: 'euro banknote',
    keywords: ['money', 'sales', 'dollar'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['euro', 'money', 'european'],
  },
  {
    emoji: '💷',
    name: 'pound banknote',
    keywords: ['british', 'sterling', 'money'],
    category: 'objects',
    color: '#DDA0DD',
    tags: ['pound', 'money', 'british'],
  },
  {
    emoji: '💸',
    name: 'money with wings',
    keywords: ['dollar', 'bills', 'payment'],
    category: 'objects',
    color: '#90EE90',
    tags: ['money', 'flying', 'spending'],
  },
  {
    emoji: '💳',
    name: 'credit card',
    keywords: ['money', 'sales', 'shopping'],
    category: 'objects',
    color: '#4169E1',
    tags: ['credit-card', 'payment', 'shopping'],
  },
  {
    emoji: '🧾',
    name: 'receipt',
    keywords: ['accounting', 'expenses', 'bill'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['receipt', 'bill', 'payment'],
  },
  {
    emoji: '💹',
    name: 'chart increasing with yen',
    keywords: ['green-square', 'graph', 'presentation'],
    category: 'objects',
    color: '#90EE90',
    tags: ['chart', 'stocks', 'increase'],
  },

  // Mail
  {
    emoji: '✉️',
    name: 'envelope',
    keywords: ['letter', 'postal', 'inbox'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['envelope', 'mail', 'letter'],
  },
  {
    emoji: '📧',
    name: 'e-mail',
    keywords: ['communication', 'inbox', 'email'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['email', 'mail', 'electronic'],
  },
  {
    emoji: '📨',
    name: 'incoming envelope',
    keywords: ['email', 'inbox', 'mail'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['envelope', 'incoming', 'mail'],
  },
  {
    emoji: '📩',
    name: 'envelope with arrow',
    keywords: ['email', 'communication', 'sent'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['envelope', 'sent', 'mail'],
  },
  {
    emoji: '📤',
    name: 'outbox tray',
    keywords: ['inbox', 'email', 'sent'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['outbox', 'sent', 'mail'],
  },
  {
    emoji: '📥',
    name: 'inbox tray',
    keywords: ['email', 'documents', 'inbox'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['inbox', 'received', 'mail'],
  },
  {
    emoji: '📦',
    name: 'package',
    keywords: ['mail', 'gift', 'cardboard'],
    category: 'objects',
    color: '#8B4513',
    tags: ['package', 'box', 'delivery'],
  },
  {
    emoji: '📫',
    name: 'closed mailbox with raised flag',
    keywords: ['email', 'inbox', 'communication'],
    category: 'objects',
    color: '#4169E1',
    tags: ['mailbox', 'mail', 'full'],
  },
  {
    emoji: '📪',
    name: 'closed mailbox with lowered flag',
    keywords: ['email', 'communication', 'inbox'],
    category: 'objects',
    color: '#4169E1',
    tags: ['mailbox', 'empty', 'mail'],
  },
  {
    emoji: '📬',
    name: 'open mailbox with raised flag',
    keywords: ['email', 'inbox', 'communication'],
    category: 'objects',
    color: '#4169E1',
    tags: ['mailbox', 'open', 'mail'],
  },
  {
    emoji: '📭',
    name: 'open mailbox with lowered flag',
    keywords: ['email', 'inbox', 'communication'],
    category: 'objects',
    color: '#4169E1',
    tags: ['mailbox', 'open', 'empty'],
  },
  {
    emoji: '📮',
    name: 'postbox',
    keywords: ['email', 'letter', 'envelope'],
    category: 'objects',
    color: '#DC143C',
    tags: ['postbox', 'mail', 'letters'],
  },
  {
    emoji: '🗳️',
    name: 'ballot box with ballot',
    keywords: ['election', 'vote', 'ballot'],
    category: 'objects',
    color: '#4169E1',
    tags: ['ballot', 'vote', 'election'],
  },

  // Writing tools
  {
    emoji: '✏️',
    name: 'pencil',
    keywords: ['stationery', 'write', 'paper'],
    category: 'objects',
    color: '#FFD700',
    tags: ['pencil', 'write', 'draw'],
  },
  {
    emoji: '✒️',
    name: 'black nib',
    keywords: ['pen', 'stationery', 'writing'],
    category: 'objects',
    color: '#000000',
    tags: ['nib', 'pen', 'writing'],
  },
  {
    emoji: '🖋️',
    name: 'fountain pen',
    keywords: ['stationery', 'writing', 'write'],
    category: 'objects',
    color: '#000000',
    tags: ['fountain-pen', 'writing', 'fancy'],
  },
  {
    emoji: '🖊️',
    name: 'pen',
    keywords: ['stationery', 'writing', 'write'],
    category: 'objects',
    color: '#4169E1',
    tags: ['pen', 'ballpoint', 'writing'],
  },
  {
    emoji: '🖌️',
    name: 'paintbrush',
    keywords: ['drawing', 'creativity', 'art'],
    category: 'objects',
    color: '#8B4513',
    tags: ['paintbrush', 'art', 'painting'],
  },
  {
    emoji: '🖍️',
    name: 'crayon',
    keywords: ['drawing', 'creativity', 'color'],
    category: 'objects',
    color: '#DC143C',
    tags: ['crayon', 'drawing', 'coloring'],
  },
  {
    emoji: '📝',
    name: 'memo',
    keywords: ['write', 'documents', 'stationery'],
    category: 'objects',
    color: '#F0E68C',
    tags: ['memo', 'note', 'writing'],
  },

  // Office supplies
  {
    emoji: '💼',
    name: 'briefcase',
    keywords: ['business', 'work', 'law'],
    category: 'objects',
    color: '#8B4513',
    tags: ['briefcase', 'business', 'work'],
  },
  {
    emoji: '📁',
    name: 'file folder',
    keywords: ['documents', 'business', 'office'],
    category: 'objects',
    color: '#FFD700',
    tags: ['folder', 'file', 'documents'],
  },
  {
    emoji: '📂',
    name: 'open file folder',
    keywords: ['documents', 'load', 'folder'],
    category: 'objects',
    color: '#FFD700',
    tags: ['folder', 'open', 'files'],
  },
  {
    emoji: '🗂️',
    name: 'card index dividers',
    keywords: ['organizing', 'business', 'stationery'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['dividers', 'organize', 'index'],
  },
  {
    emoji: '📅',
    name: 'calendar',
    keywords: ['calendar', 'schedule', 'date'],
    category: 'objects',
    color: '#DC143C',
    tags: ['calendar', 'date', 'schedule'],
  },
  {
    emoji: '📆',
    name: 'tear-off calendar',
    keywords: ['schedule', 'date', 'planning'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['calendar', 'tear-off', 'daily'],
  },
  {
    emoji: '🗒️',
    name: 'spiral notepad',
    keywords: ['memo', 'stationery', 'notes'],
    category: 'objects',
    color: '#F0E68C',
    tags: ['notepad', 'spiral', 'notes'],
  },
  {
    emoji: '🗓️',
    name: 'spiral calendar',
    keywords: ['date', 'schedule', 'planning'],
    category: 'objects',
    color: '#DC143C',
    tags: ['calendar', 'spiral', 'desktop'],
  },
  {
    emoji: '📇',
    name: 'card index',
    keywords: ['business', 'stationery', 'rolodex'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['rolodex', 'contacts', 'index'],
  },
  {
    emoji: '📈',
    name: 'chart increasing',
    keywords: ['graph', 'presentation', 'stats'],
    category: 'objects',
    color: '#90EE90',
    tags: ['chart', 'growth', 'increase'],
  },
  {
    emoji: '📉',
    name: 'chart decreasing',
    keywords: ['graph', 'presentation', 'stats'],
    category: 'objects',
    color: '#DC143C',
    tags: ['chart', 'decline', 'decrease'],
  },
  {
    emoji: '📊',
    name: 'bar chart',
    keywords: ['graph', 'presentation', 'stats'],
    category: 'objects',
    color: '#4169E1',
    tags: ['chart', 'bar', 'statistics'],
  },
  {
    emoji: '📋',
    name: 'clipboard',
    keywords: ['stationery', 'documents', 'clipboard'],
    category: 'objects',
    color: '#8B4513',
    tags: ['clipboard', 'notes', 'checklist'],
  },
  {
    emoji: '📌',
    name: 'pushpin',
    keywords: ['stationery', 'mark', 'here'],
    category: 'objects',
    color: '#DC143C',
    tags: ['pushpin', 'pin', 'tack'],
  },
  {
    emoji: '📍',
    name: 'round pushpin',
    keywords: ['stationery', 'location', 'map'],
    category: 'objects',
    color: '#DC143C',
    tags: ['pushpin', 'location', 'marker'],
  },
  {
    emoji: '📎',
    name: 'paperclip',
    keywords: ['documents', 'stationery', 'paperclip'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['paperclip', 'attach', 'clip'],
  },
  {
    emoji: '🖇️',
    name: 'linked paperclips',
    keywords: ['documents', 'stationery', 'link'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['paperclips', 'linked', 'chain'],
  },
  {
    emoji: '📏',
    name: 'straight ruler',
    keywords: ['stationery', 'calculate', 'length'],
    category: 'objects',
    color: '#8B4513',
    tags: ['ruler', 'straight', 'measure'],
  },
  {
    emoji: '📐',
    name: 'triangular ruler',
    keywords: ['stationery', 'math', 'architect'],
    category: 'objects',
    color: '#8B4513',
    tags: ['ruler', 'triangle', 'geometry'],
  },
  {
    emoji: '✂️',
    name: 'scissors',
    keywords: ['stationery', 'cut', 'scissors'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['scissors', 'cut', 'tool'],
  },
  {
    emoji: '🗃️',
    name: 'card file box',
    keywords: ['business', 'stationery', 'index'],
    category: 'objects',
    color: '#696969',
    tags: ['file-box', 'storage', 'archive'],
  },
  {
    emoji: '🗄️',
    name: 'file cabinet',
    keywords: ['filing', 'organizing', 'storage'],
    category: 'objects',
    color: '#696969',
    tags: ['cabinet', 'filing', 'storage'],
  },
  {
    emoji: '🗑️',
    name: 'wastebasket',
    keywords: ['bin', 'trash', 'rubbish'],
    category: 'objects',
    color: '#696969',
    tags: ['trash', 'bin', 'wastebasket'],
  },

  // Locks and security
  {
    emoji: '🔒',
    name: 'locked',
    keywords: ['security', 'password', 'padlock'],
    category: 'objects',
    color: '#FFD700',
    tags: ['lock', 'locked', 'secure'],
  },
  {
    emoji: '🔓',
    name: 'unlocked',
    keywords: ['privacy', 'security', 'unlock'],
    category: 'objects',
    color: '#FFD700',
    tags: ['unlock', 'open', 'unlocked'],
  },
  {
    emoji: '🔏',
    name: 'locked with pen',
    keywords: ['security', 'secret', 'lock'],
    category: 'objects',
    color: '#FFD700',
    tags: ['lock', 'pen', 'secure'],
  },
  {
    emoji: '🔐',
    name: 'locked with key',
    keywords: ['security', 'privacy', 'lock'],
    category: 'objects',
    color: '#FFD700',
    tags: ['lock', 'key', 'secure'],
  },
  {
    emoji: '🔑',
    name: 'key',
    keywords: ['lock', 'door', 'password'],
    category: 'objects',
    color: '#FFD700',
    tags: ['key', 'unlock', 'access'],
  },
  {
    emoji: '🗝️',
    name: 'old key',
    keywords: ['lock', 'door', 'antique'],
    category: 'objects',
    color: '#8B4513',
    tags: ['key', 'old', 'antique'],
  },

  // Tools
  {
    emoji: '🔨',
    name: 'hammer',
    keywords: ['tools', 'build', 'create'],
    category: 'objects',
    color: '#696969',
    tags: ['hammer', 'tool', 'build'],
  },
  {
    emoji: '🪓',
    name: 'axe',
    keywords: ['tool', 'chop', 'cut'],
    category: 'objects',
    color: '#8B4513',
    tags: ['axe', 'chop', 'tool'],
  },
  {
    emoji: '⛏️',
    name: 'pick',
    keywords: ['tools', 'dig', 'mine'],
    category: 'objects',
    color: '#696969',
    tags: ['pickaxe', 'mining', 'tool'],
  },
  {
    emoji: '⚒️',
    name: 'hammer and pick',
    keywords: ['tools', 'build', 'create'],
    category: 'objects',
    color: '#696969',
    tags: ['tools', 'mining', 'work'],
  },
  {
    emoji: '🛠️',
    name: 'hammer and wrench',
    keywords: ['tools', 'build', 'create'],
    category: 'objects',
    color: '#696969',
    tags: ['tools', 'repair', 'fix'],
  },
  {
    emoji: '🗡️',
    name: 'dagger',
    keywords: ['weapon', 'knife', 'blade'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['dagger', 'knife', 'weapon'],
  },
  {
    emoji: '⚔️',
    name: 'crossed swords',
    keywords: ['weapon', 'battle', 'fight'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['swords', 'battle', 'crossed'],
  },
  {
    emoji: '🔫',
    name: 'water pistol',
    keywords: ['violence', 'weapon', 'pistol'],
    category: 'objects',
    color: '#90EE90',
    tags: ['water-gun', 'toy', 'pistol'],
  },
  {
    emoji: '🪃',
    name: 'boomerang',
    keywords: ['weapon', 'australia', 'rebound'],
    category: 'objects',
    color: '#8B4513',
    tags: ['boomerang', 'return', 'throw'],
  },
  {
    emoji: '🏹',
    name: 'bow and arrow',
    keywords: ['sports', 'archery', 'bow'],
    category: 'objects',
    color: '#8B4513',
    tags: ['bow', 'arrow', 'archery'],
  },
  {
    emoji: '🛡️',
    name: 'shield',
    keywords: ['protection', 'security', 'defense'],
    category: 'objects',
    color: '#DC143C',
    tags: ['shield', 'protection', 'defense'],
  },
  {
    emoji: '🪚',
    name: 'carpentry saw',
    keywords: ['cut', 'tool', 'carpenter'],
    category: 'objects',
    color: '#8B4513',
    tags: ['saw', 'carpentry', 'tool'],
  },
  {
    emoji: '🔧',
    name: 'wrench',
    keywords: ['tools', 'diy', 'ikea'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['wrench', 'tool', 'fix'],
  },
  {
    emoji: '🪛',
    name: 'screwdriver',
    keywords: ['tools', 'build', 'fix'],
    category: 'objects',
    color: '#DC143C',
    tags: ['screwdriver', 'tool', 'fix'],
  },
  {
    emoji: '🔩',
    name: 'nut and bolt',
    keywords: ['handy', 'tools', 'fix'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['bolt', 'nut', 'hardware'],
  },
  {
    emoji: '⚙️',
    name: 'gear',
    keywords: ['cog', 'settings', 'machine'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['gear', 'settings', 'cog'],
  },
  {
    emoji: '🗜️',
    name: 'clamp',
    keywords: ['tool', 'compress', 'vice'],
    category: 'objects',
    color: '#696969',
    tags: ['clamp', 'vice', 'tool'],
  },
  {
    emoji: '⚖️',
    name: 'balance scale',
    keywords: ['law', 'fairness', 'weight'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['scale', 'justice', 'balance'],
  },
  {
    emoji: '🦯',
    name: 'white cane',
    keywords: ['accessibility', 'blind', 'cane'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['cane', 'blind', 'accessibility'],
  },
  {
    emoji: '🔗',
    name: 'link',
    keywords: ['rings', 'url', 'chain'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['link', 'chain', 'connection'],
  },
  {
    emoji: '⛓️',
    name: 'chains',
    keywords: ['lock', 'arrest', 'chain'],
    category: 'objects',
    color: '#696969',
    tags: ['chains', 'linked', 'metal'],
  },
  {
    emoji: '🪝',
    name: 'hook',
    keywords: ['catch', 'fishing', 'hang'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['hook', 'fishing', 'catch'],
  },
  {
    emoji: '🧰',
    name: 'toolbox',
    keywords: ['tools', 'diy', 'fix'],
    category: 'objects',
    color: '#DC143C',
    tags: ['toolbox', 'tools', 'repair'],
  },
  {
    emoji: '🧲',
    name: 'magnet',
    keywords: ['attraction', 'magnetic', 'draw'],
    category: 'objects',
    color: '#DC143C',
    tags: ['magnet', 'magnetic', 'attract'],
  },
  {
    emoji: '🪜',
    name: 'ladder',
    keywords: ['climb', 'step', 'tool'],
    category: 'objects',
    color: '#8B4513',
    tags: ['ladder', 'climb', 'steps'],
  },

  // Science
  {
    emoji: '⚗️',
    name: 'alembic',
    keywords: ['distilling', 'science', 'experiment'],
    category: 'objects',
    color: '#4169E1',
    tags: ['alembic', 'chemistry', 'distill'],
  },
  {
    emoji: '🧪',
    name: 'test tube',
    keywords: ['chemistry', 'experiment', 'lab'],
    category: 'objects',
    color: '#90EE90',
    tags: ['test-tube', 'science', 'experiment'],
  },
  {
    emoji: '🧫',
    name: 'petri dish',
    keywords: ['bacteria', 'biology', 'culture'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['petri-dish', 'biology', 'lab'],
  },
  {
    emoji: '🧬',
    name: 'dna',
    keywords: ['biologist', 'genetics', 'life'],
    category: 'objects',
    color: '#9370DB',
    tags: ['dna', 'genetics', 'biology'],
  },
  {
    emoji: '🔬',
    name: 'microscope',
    keywords: ['science', 'laboratory', 'investigate'],
    category: 'objects',
    color: '#696969',
    tags: ['microscope', 'science', 'research'],
  },
  {
    emoji: '🔭',
    name: 'telescope',
    keywords: ['stars', 'space', 'zoom'],
    category: 'objects',
    color: '#696969',
    tags: ['telescope', 'astronomy', 'stars'],
  },
  {
    emoji: '📡',
    name: 'satellite antenna',
    keywords: ['communication', 'future', 'radio'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['satellite', 'antenna', 'communication'],
  },

  // Medical
  {
    emoji: '💉',
    name: 'syringe',
    keywords: ['health', 'hospital', 'drugs'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['syringe', 'vaccine', 'medical'],
  },
  {
    emoji: '🩸',
    name: 'drop of blood',
    keywords: ['period', 'hurt', 'harm'],
    category: 'objects',
    color: '#DC143C',
    tags: ['blood', 'drop', 'medical'],
  },
  {
    emoji: '💊',
    name: 'pill',
    keywords: ['health', 'medicine', 'doctor'],
    category: 'objects',
    color: '#DC143C',
    tags: ['pill', 'medicine', 'drug'],
  },
  {
    emoji: '🩹',
    name: 'adhesive bandage',
    keywords: ['heal', 'bandage', 'bandaid'],
    category: 'objects',
    color: '#FDBCB4',
    tags: ['bandage', 'bandaid', 'heal'],
  },
  {
    emoji: '🩺',
    name: 'stethoscope',
    keywords: ['health', 'medical', 'doctor'],
    category: 'objects',
    color: '#000000',
    tags: ['stethoscope', 'doctor', 'medical'],
  },

  // Household
  {
    emoji: '🚪',
    name: 'door',
    keywords: ['house', 'entry', 'exit'],
    category: 'objects',
    color: '#8B4513',
    tags: ['door', 'entrance', 'exit'],
  },
  {
    emoji: '🛗',
    name: 'elevator',
    keywords: ['lift', 'elevator', 'up'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['elevator', 'lift', 'building'],
  },
  {
    emoji: '🪞',
    name: 'mirror',
    keywords: ['reflection', 'reflect', 'magic'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['mirror', 'reflection', 'glass'],
  },
  {
    emoji: '🪟',
    name: 'window',
    keywords: ['view', 'scenery', 'frame'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['window', 'view', 'glass'],
  },
  {
    emoji: '🛏️',
    name: 'bed',
    keywords: ['sleep', 'rest', 'bedroom'],
    category: 'objects',
    color: '#8B4513',
    tags: ['bed', 'sleep', 'rest'],
  },
  {
    emoji: '🛋️',
    name: 'couch and lamp',
    keywords: ['read', 'chill', 'living room'],
    category: 'objects',
    color: '#DC143C',
    tags: ['couch', 'sofa', 'furniture'],
  },
  {
    emoji: '🪑',
    name: 'chair',
    keywords: ['sit', 'furniture', 'seat'],
    category: 'objects',
    color: '#8B4513',
    tags: ['chair', 'seat', 'furniture'],
  },
  {
    emoji: '🚽',
    name: 'toilet',
    keywords: ['restroom', 'wc', 'washroom'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['toilet', 'bathroom', 'wc'],
  },
  {
    emoji: '🪠',
    name: 'plunger',
    keywords: ['toilet', 'unclog', 'plumber'],
    category: 'objects',
    color: '#8B4513',
    tags: ['plunger', 'toilet', 'plumbing'],
  },
  {
    emoji: '🚿',
    name: 'shower',
    keywords: ['clean', 'water', 'bathroom'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['shower', 'bathroom', 'clean'],
  },
  {
    emoji: '🛁',
    name: 'bathtub',
    keywords: ['clean', 'shower', 'bathroom'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['bathtub', 'bath', 'bathroom'],
  },
  {
    emoji: '🪤',
    name: 'mouse trap',
    keywords: ['bait', 'trap', 'cheese'],
    category: 'objects',
    color: '#8B4513',
    tags: ['mousetrap', 'trap', 'catch'],
  },
  {
    emoji: '🪒',
    name: 'razor',
    keywords: ['sharp', 'shave', 'blade'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['razor', 'shave', 'blade'],
  },
  {
    emoji: '🧴',
    name: 'lotion bottle',
    keywords: ['moisturizer', 'sunscreen', 'shampoo'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['lotion', 'bottle', 'cosmetic'],
  },
  {
    emoji: '🧷',
    name: 'safety pin',
    keywords: ['diaper', 'punk rock', 'pin'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['safety-pin', 'pin', 'fasten'],
  },
  {
    emoji: '🧹',
    name: 'broom',
    keywords: ['cleaning', 'sweeping', 'witch'],
    category: 'objects',
    color: '#8B4513',
    tags: ['broom', 'sweep', 'clean'],
  },
  {
    emoji: '🧺',
    name: 'basket',
    keywords: ['laundry', 'basket', 'picnic'],
    category: 'objects',
    color: '#DEB887',
    tags: ['basket', 'container', 'picnic'],
  },
  {
    emoji: '🧻',
    name: 'roll of paper',
    keywords: ['roll', 'toilet paper', 'tissue'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['toilet-paper', 'tissue', 'roll'],
  },
  {
    emoji: '🪣',
    name: 'bucket',
    keywords: ['cask', 'pail', 'container'],
    category: 'objects',
    color: '#4169E1',
    tags: ['bucket', 'pail', 'container'],
  },
  {
    emoji: '🧼',
    name: 'soap',
    keywords: ['bar', 'bathing', 'cleaning'],
    category: 'objects',
    color: '#FFB6C1',
    tags: ['soap', 'clean', 'wash'],
  },
  {
    emoji: '🫧',
    name: 'bubbles',
    keywords: ['soap', 'champagne', 'carbonation'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['bubbles', 'soap', 'floating'],
  },
  {
    emoji: '🪥',
    name: 'toothbrush',
    keywords: ['hygiene', 'dental', 'clean'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['toothbrush', 'dental', 'hygiene'],
  },
  {
    emoji: '🧽',
    name: 'sponge',
    keywords: ['absorbing', 'cleaning', 'kitchen'],
    category: 'objects',
    color: '#FFD700',
    tags: ['sponge', 'cleaning', 'wash'],
  },
  {
    emoji: '🧯',
    name: 'fire extinguisher',
    keywords: ['quench', 'fire', 'extinguish'],
    category: 'objects',
    color: '#DC143C',
    tags: ['fire-extinguisher', 'safety', 'fire'],
  },
  {
    emoji: '🛒',
    name: 'shopping cart',
    keywords: ['trolley', 'shopping', 'cart'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['cart', 'shopping', 'grocery'],
  },

  // Smoking
  {
    emoji: '🚬',
    name: 'cigarette',
    keywords: ['kills', 'tobacco', 'cigarette'],
    category: 'objects',
    color: '#F5F5F5',
    tags: ['cigarette', 'smoking', 'tobacco'],
  },
  {
    emoji: '⚰️',
    name: 'coffin',
    keywords: ['vampire', 'dead', 'die'],
    category: 'objects',
    color: '#8B4513',
    tags: ['coffin', 'death', 'funeral'],
  },
  {
    emoji: '🪦',
    name: 'headstone',
    keywords: ['tombstone', 'cemetery', 'grave'],
    category: 'objects',
    color: '#696969',
    tags: ['headstone', 'grave', 'cemetery'],
  },
  {
    emoji: '⚱️',
    name: 'funeral urn',
    keywords: ['dead', 'die', 'death'],
    category: 'objects',
    color: '#8B4513',
    tags: ['urn', 'funeral', 'ashes'],
  },
  {
    emoji: '🗿',
    name: 'moai',
    keywords: ['stone', 'easter island', 'statue'],
    category: 'objects',
    color: '#696969',
    tags: ['moai', 'statue', 'easter-island'],
  },
  {
    emoji: '🪧',
    name: 'placard',
    keywords: ['sign', 'protest', 'demonstration'],
    category: 'objects',
    color: '#8B4513',
    tags: ['sign', 'placard', 'protest'],
  },

  // Other objects
  {
    emoji: '🧿',
    name: 'nazar amulet',
    keywords: ['evil eye', 'bead', 'charm'],
    category: 'objects',
    color: '#4169E1',
    tags: ['evil-eye', 'amulet', 'protection'],
  },
  {
    emoji: '🪬',
    name: 'hamsa',
    keywords: ['religion', 'protection', 'amulet'],
    category: 'objects',
    color: '#87CEEB',
    tags: ['hamsa', 'hand', 'protection'],
  },
  {
    emoji: '💿',
    name: 'optical disk',
    keywords: ['technology', 'dvd', 'disk'],
    category: 'objects',
    color: '#C0C0C0',
    tags: ['cd', 'dvd', 'disk'],
  },
];
