import type { Emoji } from '../../schema';

export const objectEmojis: Emoji[] = [
  // Glasses and optical
  {
    emoji: '👓',
    name: 'glasses',
    keywords: ['fashion', 'accessories', 'eyesight'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🕶️',
    name: 'sunglasses',
    keywords: ['face', 'cool', 'accessories'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '🥽',
    name: 'goggles',
    keywords: ['eyes', 'protection', 'safety'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '🥼',
    name: 'lab coat',
    keywords: ['doctor', 'experiment', 'scientist'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '🦺',
    name: 'safety vest',
    keywords: ['safety', 'orange', 'warning'],
    category: 'objects',
    color: '#FF8C00',
  },
  {
    emoji: '👔',
    name: 'necktie',
    keywords: ['shirt', 'suitup', 'formal'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '👕',
    name: 't-shirt',
    keywords: ['fashion', 'cloth', 'casual'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '👖',
    name: 'jeans',
    keywords: ['fashion', 'shopping', 'pants'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '🧣',
    name: 'scarf',
    keywords: ['neck', 'winter', 'clothes'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '🧤',
    name: 'gloves',
    keywords: ['hands', 'winter', 'clothes'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '🧥',
    name: 'coat',
    keywords: ['jacket', 'coat', 'clothes'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '🧦',
    name: 'socks',
    keywords: ['stocking', 'clothes', 'feet'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '👗',
    name: 'dress',
    keywords: ['clothes', 'fashion', 'shopping'],
    category: 'objects',
    color: '#FF69B4',
  },
  {
    emoji: '👘',
    name: 'kimono',
    keywords: ['dress', 'fashion', 'women'],
    category: 'objects',
    color: '#FF69B4',
  },
  {
    emoji: '🥻',
    name: 'sari',
    keywords: ['dress', 'fashion', 'indian'],
    category: 'objects',
    color: '#FF69B4',
  },
  {
    emoji: '🩱',
    name: 'one-piece swimsuit',
    keywords: ['fashion', 'swim', 'bathing'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '🩲',
    name: 'briefs',
    keywords: ['clothing', 'underwear', 'pants'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '🩳',
    name: 'shorts',
    keywords: ['clothing', 'pants', 'fashion'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '👙',
    name: 'bikini',
    keywords: ['swimming', 'female', 'woman'],
    category: 'objects',
    color: '#FF69B4',
  },
  {
    emoji: '👚',
    name: `woman's clothes`,
    keywords: ['fashion', 'shopping', 'female'],
    category: 'objects',
    color: '#FFB6C1',
  },
  {
    emoji: '👛',
    name: 'purse',
    keywords: ['fashion', 'accessories', 'money'],
    category: 'objects',
    color: '#FF69B4',
  },
  {
    emoji: '👜',
    name: 'handbag',
    keywords: ['fashion', 'accessory', 'accessories'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '👝',
    name: 'clutch bag',
    keywords: ['bag', 'accessories', 'shopping'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '🛍️',
    name: 'shopping bags',
    keywords: ['mall', 'buy', 'purchase'],
    category: 'objects',
    color: '#FF69B4',
  },
  {
    emoji: '🎒',
    name: 'backpack',
    keywords: ['student', 'education', 'bag'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '🩴',
    name: 'thong sandal',
    keywords: ['footwear', 'summer', 'flip flop'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '👞',
    name: `man's shoe`,
    keywords: ['fashion', 'male', 'formal'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '👟',
    name: 'running shoe',
    keywords: ['shoes', 'sports', 'sneakers'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '🥾',
    name: 'hiking boot',
    keywords: ['backpacking', 'camping', 'hiking'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '🥿',
    name: 'flat shoe',
    keywords: ['ballet flat', 'slip-on', 'slipper'],
    category: 'objects',
    color: '#FFB6C1',
  },
  {
    emoji: '👠',
    name: 'high-heeled shoe',
    keywords: ['fashion', 'shoes', 'female'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '👡',
    name: `woman's sandal`,
    keywords: ['shoes', 'fashion', 'flip flops'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '🩰',
    name: 'ballet shoes',
    keywords: ['dance', 'ballet', 'shoes'],
    category: 'objects',
    color: '#FFB6C1',
  },
  {
    emoji: '👢',
    name: `woman's boot`,
    keywords: ['shoes', 'fashion', 'boot'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '👑',
    name: 'crown',
    keywords: ['king', 'kod', 'leader'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '👒',
    name: `woman's hat`,
    keywords: ['fashion', 'accessories', 'female'],
    category: 'objects',
    color: '#F5DEB3',
  },
  {
    emoji: '🎩',
    name: 'top hat',
    keywords: ['magic', 'gentleman', 'classy'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '🎓',
    name: 'graduation cap',
    keywords: ['school', 'college', 'degree'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '🧢',
    name: 'billed cap',
    keywords: ['cap', 'baseball', 'hat'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '🪖',
    name: 'military helmet',
    keywords: ['army', 'protection', 'soldier'],
    category: 'objects',
    color: '#556B2F',
  },
  {
    emoji: '⛑️',
    name: `rescue worker's helmet`,
    keywords: ['construction', 'build', 'safety'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '📿',
    name: 'prayer beads',
    keywords: ['dhikr', 'religious', 'rosary'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '💄',
    name: 'lipstick',
    keywords: ['female', 'girl', 'fashion'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '💍',
    name: 'ring',
    keywords: ['wedding', 'propose', 'marriage'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '💎',
    name: 'gem stone',
    keywords: ['blue', 'ruby', 'diamond'],
    category: 'objects',
    color: '#87CEEB',
  },

  // Sound
  {
    emoji: '🔇',
    name: 'muted speaker',
    keywords: ['sound', 'volume', 'silence'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🔈',
    name: 'speaker low volume',
    keywords: ['sound', 'volume', 'silence'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🔉',
    name: 'speaker medium volume',
    keywords: ['volume', 'speaker', 'broadcast'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🔊',
    name: 'speaker high volume',
    keywords: ['volume', 'noise', 'noisy'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '📢',
    name: 'loudspeaker',
    keywords: ['volume', 'sound', 'announcement'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '📣',
    name: 'megaphone',
    keywords: ['sound', 'speaker', 'volume'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '📯',
    name: 'postal horn',
    keywords: ['instrument', 'music', 'horn'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '🔔',
    name: 'bell',
    keywords: ['sound', 'notification', 'christmas'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '🔕',
    name: 'bell with slash',
    keywords: ['sound', 'volume', 'mute'],
    category: 'objects',
    color: '#DC143C',
  },

  // Technology
  {
    emoji: '📱',
    name: 'mobile phone',
    keywords: ['technology', 'apple', 'gadgets'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '📲',
    name: 'mobile phone with arrow',
    keywords: ['iphone', 'incoming', 'call'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '☎️',
    name: 'telephone',
    keywords: ['technology', 'communication', 'dial'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '📞',
    name: 'telephone receiver',
    keywords: ['technology', 'communication', 'dial'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '📟',
    name: 'pager',
    keywords: ['bbcall', 'oldschool', '90s'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '📠',
    name: 'fax machine',
    keywords: ['communication', 'technology', 'fax'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🔋',
    name: 'battery',
    keywords: ['power', 'energy', 'sustain'],
    category: 'objects',
    color: '#90EE90',
  },
  {
    emoji: '🔌',
    name: 'electric plug',
    keywords: ['charger', 'power', 'electricity'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '💻',
    name: 'laptop',
    keywords: ['technology', 'laptop', 'screen'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '🖥️',
    name: 'desktop computer',
    keywords: ['technology', 'computing', 'screen'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🖨️',
    name: 'printer',
    keywords: ['paper', 'ink', 'office'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '⌨️',
    name: 'keyboard',
    keywords: ['technology', 'computer', 'type'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🖱️',
    name: 'computer mouse',
    keywords: ['click', 'button', 'pointer'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🖲️',
    name: 'trackball',
    keywords: ['technology', 'trackball', 'computer'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '💽',
    name: 'computer disk',
    keywords: ['technology', 'record', 'data'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '💾',
    name: 'floppy disk',
    keywords: ['oldschool', 'technology', 'save'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '💿',
    name: 'optical disk',
    keywords: ['technology', 'dvd', 'disk'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '📀',
    name: 'dvd',
    keywords: ['cd', 'disk', 'disc'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '🧮',
    name: 'abacus',
    keywords: ['calculation', 'math', 'count'],
    category: 'objects',
    color: '#8B4513',
  },

  // Media
  {
    emoji: '🎥',
    name: 'movie camera',
    keywords: ['film', 'record', 'movie'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '🎞️',
    name: 'film frames',
    keywords: ['movie', 'film', 'frames'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '📽️',
    name: 'film projector',
    keywords: ['movie', 'film', 'projector'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '📺',
    name: 'television',
    keywords: ['technology', 'program', 'oldschool'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '📷',
    name: 'camera',
    keywords: ['gadgets', 'photography', 'camera'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '📸',
    name: 'camera with flash',
    keywords: ['photography', 'gadgets', 'flash'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '📹',
    name: 'video camera',
    keywords: ['film', 'record', 'video'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '📼',
    name: 'videocassette',
    keywords: ['record', 'video', 'oldschool'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '🔍',
    name: 'magnifying glass tilted left',
    keywords: ['search', 'zoom', 'find'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '🔎',
    name: 'magnifying glass tilted right',
    keywords: ['search', 'zoom', 'find'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '🕯️',
    name: 'candle',
    keywords: ['fire', 'wax', 'light'],
    category: 'objects',
    color: '#F0E68C',
  },
  {
    emoji: '💡',
    name: 'light bulb',
    keywords: ['light', 'electricity', 'idea'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '🔦',
    name: 'flashlight',
    keywords: ['dark', 'camping', 'sight'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '🏮',
    name: 'red paper lantern',
    keywords: ['light', 'paper', 'halloween'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '🪔',
    name: 'diya lamp',
    keywords: ['lighting', 'candle', 'diwali'],
    category: 'objects',
    color: '#FF8C00',
  },

  // Books and paper
  {
    emoji: '📔',
    name: 'notebook with decorative cover',
    keywords: ['classroom', 'notes', 'record'],
    category: 'objects',
    color: '#DEB887',
  },
  {
    emoji: '📕',
    name: 'closed book',
    keywords: ['read', 'library', 'knowledge'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '📖',
    name: 'open book',
    keywords: ['book', 'read', 'open'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '📗',
    name: 'green book',
    keywords: ['read', 'library', 'knowledge'],
    category: 'objects',
    color: '#90EE90',
  },
  {
    emoji: '📘',
    name: 'blue book',
    keywords: ['read', 'library', 'knowledge'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '📙',
    name: 'orange book',
    keywords: ['read', 'library', 'knowledge'],
    category: 'objects',
    color: '#FF8C00',
  },
  {
    emoji: '📚',
    name: 'books',
    keywords: ['literature', 'library', 'study'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '📓',
    name: 'notebook',
    keywords: ['stationery', 'record', 'notes'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '📒',
    name: 'ledger',
    keywords: ['notes', 'paper', 'notebook'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '📃',
    name: 'page with curl',
    keywords: ['documents', 'office', 'paper'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '📜',
    name: 'scroll',
    keywords: ['documents', 'ancient', 'history'],
    category: 'objects',
    color: '#DEB887',
  },
  {
    emoji: '📄',
    name: 'page facing up',
    keywords: ['documents', 'office', 'paper'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '📰',
    name: 'newspaper',
    keywords: ['press', 'headline', 'news'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '🗞️',
    name: 'rolled-up newspaper',
    keywords: ['press', 'headline', 'delivery'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '📑',
    name: 'bookmark tabs',
    keywords: ['favorite', 'save', 'order'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '🔖',
    name: 'bookmark',
    keywords: ['favorite', 'label', 'save'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '🏷️',
    name: 'label',
    keywords: ['sale', 'tag', 'price'],
    category: 'objects',
    color: '#F0E68C',
  },

  // Money
  {
    emoji: '💰',
    name: 'money bag',
    keywords: ['dollar', 'payment', 'coins'],
    category: 'objects',
    color: '#F0E68C',
  },
  {
    emoji: '🪙',
    name: 'coin',
    keywords: ['money', 'currency', 'gold'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '💴',
    name: 'yen banknote',
    keywords: ['money', 'sales', 'japanese'],
    category: 'objects',
    color: '#F0E68C',
  },
  {
    emoji: '💵',
    name: 'dollar banknote',
    keywords: ['money', 'sales', 'bill'],
    category: 'objects',
    color: '#90EE90',
  },
  {
    emoji: '💶',
    name: 'euro banknote',
    keywords: ['money', 'sales', 'dollar'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '💷',
    name: 'pound banknote',
    keywords: ['british', 'sterling', 'money'],
    category: 'objects',
    color: '#DDA0DD',
  },
  {
    emoji: '💸',
    name: 'money with wings',
    keywords: ['dollar', 'bills', 'payment'],
    category: 'objects',
    color: '#90EE90',
  },
  {
    emoji: '💳',
    name: 'credit card',
    keywords: ['money', 'sales', 'shopping'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '🧾',
    name: 'receipt',
    keywords: ['accounting', 'expenses', 'bill'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '💹',
    name: 'chart increasing with yen',
    keywords: ['green-square', 'graph', 'presentation'],
    category: 'objects',
    color: '#90EE90',
  },

  // Mail
  {
    emoji: '✉️',
    name: 'envelope',
    keywords: ['letter', 'postal', 'inbox'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '📧',
    name: 'e-mail',
    keywords: ['communication', 'inbox', 'email'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '📨',
    name: 'incoming envelope',
    keywords: ['email', 'inbox', 'mail'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '📩',
    name: 'envelope with arrow',
    keywords: ['email', 'communication', 'sent'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '📤',
    name: 'outbox tray',
    keywords: ['inbox', 'email', 'sent'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '📥',
    name: 'inbox tray',
    keywords: ['email', 'documents', 'inbox'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '📦',
    name: 'package',
    keywords: ['mail', 'gift', 'cardboard'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '📫',
    name: 'closed mailbox with raised flag',
    keywords: ['email', 'inbox', 'communication'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '📪',
    name: 'closed mailbox with lowered flag',
    keywords: ['email', 'communication', 'inbox'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '📬',
    name: 'open mailbox with raised flag',
    keywords: ['email', 'inbox', 'communication'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '📭',
    name: 'open mailbox with lowered flag',
    keywords: ['email', 'inbox', 'communication'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '📮',
    name: 'postbox',
    keywords: ['email', 'letter', 'envelope'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '🗳️',
    name: 'ballot box with ballot',
    keywords: ['election', 'vote', 'ballot'],
    category: 'objects',
    color: '#4169E1',
  },

  // Writing tools
  {
    emoji: '✏️',
    name: 'pencil',
    keywords: ['stationery', 'write', 'paper'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '✒️',
    name: 'black nib',
    keywords: ['pen', 'stationery', 'writing'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '🖋️',
    name: 'fountain pen',
    keywords: ['stationery', 'writing', 'write'],
    category: 'objects',
    color: '#000000',
  },
  {
    emoji: '🖊️',
    name: 'pen',
    keywords: ['stationery', 'writing', 'write'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '🖌️',
    name: 'paintbrush',
    keywords: ['drawing', 'creativity', 'art'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '🖍️',
    name: 'crayon',
    keywords: ['drawing', 'creativity', 'color'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '📝',
    name: 'memo',
    keywords: ['write', 'documents', 'stationery'],
    category: 'objects',
    color: '#F0E68C',
  },

  // Office supplies
  {
    emoji: '💼',
    name: 'briefcase',
    keywords: ['business', 'work', 'law'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '📁',
    name: 'file folder',
    keywords: ['documents', 'business', 'office'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '📂',
    name: 'open file folder',
    keywords: ['documents', 'load', 'folder'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '🗂️',
    name: 'card index dividers',
    keywords: ['organizing', 'business', 'stationery'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '📅',
    name: 'calendar',
    keywords: ['calendar', 'schedule', 'date'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '📆',
    name: 'tear-off calendar',
    keywords: ['schedule', 'date', 'planning'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '🗒️',
    name: 'spiral notepad',
    keywords: ['memo', 'stationery', 'notes'],
    category: 'objects',
    color: '#F0E68C',
  },
  {
    emoji: '🗓️',
    name: 'spiral calendar',
    keywords: ['date', 'schedule', 'planning'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '📇',
    name: 'card index',
    keywords: ['business', 'stationery', 'rolodex'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '📈',
    name: 'chart increasing',
    keywords: ['graph', 'presentation', 'stats'],
    category: 'objects',
    color: '#90EE90',
  },
  {
    emoji: '📉',
    name: 'chart decreasing',
    keywords: ['graph', 'presentation', 'stats'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '📊',
    name: 'bar chart',
    keywords: ['graph', 'presentation', 'stats'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '📋',
    name: 'clipboard',
    keywords: ['stationery', 'documents', 'clipboard'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '📌',
    name: 'pushpin',
    keywords: ['stationery', 'mark', 'here'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '📍',
    name: 'round pushpin',
    keywords: ['stationery', 'location', 'map'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '📎',
    name: 'paperclip',
    keywords: ['documents', 'stationery', 'paperclip'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '🖇️',
    name: 'linked paperclips',
    keywords: ['documents', 'stationery', 'link'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '📏',
    name: 'straight ruler',
    keywords: ['stationery', 'calculate', 'length'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '📐',
    name: 'triangular ruler',
    keywords: ['stationery', 'math', 'architect'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '✂️',
    name: 'scissors',
    keywords: ['stationery', 'cut', 'scissors'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '🗃️',
    name: 'card file box',
    keywords: ['business', 'stationery', 'index'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🗄️',
    name: 'file cabinet',
    keywords: ['filing', 'organizing', 'storage'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🗑️',
    name: 'wastebasket',
    keywords: ['bin', 'trash', 'rubbish'],
    category: 'objects',
    color: '#696969',
  },

  // Locks and security
  {
    emoji: '🔒',
    name: 'locked',
    keywords: ['security', 'password', 'padlock'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '🔓',
    name: 'unlocked',
    keywords: ['privacy', 'security', 'unlock'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '🔏',
    name: 'locked with pen',
    keywords: ['security', 'secret', 'lock'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '🔐',
    name: 'locked with key',
    keywords: ['security', 'privacy', 'lock'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '🔑',
    name: 'key',
    keywords: ['lock', 'door', 'password'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '🗝️',
    name: 'old key',
    keywords: ['lock', 'door', 'antique'],
    category: 'objects',
    color: '#8B4513',
  },

  // Tools
  {
    emoji: '🔨',
    name: 'hammer',
    keywords: ['tools', 'build', 'create'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🪓',
    name: 'axe',
    keywords: ['tool', 'chop', 'cut'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '⛏️',
    name: 'pick',
    keywords: ['tools', 'dig', 'mine'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '⚒️',
    name: 'hammer and pick',
    keywords: ['tools', 'build', 'create'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🛠️',
    name: 'hammer and wrench',
    keywords: ['tools', 'build', 'create'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🗡️',
    name: 'dagger',
    keywords: ['weapon', 'knife', 'blade'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '⚔️',
    name: 'crossed swords',
    keywords: ['weapon', 'battle', 'fight'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '🔫',
    name: 'water pistol',
    keywords: ['violence', 'weapon', 'pistol'],
    category: 'objects',
    color: '#90EE90',
  },
  {
    emoji: '🛡️',
    name: 'shield',
    keywords: ['protection', 'security', 'defense'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '🪚',
    name: 'carpentry saw',
    keywords: ['cut', 'tool', 'carpenter'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '🔧',
    name: 'wrench',
    keywords: ['tools', 'diy', 'ikea'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '🪛',
    name: 'screwdriver',
    keywords: ['tools', 'build', 'fix'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '🔩',
    name: 'nut and bolt',
    keywords: ['handy', 'tools', 'fix'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '⚙️',
    name: 'gear',
    keywords: ['cog', 'settings', 'machine'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '🗜️',
    name: 'clamp',
    keywords: ['tool', 'compress', 'vice'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '⚖️',
    name: 'balance scale',
    keywords: ['law', 'fairness', 'weight'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '🦯',
    name: 'white cane',
    keywords: ['accessibility', 'blind', 'cane'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '🔗',
    name: 'link',
    keywords: ['rings', 'url', 'chain'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '⛓️',
    name: 'chains',
    keywords: ['lock', 'arrest', 'chain'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🪝',
    name: 'hook',
    keywords: ['catch', 'fishing', 'hang'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '🧰',
    name: 'toolbox',
    keywords: ['tools', 'diy', 'fix'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '🧲',
    name: 'magnet',
    keywords: ['attraction', 'magnetic', 'draw'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '🪜',
    name: 'ladder',
    keywords: ['climb', 'step', 'tool'],
    category: 'objects',
    color: '#8B4513',
  },

  // Science
  {
    emoji: '⚗️',
    name: 'alembic',
    keywords: ['distilling', 'science', 'experiment'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '🧪',
    name: 'test tube',
    keywords: ['chemistry', 'experiment', 'lab'],
    category: 'objects',
    color: '#90EE90',
  },
  {
    emoji: '🧫',
    name: 'petri dish',
    keywords: ['bacteria', 'biology', 'culture'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '🧬',
    name: 'dna',
    keywords: ['biologist', 'genetics', 'life'],
    category: 'objects',
    color: '#9370DB',
  },
  {
    emoji: '🔬',
    name: 'microscope',
    keywords: ['science', 'laboratory', 'investigate'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '🔭',
    name: 'telescope',
    keywords: ['stars', 'space', 'zoom'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '📡',
    name: 'satellite antenna',
    keywords: ['communication', 'future', 'radio'],
    category: 'objects',
    color: '#C0C0C0',
  },

  // Medical
  {
    emoji: '💉',
    name: 'syringe',
    keywords: ['health', 'hospital', 'drugs'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '🩸',
    name: 'drop of blood',
    keywords: ['period', 'hurt', 'harm'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '💊',
    name: 'pill',
    keywords: ['health', 'medicine', 'doctor'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '🩹',
    name: 'adhesive bandage',
    keywords: ['heal', 'bandage', 'bandaid'],
    category: 'objects',
    color: '#FDBCB4',
  },
  {
    emoji: '🩺',
    name: 'stethoscope',
    keywords: ['health', 'medical', 'doctor'],
    category: 'objects',
    color: '#000000',
  },

  // Household
  {
    emoji: '🚪',
    name: 'door',
    keywords: ['house', 'entry', 'exit'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '🛗',
    name: 'elevator',
    keywords: ['lift', 'elevator', 'up'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '🪞',
    name: 'mirror',
    keywords: ['reflection', 'reflect', 'magic'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '🪟',
    name: 'window',
    keywords: ['view', 'scenery', 'frame'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '🛏️',
    name: 'bed',
    keywords: ['sleep', 'rest', 'bedroom'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '🛋️',
    name: 'couch and lamp',
    keywords: ['read', 'chill', 'living room'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '🪑',
    name: 'chair',
    keywords: ['sit', 'furniture', 'seat'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '🚽',
    name: 'toilet',
    keywords: ['restroom', 'wc', 'washroom'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '🪠',
    name: 'plunger',
    keywords: ['toilet', 'unclog', 'plumber'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '🚿',
    name: 'shower',
    keywords: ['clean', 'water', 'bathroom'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '🛁',
    name: 'bathtub',
    keywords: ['clean', 'shower', 'bathroom'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '🪤',
    name: 'mouse trap',
    keywords: ['bait', 'trap', 'cheese'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '🪒',
    name: 'razor',
    keywords: ['sharp', 'shave', 'blade'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '🧴',
    name: 'lotion bottle',
    keywords: ['moisturizer', 'sunscreen', 'shampoo'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '🧷',
    name: 'safety pin',
    keywords: ['diaper', 'punk rock', 'pin'],
    category: 'objects',
    color: '#C0C0C0',
  },
  {
    emoji: '🧹',
    name: 'broom',
    keywords: ['cleaning', 'sweeping', 'witch'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '🧺',
    name: 'basket',
    keywords: ['laundry', 'basket', 'picnic'],
    category: 'objects',
    color: '#DEB887',
  },
  {
    emoji: '🧻',
    name: 'roll of paper',
    keywords: ['roll', 'toilet paper', 'tissue'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '🪣',
    name: 'bucket',
    keywords: ['cask', 'pail', 'container'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '🧼',
    name: 'soap',
    keywords: ['bar', 'bathing', 'cleaning'],
    category: 'objects',
    color: '#FFB6C1',
  },
  {
    emoji: '🫧',
    name: 'bubbles',
    keywords: ['soap', 'champagne', 'carbonation'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '🪥',
    name: 'toothbrush',
    keywords: ['hygiene', 'dental', 'clean'],
    category: 'objects',
    color: '#87CEEB',
  },
  {
    emoji: '🧽',
    name: 'sponge',
    keywords: ['absorbing', 'cleaning', 'kitchen'],
    category: 'objects',
    color: '#FFD700',
  },
  {
    emoji: '🧯',
    name: 'fire extinguisher',
    keywords: ['quench', 'fire', 'extinguish'],
    category: 'objects',
    color: '#DC143C',
  },
  {
    emoji: '🛒',
    name: 'shopping cart',
    keywords: ['trolley', 'shopping', 'cart'],
    category: 'objects',
    color: '#C0C0C0',
  },

  // Smoking
  {
    emoji: '🚬',
    name: 'cigarette',
    keywords: ['kills', 'tobacco', 'cigarette'],
    category: 'objects',
    color: '#F5F5F5',
  },
  {
    emoji: '⚰️',
    name: 'coffin',
    keywords: ['vampire', 'dead', 'die'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '🪦',
    name: 'headstone',
    keywords: ['tombstone', 'cemetery', 'grave'],
    category: 'objects',
    color: '#696969',
  },
  {
    emoji: '⚱️',
    name: 'funeral urn',
    keywords: ['dead', 'die', 'death'],
    category: 'objects',
    color: '#8B4513',
  },
  {
    emoji: '🪧',
    name: 'placard',
    keywords: ['sign', 'protest', 'demonstration'],
    category: 'objects',
    color: '#8B4513',
  },

  // Other objects
  {
    emoji: '🧿',
    name: 'nazar amulet',
    keywords: ['evil eye', 'bead', 'charm'],
    category: 'objects',
    color: '#4169E1',
  },
  {
    emoji: '🪬',
    name: 'hamsa',
    keywords: ['religion', 'protection', 'amulet'],
    category: 'objects',
    color: '#87CEEB',
  },
];
