import type { Emoji } from '../../schema';

// Generated from OpenMoji dataset - 264 emojis
// Unicode versions up to 15.1 + OpenMoji extras
export const objectsEmojisAll: Omit<Emoji, 'sentiment'>[] = [
  {
    emoji: '👓️',
    name: 'glasses',
    keywords: ['clothing', 'eye', 'eyeglasses', 'eyewear'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F453',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕶️',
    name: 'sunglasses',
    keywords: ['dark', 'eye', 'eyewear', 'glasses'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F576',
    version: '0.7',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥽',
    name: 'goggles',
    keywords: ['dive', 'eye', 'protection', 'scuba', 'swimming', 'welding'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F97D',
    version: '11',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥼',
    name: 'lab coat',
    keywords: ['clothes', 'coat', 'doctor', 'dr', 'experiment', 'jacket', 'lab', 'scientist', 'white'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F97C',
    version: '11',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦺',
    name: 'safety vest',
    keywords: ['emergency', 'safety', 'vest'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F9BA',
    version: '12',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👔',
    name: 'necktie',
    keywords: ['clothing', 'employed', 'serious', 'shirt', 'tie'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F454',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👕',
    name: 't-shirt',
    keywords: ['blue', 'casual', 'clothes', 'clothing', 'collar', 'dressed', 'shirt', 'shopping', 'tshirt', 'weekend'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F455',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👖',
    name: 'jeans',
    keywords: ['blue', 'casual', 'clothes', 'clothing', 'denim', 'dressed', 'pants', 'shopping', 'trousers', 'weekend'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F456',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧣',
    name: 'scarf',
    keywords: ['bundle', 'cold', 'neck', 'up'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F9E3',
    version: '5',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧤',
    name: 'gloves',
    keywords: ['hand'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F9E4',
    version: '5',
    color: '#9370DB',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🧥',
    name: 'coat',
    keywords: ['brr', 'bundle', 'cold', 'jacket', 'up'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F9E5',
    version: '5',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧦',
    name: 'socks',
    keywords: ['stocking'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F9E6',
    version: '5',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👗',
    name: 'dress',
    keywords: ['clothes', 'clothing', 'dressed', 'fancy', 'shopping'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F457',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👘',
    name: 'kimono',
    keywords: ['clothing', 'comfortable'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F458',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥻',
    name: 'sari',
    keywords: ['clothing', 'dress'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F97B',
    version: '12',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🩱',
    name: 'one-piece swimsuit',
    keywords: ['bathing', 'one-piece', 'suit', 'swimsuit'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1FA71',
    version: '12',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🩲',
    name: 'briefs',
    keywords: ['bathing', 'one-piece', 'suit', 'swimsuit', 'underwear'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1FA72',
    version: '12',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🩳',
    name: 'shorts',
    keywords: ['bathing', 'pants', 'suit', 'swimsuit', 'underwear'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1FA73',
    version: '12',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👙',
    name: 'bikini',
    keywords: ['bathing', 'beach', 'clothing', 'pool', 'suit', 'swim'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F459',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👚',
    name: 'woman’s clothes',
    keywords: ['blouse', 'clothes', 'clothing', 'collar', 'dress', 'dressed', 'lady', 'shirt', 'shopping', 'woman', 'woman’s'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F45A',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪭',
    name: 'folding hand fan',
    keywords: ['clack', 'clap', 'cool', 'cooling', 'dance', 'fan', 'flirt', 'flutter', 'folding', 'hand', 'hot', 'shy'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1FAAD',
    version: '15',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👛',
    name: 'purse',
    keywords: ['clothes', 'clothing', 'coin', 'dress', 'fancy', 'handbag', 'shopping'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F45B',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👜',
    name: 'handbag',
    keywords: ['bag', 'clothes', 'clothing', 'dress', 'lady', 'purse', 'shopping'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F45C',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👝',
    name: 'clutch bag',
    keywords: ['bag', 'clothes', 'clothing', 'clutch', 'dress', 'handbag', 'pouch', 'purse'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F45D',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛍️',
    name: 'shopping bags',
    keywords: ['bag', 'bags', 'hotel', 'shopping'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F6CD',
    version: '0.7',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎒',
    name: 'backpack',
    keywords: ['backpacking', 'bag', 'bookbag', 'education', 'rucksack', 'satchel', 'school'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F392',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🩴',
    name: 'thong sandal',
    keywords: ['beach', 'flip', 'flop', 'sandal', 'sandals', 'shoe', 'thong', 'thongs', 'zōri'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1FA74',
    version: '13',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👞',
    name: 'man’s shoe',
    keywords: ['brown', 'clothes', 'clothing', 'feet', 'foot', 'kick', 'man', 'man’s', 'shoe', 'shoes', 'shopping'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F45E',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👟',
    name: 'running shoe',
    keywords: ['athletic', 'clothes', 'clothing', 'fast', 'kick', 'running', 'shoe', 'shoes', 'shopping', 'sneaker', 'tennis'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F45F',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥾',
    name: 'hiking boot',
    keywords: ['backpacking', 'boot', 'brown', 'camping', 'hiking', 'outdoors', 'shoe'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F97E',
    version: '11',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥿',
    name: 'flat shoe',
    keywords: ['ballet', 'comfy', 'flat', 'flats', 'shoe', 'slip-on', 'slipper'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F97F',
    version: '11',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👠',
    name: 'high-heeled shoe',
    keywords: ['clothes', 'clothing', 'dress', 'fashion', 'heel', 'heels', 'high-heeled', 'shoe', 'shoes', 'shopping', 'stiletto', 'woman'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F460',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👡',
    name: 'woman’s sandal',
    keywords: ['clothing', 'sandal', 'shoe', 'woman', 'woman’s'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F461',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🩰',
    name: 'ballet shoes',
    keywords: ['ballet', 'dance', 'shoes'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1FA70',
    version: '12',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👢',
    name: 'woman’s boot',
    keywords: ['boot', 'clothes', 'clothing', 'dress', 'shoe', 'shoes', 'shopping', 'woman', 'woman’s'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F462',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪮',
    name: 'hair pick',
    keywords: ['afro', 'comb', 'groom', 'hair', 'pick'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1FAAE',
    version: '15',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👑',
    name: 'crown',
    keywords: ['clothing', 'family', 'king', 'medieval', 'queen', 'royal', 'royalty', 'win'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F451',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👒',
    name: 'woman’s hat',
    keywords: ['clothes', 'clothing', 'garden', 'hat', 'hats', 'party', 'woman', 'woman’s'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F452',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🎩',
    name: 'top hat',
    keywords: ['clothes', 'clothing', 'fancy', 'formal', 'hat', 'magic', 'top', 'tophat'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F3A9',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎓️',
    name: 'graduation cap',
    keywords: ['cap', 'celebration', 'clothing', 'education', 'graduation', 'hat', 'scholar'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F393',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🧢',
    name: 'billed cap',
    keywords: ['baseball', 'bent', 'billed', 'cap', 'dad', 'hat'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F9E2',
    version: '5',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪖',
    name: 'military helmet',
    keywords: ['army', 'helmet', 'military', 'soldier', 'war', 'warrior'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1FA96',
    version: '13',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛑️',
    name: 'rescue worker’s helmet',
    keywords: ['aid', 'cross', 'face', 'hat', 'helmet', 'rescue', 'worker’s'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '26D1',
    version: '0.7',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📿',
    name: 'prayer beads',
    keywords: ['beads', 'clothing', 'necklace', 'prayer', 'religion'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F4FF',
    version: '1',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💄',
    name: 'lipstick',
    keywords: ['cosmetics', 'date', 'makeup'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F484',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💍',
    name: 'ring',
    keywords: ['diamond', 'engaged', 'engagement', 'married', 'romance', 'shiny', 'sparkling', 'wedding'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F48D',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💎',
    name: 'gem stone',
    keywords: ['diamond', 'engagement', 'gem', 'jewel', 'money', 'romance', 'stone', 'wedding'],
    category: 'objects',
    subcategory: 'clothing',
    unicode: '1F48E',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔇',
    name: 'muted speaker',
    keywords: ['mute', 'muted', 'quiet', 'silent', 'sound', 'speaker'],
    category: 'objects',
    subcategory: 'sound',
    unicode: '1F507',
    version: '1',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔈️',
    name: 'speaker low volume',
    keywords: ['low', 'soft', 'sound', 'speaker', 'volume'],
    category: 'objects',
    subcategory: 'sound',
    unicode: '1F508',
    version: '0.7',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔉',
    name: 'speaker medium volume',
    keywords: ['medium', 'sound', 'speaker', 'volume'],
    category: 'objects',
    subcategory: 'sound',
    unicode: '1F509',
    version: '1',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔊',
    name: 'speaker high volume',
    keywords: ['high', 'loud', 'music', 'sound', 'speaker', 'volume'],
    category: 'objects',
    subcategory: 'sound',
    unicode: '1F50A',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📢',
    name: 'loudspeaker',
    keywords: ['address', 'communication', 'loud', 'public', 'sound'],
    category: 'objects',
    subcategory: 'sound',
    unicode: '1F4E2',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📣',
    name: 'megaphone',
    keywords: ['cheering', 'sound'],
    category: 'objects',
    subcategory: 'sound',
    unicode: '1F4E3',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📯',
    name: 'postal horn',
    keywords: ['horn', 'post', 'postal'],
    category: 'objects',
    subcategory: 'sound',
    unicode: '1F4EF',
    version: '1',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔔',
    name: 'bell',
    keywords: ['break', 'church', 'sound'],
    category: 'objects',
    subcategory: 'sound',
    unicode: '1F514',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔕',
    name: 'bell with slash',
    keywords: ['bell', 'forbidden', 'mute', 'no', 'not', 'prohibited', 'quiet', 'silent', 'slash', 'sound'],
    category: 'objects',
    subcategory: 'sound',
    unicode: '1F515',
    version: '1',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎼',
    name: 'musical score',
    keywords: ['music', 'musical', 'note', 'score'],
    category: 'objects',
    subcategory: 'music',
    unicode: '1F3BC',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎵',
    name: 'musical note',
    keywords: ['music', 'musical', 'note', 'sound'],
    category: 'objects',
    subcategory: 'music',
    unicode: '1F3B5',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎶',
    name: 'musical notes',
    keywords: ['music', 'musical', 'note', 'notes', 'sound'],
    category: 'objects',
    subcategory: 'music',
    unicode: '1F3B6',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎙️',
    name: 'studio microphone',
    keywords: ['mic', 'microphone', 'music', 'studio'],
    category: 'objects',
    subcategory: 'music',
    unicode: '1F399',
    version: '0.7',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎚️',
    name: 'level slider',
    keywords: ['level', 'music', 'slider'],
    category: 'objects',
    subcategory: 'music',
    unicode: '1F39A',
    version: '0.7',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎛️',
    name: 'control knobs',
    keywords: ['control', 'knobs', 'music'],
    category: 'objects',
    subcategory: 'music',
    unicode: '1F39B',
    version: '0.7',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎤',
    name: 'microphone',
    keywords: ['karaoke', 'mic', 'music', 'sing', 'sound'],
    category: 'objects',
    subcategory: 'music',
    unicode: '1F3A4',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎧️',
    name: 'headphone',
    keywords: ['earbud', 'sound'],
    category: 'objects',
    subcategory: 'music',
    unicode: '1F3A7',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📻️',
    name: 'radio',
    keywords: ['entertainment', 'tbt', 'video'],
    category: 'objects',
    subcategory: 'music',
    unicode: '1F4FB',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎷',
    name: 'saxophone',
    keywords: ['instrument', 'music', 'sax'],
    category: 'objects',
    subcategory: 'musical-instrument',
    unicode: '1F3B7',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪗',
    name: 'accordion',
    keywords: ['box', 'concertina', 'instrument', 'music', 'squeeze', 'squeezebox'],
    category: 'objects',
    subcategory: 'musical-instrument',
    unicode: '1FA97',
    version: '13',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎸',
    name: 'guitar',
    keywords: ['instrument', 'music', 'strat'],
    category: 'objects',
    subcategory: 'musical-instrument',
    unicode: '1F3B8',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎹',
    name: 'musical keyboard',
    keywords: ['instrument', 'keyboard', 'music', 'musical', 'piano'],
    category: 'objects',
    subcategory: 'musical-instrument',
    unicode: '1F3B9',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎺',
    name: 'trumpet',
    keywords: ['instrument', 'music'],
    category: 'objects',
    subcategory: 'musical-instrument',
    unicode: '1F3BA',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎻',
    name: 'violin',
    keywords: ['instrument', 'music'],
    category: 'objects',
    subcategory: 'musical-instrument',
    unicode: '1F3BB',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪕',
    name: 'banjo',
    keywords: ['music', 'stringed'],
    category: 'objects',
    subcategory: 'musical-instrument',
    unicode: '1FA95',
    version: '12',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥁',
    name: 'drum',
    keywords: ['drumsticks', 'music'],
    category: 'objects',
    subcategory: 'musical-instrument',
    unicode: '1F941',
    version: '3',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪘',
    name: 'long drum',
    keywords: ['beat', 'conga', 'drum', 'instrument', 'long', 'rhythm'],
    category: 'objects',
    subcategory: 'musical-instrument',
    unicode: '1FA98',
    version: '13',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪇',
    name: 'maracas',
    keywords: ['cha', 'dance', 'instrument', 'music', 'party', 'percussion', 'rattle', 'shake', 'shaker'],
    category: 'objects',
    subcategory: 'musical-instrument',
    unicode: '1FA87',
    version: '15',
    color: '#8B4513',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🪈',
    name: 'flute',
    keywords: ['band', 'fife', 'flautist', 'instrument', 'marching', 'music', 'orchestra', 'piccolo', 'pipe', 'recorder', 'woodwind'],
    category: 'objects',
    subcategory: 'musical-instrument',
    unicode: '1FA88',
    version: '15',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪉',
    name: 'harp',
    keywords: ['cupid', 'instrument', 'love', 'music', 'orchestra'],
    category: 'objects',
    subcategory: 'musical-instrument',
    unicode: '1FA89',
    version: '16',
    color: '#8B4513',
    sentiment: 'positive' as const,
  },
  {
    emoji: '📱',
    name: 'mobile phone',
    keywords: ['cell', 'communication', 'mobile', 'phone', 'telephone'],
    category: 'objects',
    subcategory: 'phone',
    unicode: '1F4F1',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📲',
    name: 'mobile phone with arrow',
    keywords: ['arrow', 'build', 'call', 'cell', 'communication', 'mobile', 'phone', 'receive', 'telephone'],
    category: 'objects',
    subcategory: 'phone',
    unicode: '1F4F2',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '☎️',
    name: 'telephone',
    keywords: ['phone'],
    category: 'objects',
    subcategory: 'phone',
    unicode: '260E',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📞',
    name: 'telephone receiver',
    keywords: ['communication', 'phone', 'receiver', 'telephone', 'voip'],
    category: 'objects',
    subcategory: 'phone',
    unicode: '1F4DE',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📟️',
    name: 'pager',
    keywords: ['communication'],
    category: 'objects',
    subcategory: 'phone',
    unicode: '1F4DF',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📠',
    name: 'fax machine',
    keywords: ['communication', 'fax', 'machine'],
    category: 'objects',
    subcategory: 'phone',
    unicode: '1F4E0',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔋',
    name: 'battery',
    keywords: ['battery'],
    category: 'objects',
    subcategory: 'computer',
    unicode: '1F50B',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪫',
    name: 'low battery',
    keywords: ['battery', 'drained', 'electronic', 'energy', 'low', 'power'],
    category: 'objects',
    subcategory: 'computer',
    unicode: '1FAAB',
    version: '14',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔌',
    name: 'electric plug',
    keywords: ['electric', 'electricity', 'plug'],
    category: 'objects',
    subcategory: 'computer',
    unicode: '1F50C',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💻️',
    name: 'laptop',
    keywords: ['computer', 'office', 'pc', 'personal'],
    category: 'objects',
    subcategory: 'computer',
    unicode: '1F4BB',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🖥️',
    name: 'desktop computer',
    keywords: ['computer', 'desktop', 'monitor'],
    category: 'objects',
    subcategory: 'computer',
    unicode: '1F5A5',
    version: '0.7',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🖨️',
    name: 'printer',
    keywords: ['computer'],
    category: 'objects',
    subcategory: 'computer',
    unicode: '1F5A8',
    version: '0.7',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⌨️',
    name: 'keyboard',
    keywords: ['computer'],
    category: 'objects',
    subcategory: 'computer',
    unicode: '2328',
    version: '1',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🖱️',
    name: 'computer mouse',
    keywords: ['computer', 'mouse'],
    category: 'objects',
    subcategory: 'computer',
    unicode: '1F5B1',
    version: '0.7',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🖲️',
    name: 'trackball',
    keywords: ['computer'],
    category: 'objects',
    subcategory: 'computer',
    unicode: '1F5B2',
    version: '0.7',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💽',
    name: 'computer disk',
    keywords: ['computer', 'disk', 'minidisk', 'optical'],
    category: 'objects',
    subcategory: 'computer',
    unicode: '1F4BD',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💾',
    name: 'floppy disk',
    keywords: ['computer', 'disk', 'floppy'],
    category: 'objects',
    subcategory: 'computer',
    unicode: '1F4BE',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💿️',
    name: 'optical disk',
    keywords: ['blu-ray', 'cd', 'computer', 'disk', 'dvd', 'optical'],
    category: 'objects',
    subcategory: 'computer',
    unicode: '1F4BF',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📀',
    name: 'dvd',
    keywords: ['blu-ray', 'cd', 'computer', 'disk', 'optical'],
    category: 'objects',
    subcategory: 'computer',
    unicode: '1F4C0',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧮',
    name: 'abacus',
    keywords: ['calculation', 'calculator'],
    category: 'objects',
    subcategory: 'computer',
    unicode: '1F9EE',
    version: '11',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎥',
    name: 'movie camera',
    keywords: ['bollywood', 'camera', 'cinema', 'film', 'hollywood', 'movie', 'record'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F3A5',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎞️',
    name: 'film frames',
    keywords: ['cinema', 'film', 'frames', 'movie'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F39E',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📽️',
    name: 'film projector',
    keywords: ['cinema', 'film', 'movie', 'projector', 'video'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F4FD',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎬️',
    name: 'clapper board',
    keywords: ['action', 'board', 'clapper', 'movie'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F3AC',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📺️',
    name: 'television',
    keywords: ['tv', 'video'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F4FA',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📷️',
    name: 'camera',
    keywords: ['photo', 'selfie', 'snap', 'tbt', 'trip', 'video'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F4F7',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📸',
    name: 'camera with flash',
    keywords: ['camera', 'flash', 'video'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F4F8',
    version: '1',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📹️',
    name: 'video camera',
    keywords: ['camcorder', 'camera', 'tbt', 'video'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F4F9',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📼',
    name: 'videocassette',
    keywords: ['old', 'school', 'tape', 'vcr', 'vhs', 'video'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F4FC',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔍️',
    name: 'magnifying glass tilted left',
    keywords: ['glass', 'lab', 'left', 'left-pointing', 'magnifying', 'science', 'search', 'tilted', 'tool'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F50D',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔎',
    name: 'magnifying glass tilted right',
    keywords: ['contact', 'glass', 'lab', 'magnifying', 'right', 'right-pointing', 'science', 'search', 'tilted', 'tool'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F50E',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕯️',
    name: 'candle',
    keywords: ['light'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F56F',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💡',
    name: 'light bulb',
    keywords: ['bulb', 'comic', 'electric', 'idea', 'light'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F4A1',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔦',
    name: 'flashlight',
    keywords: ['electric', 'light', 'tool', 'torch'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F526',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏮',
    name: 'red paper lantern',
    keywords: ['bar', 'lantern', 'light', 'paper', 'red', 'restaurant'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1F3EE',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪔',
    name: 'diya lamp',
    keywords: ['diya', 'lamp', 'light', 'oil'],
    category: 'objects',
    subcategory: 'light-video',
    unicode: '1FA94',
    version: '12',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📔',
    name: 'notebook with decorative cover',
    keywords: ['book', 'cover', 'decorated', 'decorative', 'education', 'notebook', 'school', 'writing'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F4D4',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📕',
    name: 'closed book',
    keywords: ['book', 'closed', 'education'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F4D5',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📖',
    name: 'open book',
    keywords: ['book', 'education', 'fantasy', 'knowledge', 'library', 'novels', 'open', 'reading'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F4D6',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📗',
    name: 'green book',
    keywords: ['book', 'education', 'fantasy', 'green', 'library', 'reading'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F4D7',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📘',
    name: 'blue book',
    keywords: ['blue', 'book', 'education', 'fantasy', 'library', 'reading'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F4D8',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📙',
    name: 'orange book',
    keywords: ['book', 'education', 'fantasy', 'library', 'orange', 'reading'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F4D9',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📚️',
    name: 'books',
    keywords: ['book', 'education', 'fantasy', 'knowledge', 'library', 'novels', 'reading', 'school', 'study'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F4DA',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📓',
    name: 'notebook',
    keywords: ['notebook'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F4D3',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📒',
    name: 'ledger',
    keywords: ['notebook'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F4D2',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📃',
    name: 'page with curl',
    keywords: ['curl', 'document', 'page', 'paper'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F4C3',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📜',
    name: 'scroll',
    keywords: ['paper'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F4DC',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📄',
    name: 'page facing up',
    keywords: ['document', 'facing', 'page', 'paper', 'up'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F4C4',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📰',
    name: 'newspaper',
    keywords: ['communication', 'news', 'paper'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F4F0',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗞️',
    name: 'rolled-up newspaper',
    keywords: ['news', 'newspaper', 'paper', 'rolled', 'rolled-up'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F5DE',
    version: '0.7',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📑',
    name: 'bookmark tabs',
    keywords: ['bookmark', 'mark', 'marker', 'tabs'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F4D1',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔖',
    name: 'bookmark',
    keywords: ['mark'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F516',
    version: '0.6',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏷️',
    name: 'label',
    keywords: ['tag'],
    category: 'objects',
    subcategory: 'book-paper',
    unicode: '1F3F7',
    version: '0.7',
    color: '#8B4513',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💰️',
    name: 'money bag',
    keywords: ['bag', 'bank', 'bet', 'billion', 'cash', 'cost', 'dollar', 'gold', 'million', 'money', 'moneybag', 'paid', 'paying', 'pot', 'rich', 'win'],
    category: 'objects',
    subcategory: 'money',
    unicode: '1F4B0',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪙',
    name: 'coin',
    keywords: ['dollar', 'euro', 'gold', 'metal', 'money', 'rich', 'silver', 'treasure'],
    category: 'objects',
    subcategory: 'money',
    unicode: '1FA99',
    version: '13',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💴',
    name: 'yen banknote',
    keywords: ['bank', 'banknote', 'bill', 'currency', 'money', 'note', 'yen'],
    category: 'objects',
    subcategory: 'money',
    unicode: '1F4B4',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💵',
    name: 'dollar banknote',
    keywords: ['bank', 'banknote', 'bill', 'currency', 'dollar', 'money', 'note'],
    category: 'objects',
    subcategory: 'money',
    unicode: '1F4B5',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💶',
    name: 'euro banknote',
    keywords: ['100', 'bank', 'banknote', 'bill', 'currency', 'euro', 'money', 'note', 'rich'],
    category: 'objects',
    subcategory: 'money',
    unicode: '1F4B6',
    version: '1',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💷',
    name: 'pound banknote',
    keywords: ['bank', 'banknote', 'bill', 'billion', 'cash', 'currency', 'money', 'note', 'pound', 'pounds'],
    category: 'objects',
    subcategory: 'money',
    unicode: '1F4B7',
    version: '1',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💸',
    name: 'money with wings',
    keywords: ['bank', 'banknote', 'bill', 'billion', 'cash', 'dollar', 'fly', 'million', 'money', 'note', 'pay', 'wings'],
    category: 'objects',
    subcategory: 'money',
    unicode: '1F4B8',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💳️',
    name: 'credit card',
    keywords: ['bank', 'card', 'cash', 'charge', 'credit', 'money', 'pay'],
    category: 'objects',
    subcategory: 'money',
    unicode: '1F4B3',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧾',
    name: 'receipt',
    keywords: ['accounting', 'bookkeeping', 'evidence', 'invoice', 'proof'],
    category: 'objects',
    subcategory: 'money',
    unicode: '1F9FE',
    version: '11',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💹',
    name: 'chart increasing with yen',
    keywords: ['bank', 'chart', 'currency', 'graph', 'growth', 'increasing', 'market', 'money', 'rise', 'trend', 'upward', 'yen'],
    category: 'objects',
    subcategory: 'money',
    unicode: '1F4B9',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '✉️',
    name: 'envelope',
    keywords: ['e-mail', 'email', 'letter'],
    category: 'objects',
    subcategory: 'mail',
    unicode: '2709',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📧',
    name: 'e-mail',
    keywords: ['email', 'letter', 'mail'],
    category: 'objects',
    subcategory: 'mail',
    unicode: '1F4E7',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📨',
    name: 'incoming envelope',
    keywords: ['delivering', 'e-mail', 'email', 'envelope', 'incoming', 'letter', 'mail', 'receive', 'sent'],
    category: 'objects',
    subcategory: 'mail',
    unicode: '1F4E8',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📩',
    name: 'envelope with arrow',
    keywords: ['arrow', 'communication', 'down', 'e-mail', 'email', 'envelope', 'letter', 'mail', 'outgoing', 'send', 'sent'],
    category: 'objects',
    subcategory: 'mail',
    unicode: '1F4E9',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📤️',
    name: 'outbox tray',
    keywords: ['box', 'email', 'letter', 'mail', 'outbox', 'sent', 'tray'],
    category: 'objects',
    subcategory: 'mail',
    unicode: '1F4E4',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📥️',
    name: 'inbox tray',
    keywords: ['box', 'email', 'inbox', 'letter', 'mail', 'receive', 'tray', 'zero'],
    category: 'objects',
    subcategory: 'mail',
    unicode: '1F4E5',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📦️',
    name: 'package',
    keywords: ['box', 'communication', 'delivery', 'parcel', 'shipping'],
    category: 'objects',
    subcategory: 'mail',
    unicode: '1F4E6',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📫️',
    name: 'closed mailbox with raised flag',
    keywords: ['closed', 'communication', 'flag', 'mail', 'mailbox', 'postbox', 'raised'],
    category: 'objects',
    subcategory: 'mail',
    unicode: '1F4EB',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📪️',
    name: 'closed mailbox with lowered flag',
    keywords: ['closed', 'flag', 'lowered', 'mail', 'mailbox', 'postbox'],
    category: 'objects',
    subcategory: 'mail',
    unicode: '1F4EA',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📬️',
    name: 'open mailbox with raised flag',
    keywords: ['flag', 'mail', 'mailbox', 'open', 'postbox', 'raised'],
    category: 'objects',
    subcategory: 'mail',
    unicode: '1F4EC',
    version: '0.7',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📭️',
    name: 'open mailbox with lowered flag',
    keywords: ['flag', 'lowered', 'mail', 'mailbox', 'open', 'postbox'],
    category: 'objects',
    subcategory: 'mail',
    unicode: '1F4ED',
    version: '0.7',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📮',
    name: 'postbox',
    keywords: ['mail', 'mailbox'],
    category: 'objects',
    subcategory: 'mail',
    unicode: '1F4EE',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗳️',
    name: 'ballot box with ballot',
    keywords: ['ballot', 'box'],
    category: 'objects',
    subcategory: 'mail',
    unicode: '1F5F3',
    version: '0.7',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '✏️',
    name: 'pencil',
    keywords: ['pencil'],
    category: 'objects',
    subcategory: 'writing',
    unicode: '270F',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '✒️',
    name: 'black nib',
    keywords: ['black', 'nib', 'pen'],
    category: 'objects',
    subcategory: 'writing',
    unicode: '2712',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🖋️',
    name: 'fountain pen',
    keywords: ['fountain', 'pen'],
    category: 'objects',
    subcategory: 'writing',
    unicode: '1F58B',
    version: '0.7',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🖊️',
    name: 'pen',
    keywords: ['ballpoint'],
    category: 'objects',
    subcategory: 'writing',
    unicode: '1F58A',
    version: '0.7',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🖌️',
    name: 'paintbrush',
    keywords: ['painting'],
    category: 'objects',
    subcategory: 'writing',
    unicode: '1F58C',
    version: '0.7',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🖍️',
    name: 'crayon',
    keywords: ['crayon'],
    category: 'objects',
    subcategory: 'writing',
    unicode: '1F58D',
    version: '0.7',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📝',
    name: 'memo',
    keywords: ['communication', 'media', 'notes', 'pencil'],
    category: 'objects',
    subcategory: 'writing',
    unicode: '1F4DD',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💼',
    name: 'briefcase',
    keywords: ['office'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4BC',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📁',
    name: 'file folder',
    keywords: ['file', 'folder'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4C1',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📂',
    name: 'open file folder',
    keywords: ['file', 'folder', 'open'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4C2',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗂️',
    name: 'card index dividers',
    keywords: ['card', 'dividers', 'index'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F5C2',
    version: '0.7',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📅',
    name: 'calendar',
    keywords: ['date'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4C5',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📆',
    name: 'tear-off calendar',
    keywords: ['calendar', 'tear-off'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4C6',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗒️',
    name: 'spiral notepad',
    keywords: ['note', 'notepad', 'pad', 'spiral'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F5D2',
    version: '0.7',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗓️',
    name: 'spiral calendar',
    keywords: ['calendar', 'pad', 'spiral'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F5D3',
    version: '0.7',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📇',
    name: 'card index',
    keywords: ['card', 'index', 'old', 'rolodex', 'school'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4C7',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📈',
    name: 'chart increasing',
    keywords: ['chart', 'data', 'graph', 'growth', 'increasing', 'right', 'trend', 'up', 'upward'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4C8',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📉',
    name: 'chart decreasing',
    keywords: ['chart', 'data', 'decreasing', 'down', 'downward', 'graph', 'negative', 'trend'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4C9',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📊',
    name: 'bar chart',
    keywords: ['bar', 'chart', 'data', 'graph'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4CA',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📋️',
    name: 'clipboard',
    keywords: ['do', 'list', 'notes'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4CB',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📌',
    name: 'pushpin',
    keywords: ['collage', 'pin'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4CC',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📍',
    name: 'round pushpin',
    keywords: ['location', 'map', 'pin', 'pushpin', 'round'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4CD',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📎',
    name: 'paperclip',
    keywords: ['paperclip'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4CE',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🖇️',
    name: 'linked paperclips',
    keywords: ['link', 'linked', 'paperclip', 'paperclips'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F587',
    version: '0.7',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📏',
    name: 'straight ruler',
    keywords: ['angle', 'edge', 'math', 'ruler', 'straight', 'straightedge'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4CF',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📐',
    name: 'triangular ruler',
    keywords: ['angle', 'math', 'rule', 'ruler', 'set', 'slide', 'triangle', 'triangular'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F4D0',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '✂️',
    name: 'scissors',
    keywords: ['cut', 'cutting', 'paper', 'tool'],
    category: 'objects',
    subcategory: 'office',
    unicode: '2702',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗃️',
    name: 'card file box',
    keywords: ['box', 'card', 'file'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F5C3',
    version: '0.7',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗄️',
    name: 'file cabinet',
    keywords: ['cabinet', 'file', 'filing', 'paper'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F5C4',
    version: '0.7',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗑️',
    name: 'wastebasket',
    keywords: ['can', 'garbage', 'trash', 'waste'],
    category: 'objects',
    subcategory: 'office',
    unicode: '1F5D1',
    version: '0.7',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔒️',
    name: 'locked',
    keywords: ['closed', 'lock', 'private'],
    category: 'objects',
    subcategory: 'lock',
    unicode: '1F512',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔓️',
    name: 'unlocked',
    keywords: ['cracked', 'lock', 'open', 'unlock'],
    category: 'objects',
    subcategory: 'lock',
    unicode: '1F513',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔏',
    name: 'locked with pen',
    keywords: ['ink', 'lock', 'locked', 'nib', 'pen', 'privacy'],
    category: 'objects',
    subcategory: 'lock',
    unicode: '1F50F',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔐',
    name: 'locked with key',
    keywords: ['bike', 'closed', 'key', 'lock', 'locked', 'secure'],
    category: 'objects',
    subcategory: 'lock',
    unicode: '1F510',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔑',
    name: 'key',
    keywords: ['keys', 'lock', 'major', 'password', 'unlock'],
    category: 'objects',
    subcategory: 'lock',
    unicode: '1F511',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗝️',
    name: 'old key',
    keywords: ['clue', 'key', 'lock', 'old'],
    category: 'objects',
    subcategory: 'lock',
    unicode: '1F5DD',
    version: '0.7',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔨',
    name: 'hammer',
    keywords: ['home', 'improvement', 'repairs', 'tool'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1F528',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪓',
    name: 'axe',
    keywords: ['ax', 'chop', 'hatchet', 'split', 'wood'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1FA93',
    version: '12',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛏️',
    name: 'pick',
    keywords: ['hammer', 'mining', 'tool'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '26CF',
    version: '0.7',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚒️',
    name: 'hammer and pick',
    keywords: ['hammer', 'pick', 'tool'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '2692',
    version: '1',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛠️',
    name: 'hammer and wrench',
    keywords: ['hammer', 'spanner', 'tool', 'wrench'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1F6E0',
    version: '0.7',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗡️',
    name: 'dagger',
    keywords: ['knife', 'weapon'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1F5E1',
    version: '0.7',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚔️',
    name: 'crossed swords',
    keywords: ['crossed', 'swords', 'weapon'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '2694',
    version: '1',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💣️',
    name: 'bomb',
    keywords: ['boom', 'comic', 'dangerous', 'explosion', 'hot'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1F4A3',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪃',
    name: 'boomerang',
    keywords: ['rebound', 'repercussion', 'weapon'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1FA83',
    version: '13',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏹',
    name: 'bow and arrow',
    keywords: ['archer', 'archery', 'arrow', 'bow', 'sagittarius', 'tool', 'weapon', 'zodiac'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1F3F9',
    version: '1',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛡️',
    name: 'shield',
    keywords: ['weapon'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1F6E1',
    version: '0.7',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪚',
    name: 'carpentry saw',
    keywords: ['carpenter', 'carpentry', 'cut', 'lumber', 'saw', 'tool', 'trim'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1FA9A',
    version: '13',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔧',
    name: 'wrench',
    keywords: ['home', 'improvement', 'spanner', 'tool'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1F527',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪛',
    name: 'screwdriver',
    keywords: ['flathead', 'handy', 'screw', 'tool'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1FA9B',
    version: '13',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔩',
    name: 'nut and bolt',
    keywords: ['bolt', 'home', 'improvement', 'nut', 'tool'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1F529',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚙️',
    name: 'gear',
    keywords: ['cog', 'cogwheel', 'tool'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '2699',
    version: '1',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗜️',
    name: 'clamp',
    keywords: ['compress', 'tool', 'vice'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1F5DC',
    version: '0.7',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚖️',
    name: 'balance scale',
    keywords: ['balance', 'justice', 'libra', 'scale', 'scales', 'tool', 'weight', 'zodiac'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '2696',
    version: '1',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦯',
    name: 'white cane',
    keywords: ['accessibility', 'blind', 'cane', 'probing', 'white'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1F9AF',
    version: '12',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔗',
    name: 'link',
    keywords: ['links'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1F517',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛓️‍💥',
    name: 'broken chain',
    keywords: ['break', 'breaking', 'broken', 'chain', 'cuffs', 'freedom'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '26D3 FE0F 200D 1F4A5',
    version: '15.1',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛓️',
    name: 'chains',
    keywords: ['chain'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '26D3',
    version: '0.7',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪝',
    name: 'hook',
    keywords: ['catch', 'crook', 'curve', 'ensnare', 'point', 'selling'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1FA9D',
    version: '13',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧰',
    name: 'toolbox',
    keywords: ['box', 'chest', 'mechanic', 'red', 'tool'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1F9F0',
    version: '11',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧲',
    name: 'magnet',
    keywords: ['attraction', 'horseshoe', 'magnetic', 'negative', 'positive', 'shape', 'u'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1F9F2',
    version: '11',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪜',
    name: 'ladder',
    keywords: ['climb', 'rung', 'step'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1FA9C',
    version: '13',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪏',
    name: 'shovel',
    keywords: ['bury', 'dig', 'garden', 'hole', 'plant', 'scoop', 'snow', 'spade'],
    category: 'objects',
    subcategory: 'tool',
    unicode: '1FA8F',
    version: '16',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚗️',
    name: 'alembic',
    keywords: ['chemistry', 'tool'],
    category: 'objects',
    subcategory: 'science',
    unicode: '2697',
    version: '1',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧪',
    name: 'test tube',
    keywords: ['chemist', 'chemistry', 'experiment', 'lab', 'science', 'test', 'tube'],
    category: 'objects',
    subcategory: 'science',
    unicode: '1F9EA',
    version: '11',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧫',
    name: 'petri dish',
    keywords: ['bacteria', 'biologist', 'biology', 'culture', 'dish', 'lab', 'petri'],
    category: 'objects',
    subcategory: 'science',
    unicode: '1F9EB',
    version: '11',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧬',
    name: 'dna',
    keywords: ['biologist', 'evolution', 'gene', 'genetics', 'life'],
    category: 'objects',
    subcategory: 'science',
    unicode: '1F9EC',
    version: '11',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔬',
    name: 'microscope',
    keywords: ['experiment', 'lab', 'science', 'tool'],
    category: 'objects',
    subcategory: 'science',
    unicode: '1F52C',
    version: '1',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔭',
    name: 'telescope',
    keywords: ['contact', 'extraterrestrial', 'science', 'tool'],
    category: 'objects',
    subcategory: 'science',
    unicode: '1F52D',
    version: '1',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📡',
    name: 'satellite antenna',
    keywords: ['aliens', 'antenna', 'contact', 'dish', 'satellite', 'science'],
    category: 'objects',
    subcategory: 'science',
    unicode: '1F4E1',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💉',
    name: 'syringe',
    keywords: ['doctor', 'flu', 'medicine', 'needle', 'shot', 'sick', 'tool', 'vaccination'],
    category: 'objects',
    subcategory: 'medical',
    unicode: '1F489',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🩸',
    name: 'drop of blood',
    keywords: ['bleed', 'blood', 'donation', 'drop', 'injury', 'medicine', 'menstruation'],
    category: 'objects',
    subcategory: 'medical',
    unicode: '1FA78',
    version: '12',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💊',
    name: 'pill',
    keywords: ['doctor', 'drugs', 'medicated', 'medicine', 'pills', 'sick', 'vitamin'],
    category: 'objects',
    subcategory: 'medical',
    unicode: '1F48A',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🩹',
    name: 'adhesive bandage',
    keywords: ['adhesive', 'bandage'],
    category: 'objects',
    subcategory: 'medical',
    unicode: '1FA79',
    version: '12',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🩼',
    name: 'crutch',
    keywords: ['aid', 'cane', 'disability', 'help', 'hurt', 'injured', 'mobility', 'stick'],
    category: 'objects',
    subcategory: 'medical',
    unicode: '1FA7C',
    version: '14',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🩺',
    name: 'stethoscope',
    keywords: ['doctor', 'heart', 'medicine'],
    category: 'objects',
    subcategory: 'medical',
    unicode: '1FA7A',
    version: '12',
    color: '#FF0000',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🩻',
    name: 'x-ray',
    keywords: ['bones', 'doctor', 'medical', 'skeleton', 'skull', 'xray'],
    category: 'objects',
    subcategory: 'medical',
    unicode: '1FA7B',
    version: '14',
    color: '#FF0000',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🚪',
    name: 'door',
    keywords: ['back', 'closet', 'front'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F6AA',
    version: '0.6',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛗',
    name: 'elevator',
    keywords: ['accessibility', 'hoist', 'lift'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F6D7',
    version: '13',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪞',
    name: 'mirror',
    keywords: ['makeup', 'reflection', 'reflector', 'speculum'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1FA9E',
    version: '13',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪟',
    name: 'window',
    keywords: ['air', 'frame', 'fresh', 'opening', 'transparent', 'view'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1FA9F',
    version: '13',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛏️',
    name: 'bed',
    keywords: ['hotel', 'sleep'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F6CF',
    version: '0.7',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛋️',
    name: 'couch and lamp',
    keywords: ['couch', 'hotel', 'lamp'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F6CB',
    version: '0.7',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪑',
    name: 'chair',
    keywords: ['seat', 'sit'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1FA91',
    version: '12',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚽',
    name: 'toilet',
    keywords: ['bathroom'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F6BD',
    version: '0.6',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪠',
    name: 'plunger',
    keywords: ['cup', 'force', 'plumber', 'poop', 'suction', 'toilet'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1FAA0',
    version: '13',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚿',
    name: 'shower',
    keywords: ['water'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F6BF',
    version: '1',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛁',
    name: 'bathtub',
    keywords: ['bath'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F6C1',
    version: '1',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪤',
    name: 'mouse trap',
    keywords: ['bait', 'cheese', 'lure', 'mouse', 'mousetrap', 'snare', 'trap'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1FAA4',
    version: '13',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪒',
    name: 'razor',
    keywords: ['sharp', 'shave'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1FA92',
    version: '12',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧴',
    name: 'lotion bottle',
    keywords: ['bottle', 'lotion', 'moisturizer', 'shampoo', 'sunscreen'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F9F4',
    version: '11',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧷',
    name: 'safety pin',
    keywords: ['diaper', 'pin', 'punk', 'rock', 'safety'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F9F7',
    version: '11',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧹',
    name: 'broom',
    keywords: ['cleaning', 'sweeping', 'witch'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F9F9',
    version: '11',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧺',
    name: 'basket',
    keywords: ['farming', 'laundry', 'picnic'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F9FA',
    version: '11',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧻',
    name: 'roll of paper',
    keywords: ['paper', 'roll', 'toilet', 'towels'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F9FB',
    version: '11',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪣',
    name: 'bucket',
    keywords: ['cask', 'pail', 'vat'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1FAA3',
    version: '13',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧼',
    name: 'soap',
    keywords: ['bar', 'bathing', 'clean', 'cleaning', 'lather', 'soapdish'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F9FC',
    version: '11',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫧',
    name: 'bubbles',
    keywords: ['bubble', 'burp', 'clean', 'floating', 'pearl', 'soap', 'underwater'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1FAE7',
    version: '14',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪥',
    name: 'toothbrush',
    keywords: ['bathroom', 'brush', 'clean', 'dental', 'hygiene', 'teeth', 'toiletry'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1FAA5',
    version: '13',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧽',
    name: 'sponge',
    keywords: ['absorbing', 'cleaning', 'porous', 'soak'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F9FD',
    version: '11',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧯',
    name: 'fire extinguisher',
    keywords: ['extinguish', 'extinguisher', 'fire', 'quench'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F9EF',
    version: '11',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛒',
    name: 'shopping cart',
    keywords: ['cart', 'shopping', 'trolley'],
    category: 'objects',
    subcategory: 'household',
    unicode: '1F6D2',
    version: '3',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚬',
    name: 'cigarette',
    keywords: ['smoking'],
    category: 'objects',
    subcategory: 'other-object',
    unicode: '1F6AC',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚰️',
    name: 'coffin',
    keywords: ['dead', 'death', 'vampire'],
    category: 'objects',
    subcategory: 'other-object',
    unicode: '26B0',
    version: '1',
    color: '#808080',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🪦',
    name: 'headstone',
    keywords: ['cemetery', 'dead', 'grave', 'graveyard', 'memorial', 'rip', 'tomb', 'tombstone'],
    category: 'objects',
    subcategory: 'other-object',
    unicode: '1FAA6',
    version: '13',
    color: '#808080',
    sentiment: 'negative' as const,
  },
  {
    emoji: '⚱️',
    name: 'funeral urn',
    keywords: ['ashes', 'death', 'funeral', 'urn'],
    category: 'objects',
    subcategory: 'other-object',
    unicode: '26B1',
    version: '1',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧿',
    name: 'nazar amulet',
    keywords: ['amulet', 'bead', 'blue', 'charm', 'evil-eye', 'nazar', 'talisman'],
    category: 'objects',
    subcategory: 'other-object',
    unicode: '1F9FF',
    version: '11',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪬',
    name: 'hamsa',
    keywords: ['amulet', 'fatima', 'fortune', 'guide', 'hand', 'mary', 'miriam', 'palm', 'protect', 'protection'],
    category: 'objects',
    subcategory: 'other-object',
    unicode: '1FAAC',
    version: '14',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗿',
    name: 'moai',
    keywords: ['face', 'moyai', 'statue', 'stoneface', 'travel'],
    category: 'objects',
    subcategory: 'other-object',
    unicode: '1F5FF',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪧',
    name: 'placard',
    keywords: ['card', 'demonstration', 'notice', 'picket', 'plaque', 'protest', 'sign'],
    category: 'objects',
    subcategory: 'other-object',
    unicode: '1FAA7',
    version: '13',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪪',
    name: 'identification card',
    keywords: ['card', 'credentials', 'document', 'id', 'identification', 'license', 'security'],
    category: 'objects',
    subcategory: 'other-object',
    unicode: '1FAAA',
    version: '14',
    color: '#808080',
    sentiment: 'neutral' as const,
  }
];