import type { Emoji } from '../../schema';

export const peopleEmojis = [
  // Hand gestures
  {
    emoji: '👋',
    name: 'waving hand',
    keywords: ['wave', 'hello', 'goodbye', 'hi'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['greeting', 'farewell', 'hand'],
  },
  {
    emoji: '🤚',
    name: 'raised back of hand',
    keywords: ['raised', 'hand', 'stop'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['stop', 'halt', 'hand'],
  },
  {
    emoji: '🖐️',
    name: 'hand with fingers splayed',
    keywords: ['hand', 'five', 'splayed'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['five', 'hand', 'stop'],
  },
  {
    emoji: '✋',
    name: 'raised hand',
    keywords: ['hand', 'high five', 'stop'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['stop', 'high-five', 'hand'],
  },
  {
    emoji: '🖖',
    name: 'vulcan salute',
    keywords: ['vulcan', 'spock', 'star trek'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['star-trek', 'vulcan', 'greeting'],
  },
  {
    emoji: '👌',
    name: 'OK hand',
    keywords: ['ok', 'perfect', 'yes'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['ok', 'perfect', 'approval'],
  },
  {
    emoji: '🤌',
    name: 'pinched fingers',
    keywords: ['italian', 'fingers', 'gesture'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['italian', 'gesture', 'questioning'],
  },
  {
    emoji: '🤏',
    name: 'pinching hand',
    keywords: ['tiny', 'small', 'pinch'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['small', 'tiny', 'little'],
  },
  {
    emoji: '✌️',
    name: 'victory hand',
    keywords: ['peace', 'victory', 'two'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['peace', 'victory', 'v-sign'],
  },
  {
    emoji: '🤞',
    name: 'crossed fingers',
    keywords: ['luck', 'hope', 'cross'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['luck', 'hope', 'wishing'],
  },
  {
    emoji: '🤟',
    name: 'love-you gesture',
    keywords: ['love', 'rock', 'ily'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['love', 'rock-on', 'ily'],
  },
  {
    emoji: '🤘',
    name: 'sign of the horns',
    keywords: ['rock', 'metal', 'horns'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['rock', 'metal', 'concert'],
  },
  {
    emoji: '🤙',
    name: 'call me hand',
    keywords: ['call', 'shaka', 'hang loose'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['call-me', 'shaka', 'chill'],
  },

  // Pointing hands
  {
    emoji: '👈',
    name: 'backhand index pointing left',
    keywords: ['point', 'left', 'direction'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['pointing', 'left', 'direction'],
  },
  {
    emoji: '👉',
    name: 'backhand index pointing right',
    keywords: ['point', 'right', 'direction'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['pointing', 'right', 'direction'],
  },
  {
    emoji: '👆',
    name: 'backhand index pointing up',
    keywords: ['point', 'up', 'direction'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['pointing', 'up', 'direction'],
  },
  {
    emoji: '🖕',
    name: 'middle finger',
    keywords: ['middle finger', 'rude', 'flip off'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['rude', 'offensive', 'middle-finger'],
  },
  {
    emoji: '👇',
    name: 'backhand index pointing down',
    keywords: ['point', 'down', 'direction'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['pointing', 'down', 'direction'],
  },
  {
    emoji: '☝️',
    name: 'index pointing up',
    keywords: ['point', 'up', 'one'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['one', 'pointing', 'up'],
  },

  // Thumbs
  {
    emoji: '👍',
    name: 'thumbs up',
    keywords: ['thumbs up', 'yes', 'approve', 'like'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['approval', 'like', 'yes'],
  },
  {
    emoji: '👎',
    name: 'thumbs down',
    keywords: ['thumbs down', 'no', 'disapprove', 'dislike'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['disapproval', 'dislike', 'no'],
  },

  // Fists and clapping
  {
    emoji: '👊',
    name: 'oncoming fist',
    keywords: ['fist', 'punch', 'bump'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['fist-bump', 'punch', 'power'],
  },
  {
    emoji: '✊',
    name: 'raised fist',
    keywords: ['fist', 'power', 'solidarity'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['power', 'solidarity', 'resistance'],
  },
  {
    emoji: '🤛',
    name: 'left-facing fist',
    keywords: ['fist', 'left', 'bump'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['fist-bump', 'left', 'greeting'],
  },
  {
    emoji: '🤜',
    name: 'right-facing fist',
    keywords: ['fist', 'right', 'bump'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['fist-bump', 'right', 'greeting'],
  },
  {
    emoji: '👏',
    name: 'clapping hands',
    keywords: ['clap', 'applause', 'congrats'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['applause', 'congratulations', 'celebration'],
  },
  {
    emoji: '🙌',
    name: 'raising hands',
    keywords: ['raise', 'celebration', 'hooray'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['celebration', 'praise', 'hooray'],
  },
  {
    emoji: '🤝',
    name: 'handshake',
    keywords: ['handshake', 'deal', 'agreement'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['agreement', 'deal', 'partnership'],
  },
  {
    emoji: '🙏',
    name: 'folded hands',
    keywords: ['pray', 'please', 'thank you', 'namaste'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['prayer', 'thanks', 'please'],
  },

  // Writing hands
  {
    emoji: '✍️',
    name: 'writing hand',
    keywords: ['write', 'pen', 'sign'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['writing', 'signing', 'pen'],
  },

  // Body parts
  {
    emoji: '💅',
    name: 'nail polish',
    keywords: ['nails', 'beauty', 'manicure'],
    category: 'people',
    color: '#FF69B4',
    tags: ['beauty', 'nails', 'self-care'],
  },
  {
    emoji: '🤳',
    name: 'selfie',
    keywords: ['selfie', 'phone', 'camera'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['selfie', 'photo', 'camera'],
  },

  // Muscles
  {
    emoji: '💪',
    name: 'flexed biceps',
    keywords: ['muscle', 'strong', 'flex', 'workout'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['strength', 'muscle', 'power'],
  },

  // Legs and feet
  {
    emoji: '🦵',
    name: 'leg',
    keywords: ['leg', 'kick', 'limb'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['leg', 'limb', 'kick'],
  },
  {
    emoji: '🦶',
    name: 'foot',
    keywords: ['foot', 'kick', 'step'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['foot', 'step', 'walk'],
  },

  // Ears and sensory
  {
    emoji: '👂',
    name: 'ear',
    keywords: ['ear', 'hear', 'listen'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['hearing', 'listening', 'ear'],
  },
  {
    emoji: '🦻',
    name: 'ear with hearing aid',
    keywords: ['ear', 'hearing aid', 'accessibility'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['hearing-aid', 'accessibility', 'deaf'],
  },
  {
    emoji: '👃',
    name: 'nose',
    keywords: ['nose', 'smell', 'sniff'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['nose', 'smell', 'scent'],
  },

  // Internal organs
  {
    emoji: '🧠',
    name: 'brain',
    keywords: ['brain', 'smart', 'intelligent'],
    category: 'people',
    color: '#FFB6C1',
    tags: ['brain', 'intelligence', 'thinking'],
  },
  {
    emoji: '🫀',
    name: 'anatomical heart',
    keywords: ['heart', 'organ', 'anatomical'],
    category: 'people',
    color: '#DC143C',
    tags: ['heart', 'organ', 'medical'],
  },
  {
    emoji: '🫁',
    name: 'lungs',
    keywords: ['lungs', 'breathe', 'organ'],
    category: 'people',
    color: '#FFB6C1',
    tags: ['lungs', 'breathing', 'organ'],
  },
  {
    emoji: '🦷',
    name: 'tooth',
    keywords: ['tooth', 'dentist', 'teeth'],
    category: 'people',
    color: '#F5F5F5',
    tags: ['tooth', 'dental', 'teeth'],
  },
  {
    emoji: '🦴',
    name: 'bone',
    keywords: ['bone', 'skeleton', 'dog'],
    category: 'people',
    color: '#F5F5F5',
    tags: ['bone', 'skeleton', 'anatomy'],
  },

  // Eyes
  {
    emoji: '👀',
    name: 'eyes',
    keywords: ['eyes', 'look', 'see', 'watch'],
    category: 'people',
    color: '#4169E1',
    tags: ['looking', 'watching', 'eyes'],
  },
  {
    emoji: '👁️',
    name: 'eye',
    keywords: ['eye', 'see', 'watch', 'look'],
    category: 'people',
    color: '#4169E1',
    tags: ['eye', 'seeing', 'watching'],
  },

  // Mouth
  {
    emoji: '👅',
    name: 'tongue',
    keywords: ['tongue', 'taste', 'lick'],
    category: 'people',
    color: '#FF69B4',
    tags: ['tongue', 'taste', 'playful'],
  },
  {
    emoji: '👄',
    name: 'mouth',
    keywords: ['mouth', 'lips', 'kiss'],
    category: 'people',
    color: '#DC143C',
    tags: ['lips', 'kiss', 'mouth'],
  },

  // People
  {
    emoji: '👶',
    name: 'baby',
    keywords: ['baby', 'child', 'infant'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['baby', 'infant', 'child'],
  },
  {
    emoji: '🧒',
    name: 'child',
    keywords: ['child', 'kid', 'young'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['child', 'kid', 'youth'],
  },
  {
    emoji: '👦',
    name: 'boy',
    keywords: ['boy', 'child', 'male'],
    category: 'people',
    color: '#87CEEB',
    tags: ['boy', 'male', 'child'],
  },
  {
    emoji: '👧',
    name: 'girl',
    keywords: ['girl', 'child', 'female'],
    category: 'people',
    color: '#FFB6C1',
    tags: ['girl', 'female', 'child'],
  },
  {
    emoji: '🧑',
    name: 'person',
    keywords: ['person', 'adult', 'gender neutral'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['person', 'adult', 'neutral'],
  },
  {
    emoji: '👱',
    name: 'person blond hair',
    keywords: ['blond', 'person', 'hair'],
    category: 'people',
    color: '#FFD700',
    tags: ['blond', 'person', 'hair'],
  },
  {
    emoji: '👨',
    name: 'man',
    keywords: ['man', 'male', 'adult'],
    category: 'people',
    color: '#87CEEB',
    tags: ['man', 'male', 'adult'],
  },
  {
    emoji: '🧔',
    name: 'person beard',
    keywords: ['beard', 'person', 'bewhiskered'],
    category: 'people',
    color: '#8B4513',
    tags: ['beard', 'facial-hair', 'person'],
  },
  {
    emoji: '👨‍🦰',
    name: 'man red hair',
    keywords: ['man', 'red hair', 'ginger'],
    category: 'people',
    color: '#FF6347',
    tags: ['redhead', 'man', 'ginger'],
  },
  {
    emoji: '👨‍🦱',
    name: 'man curly hair',
    keywords: ['man', 'curly', 'hair'],
    category: 'people',
    color: '#8B4513',
    tags: ['curly-hair', 'man', 'hair'],
  },
  {
    emoji: '👨‍🦳',
    name: 'man white hair',
    keywords: ['man', 'white hair', 'old'],
    category: 'people',
    color: '#D3D3D3',
    tags: ['white-hair', 'man', 'elderly'],
  },
  {
    emoji: '👨‍🦲',
    name: 'man bald',
    keywords: ['man', 'bald', 'no hair'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['bald', 'man', 'hairless'],
  },
  {
    emoji: '👩',
    name: 'woman',
    keywords: ['woman', 'female', 'adult'],
    category: 'people',
    color: '#FFB6C1',
    tags: ['woman', 'female', 'adult'],
  },
  {
    emoji: '👩‍🦰',
    name: 'woman red hair',
    keywords: ['woman', 'red hair', 'ginger'],
    category: 'people',
    color: '#FF6347',
    tags: ['redhead', 'woman', 'ginger'],
  },
  {
    emoji: '🧑‍🦰',
    name: 'person red hair',
    keywords: ['person', 'red hair', 'ginger'],
    category: 'people',
    color: '#FF6347',
    tags: ['redhead', 'person', 'ginger'],
  },
  {
    emoji: '👩‍🦱',
    name: 'woman curly hair',
    keywords: ['woman', 'curly', 'hair'],
    category: 'people',
    color: '#8B4513',
    tags: ['curly-hair', 'woman', 'hair'],
  },
  {
    emoji: '🧑‍🦱',
    name: 'person curly hair',
    keywords: ['person', 'curly', 'hair'],
    category: 'people',
    color: '#8B4513',
    tags: ['curly-hair', 'person', 'hair'],
  },
  {
    emoji: '👩‍🦳',
    name: 'woman white hair',
    keywords: ['woman', 'white hair', 'old'],
    category: 'people',
    color: '#D3D3D3',
    tags: ['white-hair', 'woman', 'elderly'],
  },
  {
    emoji: '🧑‍🦳',
    name: 'person white hair',
    keywords: ['person', 'white hair', 'old'],
    category: 'people',
    color: '#D3D3D3',
    tags: ['white-hair', 'person', 'elderly'],
  },
  {
    emoji: '👩‍🦲',
    name: 'woman bald',
    keywords: ['woman', 'bald', 'no hair'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['bald', 'woman', 'hairless'],
  },
  {
    emoji: '🧑‍🦲',
    name: 'person bald',
    keywords: ['person', 'bald', 'no hair'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['bald', 'person', 'hairless'],
  },
  {
    emoji: '👱‍♀️',
    name: 'woman blond hair',
    keywords: ['woman', 'blond', 'hair'],
    category: 'people',
    color: '#FFD700',
    tags: ['blond', 'woman', 'hair'],
  },
  {
    emoji: '👱‍♂️',
    name: 'man blond hair',
    keywords: ['man', 'blond', 'hair'],
    category: 'people',
    color: '#FFD700',
    tags: ['blond', 'man', 'hair'],
  },
  {
    emoji: '🧓',
    name: 'older person',
    keywords: ['old', 'elderly', 'grandparent'],
    category: 'people',
    color: '#D3D3D3',
    tags: ['elderly', 'old', 'senior'],
  },
  {
    emoji: '👴',
    name: 'old man',
    keywords: ['old', 'man', 'elderly'],
    category: 'people',
    color: '#D3D3D3',
    tags: ['elderly', 'grandfather', 'old'],
  },
  {
    emoji: '👵',
    name: 'old woman',
    keywords: ['old', 'woman', 'elderly'],
    category: 'people',
    color: '#D3D3D3',
    tags: ['elderly', 'grandmother', 'old'],
  },

  // Gestures
  {
    emoji: '🙍',
    name: 'person frowning',
    keywords: ['frown', 'sad', 'person'],
    category: 'people',
    color: '#4682B4',
    tags: ['frowning', 'sad', 'disappointed'],
  },
  {
    emoji: '🙍‍♂️',
    name: 'man frowning',
    keywords: ['man', 'frown', 'sad'],
    category: 'people',
    color: '#4682B4',
    tags: ['frowning', 'man', 'sad'],
  },
  {
    emoji: '🙍‍♀️',
    name: 'woman frowning',
    keywords: ['woman', 'frown', 'sad'],
    category: 'people',
    color: '#4682B4',
    tags: ['frowning', 'woman', 'sad'],
  },
  {
    emoji: '🙎',
    name: 'person pouting',
    keywords: ['pout', 'person', 'upset'],
    category: 'people',
    color: '#DC143C',
    tags: ['pouting', 'upset', 'angry'],
  },
  {
    emoji: '🙎‍♂️',
    name: 'man pouting',
    keywords: ['man', 'pout', 'upset'],
    category: 'people',
    color: '#DC143C',
    tags: ['pouting', 'man', 'upset'],
  },
  {
    emoji: '🙎‍♀️',
    name: 'woman pouting',
    keywords: ['woman', 'pout', 'upset'],
    category: 'people',
    color: '#DC143C',
    tags: ['pouting', 'woman', 'upset'],
  },
  {
    emoji: '🙅',
    name: 'person gesturing no',
    keywords: ['no', 'stop', 'not'],
    category: 'people',
    color: '#DC143C',
    tags: ['no', 'stop', 'rejection'],
  },
  {
    emoji: '🙅‍♂️',
    name: 'man gesturing no',
    keywords: ['man', 'no', 'stop'],
    category: 'people',
    color: '#DC143C',
    tags: ['no', 'man', 'stop'],
  },
  {
    emoji: '🙅‍♀️',
    name: 'woman gesturing no',
    keywords: ['woman', 'no', 'stop'],
    category: 'people',
    color: '#DC143C',
    tags: ['no', 'woman', 'stop'],
  },
  {
    emoji: '🙆',
    name: 'person gesturing OK',
    keywords: ['ok', 'yes', 'agree'],
    category: 'people',
    color: '#90EE90',
    tags: ['ok', 'yes', 'agreement'],
  },
  {
    emoji: '🙆‍♂️',
    name: 'man gesturing OK',
    keywords: ['man', 'ok', 'yes'],
    category: 'people',
    color: '#90EE90',
    tags: ['ok', 'man', 'yes'],
  },
  {
    emoji: '🙆‍♀️',
    name: 'woman gesturing OK',
    keywords: ['woman', 'ok', 'yes'],
    category: 'people',
    color: '#90EE90',
    tags: ['ok', 'woman', 'yes'],
  },
  {
    emoji: '💁',
    name: 'person tipping hand',
    keywords: ['sassy', 'information', 'help'],
    category: 'people',
    color: '#DDA0DD',
    tags: ['sassy', 'information', 'helpful'],
  },
  {
    emoji: '💁‍♂️',
    name: 'man tipping hand',
    keywords: ['man', 'sassy', 'information'],
    category: 'people',
    color: '#DDA0DD',
    tags: ['sassy', 'man', 'information'],
  },
  {
    emoji: '💁‍♀️',
    name: 'woman tipping hand',
    keywords: ['woman', 'sassy', 'information'],
    category: 'people',
    color: '#DDA0DD',
    tags: ['sassy', 'woman', 'information'],
  },
  {
    emoji: '🙋',
    name: 'person raising hand',
    keywords: ['raise', 'hand', 'question'],
    category: 'people',
    color: '#FFD700',
    tags: ['question', 'volunteer', 'raising'],
  },
  {
    emoji: '🙋‍♂️',
    name: 'man raising hand',
    keywords: ['man', 'raise', 'hand'],
    category: 'people',
    color: '#FFD700',
    tags: ['question', 'man', 'volunteer'],
  },
  {
    emoji: '🙋‍♀️',
    name: 'woman raising hand',
    keywords: ['woman', 'raise', 'hand'],
    category: 'people',
    color: '#FFD700',
    tags: ['question', 'woman', 'volunteer'],
  },
  {
    emoji: '🧏',
    name: 'deaf person',
    keywords: ['deaf', 'ear', 'hearing'],
    category: 'people',
    color: '#87CEEB',
    tags: ['deaf', 'accessibility', 'hearing'],
  },
  {
    emoji: '🧏‍♂️',
    name: 'deaf man',
    keywords: ['deaf', 'man', 'hearing'],
    category: 'people',
    color: '#87CEEB',
    tags: ['deaf', 'man', 'accessibility'],
  },
  {
    emoji: '🧏‍♀️',
    name: 'deaf woman',
    keywords: ['deaf', 'woman', 'hearing'],
    category: 'people',
    color: '#87CEEB',
    tags: ['deaf', 'woman', 'accessibility'],
  },
  {
    emoji: '🙇',
    name: 'person bowing',
    keywords: ['bow', 'respect', 'sorry'],
    category: 'people',
    color: '#4169E1',
    tags: ['bow', 'respect', 'apology'],
  },
  {
    emoji: '🙇‍♂️',
    name: 'man bowing',
    keywords: ['man', 'bow', 'respect'],
    category: 'people',
    color: '#4169E1',
    tags: ['bow', 'man', 'respect'],
  },
  {
    emoji: '🙇‍♀️',
    name: 'woman bowing',
    keywords: ['woman', 'bow', 'respect'],
    category: 'people',
    color: '#4169E1',
    tags: ['bow', 'woman', 'respect'],
  },
  {
    emoji: '🤦',
    name: 'person facepalming',
    keywords: ['facepalm', 'disbelief', 'exasperation'],
    category: 'people',
    color: '#DEB887',
    tags: ['facepalm', 'frustrated', 'disbelief'],
  },
  {
    emoji: '🤦‍♂️',
    name: 'man facepalming',
    keywords: ['man', 'facepalm', 'disbelief'],
    category: 'people',
    color: '#DEB887',
    tags: ['facepalm', 'man', 'frustrated'],
  },
  {
    emoji: '🤦‍♀️',
    name: 'woman facepalming',
    keywords: ['woman', 'facepalm', 'disbelief'],
    category: 'people',
    color: '#DEB887',
    tags: ['facepalm', 'woman', 'frustrated'],
  },
  {
    emoji: '🤷',
    name: 'person shrugging',
    keywords: ['shrug', 'doubt', 'ignorance'],
    category: 'people',
    color: '#DDA0DD',
    tags: ['shrug', 'confused', 'indifferent'],
  },
  {
    emoji: '🤷‍♂️',
    name: 'man shrugging',
    keywords: ['man', 'shrug', 'doubt'],
    category: 'people',
    color: '#DDA0DD',
    tags: ['shrug', 'man', 'confused'],
  },
  {
    emoji: '🤷‍♀️',
    name: 'woman shrugging',
    keywords: ['woman', 'shrug', 'doubt'],
    category: 'people',
    color: '#DDA0DD',
    tags: ['shrug', 'woman', 'confused'],
  },

  // Professions
  {
    emoji: '🧑‍⚕️',
    name: 'health worker',
    keywords: ['doctor', 'nurse', 'healthcare'],
    category: 'people',
    color: '#F0F8FF',
    tags: ['healthcare', 'medical', 'doctor'],
  },
  {
    emoji: '👨‍⚕️',
    name: 'man health worker',
    keywords: ['man', 'doctor', 'healthcare'],
    category: 'people',
    color: '#F0F8FF',
    tags: ['doctor', 'man', 'medical'],
  },
  {
    emoji: '👩‍⚕️',
    name: 'woman health worker',
    keywords: ['woman', 'doctor', 'healthcare'],
    category: 'people',
    color: '#F0F8FF',
    tags: ['doctor', 'woman', 'medical'],
  },
  {
    emoji: '🧑‍🎓',
    name: 'student',
    keywords: ['student', 'graduate', 'learn'],
    category: 'people',
    color: '#000000',
    tags: ['student', 'education', 'graduate'],
  },
  {
    emoji: '👨‍🎓',
    name: 'man student',
    keywords: ['man', 'student', 'graduate'],
    category: 'people',
    color: '#000000',
    tags: ['student', 'man', 'graduate'],
  },
  {
    emoji: '👩‍🎓',
    name: 'woman student',
    keywords: ['woman', 'student', 'graduate'],
    category: 'people',
    color: '#000000',
    tags: ['student', 'woman', 'graduate'],
  },
  {
    emoji: '🧑‍🏫',
    name: 'teacher',
    keywords: ['teacher', 'professor', 'instructor'],
    category: 'people',
    color: '#8B4513',
    tags: ['teacher', 'education', 'instructor'],
  },
  {
    emoji: '👨‍🏫',
    name: 'man teacher',
    keywords: ['man', 'teacher', 'professor'],
    category: 'people',
    color: '#8B4513',
    tags: ['teacher', 'man', 'professor'],
  },
  {
    emoji: '👩‍🏫',
    name: 'woman teacher',
    keywords: ['woman', 'teacher', 'professor'],
    category: 'people',
    color: '#8B4513',
    tags: ['teacher', 'woman', 'professor'],
  },
  {
    emoji: '🧑‍⚖️',
    name: 'judge',
    keywords: ['judge', 'justice', 'law'],
    category: 'people',
    color: '#000000',
    tags: ['judge', 'justice', 'legal'],
  },
  {
    emoji: '👨‍⚖️',
    name: 'man judge',
    keywords: ['man', 'judge', 'justice'],
    category: 'people',
    color: '#000000',
    tags: ['judge', 'man', 'legal'],
  },
  {
    emoji: '👩‍⚖️',
    name: 'woman judge',
    keywords: ['woman', 'judge', 'justice'],
    category: 'people',
    color: '#000000',
    tags: ['judge', 'woman', 'legal'],
  },
  {
    emoji: '🧑‍🌾',
    name: 'farmer',
    keywords: ['farmer', 'gardener', 'agriculture'],
    category: 'people',
    color: '#228B22',
    tags: ['farmer', 'agriculture', 'gardening'],
  },
  {
    emoji: '👨‍🌾',
    name: 'man farmer',
    keywords: ['man', 'farmer', 'gardener'],
    category: 'people',
    color: '#228B22',
    tags: ['farmer', 'man', 'agriculture'],
  },
  {
    emoji: '👩‍🌾',
    name: 'woman farmer',
    keywords: ['woman', 'farmer', 'gardener'],
    category: 'people',
    color: '#228B22',
    tags: ['farmer', 'woman', 'agriculture'],
  },
  {
    emoji: '🧑‍🍳',
    name: 'cook',
    keywords: ['cook', 'chef', 'food'],
    category: 'people',
    color: '#F5F5F5',
    tags: ['chef', 'cooking', 'food'],
  },
  {
    emoji: '👨‍🍳',
    name: 'man cook',
    keywords: ['man', 'cook', 'chef'],
    category: 'people',
    color: '#F5F5F5',
    tags: ['chef', 'man', 'cooking'],
  },
  {
    emoji: '👩‍🍳',
    name: 'woman cook',
    keywords: ['woman', 'cook', 'chef'],
    category: 'people',
    color: '#F5F5F5',
    tags: ['chef', 'woman', 'cooking'],
  },
  {
    emoji: '🧑‍🔧',
    name: 'mechanic',
    keywords: ['mechanic', 'worker', 'repair'],
    category: 'people',
    color: '#4169E1',
    tags: ['mechanic', 'repair', 'worker'],
  },
  {
    emoji: '👨‍🔧',
    name: 'man mechanic',
    keywords: ['man', 'mechanic', 'worker'],
    category: 'people',
    color: '#4169E1',
    tags: ['mechanic', 'man', 'repair'],
  },
  {
    emoji: '👩‍🔧',
    name: 'woman mechanic',
    keywords: ['woman', 'mechanic', 'worker'],
    category: 'people',
    color: '#4169E1',
    tags: ['mechanic', 'woman', 'repair'],
  },
  {
    emoji: '🧑‍🏭',
    name: 'factory worker',
    keywords: ['factory', 'worker', 'industrial'],
    category: 'people',
    color: '#696969',
    tags: ['factory', 'worker', 'industrial'],
  },
  {
    emoji: '👨‍🏭',
    name: 'man factory worker',
    keywords: ['man', 'factory', 'worker'],
    category: 'people',
    color: '#696969',
    tags: ['factory', 'man', 'worker'],
  },
  {
    emoji: '👩‍🏭',
    name: 'woman factory worker',
    keywords: ['woman', 'factory', 'worker'],
    category: 'people',
    color: '#696969',
    tags: ['factory', 'woman', 'worker'],
  },
  {
    emoji: '🧑‍💼',
    name: 'office worker',
    keywords: ['office', 'business', 'manager'],
    category: 'people',
    color: '#000080',
    tags: ['office', 'business', 'professional'],
  },
  {
    emoji: '👨‍💼',
    name: 'man office worker',
    keywords: ['man', 'office', 'business'],
    category: 'people',
    color: '#000080',
    tags: ['office', 'man', 'business'],
  },
  {
    emoji: '👩‍💼',
    name: 'woman office worker',
    keywords: ['woman', 'office', 'business'],
    category: 'people',
    color: '#000080',
    tags: ['office', 'woman', 'business'],
  },
  {
    emoji: '🧑‍🔬',
    name: 'scientist',
    keywords: ['scientist', 'biologist', 'researcher'],
    category: 'people',
    color: '#F0F8FF',
    tags: ['scientist', 'research', 'lab'],
  },
  {
    emoji: '👨‍🔬',
    name: 'man scientist',
    keywords: ['man', 'scientist', 'biologist'],
    category: 'people',
    color: '#F0F8FF',
    tags: ['scientist', 'man', 'research'],
  },
  {
    emoji: '👩‍🔬',
    name: 'woman scientist',
    keywords: ['woman', 'scientist', 'biologist'],
    category: 'people',
    color: '#F0F8FF',
    tags: ['scientist', 'woman', 'research'],
  },
  {
    emoji: '🧑‍💻',
    name: 'technologist',
    keywords: ['coder', 'developer', 'software'],
    category: 'people',
    color: '#4169E1',
    tags: ['developer', 'coding', 'tech'],
  },
  {
    emoji: '👨‍💻',
    name: 'man technologist',
    keywords: ['man', 'coder', 'developer'],
    category: 'people',
    color: '#4169E1',
    tags: ['developer', 'man', 'coding'],
  },
  {
    emoji: '👩‍💻',
    name: 'woman technologist',
    keywords: ['woman', 'coder', 'developer'],
    category: 'people',
    color: '#4169E1',
    tags: ['developer', 'woman', 'coding'],
  },
  {
    emoji: '🧑‍🎤',
    name: 'singer',
    keywords: ['singer', 'rockstar', 'performer'],
    category: 'people',
    color: '#FF1493',
    tags: ['singer', 'musician', 'performer'],
  },
  {
    emoji: '👨‍🎤',
    name: 'man singer',
    keywords: ['man', 'singer', 'rockstar'],
    category: 'people',
    color: '#FF1493',
    tags: ['singer', 'man', 'musician'],
  },
  {
    emoji: '👩‍🎤',
    name: 'woman singer',
    keywords: ['woman', 'singer', 'rockstar'],
    category: 'people',
    color: '#FF1493',
    tags: ['singer', 'woman', 'musician'],
  },
  {
    emoji: '🧑‍🎨',
    name: 'artist',
    keywords: ['artist', 'painter', 'palette'],
    category: 'people',
    color: '#FF69B4',
    tags: ['artist', 'creative', 'painter'],
  },
  {
    emoji: '👨‍🎨',
    name: 'man artist',
    keywords: ['man', 'artist', 'painter'],
    category: 'people',
    color: '#FF69B4',
    tags: ['artist', 'man', 'creative'],
  },
  {
    emoji: '👩‍🎨',
    name: 'woman artist',
    keywords: ['woman', 'artist', 'painter'],
    category: 'people',
    color: '#FF69B4',
    tags: ['artist', 'woman', 'creative'],
  },
  {
    emoji: '🧑‍✈️',
    name: 'pilot',
    keywords: ['pilot', 'plane', 'captain'],
    category: 'people',
    color: '#000080',
    tags: ['pilot', 'aviation', 'captain'],
  },
  {
    emoji: '👨‍✈️',
    name: 'man pilot',
    keywords: ['man', 'pilot', 'plane'],
    category: 'people',
    color: '#000080',
    tags: ['pilot', 'man', 'aviation'],
  },
  {
    emoji: '👩‍✈️',
    name: 'woman pilot',
    keywords: ['woman', 'pilot', 'plane'],
    category: 'people',
    color: '#000080',
    tags: ['pilot', 'woman', 'aviation'],
  },
  {
    emoji: '🧑‍🚀',
    name: 'astronaut',
    keywords: ['astronaut', 'space', 'rocket'],
    category: 'people',
    color: '#F5F5F5',
    tags: ['astronaut', 'space', 'nasa'],
  },
  {
    emoji: '👨‍🚀',
    name: 'man astronaut',
    keywords: ['man', 'astronaut', 'space'],
    category: 'people',
    color: '#F5F5F5',
    tags: ['astronaut', 'man', 'space'],
  },
  {
    emoji: '👩‍🚀',
    name: 'woman astronaut',
    keywords: ['woman', 'astronaut', 'space'],
    category: 'people',
    color: '#F5F5F5',
    tags: ['astronaut', 'woman', 'space'],
  },
  {
    emoji: '🧑‍🚒',
    name: 'firefighter',
    keywords: ['firefighter', 'firetruck', 'rescue'],
    category: 'people',
    color: '#DC143C',
    tags: ['firefighter', 'rescue', 'hero'],
  },
  {
    emoji: '👨‍🚒',
    name: 'man firefighter',
    keywords: ['man', 'firefighter', 'firetruck'],
    category: 'people',
    color: '#DC143C',
    tags: ['firefighter', 'man', 'rescue'],
  },
  {
    emoji: '👩‍🚒',
    name: 'woman firefighter',
    keywords: ['woman', 'firefighter', 'firetruck'],
    category: 'people',
    color: '#DC143C',
    tags: ['firefighter', 'woman', 'rescue'],
  },
  {
    emoji: '👮',
    name: 'police officer',
    keywords: ['cop', 'police', 'officer'],
    category: 'people',
    color: '#000080',
    tags: ['police', 'cop', 'law'],
  },
  {
    emoji: '👮‍♂️',
    name: 'man police officer',
    keywords: ['man', 'cop', 'police'],
    category: 'people',
    color: '#000080',
    tags: ['police', 'man', 'cop'],
  },
  {
    emoji: '👮‍♀️',
    name: 'woman police officer',
    keywords: ['woman', 'cop', 'police'],
    category: 'people',
    color: '#000080',
    tags: ['police', 'woman', 'cop'],
  },
  {
    emoji: '🕵️',
    name: 'detective',
    keywords: ['detective', 'sleuth', 'spy'],
    category: 'people',
    color: '#696969',
    tags: ['detective', 'spy', 'investigate'],
  },
  {
    emoji: '🕵️‍♂️',
    name: 'man detective',
    keywords: ['man', 'detective', 'sleuth'],
    category: 'people',
    color: '#696969',
    tags: ['detective', 'man', 'spy'],
  },
  {
    emoji: '🕵️‍♀️',
    name: 'woman detective',
    keywords: ['woman', 'detective', 'sleuth'],
    category: 'people',
    color: '#696969',
    tags: ['detective', 'woman', 'spy'],
  },
  {
    emoji: '💂',
    name: 'guard',
    keywords: ['guard', 'british', 'soldier'],
    category: 'people',
    color: '#DC143C',
    tags: ['guard', 'british', 'soldier'],
  },
  {
    emoji: '💂‍♂️',
    name: 'man guard',
    keywords: ['man', 'guard', 'british'],
    category: 'people',
    color: '#DC143C',
    tags: ['guard', 'man', 'british'],
  },
  {
    emoji: '💂‍♀️',
    name: 'woman guard',
    keywords: ['woman', 'guard', 'british'],
    category: 'people',
    color: '#DC143C',
    tags: ['guard', 'woman', 'british'],
  },
  {
    emoji: '🥷',
    name: 'ninja',
    keywords: ['ninja', 'fighter', 'hidden'],
    category: 'people',
    color: '#000000',
    tags: ['ninja', 'stealth', 'fighter'],
  },
  {
    emoji: '👷',
    name: 'construction worker',
    keywords: ['construction', 'worker', 'helmet'],
    category: 'people',
    color: '#FFD700',
    tags: ['construction', 'worker', 'builder'],
  },
  {
    emoji: '👷‍♂️',
    name: 'man construction worker',
    keywords: ['man', 'construction', 'worker'],
    category: 'people',
    color: '#FFD700',
    tags: ['construction', 'man', 'builder'],
  },
  {
    emoji: '👷‍♀️',
    name: 'woman construction worker',
    keywords: ['woman', 'construction', 'worker'],
    category: 'people',
    color: '#FFD700',
    tags: ['construction', 'woman', 'builder'],
  },
  {
    emoji: '🤴',
    name: 'prince',
    keywords: ['prince', 'crown', 'royal'],
    category: 'people',
    color: '#FFD700',
    tags: ['prince', 'royalty', 'crown'],
  },
  {
    emoji: '👸',
    name: 'princess',
    keywords: ['princess', 'crown', 'royal'],
    category: 'people',
    color: '#FFB6C1',
    tags: ['princess', 'royalty', 'crown'],
  },
  {
    emoji: '👳',
    name: 'person wearing turban',
    keywords: ['turban', 'person', 'muslim'],
    category: 'people',
    color: '#F5F5F5',
    tags: ['turban', 'culture', 'person'],
  },
  {
    emoji: '👳‍♂️',
    name: 'man wearing turban',
    keywords: ['man', 'turban', 'muslim'],
    category: 'people',
    color: '#F5F5F5',
    tags: ['turban', 'man', 'culture'],
  },
  {
    emoji: '👳‍♀️',
    name: 'woman wearing turban',
    keywords: ['woman', 'turban', 'muslim'],
    category: 'people',
    color: '#F5F5F5',
    tags: ['turban', 'woman', 'culture'],
  },
  {
    emoji: '👲',
    name: 'person with skullcap',
    keywords: ['hat', 'person', 'chinese'],
    category: 'people',
    color: '#4169E1',
    tags: ['hat', 'culture', 'chinese'],
  },
  {
    emoji: '🧕',
    name: 'woman with headscarf',
    keywords: ['hijab', 'headscarf', 'muslim'],
    category: 'people',
    color: '#DDA0DD',
    tags: ['hijab', 'headscarf', 'culture'],
  },
  {
    emoji: '🤵',
    name: 'person in tuxedo',
    keywords: ['groom', 'person', 'suit'],
    category: 'people',
    color: '#000000',
    tags: ['tuxedo', 'formal', 'groom'],
  },
  {
    emoji: '🤵‍♂️',
    name: 'man in tuxedo',
    keywords: ['man', 'groom', 'suit'],
    category: 'people',
    color: '#000000',
    tags: ['tuxedo', 'man', 'formal'],
  },
  {
    emoji: '🤵‍♀️',
    name: 'woman in tuxedo',
    keywords: ['woman', 'groom', 'suit'],
    category: 'people',
    color: '#000000',
    tags: ['tuxedo', 'woman', 'formal'],
  },
  {
    emoji: '👰',
    name: 'person with veil',
    keywords: ['bride', 'person', 'wedding'],
    category: 'people',
    color: '#F5F5F5',
    tags: ['bride', 'wedding', 'veil'],
  },
  {
    emoji: '👰‍♂️',
    name: 'man with veil',
    keywords: ['man', 'bride', 'wedding'],
    category: 'people',
    color: '#F5F5F5',
    tags: ['veil', 'man', 'wedding'],
  },
  {
    emoji: '👰‍♀️',
    name: 'woman with veil',
    keywords: ['woman', 'bride', 'wedding'],
    category: 'people',
    color: '#F5F5F5',
    tags: ['bride', 'woman', 'wedding'],
  },
  {
    emoji: '🤰',
    name: 'pregnant woman',
    keywords: ['pregnant', 'woman', 'baby'],
    category: 'people',
    color: '#FFB6C1',
    tags: ['pregnant', 'expecting', 'mother'],
  },
  {
    emoji: '🤱',
    name: 'breast-feeding',
    keywords: ['nursing', 'baby', 'child'],
    category: 'people',
    color: '#FFB6C1',
    tags: ['breastfeeding', 'baby', 'mother'],
  },
  {
    emoji: '👩‍🍼',
    name: 'woman feeding baby',
    keywords: ['woman', 'feeding', 'baby'],
    category: 'people',
    color: '#FFB6C1',
    tags: ['feeding', 'baby', 'mother'],
  },
  {
    emoji: '👨‍🍼',
    name: 'man feeding baby',
    keywords: ['man', 'feeding', 'baby'],
    category: 'people',
    color: '#87CEEB',
    tags: ['feeding', 'baby', 'father'],
  },
  {
    emoji: '🧑‍🍼',
    name: 'person feeding baby',
    keywords: ['person', 'feeding', 'baby'],
    category: 'people',
    color: '#FDBCB4',
    tags: ['feeding', 'baby', 'parent'],
  },

  // Fantasy characters
  {
    emoji: '👼',
    name: 'baby angel',
    keywords: ['angel', 'cherub', 'face'],
    category: 'people',
    color: '#87CEEB',
    tags: ['angel', 'baby', 'cherub'],
  },
  {
    emoji: '🎅',
    name: 'Santa Claus',
    keywords: ['santa', 'christmas', 'claus'],
    category: 'people',
    color: '#DC143C',
    tags: ['santa', 'christmas', 'holiday'],
  },
  {
    emoji: '🤶',
    name: 'Mrs. Claus',
    keywords: ['mrs claus', 'christmas', 'mother'],
    category: 'people',
    color: '#DC143C',
    tags: ['mrs-claus', 'christmas', 'holiday'],
  },
  {
    emoji: '🧑‍🎄',
    name: 'mx claus',
    keywords: ['mx claus', 'christmas', 'person'],
    category: 'people',
    color: '#DC143C',
    tags: ['mx-claus', 'christmas', 'holiday'],
  },
  {
    emoji: '🦸',
    name: 'superhero',
    keywords: ['superhero', 'superpowers', 'hero'],
    category: 'people',
    color: '#FF0000',
    tags: ['superhero', 'hero', 'super'],
  },
  {
    emoji: '🦸‍♂️',
    name: 'man superhero',
    keywords: ['man', 'superhero', 'superpowers'],
    category: 'people',
    color: '#FF0000',
    tags: ['superhero', 'man', 'hero'],
  },
  {
    emoji: '🦸‍♀️',
    name: 'woman superhero',
    keywords: ['woman', 'superhero', 'superpowers'],
    category: 'people',
    color: '#FF0000',
    tags: ['superhero', 'woman', 'hero'],
  },
  {
    emoji: '🦹',
    name: 'supervillain',
    keywords: ['supervillain', 'criminal', 'evil'],
    category: 'people',
    color: '#800080',
    tags: ['villain', 'evil', 'super'],
  },
  {
    emoji: '🦹‍♂️',
    name: 'man supervillain',
    keywords: ['man', 'supervillain', 'criminal'],
    category: 'people',
    color: '#800080',
    tags: ['villain', 'man', 'evil'],
  },
  {
    emoji: '🦹‍♀️',
    name: 'woman supervillain',
    keywords: ['woman', 'supervillain', 'criminal'],
    category: 'people',
    color: '#800080',
    tags: ['villain', 'woman', 'evil'],
  },
  {
    emoji: '🧙',
    name: 'mage',
    keywords: ['wizard', 'sorcerer', 'witch'],
    category: 'people',
    color: '#4B0082',
    tags: ['wizard', 'magic', 'mage'],
  },
  {
    emoji: '🧙‍♂️',
    name: 'man mage',
    keywords: ['man', 'wizard', 'sorcerer'],
    category: 'people',
    color: '#4B0082',
    tags: ['wizard', 'man', 'magic'],
  },
  {
    emoji: '🧙‍♀️',
    name: 'woman mage',
    keywords: ['woman', 'wizard', 'sorcerer'],
    category: 'people',
    color: '#4B0082',
    tags: ['wizard', 'woman', 'magic'],
  },
  {
    emoji: '🧚',
    name: 'fairy',
    keywords: ['fairy', 'oberon', 'puck'],
    category: 'people',
    color: '#FFB6C1',
    tags: ['fairy', 'magic', 'fantasy'],
  },
  {
    emoji: '🧚‍♂️',
    name: 'man fairy',
    keywords: ['man', 'fairy', 'oberon'],
    category: 'people',
    color: '#87CEEB',
    tags: ['fairy', 'man', 'magic'],
  },
  {
    emoji: '🧚‍♀️',
    name: 'woman fairy',
    keywords: ['woman', 'fairy', 'titania'],
    category: 'people',
    color: '#FFB6C1',
    tags: ['fairy', 'woman', 'magic'],
  },
  {
    emoji: '🧛',
    name: 'vampire',
    keywords: ['vampire', 'dracula', 'undead'],
    category: 'people',
    color: '#8B0000',
    tags: ['vampire', 'dracula', 'undead'],
  },
  {
    emoji: '🧛‍♂️',
    name: 'man vampire',
    keywords: ['man', 'vampire', 'dracula'],
    category: 'people',
    color: '#8B0000',
    tags: ['vampire', 'man', 'dracula'],
  },
  {
    emoji: '🧛‍♀️',
    name: 'woman vampire',
    keywords: ['woman', 'vampire', 'undead'],
    category: 'people',
    color: '#8B0000',
    tags: ['vampire', 'woman', 'undead'],
  },
  {
    emoji: '🧜',
    name: 'merperson',
    keywords: ['mermaid', 'merman', 'merwoman'],
    category: 'people',
    color: '#20B2AA',
    tags: ['mermaid', 'ocean', 'fantasy'],
  },
  {
    emoji: '🧜‍♂️',
    name: 'merman',
    keywords: ['merman', 'triton', 'man'],
    category: 'people',
    color: '#20B2AA',
    tags: ['merman', 'ocean', 'fantasy'],
  },
  {
    emoji: '🧜‍♀️',
    name: 'mermaid',
    keywords: ['mermaid', 'ariel', 'woman'],
    category: 'people',
    color: '#20B2AA',
    tags: ['mermaid', 'ocean', 'fantasy'],
  },
  {
    emoji: '🧝',
    name: 'elf',
    keywords: ['elf', 'magical', 'fantasy'],
    category: 'people',
    color: '#228B22',
    tags: ['elf', 'fantasy', 'magical'],
  },
  {
    emoji: '🧝‍♂️',
    name: 'man elf',
    keywords: ['man', 'elf', 'magical'],
    category: 'people',
    color: '#228B22',
    tags: ['elf', 'man', 'fantasy'],
  },
  {
    emoji: '🧝‍♀️',
    name: 'woman elf',
    keywords: ['woman', 'elf', 'magical'],
    category: 'people',
    color: '#228B22',
    tags: ['elf', 'woman', 'fantasy'],
  },
  {
    emoji: '🧞',
    name: 'genie',
    keywords: ['genie', 'djinn', 'wish'],
    category: 'people',
    color: '#4169E1',
    tags: ['genie', 'magic', 'wish'],
  },
  {
    emoji: '🧞‍♂️',
    name: 'man genie',
    keywords: ['man', 'genie', 'djinn'],
    category: 'people',
    color: '#4169E1',
    tags: ['genie', 'man', 'magic'],
  },
  {
    emoji: '🧞‍♀️',
    name: 'woman genie',
    keywords: ['woman', 'genie', 'djinn'],
    category: 'people',
    color: '#4169E1',
    tags: ['genie', 'woman', 'magic'],
  },
  {
    emoji: '🧟',
    name: 'zombie',
    keywords: ['zombie', 'undead', 'walking dead'],
    category: 'people',
    color: '#556B2F',
    tags: ['zombie', 'undead', 'horror'],
  },
  {
    emoji: '🧟‍♂️',
    name: 'man zombie',
    keywords: ['man', 'zombie', 'undead'],
    category: 'people',
    color: '#556B2F',
    tags: ['zombie', 'man', 'undead'],
  },
  {
    emoji: '🧟‍♀️',
    name: 'woman zombie',
    keywords: ['woman', 'zombie', 'undead'],
    category: 'people',
    color: '#556B2F',
    tags: ['zombie', 'woman', 'undead'],
  },

  // Activities
  {
    emoji: '💆',
    name: 'person getting massage',
    keywords: ['massage', 'salon', 'face'],
    category: 'people',
    color: '#DDA0DD',
    tags: ['massage', 'relaxation', 'spa'],
  },
  {
    emoji: '💆‍♂️',
    name: 'man getting massage',
    keywords: ['man', 'massage', 'salon'],
    category: 'people',
    color: '#DDA0DD',
    tags: ['massage', 'man', 'spa'],
  },
  {
    emoji: '💆‍♀️',
    name: 'woman getting massage',
    keywords: ['woman', 'massage', 'salon'],
    category: 'people',
    color: '#DDA0DD',
    tags: ['massage', 'woman', 'spa'],
  },
  {
    emoji: '💇',
    name: 'person getting haircut',
    keywords: ['haircut', 'beauty', 'barber'],
    category: 'people',
    color: '#8B4513',
    tags: ['haircut', 'salon', 'barber'],
  },
  {
    emoji: '💇‍♂️',
    name: 'man getting haircut',
    keywords: ['man', 'haircut', 'barber'],
    category: 'people',
    color: '#8B4513',
    tags: ['haircut', 'man', 'barber'],
  },
  {
    emoji: '💇‍♀️',
    name: 'woman getting haircut',
    keywords: ['woman', 'haircut', 'beauty'],
    category: 'people',
    color: '#8B4513',
    tags: ['haircut', 'woman', 'salon'],
  },
  {
    emoji: '🚶',
    name: 'person walking',
    keywords: ['walk', 'hike', 'move'],
    category: 'people',
    color: '#4169E1',
    tags: ['walking', 'moving', 'exercise'],
  },
  {
    emoji: '🚶‍♂️',
    name: 'man walking',
    keywords: ['man', 'walk', 'hike'],
    category: 'people',
    color: '#4169E1',
    tags: ['walking', 'man', 'exercise'],
  },
  {
    emoji: '🚶‍♀️',
    name: 'woman walking',
    keywords: ['woman', 'walk', 'hike'],
    category: 'people',
    color: '#4169E1',
    tags: ['walking', 'woman', 'exercise'],
  },
  {
    emoji: '🧍',
    name: 'person standing',
    keywords: ['stand', 'standing', 'person'],
    category: 'people',
    color: '#696969',
    tags: ['standing', 'still', 'person'],
  },
  {
    emoji: '🧍‍♂️',
    name: 'man standing',
    keywords: ['man', 'stand', 'standing'],
    category: 'people',
    color: '#696969',
    tags: ['standing', 'man', 'still'],
  },
  {
    emoji: '🧍‍♀️',
    name: 'woman standing',
    keywords: ['woman', 'stand', 'standing'],
    category: 'people',
    color: '#696969',
    tags: ['standing', 'woman', 'still'],
  },
  {
    emoji: '🧎',
    name: 'person kneeling',
    keywords: ['kneel', 'kneeling', 'person'],
    category: 'people',
    color: '#8B4513',
    tags: ['kneeling', 'kneel', 'person'],
  },
  {
    emoji: '🧎‍♂️',
    name: 'man kneeling',
    keywords: ['man', 'kneel', 'kneeling'],
    category: 'people',
    color: '#8B4513',
    tags: ['kneeling', 'man', 'kneel'],
  },
  {
    emoji: '🧎‍♀️',
    name: 'woman kneeling',
    keywords: ['woman', 'kneel', 'kneeling'],
    category: 'people',
    color: '#8B4513',
    tags: ['kneeling', 'woman', 'kneel'],
  },
  {
    emoji: '🧑‍🦯',
    name: 'person with white cane',
    keywords: ['blind', 'accessibility', 'person'],
    category: 'people',
    color: '#696969',
    tags: ['blind', 'accessibility', 'cane'],
  },
  {
    emoji: '👨‍🦯',
    name: 'man with white cane',
    keywords: ['man', 'blind', 'accessibility'],
    category: 'people',
    color: '#696969',
    tags: ['blind', 'man', 'cane'],
  },
  {
    emoji: '👩‍🦯',
    name: 'woman with white cane',
    keywords: ['woman', 'blind', 'accessibility'],
    category: 'people',
    color: '#696969',
    tags: ['blind', 'woman', 'cane'],
  },
  {
    emoji: '🧑‍🦼',
    name: 'person in motorized wheelchair',
    keywords: ['wheelchair', 'accessibility', 'person'],
    category: 'people',
    color: '#4169E1',
    tags: ['wheelchair', 'accessibility', 'mobility'],
  },
  {
    emoji: '👨‍🦼',
    name: 'man in motorized wheelchair',
    keywords: ['man', 'wheelchair', 'accessibility'],
    category: 'people',
    color: '#4169E1',
    tags: ['wheelchair', 'man', 'mobility'],
  },
  {
    emoji: '👩‍🦼',
    name: 'woman in motorized wheelchair',
    keywords: ['woman', 'wheelchair', 'accessibility'],
    category: 'people',
    color: '#4169E1',
    tags: ['wheelchair', 'woman', 'mobility'],
  },
  {
    emoji: '🧑‍🦽',
    name: 'person in manual wheelchair',
    keywords: ['wheelchair', 'accessibility', 'person'],
    category: 'people',
    color: '#696969',
    tags: ['wheelchair', 'accessibility', 'manual'],
  },
  {
    emoji: '👨‍🦽',
    name: 'man in manual wheelchair',
    keywords: ['man', 'wheelchair', 'accessibility'],
    category: 'people',
    color: '#696969',
    tags: ['wheelchair', 'man', 'manual'],
  },
  {
    emoji: '👩‍🦽',
    name: 'woman in manual wheelchair',
    keywords: ['woman', 'wheelchair', 'accessibility'],
    category: 'people',
    color: '#696969',
    tags: ['wheelchair', 'woman', 'manual'],
  },
  {
    emoji: '🏃',
    name: 'person running',
    keywords: ['run', 'exercise', 'marathon'],
    category: 'people',
    color: '#FF4500',
    tags: ['running', 'exercise', 'jogging'],
  },
  {
    emoji: '🏃‍♂️',
    name: 'man running',
    keywords: ['man', 'run', 'exercise'],
    category: 'people',
    color: '#FF4500',
    tags: ['running', 'man', 'jogging'],
  },
  {
    emoji: '🏃‍♀️',
    name: 'woman running',
    keywords: ['woman', 'run', 'exercise'],
    category: 'people',
    color: '#FF4500',
    tags: ['running', 'woman', 'jogging'],
  },
  {
    emoji: '💃',
    name: 'woman dancing',
    keywords: ['dance', 'dancer', 'dress'],
    category: 'people',
    color: '#DC143C',
    tags: ['dancing', 'dancer', 'party'],
  },
  {
    emoji: '🕺',
    name: 'man dancing',
    keywords: ['dance', 'dancer', 'man'],
    category: 'people',
    color: '#800080',
    tags: ['dancing', 'dancer', 'party'],
  },
  {
    emoji: '🕴️',
    name: 'person in suit levitating',
    keywords: ['suit', 'levitate', 'hover'],
    category: 'people',
    color: '#000000',
    tags: ['levitating', 'business', 'floating'],
  },
  {
    emoji: '👯',
    name: 'people with bunny ears',
    keywords: ['bunny', 'dancer', 'partying'],
    category: 'people',
    color: '#FF69B4',
    tags: ['party', 'dancing', 'bunny'],
  },
  {
    emoji: '👯‍♂️',
    name: 'men with bunny ears',
    keywords: ['men', 'bunny', 'dancer'],
    category: 'people',
    color: '#87CEEB',
    tags: ['party', 'men', 'dancing'],
  },
  {
    emoji: '👯‍♀️',
    name: 'women with bunny ears',
    keywords: ['women', 'bunny', 'dancer'],
    category: 'people',
    color: '#FF69B4',
    tags: ['party', 'women', 'dancing'],
  },
  {
    emoji: '🧖',
    name: 'person in steamy room',
    keywords: ['sauna', 'steam', 'spa'],
    category: 'people',
    color: '#FFE4B5',
    tags: ['sauna', 'spa', 'relaxation'],
  },
  {
    emoji: '🧖‍♂️',
    name: 'man in steamy room',
    keywords: ['man', 'sauna', 'steam'],
    category: 'people',
    color: '#FFE4B5',
    tags: ['sauna', 'man', 'spa'],
  },
  {
    emoji: '🧖‍♀️',
    name: 'woman in steamy room',
    keywords: ['woman', 'sauna', 'steam'],
    category: 'people',
    color: '#FFE4B5',
    tags: ['sauna', 'woman', 'spa'],
  },
  {
    emoji: '🧗',
    name: 'person climbing',
    keywords: ['climb', 'bouldering', 'climber'],
    category: 'people',
    color: '#696969',
    tags: ['climbing', 'sport', 'boulder'],
  },
  {
    emoji: '🧗‍♂️',
    name: 'man climbing',
    keywords: ['man', 'climb', 'bouldering'],
    category: 'people',
    color: '#696969',
    tags: ['climbing', 'man', 'sport'],
  },
  {
    emoji: '🧗‍♀️',
    name: 'woman climbing',
    keywords: ['woman', 'climb', 'bouldering'],
    category: 'people',
    color: '#696969',
    tags: ['climbing', 'woman', 'sport'],
  },

  // Sports people
  {
    emoji: '🤺',
    name: 'person fencing',
    keywords: ['fencer', 'fencing', 'sword'],
    category: 'people',
    color: '#C0C0C0',
    tags: ['fencing', 'sport', 'sword'],
  },
  {
    emoji: '🏇',
    name: 'horse racing',
    keywords: ['jockey', 'racehorse', 'racing'],
    category: 'people',
    color: '#8B4513',
    tags: ['racing', 'horse', 'jockey'],
  },
  {
    emoji: '⛷️',
    name: 'skier',
    keywords: ['ski', 'snow', 'winter'],
    category: 'people',
    color: '#4169E1',
    tags: ['skiing', 'winter', 'sport'],
  },
  {
    emoji: '🏂',
    name: 'snowboarder',
    keywords: ['snowboard', 'snow', 'winter'],
    category: 'people',
    color: '#FF4500',
    tags: ['snowboarding', 'winter', 'sport'],
  },
  {
    emoji: '🏌️',
    name: 'person golfing',
    keywords: ['golf', 'ball', 'golfer'],
    category: 'people',
    color: '#228B22',
    tags: ['golf', 'sport', 'golfer'],
  },
  {
    emoji: '🏌️‍♂️',
    name: 'man golfing',
    keywords: ['man', 'golf', 'ball'],
    category: 'people',
    color: '#228B22',
    tags: ['golf', 'man', 'sport'],
  },
  {
    emoji: '🏌️‍♀️',
    name: 'woman golfing',
    keywords: ['woman', 'golf', 'ball'],
    category: 'people',
    color: '#228B22',
    tags: ['golf', 'woman', 'sport'],
  },
  {
    emoji: '🏄',
    name: 'person surfing',
    keywords: ['surf', 'surfboard', 'surfer'],
    category: 'people',
    color: '#00CED1',
    tags: ['surfing', 'ocean', 'sport'],
  },
  {
    emoji: '🏄‍♂️',
    name: 'man surfing',
    keywords: ['man', 'surf', 'surfboard'],
    category: 'people',
    color: '#00CED1',
    tags: ['surfing', 'man', 'ocean'],
  },
  {
    emoji: '🏄‍♀️',
    name: 'woman surfing',
    keywords: ['woman', 'surf', 'surfboard'],
    category: 'people',
    color: '#00CED1',
    tags: ['surfing', 'woman', 'ocean'],
  },
  {
    emoji: '🚣',
    name: 'person rowing boat',
    keywords: ['row', 'boat', 'rowboat'],
    category: 'people',
    color: '#8B4513',
    tags: ['rowing', 'boat', 'sport'],
  },
  {
    emoji: '🚣‍♂️',
    name: 'man rowing boat',
    keywords: ['man', 'row', 'boat'],
    category: 'people',
    color: '#8B4513',
    tags: ['rowing', 'man', 'boat'],
  },
  {
    emoji: '🚣‍♀️',
    name: 'woman rowing boat',
    keywords: ['woman', 'row', 'boat'],
    category: 'people',
    color: '#8B4513',
    tags: ['rowing', 'woman', 'boat'],
  },
  {
    emoji: '🏊',
    name: 'person swimming',
    keywords: ['swim', 'swimmer', 'pool'],
    category: 'people',
    color: '#00CED1',
    tags: ['swimming', 'pool', 'sport'],
  },
  {
    emoji: '🏊‍♂️',
    name: 'man swimming',
    keywords: ['man', 'swim', 'swimmer'],
    category: 'people',
    color: '#00CED1',
    tags: ['swimming', 'man', 'pool'],
  },
  {
    emoji: '🏊‍♀️',
    name: 'woman swimming',
    keywords: ['woman', 'swim', 'swimmer'],
    category: 'people',
    color: '#00CED1',
    tags: ['swimming', 'woman', 'pool'],
  },
  {
    emoji: '⛹️',
    name: 'person bouncing ball',
    keywords: ['ball', 'dribble', 'basketball'],
    category: 'people',
    color: '#FF4500',
    tags: ['basketball', 'sport', 'dribbling'],
  },
  {
    emoji: '⛹️‍♂️',
    name: 'man bouncing ball',
    keywords: ['man', 'ball', 'basketball'],
    category: 'people',
    color: '#FF4500',
    tags: ['basketball', 'man', 'sport'],
  },
  {
    emoji: '⛹️‍♀️',
    name: 'woman bouncing ball',
    keywords: ['woman', 'ball', 'basketball'],
    category: 'people',
    color: '#FF4500',
    tags: ['basketball', 'woman', 'sport'],
  },
  {
    emoji: '🏋️',
    name: 'person lifting weights',
    keywords: ['lifter', 'weight', 'weightlifter'],
    category: 'people',
    color: '#696969',
    tags: ['weightlifting', 'gym', 'sport'],
  },
  {
    emoji: '🏋️‍♂️',
    name: 'man lifting weights',
    keywords: ['man', 'lifter', 'weight'],
    category: 'people',
    color: '#696969',
    tags: ['weightlifting', 'man', 'gym'],
  },
  {
    emoji: '🏋️‍♀️',
    name: 'woman lifting weights',
    keywords: ['woman', 'lifter', 'weight'],
    category: 'people',
    color: '#696969',
    tags: ['weightlifting', 'woman', 'gym'],
  },
  {
    emoji: '🚴',
    name: 'person biking',
    keywords: ['bike', 'bicycle', 'cyclist'],
    category: 'people',
    color: '#4169E1',
    tags: ['cycling', 'bike', 'sport'],
  },
  {
    emoji: '🚴‍♂️',
    name: 'man biking',
    keywords: ['man', 'bike', 'bicycle'],
    category: 'people',
    color: '#4169E1',
    tags: ['cycling', 'man', 'bike'],
  },
  {
    emoji: '🚴‍♀️',
    name: 'woman biking',
    keywords: ['woman', 'bike', 'bicycle'],
    category: 'people',
    color: '#4169E1',
    tags: ['cycling', 'woman', 'bike'],
  },
  {
    emoji: '🚵',
    name: 'person mountain biking',
    keywords: ['bike', 'bicycle', 'mountain'],
    category: 'people',
    color: '#228B22',
    tags: ['mountain-biking', 'sport', 'extreme'],
  },
  {
    emoji: '🚵‍♂️',
    name: 'man mountain biking',
    keywords: ['man', 'bike', 'mountain'],
    category: 'people',
    color: '#228B22',
    tags: ['mountain-biking', 'man', 'extreme'],
  },
  {
    emoji: '🚵‍♀️',
    name: 'woman mountain biking',
    keywords: ['woman', 'bike', 'mountain'],
    category: 'people',
    color: '#228B22',
    tags: ['mountain-biking', 'woman', 'extreme'],
  },
  {
    emoji: '🤸',
    name: 'person cartwheeling',
    keywords: ['cartwheel', 'gymnast', 'gymnastics'],
    category: 'people',
    color: '#FF69B4',
    tags: ['gymnastics', 'cartwheel', 'sport'],
  },
  {
    emoji: '🤸‍♂️',
    name: 'man cartwheeling',
    keywords: ['man', 'cartwheel', 'gymnast'],
    category: 'people',
    color: '#87CEEB',
    tags: ['gymnastics', 'man', 'cartwheel'],
  },
  {
    emoji: '🤸‍♀️',
    name: 'woman cartwheeling',
    keywords: ['woman', 'cartwheel', 'gymnast'],
    category: 'people',
    color: '#FF69B4',
    tags: ['gymnastics', 'woman', 'cartwheel'],
  },
  {
    emoji: '🤼',
    name: 'people wrestling',
    keywords: ['wrestle', 'wrestler', 'wrestling'],
    category: 'people',
    color: '#DAA520',
    tags: ['wrestling', 'sport', 'combat'],
  },
  {
    emoji: '🤼‍♂️',
    name: 'men wrestling',
    keywords: ['men', 'wrestle', 'wrestler'],
    category: 'people',
    color: '#DAA520',
    tags: ['wrestling', 'men', 'sport'],
  },
  {
    emoji: '🤼‍♀️',
    name: 'women wrestling',
    keywords: ['women', 'wrestle', 'wrestler'],
    category: 'people',
    color: '#DAA520',
    tags: ['wrestling', 'women', 'sport'],
  },
  {
    emoji: '🤽',
    name: 'person playing water polo',
    keywords: ['water', 'polo', 'sport'],
    category: 'people',
    color: '#00CED1',
    tags: ['water-polo', 'sport', 'swimming'],
  },
  {
    emoji: '🤽‍♂️',
    name: 'man playing water polo',
    keywords: ['man', 'water', 'polo'],
    category: 'people',
    color: '#00CED1',
    tags: ['water-polo', 'man', 'sport'],
  },
  {
    emoji: '🤽‍♀️',
    name: 'woman playing water polo',
    keywords: ['woman', 'water', 'polo'],
    category: 'people',
    color: '#00CED1',
    tags: ['water-polo', 'woman', 'sport'],
  },
  {
    emoji: '🤾',
    name: 'person playing handball',
    keywords: ['ball', 'handball', 'sport'],
    category: 'people',
    color: '#FF4500',
    tags: ['handball', 'sport', 'throwing'],
  },
  {
    emoji: '🤾‍♂️',
    name: 'man playing handball',
    keywords: ['man', 'ball', 'handball'],
    category: 'people',
    color: '#FF4500',
    tags: ['handball', 'man', 'sport'],
  },
  {
    emoji: '🤾‍♀️',
    name: 'woman playing handball',
    keywords: ['woman', 'ball', 'handball'],
    category: 'people',
    color: '#FF4500',
    tags: ['handball', 'woman', 'sport'],
  },
  {
    emoji: '🤹',
    name: 'person juggling',
    keywords: ['juggle', 'balance', 'skill'],
    category: 'people',
    color: '#FFD700',
    tags: ['juggling', 'circus', 'skill'],
  },
  {
    emoji: '🤹‍♂️',
    name: 'man juggling',
    keywords: ['man', 'juggle', 'balance'],
    category: 'people',
    color: '#FFD700',
    tags: ['juggling', 'man', 'circus'],
  },
  {
    emoji: '🤹‍♀️',
    name: 'woman juggling',
    keywords: ['woman', 'juggle', 'balance'],
    category: 'people',
    color: '#FFD700',
    tags: ['juggling', 'woman', 'circus'],
  },

  // Yoga and meditation
  {
    emoji: '🧘',
    name: 'person in lotus position',
    keywords: ['yoga', 'meditation', 'serenity'],
    category: 'people',
    color: '#DDA0DD',
    tags: ['yoga', 'meditation', 'zen'],
  },
  {
    emoji: '🧘‍♂️',
    name: 'man in lotus position',
    keywords: ['man', 'yoga', 'meditation'],
    category: 'people',
    color: '#87CEEB',
    tags: ['yoga', 'man', 'meditation'],
  },
  {
    emoji: '🧘‍♀️',
    name: 'woman in lotus position',
    keywords: ['woman', 'yoga', 'meditation'],
    category: 'people',
    color: '#DDA0DD',
    tags: ['yoga', 'woman', 'meditation'],
  },

  // Couple and family
  {
    emoji: '👫',
    name: 'woman and man holding hands',
    keywords: ['couple', 'date', 'dating'],
    category: 'people',
    color: '#FF69B4',
    tags: ['couple', 'relationship', 'dating'],
  },
  {
    emoji: '👬',
    name: 'men holding hands',
    keywords: ['couple', 'gay', 'men'],
    category: 'people',
    color: '#87CEEB',
    tags: ['couple', 'gay', 'relationship'],
  },
  {
    emoji: '👭',
    name: 'women holding hands',
    keywords: ['couple', 'lesbian', 'women'],
    category: 'people',
    color: '#FF69B4',
    tags: ['couple', 'lesbian', 'relationship'],
  },
  {
    emoji: '💏',
    name: 'kiss',
    keywords: ['kiss', 'lips', 'couple'],
    category: 'people',
    color: '#FF69B4',
    tags: ['kiss', 'love', 'romance'],
  },
  {
    emoji: '👨‍❤️‍💋‍👨',
    name: 'kiss man man',
    keywords: ['kiss', 'gay', 'men'],
    category: 'people',
    color: '#87CEEB',
    tags: ['kiss', 'gay', 'love'],
  },
  {
    emoji: '👩‍❤️‍💋‍👩',
    name: 'kiss woman woman',
    keywords: ['kiss', 'lesbian', 'women'],
    category: 'people',
    color: '#FF69B4',
    tags: ['kiss', 'lesbian', 'love'],
  },
  {
    emoji: '💑',
    name: 'couple with heart',
    keywords: ['couple', 'love', 'date'],
    category: 'people',
    color: '#FF69B4',
    tags: ['couple', 'love', 'relationship'],
  },
  {
    emoji: '👨‍❤️‍👨',
    name: 'couple with heart man man',
    keywords: ['couple', 'gay', 'love'],
    category: 'people',
    color: '#87CEEB',
    tags: ['couple', 'gay', 'love'],
  },
  {
    emoji: '👩‍❤️‍👩',
    name: 'couple with heart woman woman',
    keywords: ['couple', 'lesbian', 'love'],
    category: 'people',
    color: '#FF69B4',
    tags: ['couple', 'lesbian', 'love'],
  },
  {
    emoji: '👪',
    name: 'family',
    keywords: ['home', 'parents', 'child'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'parents', 'children'],
  },
  {
    emoji: '👨‍👩‍👦',
    name: 'family man woman boy',
    keywords: ['family', 'man', 'woman', 'boy'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'parents', 'son'],
  },
  {
    emoji: '👨‍👩‍👧',
    name: 'family man woman girl',
    keywords: ['family', 'man', 'woman', 'girl'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'parents', 'daughter'],
  },
  {
    emoji: '👨‍👩‍👧‍👦',
    name: 'family man woman girl boy',
    keywords: ['family', 'man', 'woman', 'children'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'parents', 'children'],
  },
  {
    emoji: '👨‍👩‍👦‍👦',
    name: 'family man woman boy boy',
    keywords: ['family', 'man', 'woman', 'boys'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'parents', 'sons'],
  },
  {
    emoji: '👨‍👩‍👧‍👧',
    name: 'family man woman girl girl',
    keywords: ['family', 'man', 'woman', 'girls'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'parents', 'daughters'],
  },
  {
    emoji: '👨‍👨‍👦',
    name: 'family man man boy',
    keywords: ['family', 'gay', 'parents', 'boy'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'gay-parents', 'son'],
  },
  {
    emoji: '👨‍👨‍👧',
    name: 'family man man girl',
    keywords: ['family', 'gay', 'parents', 'girl'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'gay-parents', 'daughter'],
  },
  {
    emoji: '👨‍👨‍👧‍👦',
    name: 'family man man girl boy',
    keywords: ['family', 'gay', 'parents', 'children'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'gay-parents', 'children'],
  },
  {
    emoji: '👨‍👨‍👦‍👦',
    name: 'family man man boy boy',
    keywords: ['family', 'gay', 'parents', 'boys'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'gay-parents', 'sons'],
  },
  {
    emoji: '👨‍👨‍👧‍👧',
    name: 'family man man girl girl',
    keywords: ['family', 'gay', 'parents', 'girls'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'gay-parents', 'daughters'],
  },
  {
    emoji: '👩‍👩‍👦',
    name: 'family woman woman boy',
    keywords: ['family', 'lesbian', 'parents', 'boy'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'lesbian-parents', 'son'],
  },
  {
    emoji: '👩‍👩‍👧',
    name: 'family woman woman girl',
    keywords: ['family', 'lesbian', 'parents', 'girl'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'lesbian-parents', 'daughter'],
  },
  {
    emoji: '👩‍👩‍👧‍👦',
    name: 'family woman woman girl boy',
    keywords: ['family', 'lesbian', 'parents', 'children'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'lesbian-parents', 'children'],
  },
  {
    emoji: '👩‍👩‍👦‍👦',
    name: 'family woman woman boy boy',
    keywords: ['family', 'lesbian', 'parents', 'boys'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'lesbian-parents', 'sons'],
  },
  {
    emoji: '👩‍👩‍👧‍👧',
    name: 'family woman woman girl girl',
    keywords: ['family', 'lesbian', 'parents', 'girls'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'lesbian-parents', 'daughters'],
  },
  {
    emoji: '👨‍👦',
    name: 'family man boy',
    keywords: ['family', 'father', 'son'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'father', 'son'],
  },
  {
    emoji: '👨‍👦‍👦',
    name: 'family man boy boy',
    keywords: ['family', 'father', 'sons'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'father', 'sons'],
  },
  {
    emoji: '👨‍👧',
    name: 'family man girl',
    keywords: ['family', 'father', 'daughter'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'father', 'daughter'],
  },
  {
    emoji: '👨‍👧‍👦',
    name: 'family man girl boy',
    keywords: ['family', 'father', 'children'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'father', 'children'],
  },
  {
    emoji: '👨‍👧‍👧',
    name: 'family man girl girl',
    keywords: ['family', 'father', 'daughters'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'father', 'daughters'],
  },
  {
    emoji: '👩‍👦',
    name: 'family woman boy',
    keywords: ['family', 'mother', 'son'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'mother', 'son'],
  },
  {
    emoji: '👩‍👦‍👦',
    name: 'family woman boy boy',
    keywords: ['family', 'mother', 'sons'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'mother', 'sons'],
  },
  {
    emoji: '👩‍👧',
    name: 'family woman girl',
    keywords: ['family', 'mother', 'daughter'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'mother', 'daughter'],
  },
  {
    emoji: '👩‍👧‍👦',
    name: 'family woman girl boy',
    keywords: ['family', 'mother', 'children'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'mother', 'children'],
  },
  {
    emoji: '👩‍👧‍👧',
    name: 'family woman girl girl',
    keywords: ['family', 'mother', 'daughters'],
    category: 'people',
    color: '#FFD700',
    tags: ['family', 'mother', 'daughters'],
  },

  // Speech bubble
  {
    emoji: '🗣️',
    name: 'speaking head',
    keywords: ['user', 'person', 'silhouette'],
    category: 'people',
    color: '#696969',
    tags: ['speaking', 'talking', 'communication'],
  },
  {
    emoji: '👤',
    name: 'bust in silhouette',
    keywords: ['user', 'person', 'silhouette'],
    category: 'people',
    color: '#696969',
    tags: ['profile', 'user', 'silhouette'],
  },
  {
    emoji: '👥',
    name: 'busts in silhouette',
    keywords: ['users', 'people', 'silhouette'],
    category: 'people',
    color: '#696969',
    tags: ['group', 'users', 'silhouette'],
  },
  {
    emoji: '🫂',
    name: 'people hugging',
    keywords: ['hug', 'embrace', 'support'],
    category: 'people',
    color: '#87CEEB',
    tags: ['hug', 'support', 'comfort'],
  },
  {
    emoji: '👣',
    name: 'footprints',
    keywords: ['feet', 'footprints', 'tracks'],
    category: 'people',
    color: '#8B4513',
    tags: ['footprints', 'tracks', 'walking'],
  },
] as const satisfies readonly Omit<Emoji, 'sentiment'>[];
