import type { Emoji } from '../../schema';

export const peopleEmojis = [
  // Hand gestures
  {
    emoji: '👋',
    name: 'waving hand',
    keywords: ['wave', 'hello', 'goodbye', 'hi'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🤚',
    name: 'raised back of hand',
    keywords: ['raised', 'hand', 'stop'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🖐️',
    name: 'hand with fingers splayed',
    keywords: ['hand', 'five', 'splayed'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '✋',
    name: 'raised hand',
    keywords: ['hand', 'high five', 'stop'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🖖',
    name: 'vulcan salute',
    keywords: ['vulcan', 'spock', 'star trek'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '👌',
    name: 'OK hand',
    keywords: ['ok', 'perfect', 'yes'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🤌',
    name: 'pinched fingers',
    keywords: ['italian', 'fingers', 'gesture'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🤏',
    name: 'pinching hand',
    keywords: ['tiny', 'small', 'pinch'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '✌️',
    name: 'victory hand',
    keywords: ['peace', 'victory', 'two'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🤞',
    name: 'crossed fingers',
    keywords: ['luck', 'hope', 'cross'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🤟',
    name: 'love-you gesture',
    keywords: ['love', 'rock', 'ily'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🤘',
    name: 'sign of the horns',
    keywords: ['rock', 'metal', 'horns'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🤙',
    name: 'call me hand',
    keywords: ['call', 'shaka', 'hang loose'],
    category: 'people',
    color: '#FDBCB4',
  },

  // Pointing hands
  {
    emoji: '👈',
    name: 'backhand index pointing left',
    keywords: ['point', 'left', 'direction'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '👉',
    name: 'backhand index pointing right',
    keywords: ['point', 'right', 'direction'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '👆',
    name: 'backhand index pointing up',
    keywords: ['point', 'up', 'direction'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🖕',
    name: 'middle finger',
    keywords: ['middle finger', 'rude', 'flip off'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '👇',
    name: 'backhand index pointing down',
    keywords: ['point', 'down', 'direction'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '☝️',
    name: 'index pointing up',
    keywords: ['point', 'up', 'one'],
    category: 'people',
    color: '#FDBCB4',
  },

  // Thumbs
  {
    emoji: '👍',
    name: 'thumbs up',
    keywords: ['thumbs up', 'yes', 'approve', 'like'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '👎',
    name: 'thumbs down',
    keywords: ['thumbs down', 'no', 'disapprove', 'dislike'],
    category: 'people',
    color: '#FDBCB4',
  },

  // Fists and clapping
  {
    emoji: '👊',
    name: 'oncoming fist',
    keywords: ['fist', 'punch', 'bump'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '✊',
    name: 'raised fist',
    keywords: ['fist', 'power', 'solidarity'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🤛',
    name: 'left-facing fist',
    keywords: ['fist', 'left', 'bump'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🤜',
    name: 'right-facing fist',
    keywords: ['fist', 'right', 'bump'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '👏',
    name: 'clapping hands',
    keywords: ['clap', 'applause', 'congrats'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🙌',
    name: 'raising hands',
    keywords: ['raise', 'celebration', 'hooray'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🤝',
    name: 'handshake',
    keywords: ['handshake', 'deal', 'agreement'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🙏',
    name: 'folded hands',
    keywords: ['pray', 'please', 'thank you', 'namaste'],
    category: 'people',
    color: '#FDBCB4',
  },

  // Writing hands
  {
    emoji: '✍️',
    name: 'writing hand',
    keywords: ['write', 'pen', 'sign'],
    category: 'people',
    color: '#FDBCB4',
  },

  // Body parts
  {
    emoji: '💅',
    name: 'nail polish',
    keywords: ['nails', 'beauty', 'manicure'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '🤳',
    name: 'selfie',
    keywords: ['selfie', 'phone', 'camera'],
    category: 'people',
    color: '#FDBCB4',
  },

  // Muscles
  {
    emoji: '💪',
    name: 'flexed biceps',
    keywords: ['muscle', 'strong', 'flex', 'workout'],
    category: 'people',
    color: '#FDBCB4',
  },

  // Legs and feet
  {
    emoji: '🦵',
    name: 'leg',
    keywords: ['leg', 'kick', 'limb'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🦶',
    name: 'foot',
    keywords: ['foot', 'kick', 'step'],
    category: 'people',
    color: '#FDBCB4',
  },

  // Ears and sensory
  {
    emoji: '👂',
    name: 'ear',
    keywords: ['ear', 'hear', 'listen'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🦻',
    name: 'ear with hearing aid',
    keywords: ['ear', 'hearing aid', 'accessibility'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '👃',
    name: 'nose',
    keywords: ['nose', 'smell', 'sniff'],
    category: 'people',
    color: '#FDBCB4',
  },

  // Internal organs
  {
    emoji: '🧠',
    name: 'brain',
    keywords: ['brain', 'smart', 'intelligent'],
    category: 'people',
    color: '#FFB6C1',
  },
  {
    emoji: '🫀',
    name: 'anatomical heart',
    keywords: ['heart', 'organ', 'anatomical'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '🫁',
    name: 'lungs',
    keywords: ['lungs', 'breathe', 'organ'],
    category: 'people',
    color: '#FFB6C1',
  },
  {
    emoji: '🦷',
    name: 'tooth',
    keywords: ['tooth', 'dentist', 'teeth'],
    category: 'people',
    color: '#F5F5F5',
  },
  {
    emoji: '🦴',
    name: 'bone',
    keywords: ['bone', 'skeleton', 'dog'],
    category: 'people',
    color: '#F5F5F5',
  },

  // Eyes
  {
    emoji: '👀',
    name: 'eyes',
    keywords: ['eyes', 'look', 'see', 'watch'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '👁️',
    name: 'eye',
    keywords: ['eye', 'see', 'watch', 'look'],
    category: 'people',
    color: '#4169E1',
  },

  // Mouth
  {
    emoji: '👅',
    name: 'tongue',
    keywords: ['tongue', 'taste', 'lick'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '👄',
    name: 'mouth',
    keywords: ['mouth', 'lips', 'kiss'],
    category: 'people',
    color: '#DC143C',
  },

  // People
  {
    emoji: '👶',
    name: 'baby',
    keywords: ['baby', 'child', 'infant'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🧒',
    name: 'child',
    keywords: ['child', 'kid', 'young'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '👦',
    name: 'boy',
    keywords: ['boy', 'child', 'male'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '👧',
    name: 'girl',
    keywords: ['girl', 'child', 'female'],
    category: 'people',
    color: '#FFB6C1',
  },
  {
    emoji: '🧑',
    name: 'person',
    keywords: ['person', 'adult', 'gender neutral'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '👱',
    name: 'person blond hair',
    keywords: ['blond', 'person', 'hair'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨',
    name: 'man',
    keywords: ['man', 'male', 'adult'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '🧔',
    name: 'person beard',
    keywords: ['beard', 'person', 'bewhiskered'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '👨‍🦰',
    name: 'man red hair',
    keywords: ['man', 'red hair', 'ginger'],
    category: 'people',
    color: '#FF6347',
  },
  {
    emoji: '👨‍🦱',
    name: 'man curly hair',
    keywords: ['man', 'curly', 'hair'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '👨‍🦳',
    name: 'man white hair',
    keywords: ['man', 'white hair', 'old'],
    category: 'people',
    color: '#D3D3D3',
  },
  {
    emoji: '👨‍🦲',
    name: 'man bald',
    keywords: ['man', 'bald', 'no hair'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '👩',
    name: 'woman',
    keywords: ['woman', 'female', 'adult'],
    category: 'people',
    color: '#FFB6C1',
  },
  {
    emoji: '👩‍🦰',
    name: 'woman red hair',
    keywords: ['woman', 'red hair', 'ginger'],
    category: 'people',
    color: '#FF6347',
  },
  {
    emoji: '🧑‍🦰',
    name: 'person red hair',
    keywords: ['person', 'red hair', 'ginger'],
    category: 'people',
    color: '#FF6347',
  },
  {
    emoji: '👩‍🦱',
    name: 'woman curly hair',
    keywords: ['woman', 'curly', 'hair'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '🧑‍🦱',
    name: 'person curly hair',
    keywords: ['person', 'curly', 'hair'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '👩‍🦳',
    name: 'woman white hair',
    keywords: ['woman', 'white hair', 'old'],
    category: 'people',
    color: '#D3D3D3',
  },
  {
    emoji: '🧑‍🦳',
    name: 'person white hair',
    keywords: ['person', 'white hair', 'old'],
    category: 'people',
    color: '#D3D3D3',
  },
  {
    emoji: '👩‍🦲',
    name: 'woman bald',
    keywords: ['woman', 'bald', 'no hair'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '🧑‍🦲',
    name: 'person bald',
    keywords: ['person', 'bald', 'no hair'],
    category: 'people',
    color: '#FDBCB4',
  },
  {
    emoji: '👱‍♀️',
    name: 'woman blond hair',
    keywords: ['woman', 'blond', 'hair'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👱‍♂️',
    name: 'man blond hair',
    keywords: ['man', 'blond', 'hair'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '🧓',
    name: 'older person',
    keywords: ['old', 'elderly', 'grandparent'],
    category: 'people',
    color: '#D3D3D3',
  },
  {
    emoji: '👴',
    name: 'old man',
    keywords: ['old', 'man', 'elderly'],
    category: 'people',
    color: '#D3D3D3',
  },
  {
    emoji: '👵',
    name: 'old woman',
    keywords: ['old', 'woman', 'elderly'],
    category: 'people',
    color: '#D3D3D3',
  },

  // Gestures
  {
    emoji: '🙍',
    name: 'person frowning',
    keywords: ['frown', 'sad', 'person'],
    category: 'people',
    color: '#4682B4',
  },
  {
    emoji: '🙍‍♂️',
    name: 'man frowning',
    keywords: ['man', 'frown', 'sad'],
    category: 'people',
    color: '#4682B4',
  },
  {
    emoji: '🙍‍♀️',
    name: 'woman frowning',
    keywords: ['woman', 'frown', 'sad'],
    category: 'people',
    color: '#4682B4',
  },
  {
    emoji: '🙎',
    name: 'person pouting',
    keywords: ['pout', 'person', 'upset'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '🙎‍♂️',
    name: 'man pouting',
    keywords: ['man', 'pout', 'upset'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '🙎‍♀️',
    name: 'woman pouting',
    keywords: ['woman', 'pout', 'upset'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '🙅',
    name: 'person gesturing no',
    keywords: ['no', 'stop', 'not'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '🙅‍♂️',
    name: 'man gesturing no',
    keywords: ['man', 'no', 'stop'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '🙅‍♀️',
    name: 'woman gesturing no',
    keywords: ['woman', 'no', 'stop'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '🙆',
    name: 'person gesturing OK',
    keywords: ['ok', 'yes', 'agree'],
    category: 'people',
    color: '#90EE90',
  },
  {
    emoji: '🙆‍♂️',
    name: 'man gesturing OK',
    keywords: ['man', 'ok', 'yes'],
    category: 'people',
    color: '#90EE90',
  },
  {
    emoji: '🙆‍♀️',
    name: 'woman gesturing OK',
    keywords: ['woman', 'ok', 'yes'],
    category: 'people',
    color: '#90EE90',
  },
  {
    emoji: '💁',
    name: 'person tipping hand',
    keywords: ['sassy', 'information', 'help'],
    category: 'people',
    color: '#DDA0DD',
  },
  {
    emoji: '💁‍♂️',
    name: 'man tipping hand',
    keywords: ['man', 'sassy', 'information'],
    category: 'people',
    color: '#DDA0DD',
  },
  {
    emoji: '💁‍♀️',
    name: 'woman tipping hand',
    keywords: ['woman', 'sassy', 'information'],
    category: 'people',
    color: '#DDA0DD',
  },
  {
    emoji: '🙋',
    name: 'person raising hand',
    keywords: ['raise', 'hand', 'question'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '🙋‍♂️',
    name: 'man raising hand',
    keywords: ['man', 'raise', 'hand'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '🙋‍♀️',
    name: 'woman raising hand',
    keywords: ['woman', 'raise', 'hand'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '🧏',
    name: 'deaf person',
    keywords: ['deaf', 'ear', 'hearing'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '🧏‍♂️',
    name: 'deaf man',
    keywords: ['deaf', 'man', 'hearing'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '🧏‍♀️',
    name: 'deaf woman',
    keywords: ['deaf', 'woman', 'hearing'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '🙇',
    name: 'person bowing',
    keywords: ['bow', 'respect', 'sorry'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🙇‍♂️',
    name: 'man bowing',
    keywords: ['man', 'bow', 'respect'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🙇‍♀️',
    name: 'woman bowing',
    keywords: ['woman', 'bow', 'respect'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🤦',
    name: 'person facepalming',
    keywords: ['facepalm', 'disbelief', 'exasperation'],
    category: 'people',
    color: '#DEB887',
  },
  {
    emoji: '🤦‍♂️',
    name: 'man facepalming',
    keywords: ['man', 'facepalm', 'disbelief'],
    category: 'people',
    color: '#DEB887',
  },
  {
    emoji: '🤦‍♀️',
    name: 'woman facepalming',
    keywords: ['woman', 'facepalm', 'disbelief'],
    category: 'people',
    color: '#DEB887',
  },
  {
    emoji: '🤷',
    name: 'person shrugging',
    keywords: ['shrug', 'doubt', 'ignorance'],
    category: 'people',
    color: '#DDA0DD',
  },
  {
    emoji: '🤷‍♂️',
    name: 'man shrugging',
    keywords: ['man', 'shrug', 'doubt'],
    category: 'people',
    color: '#DDA0DD',
  },
  {
    emoji: '🤷‍♀️',
    name: 'woman shrugging',
    keywords: ['woman', 'shrug', 'doubt'],
    category: 'people',
    color: '#DDA0DD',
  },

  // Professions
  {
    emoji: '🧑‍⚕️',
    name: 'health worker',
    keywords: ['doctor', 'nurse', 'healthcare'],
    category: 'people',
    color: '#F0F8FF',
  },
  {
    emoji: '👨‍⚕️',
    name: 'man health worker',
    keywords: ['man', 'doctor', 'healthcare'],
    category: 'people',
    color: '#F0F8FF',
  },
  {
    emoji: '👩‍⚕️',
    name: 'woman health worker',
    keywords: ['woman', 'doctor', 'healthcare'],
    category: 'people',
    color: '#F0F8FF',
  },
  {
    emoji: '🧑‍🎓',
    name: 'student',
    keywords: ['student', 'graduate', 'learn'],
    category: 'people',
    color: '#000000',
  },
  {
    emoji: '👨‍🎓',
    name: 'man student',
    keywords: ['man', 'student', 'graduate'],
    category: 'people',
    color: '#000000',
  },
  {
    emoji: '👩‍🎓',
    name: 'woman student',
    keywords: ['woman', 'student', 'graduate'],
    category: 'people',
    color: '#000000',
  },
  {
    emoji: '🧑‍🏫',
    name: 'teacher',
    keywords: ['teacher', 'professor', 'instructor'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '👨‍🏫',
    name: 'man teacher',
    keywords: ['man', 'teacher', 'professor'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '👩‍🏫',
    name: 'woman teacher',
    keywords: ['woman', 'teacher', 'professor'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '🧑‍⚖️',
    name: 'judge',
    keywords: ['judge', 'justice', 'law'],
    category: 'people',
    color: '#000000',
  },
  {
    emoji: '👨‍⚖️',
    name: 'man judge',
    keywords: ['man', 'judge', 'justice'],
    category: 'people',
    color: '#000000',
  },
  {
    emoji: '👩‍⚖️',
    name: 'woman judge',
    keywords: ['woman', 'judge', 'justice'],
    category: 'people',
    color: '#000000',
  },
  {
    emoji: '🧑‍🌾',
    name: 'farmer',
    keywords: ['farmer', 'gardener', 'agriculture'],
    category: 'people',
    color: '#228B22',
  },
  {
    emoji: '👨‍🌾',
    name: 'man farmer',
    keywords: ['man', 'farmer', 'gardener'],
    category: 'people',
    color: '#228B22',
  },
  {
    emoji: '👩‍🌾',
    name: 'woman farmer',
    keywords: ['woman', 'farmer', 'gardener'],
    category: 'people',
    color: '#228B22',
  },
  {
    emoji: '🧑‍🍳',
    name: 'cook',
    keywords: ['cook', 'chef', 'food'],
    category: 'people',
    color: '#F5F5F5',
  },
  {
    emoji: '👨‍🍳',
    name: 'man cook',
    keywords: ['man', 'cook', 'chef'],
    category: 'people',
    color: '#F5F5F5',
  },
  {
    emoji: '👩‍🍳',
    name: 'woman cook',
    keywords: ['woman', 'cook', 'chef'],
    category: 'people',
    color: '#F5F5F5',
  },
  {
    emoji: '🧑‍🔧',
    name: 'mechanic',
    keywords: ['mechanic', 'worker', 'repair'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '👨‍🔧',
    name: 'man mechanic',
    keywords: ['man', 'mechanic', 'worker'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '👩‍🔧',
    name: 'woman mechanic',
    keywords: ['woman', 'mechanic', 'worker'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🧑‍🏭',
    name: 'factory worker',
    keywords: ['factory', 'worker', 'industrial'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '👨‍🏭',
    name: 'man factory worker',
    keywords: ['man', 'factory', 'worker'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '👩‍🏭',
    name: 'woman factory worker',
    keywords: ['woman', 'factory', 'worker'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '🧑‍💼',
    name: 'office worker',
    keywords: ['office', 'business', 'manager'],
    category: 'people',
    color: '#000080',
  },
  {
    emoji: '👨‍💼',
    name: 'man office worker',
    keywords: ['man', 'office', 'business'],
    category: 'people',
    color: '#000080',
  },
  {
    emoji: '👩‍💼',
    name: 'woman office worker',
    keywords: ['woman', 'office', 'business'],
    category: 'people',
    color: '#000080',
  },
  {
    emoji: '🧑‍🔬',
    name: 'scientist',
    keywords: ['scientist', 'biologist', 'researcher'],
    category: 'people',
    color: '#F0F8FF',
  },
  {
    emoji: '👨‍🔬',
    name: 'man scientist',
    keywords: ['man', 'scientist', 'biologist'],
    category: 'people',
    color: '#F0F8FF',
  },
  {
    emoji: '👩‍🔬',
    name: 'woman scientist',
    keywords: ['woman', 'scientist', 'biologist'],
    category: 'people',
    color: '#F0F8FF',
  },
  {
    emoji: '🧑‍💻',
    name: 'technologist',
    keywords: ['coder', 'developer', 'software'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '👨‍💻',
    name: 'man technologist',
    keywords: ['man', 'coder', 'developer'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '👩‍💻',
    name: 'woman technologist',
    keywords: ['woman', 'coder', 'developer'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🧑‍🎤',
    name: 'singer',
    keywords: ['singer', 'rockstar', 'performer'],
    category: 'people',
    color: '#FF1493',
  },
  {
    emoji: '👨‍🎤',
    name: 'man singer',
    keywords: ['man', 'singer', 'rockstar'],
    category: 'people',
    color: '#FF1493',
  },
  {
    emoji: '👩‍🎤',
    name: 'woman singer',
    keywords: ['woman', 'singer', 'rockstar'],
    category: 'people',
    color: '#FF1493',
  },
  {
    emoji: '🧑‍🎨',
    name: 'artist',
    keywords: ['artist', 'painter', 'palette'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '👨‍🎨',
    name: 'man artist',
    keywords: ['man', 'artist', 'painter'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '👩‍🎨',
    name: 'woman artist',
    keywords: ['woman', 'artist', 'painter'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '🧑‍✈️',
    name: 'pilot',
    keywords: ['pilot', 'plane', 'captain'],
    category: 'people',
    color: '#000080',
  },
  {
    emoji: '👨‍✈️',
    name: 'man pilot',
    keywords: ['man', 'pilot', 'plane'],
    category: 'people',
    color: '#000080',
  },
  {
    emoji: '👩‍✈️',
    name: 'woman pilot',
    keywords: ['woman', 'pilot', 'plane'],
    category: 'people',
    color: '#000080',
  },
  {
    emoji: '🧑‍🚀',
    name: 'astronaut',
    keywords: ['astronaut', 'space', 'rocket'],
    category: 'people',
    color: '#F5F5F5',
  },
  {
    emoji: '👨‍🚀',
    name: 'man astronaut',
    keywords: ['man', 'astronaut', 'space'],
    category: 'people',
    color: '#F5F5F5',
  },
  {
    emoji: '👩‍🚀',
    name: 'woman astronaut',
    keywords: ['woman', 'astronaut', 'space'],
    category: 'people',
    color: '#F5F5F5',
  },
  {
    emoji: '🧑‍🚒',
    name: 'firefighter',
    keywords: ['firefighter', 'firetruck', 'rescue'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '👨‍🚒',
    name: 'man firefighter',
    keywords: ['man', 'firefighter', 'firetruck'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '👩‍🚒',
    name: 'woman firefighter',
    keywords: ['woman', 'firefighter', 'firetruck'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '👮',
    name: 'police officer',
    keywords: ['cop', 'police', 'officer'],
    category: 'people',
    color: '#000080',
  },
  {
    emoji: '👮‍♂️',
    name: 'man police officer',
    keywords: ['man', 'cop', 'police'],
    category: 'people',
    color: '#000080',
  },
  {
    emoji: '👮‍♀️',
    name: 'woman police officer',
    keywords: ['woman', 'cop', 'police'],
    category: 'people',
    color: '#000080',
  },
  {
    emoji: '🕵️',
    name: 'detective',
    keywords: ['detective', 'sleuth', 'spy'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '🕵️‍♂️',
    name: 'man detective',
    keywords: ['man', 'detective', 'sleuth'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '🕵️‍♀️',
    name: 'woman detective',
    keywords: ['woman', 'detective', 'sleuth'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '💂',
    name: 'guard',
    keywords: ['guard', 'british', 'soldier'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '💂‍♂️',
    name: 'man guard',
    keywords: ['man', 'guard', 'british'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '💂‍♀️',
    name: 'woman guard',
    keywords: ['woman', 'guard', 'british'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '🥷',
    name: 'ninja',
    keywords: ['ninja', 'fighter', 'hidden'],
    category: 'people',
    color: '#000000',
  },
  {
    emoji: '👷',
    name: 'construction worker',
    keywords: ['construction', 'worker', 'helmet'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👷‍♂️',
    name: 'man construction worker',
    keywords: ['man', 'construction', 'worker'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👷‍♀️',
    name: 'woman construction worker',
    keywords: ['woman', 'construction', 'worker'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '🤴',
    name: 'prince',
    keywords: ['prince', 'crown', 'royal'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👸',
    name: 'princess',
    keywords: ['princess', 'crown', 'royal'],
    category: 'people',
    color: '#FFB6C1',
  },
  {
    emoji: '👳',
    name: 'person wearing turban',
    keywords: ['turban', 'person', 'muslim'],
    category: 'people',
    color: '#F5F5F5',
  },
  {
    emoji: '👳‍♂️',
    name: 'man wearing turban',
    keywords: ['man', 'turban', 'muslim'],
    category: 'people',
    color: '#F5F5F5',
  },
  {
    emoji: '👳‍♀️',
    name: 'woman wearing turban',
    keywords: ['woman', 'turban', 'muslim'],
    category: 'people',
    color: '#F5F5F5',
  },
  {
    emoji: '👲',
    name: 'person with skullcap',
    keywords: ['hat', 'person', 'chinese'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🧕',
    name: 'woman with headscarf',
    keywords: ['hijab', 'headscarf', 'muslim'],
    category: 'people',
    color: '#DDA0DD',
  },
  {
    emoji: '🤵',
    name: 'person in tuxedo',
    keywords: ['groom', 'person', 'suit'],
    category: 'people',
    color: '#000000',
  },
  {
    emoji: '🤵‍♂️',
    name: 'man in tuxedo',
    keywords: ['man', 'groom', 'suit'],
    category: 'people',
    color: '#000000',
  },
  {
    emoji: '🤵‍♀️',
    name: 'woman in tuxedo',
    keywords: ['woman', 'groom', 'suit'],
    category: 'people',
    color: '#000000',
  },
  {
    emoji: '👰',
    name: 'person with veil',
    keywords: ['bride', 'person', 'wedding'],
    category: 'people',
    color: '#F5F5F5',
  },
  {
    emoji: '👰‍♂️',
    name: 'man with veil',
    keywords: ['man', 'bride', 'wedding'],
    category: 'people',
    color: '#F5F5F5',
  },
  {
    emoji: '👰‍♀️',
    name: 'woman with veil',
    keywords: ['woman', 'bride', 'wedding'],
    category: 'people',
    color: '#F5F5F5',
  },
  {
    emoji: '🤰',
    name: 'pregnant woman',
    keywords: ['pregnant', 'woman', 'baby'],
    category: 'people',
    color: '#FFB6C1',
  },
  {
    emoji: '🤱',
    name: 'breast-feeding',
    keywords: ['nursing', 'baby', 'child'],
    category: 'people',
    color: '#FFB6C1',
  },
  {
    emoji: '👩‍🍼',
    name: 'woman feeding baby',
    keywords: ['woman', 'feeding', 'baby'],
    category: 'people',
    color: '#FFB6C1',
  },
  {
    emoji: '👨‍🍼',
    name: 'man feeding baby',
    keywords: ['man', 'feeding', 'baby'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '🧑‍🍼',
    name: 'person feeding baby',
    keywords: ['person', 'feeding', 'baby'],
    category: 'people',
    color: '#FDBCB4',
  },

  // Fantasy characters
  {
    emoji: '👼',
    name: 'baby angel',
    keywords: ['angel', 'cherub', 'face'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '🎅',
    name: 'Santa Claus',
    keywords: ['santa', 'christmas', 'claus'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '🤶',
    name: 'Mrs. Claus',
    keywords: ['mrs claus', 'christmas', 'mother'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '🧑‍🎄',
    name: 'mx claus',
    keywords: ['mx claus', 'christmas', 'person'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '🦸',
    name: 'superhero',
    keywords: ['superhero', 'superpowers', 'hero'],
    category: 'people',
    color: '#FF0000',
  },
  {
    emoji: '🦸‍♂️',
    name: 'man superhero',
    keywords: ['man', 'superhero', 'superpowers'],
    category: 'people',
    color: '#FF0000',
  },
  {
    emoji: '🦸‍♀️',
    name: 'woman superhero',
    keywords: ['woman', 'superhero', 'superpowers'],
    category: 'people',
    color: '#FF0000',
  },
  {
    emoji: '🦹',
    name: 'supervillain',
    keywords: ['supervillain', 'criminal', 'evil'],
    category: 'people',
    color: '#800080',
  },
  {
    emoji: '🦹‍♂️',
    name: 'man supervillain',
    keywords: ['man', 'supervillain', 'criminal'],
    category: 'people',
    color: '#800080',
  },
  {
    emoji: '🦹‍♀️',
    name: 'woman supervillain',
    keywords: ['woman', 'supervillain', 'criminal'],
    category: 'people',
    color: '#800080',
  },
  {
    emoji: '🧙',
    name: 'mage',
    keywords: ['wizard', 'sorcerer', 'witch'],
    category: 'people',
    color: '#4B0082',
  },
  {
    emoji: '🧙‍♂️',
    name: 'man mage',
    keywords: ['man', 'wizard', 'sorcerer'],
    category: 'people',
    color: '#4B0082',
  },
  {
    emoji: '🧙‍♀️',
    name: 'woman mage',
    keywords: ['woman', 'wizard', 'sorcerer'],
    category: 'people',
    color: '#4B0082',
  },
  {
    emoji: '🧚',
    name: 'fairy',
    keywords: ['fairy', 'oberon', 'puck'],
    category: 'people',
    color: '#FFB6C1',
  },
  {
    emoji: '🧚‍♂️',
    name: 'man fairy',
    keywords: ['man', 'fairy', 'oberon'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '🧚‍♀️',
    name: 'woman fairy',
    keywords: ['woman', 'fairy', 'titania'],
    category: 'people',
    color: '#FFB6C1',
  },
  {
    emoji: '🧛',
    name: 'vampire',
    keywords: ['vampire', 'dracula', 'undead'],
    category: 'people',
    color: '#8B0000',
  },
  {
    emoji: '🧛‍♂️',
    name: 'man vampire',
    keywords: ['man', 'vampire', 'dracula'],
    category: 'people',
    color: '#8B0000',
  },
  {
    emoji: '🧛‍♀️',
    name: 'woman vampire',
    keywords: ['woman', 'vampire', 'undead'],
    category: 'people',
    color: '#8B0000',
  },
  {
    emoji: '🧜',
    name: 'merperson',
    keywords: ['mermaid', 'merman', 'merwoman'],
    category: 'people',
    color: '#20B2AA',
  },
  {
    emoji: '🧜‍♂️',
    name: 'merman',
    keywords: ['merman', 'triton', 'man'],
    category: 'people',
    color: '#20B2AA',
  },
  {
    emoji: '🧜‍♀️',
    name: 'mermaid',
    keywords: ['mermaid', 'ariel', 'woman'],
    category: 'people',
    color: '#20B2AA',
  },
  {
    emoji: '🧝',
    name: 'elf',
    keywords: ['elf', 'magical', 'fantasy'],
    category: 'people',
    color: '#228B22',
  },
  {
    emoji: '🧝‍♂️',
    name: 'man elf',
    keywords: ['man', 'elf', 'magical'],
    category: 'people',
    color: '#228B22',
  },
  {
    emoji: '🧝‍♀️',
    name: 'woman elf',
    keywords: ['woman', 'elf', 'magical'],
    category: 'people',
    color: '#228B22',
  },
  {
    emoji: '🧞',
    name: 'genie',
    keywords: ['genie', 'djinn', 'wish'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🧞‍♂️',
    name: 'man genie',
    keywords: ['man', 'genie', 'djinn'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🧞‍♀️',
    name: 'woman genie',
    keywords: ['woman', 'genie', 'djinn'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🧟',
    name: 'zombie',
    keywords: ['zombie', 'undead', 'walking dead'],
    category: 'people',
    color: '#556B2F',
  },
  {
    emoji: '🧟‍♂️',
    name: 'man zombie',
    keywords: ['man', 'zombie', 'undead'],
    category: 'people',
    color: '#556B2F',
  },
  {
    emoji: '🧟‍♀️',
    name: 'woman zombie',
    keywords: ['woman', 'zombie', 'undead'],
    category: 'people',
    color: '#556B2F',
  },

  // Activities
  {
    emoji: '💆',
    name: 'person getting massage',
    keywords: ['massage', 'salon', 'face'],
    category: 'people',
    color: '#DDA0DD',
  },
  {
    emoji: '💆‍♂️',
    name: 'man getting massage',
    keywords: ['man', 'massage', 'salon'],
    category: 'people',
    color: '#DDA0DD',
  },
  {
    emoji: '💆‍♀️',
    name: 'woman getting massage',
    keywords: ['woman', 'massage', 'salon'],
    category: 'people',
    color: '#DDA0DD',
  },
  {
    emoji: '💇',
    name: 'person getting haircut',
    keywords: ['haircut', 'beauty', 'barber'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '💇‍♂️',
    name: 'man getting haircut',
    keywords: ['man', 'haircut', 'barber'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '💇‍♀️',
    name: 'woman getting haircut',
    keywords: ['woman', 'haircut', 'beauty'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '🚶',
    name: 'person walking',
    keywords: ['walk', 'hike', 'move'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🚶‍♂️',
    name: 'man walking',
    keywords: ['man', 'walk', 'hike'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🚶‍♀️',
    name: 'woman walking',
    keywords: ['woman', 'walk', 'hike'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🧍',
    name: 'person standing',
    keywords: ['stand', 'standing', 'person'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '🧍‍♂️',
    name: 'man standing',
    keywords: ['man', 'stand', 'standing'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '🧍‍♀️',
    name: 'woman standing',
    keywords: ['woman', 'stand', 'standing'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '🧎',
    name: 'person kneeling',
    keywords: ['kneel', 'kneeling', 'person'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '🧎‍♂️',
    name: 'man kneeling',
    keywords: ['man', 'kneel', 'kneeling'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '🧎‍♀️',
    name: 'woman kneeling',
    keywords: ['woman', 'kneel', 'kneeling'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '🧑‍🦯',
    name: 'person with white cane',
    keywords: ['blind', 'accessibility', 'person'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '👨‍🦯',
    name: 'man with white cane',
    keywords: ['man', 'blind', 'accessibility'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '👩‍🦯',
    name: 'woman with white cane',
    keywords: ['woman', 'blind', 'accessibility'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '🧑‍🦼',
    name: 'person in motorized wheelchair',
    keywords: ['wheelchair', 'accessibility', 'person'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '👨‍🦼',
    name: 'man in motorized wheelchair',
    keywords: ['man', 'wheelchair', 'accessibility'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '👩‍🦼',
    name: 'woman in motorized wheelchair',
    keywords: ['woman', 'wheelchair', 'accessibility'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🧑‍🦽',
    name: 'person in manual wheelchair',
    keywords: ['wheelchair', 'accessibility', 'person'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '👨‍🦽',
    name: 'man in manual wheelchair',
    keywords: ['man', 'wheelchair', 'accessibility'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '👩‍🦽',
    name: 'woman in manual wheelchair',
    keywords: ['woman', 'wheelchair', 'accessibility'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '🏃',
    name: 'person running',
    keywords: ['run', 'exercise', 'marathon'],
    category: 'people',
    color: '#FF4500',
  },
  {
    emoji: '🏃‍♂️',
    name: 'man running',
    keywords: ['man', 'run', 'exercise'],
    category: 'people',
    color: '#FF4500',
  },
  {
    emoji: '🏃‍♀️',
    name: 'woman running',
    keywords: ['woman', 'run', 'exercise'],
    category: 'people',
    color: '#FF4500',
  },
  {
    emoji: '💃',
    name: 'woman dancing',
    keywords: ['dance', 'dancer', 'dress'],
    category: 'people',
    color: '#DC143C',
  },
  {
    emoji: '🕺',
    name: 'man dancing',
    keywords: ['dance', 'dancer', 'man'],
    category: 'people',
    color: '#800080',
  },
  {
    emoji: '🕴️',
    name: 'person in suit levitating',
    keywords: ['suit', 'levitate', 'hover'],
    category: 'people',
    color: '#000000',
  },
  {
    emoji: '👯',
    name: 'people with bunny ears',
    keywords: ['bunny', 'dancer', 'partying'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '👯‍♂️',
    name: 'men with bunny ears',
    keywords: ['men', 'bunny', 'dancer'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '👯‍♀️',
    name: 'women with bunny ears',
    keywords: ['women', 'bunny', 'dancer'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '🧖',
    name: 'person in steamy room',
    keywords: ['sauna', 'steam', 'spa'],
    category: 'people',
    color: '#FFE4B5',
  },
  {
    emoji: '🧖‍♂️',
    name: 'man in steamy room',
    keywords: ['man', 'sauna', 'steam'],
    category: 'people',
    color: '#FFE4B5',
  },
  {
    emoji: '🧖‍♀️',
    name: 'woman in steamy room',
    keywords: ['woman', 'sauna', 'steam'],
    category: 'people',
    color: '#FFE4B5',
  },
  {
    emoji: '🧗',
    name: 'person climbing',
    keywords: ['climb', 'bouldering', 'climber'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '🧗‍♂️',
    name: 'man climbing',
    keywords: ['man', 'climb', 'bouldering'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '🧗‍♀️',
    name: 'woman climbing',
    keywords: ['woman', 'climb', 'bouldering'],
    category: 'people',
    color: '#696969',
  },

  // Sports people
  {
    emoji: '🤺',
    name: 'person fencing',
    keywords: ['fencer', 'fencing', 'sword'],
    category: 'people',
    color: '#C0C0C0',
  },
  {
    emoji: '🏇',
    name: 'horse racing',
    keywords: ['jockey', 'racehorse', 'racing'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '⛷️',
    name: 'skier',
    keywords: ['ski', 'snow', 'winter'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🏂',
    name: 'snowboarder',
    keywords: ['snowboard', 'snow', 'winter'],
    category: 'people',
    color: '#FF4500',
  },
  {
    emoji: '🏌️',
    name: 'person golfing',
    keywords: ['golf', 'ball', 'golfer'],
    category: 'people',
    color: '#228B22',
  },
  {
    emoji: '🏌️‍♂️',
    name: 'man golfing',
    keywords: ['man', 'golf', 'ball'],
    category: 'people',
    color: '#228B22',
  },
  {
    emoji: '🏌️‍♀️',
    name: 'woman golfing',
    keywords: ['woman', 'golf', 'ball'],
    category: 'people',
    color: '#228B22',
  },
  {
    emoji: '🏄',
    name: 'person surfing',
    keywords: ['surf', 'surfboard', 'surfer'],
    category: 'people',
    color: '#00CED1',
  },
  {
    emoji: '🏄‍♂️',
    name: 'man surfing',
    keywords: ['man', 'surf', 'surfboard'],
    category: 'people',
    color: '#00CED1',
  },
  {
    emoji: '🏄‍♀️',
    name: 'woman surfing',
    keywords: ['woman', 'surf', 'surfboard'],
    category: 'people',
    color: '#00CED1',
  },
  {
    emoji: '🚣',
    name: 'person rowing boat',
    keywords: ['row', 'boat', 'rowboat'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '🚣‍♂️',
    name: 'man rowing boat',
    keywords: ['man', 'row', 'boat'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '🚣‍♀️',
    name: 'woman rowing boat',
    keywords: ['woman', 'row', 'boat'],
    category: 'people',
    color: '#8B4513',
  },
  {
    emoji: '🏊',
    name: 'person swimming',
    keywords: ['swim', 'swimmer', 'pool'],
    category: 'people',
    color: '#00CED1',
  },
  {
    emoji: '🏊‍♂️',
    name: 'man swimming',
    keywords: ['man', 'swim', 'swimmer'],
    category: 'people',
    color: '#00CED1',
  },
  {
    emoji: '🏊‍♀️',
    name: 'woman swimming',
    keywords: ['woman', 'swim', 'swimmer'],
    category: 'people',
    color: '#00CED1',
  },
  {
    emoji: '⛹️',
    name: 'person bouncing ball',
    keywords: ['ball', 'dribble', 'basketball'],
    category: 'people',
    color: '#FF4500',
  },
  {
    emoji: '⛹️‍♂️',
    name: 'man bouncing ball',
    keywords: ['man', 'ball', 'basketball'],
    category: 'people',
    color: '#FF4500',
  },
  {
    emoji: '⛹️‍♀️',
    name: 'woman bouncing ball',
    keywords: ['woman', 'ball', 'basketball'],
    category: 'people',
    color: '#FF4500',
  },
  {
    emoji: '🏋️',
    name: 'person lifting weights',
    keywords: ['lifter', 'weight', 'weightlifter'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '🏋️‍♂️',
    name: 'man lifting weights',
    keywords: ['man', 'lifter', 'weight'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '🏋️‍♀️',
    name: 'woman lifting weights',
    keywords: ['woman', 'lifter', 'weight'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '🚴',
    name: 'person biking',
    keywords: ['bike', 'bicycle', 'cyclist'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🚴‍♂️',
    name: 'man biking',
    keywords: ['man', 'bike', 'bicycle'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🚴‍♀️',
    name: 'woman biking',
    keywords: ['woman', 'bike', 'bicycle'],
    category: 'people',
    color: '#4169E1',
  },
  {
    emoji: '🚵',
    name: 'person mountain biking',
    keywords: ['bike', 'bicycle', 'mountain'],
    category: 'people',
    color: '#228B22',
  },
  {
    emoji: '🚵‍♂️',
    name: 'man mountain biking',
    keywords: ['man', 'bike', 'mountain'],
    category: 'people',
    color: '#228B22',
  },
  {
    emoji: '🚵‍♀️',
    name: 'woman mountain biking',
    keywords: ['woman', 'bike', 'mountain'],
    category: 'people',
    color: '#228B22',
  },
  {
    emoji: '🤸',
    name: 'person cartwheeling',
    keywords: ['cartwheel', 'gymnast', 'gymnastics'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '🤸‍♂️',
    name: 'man cartwheeling',
    keywords: ['man', 'cartwheel', 'gymnast'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '🤸‍♀️',
    name: 'woman cartwheeling',
    keywords: ['woman', 'cartwheel', 'gymnast'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '🤼',
    name: 'people wrestling',
    keywords: ['wrestle', 'wrestler', 'wrestling'],
    category: 'people',
    color: '#DAA520',
  },
  {
    emoji: '🤼‍♂️',
    name: 'men wrestling',
    keywords: ['men', 'wrestle', 'wrestler'],
    category: 'people',
    color: '#DAA520',
  },
  {
    emoji: '🤼‍♀️',
    name: 'women wrestling',
    keywords: ['women', 'wrestle', 'wrestler'],
    category: 'people',
    color: '#DAA520',
  },
  {
    emoji: '🤽',
    name: 'person playing water polo',
    keywords: ['water', 'polo', 'sport'],
    category: 'people',
    color: '#00CED1',
  },
  {
    emoji: '🤽‍♂️',
    name: 'man playing water polo',
    keywords: ['man', 'water', 'polo'],
    category: 'people',
    color: '#00CED1',
  },
  {
    emoji: '🤽‍♀️',
    name: 'woman playing water polo',
    keywords: ['woman', 'water', 'polo'],
    category: 'people',
    color: '#00CED1',
  },
  {
    emoji: '🤾',
    name: 'person playing handball',
    keywords: ['ball', 'handball', 'sport'],
    category: 'people',
    color: '#FF4500',
  },
  {
    emoji: '🤾‍♂️',
    name: 'man playing handball',
    keywords: ['man', 'ball', 'handball'],
    category: 'people',
    color: '#FF4500',
  },
  {
    emoji: '🤾‍♀️',
    name: 'woman playing handball',
    keywords: ['woman', 'ball', 'handball'],
    category: 'people',
    color: '#FF4500',
  },
  {
    emoji: '🤹',
    name: 'person juggling',
    keywords: ['juggle', 'balance', 'skill'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '🤹‍♂️',
    name: 'man juggling',
    keywords: ['man', 'juggle', 'balance'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '🤹‍♀️',
    name: 'woman juggling',
    keywords: ['woman', 'juggle', 'balance'],
    category: 'people',
    color: '#FFD700',
  },

  // Yoga and meditation
  {
    emoji: '🧘',
    name: 'person in lotus position',
    keywords: ['yoga', 'meditation', 'serenity'],
    category: 'people',
    color: '#DDA0DD',
  },
  {
    emoji: '🧘‍♂️',
    name: 'man in lotus position',
    keywords: ['man', 'yoga', 'meditation'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '🧘‍♀️',
    name: 'woman in lotus position',
    keywords: ['woman', 'yoga', 'meditation'],
    category: 'people',
    color: '#DDA0DD',
  },

  // Couple and family
  {
    emoji: '👫',
    name: 'woman and man holding hands',
    keywords: ['couple', 'date', 'dating'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '👬',
    name: 'men holding hands',
    keywords: ['couple', 'gay', 'men'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '👭',
    name: 'women holding hands',
    keywords: ['couple', 'lesbian', 'women'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '💏',
    name: 'kiss',
    keywords: ['kiss', 'lips', 'couple'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '👨‍❤️‍💋‍👨',
    name: 'kiss man man',
    keywords: ['kiss', 'gay', 'men'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '👩‍❤️‍💋‍👩',
    name: 'kiss woman woman',
    keywords: ['kiss', 'lesbian', 'women'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '💑',
    name: 'couple with heart',
    keywords: ['couple', 'love', 'date'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '👨‍❤️‍👨',
    name: 'couple with heart man man',
    keywords: ['couple', 'gay', 'love'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '👩‍❤️‍👩',
    name: 'couple with heart woman woman',
    keywords: ['couple', 'lesbian', 'love'],
    category: 'people',
    color: '#FF69B4',
  },
  {
    emoji: '👪',
    name: 'family',
    keywords: ['home', 'parents', 'child'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👩‍👦',
    name: 'family man woman boy',
    keywords: ['family', 'man', 'woman', 'boy'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👩‍👧',
    name: 'family man woman girl',
    keywords: ['family', 'man', 'woman', 'girl'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👩‍👧‍👦',
    name: 'family man woman girl boy',
    keywords: ['family', 'man', 'woman', 'children'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👩‍👦‍👦',
    name: 'family man woman boy boy',
    keywords: ['family', 'man', 'woman', 'boys'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👩‍👧‍👧',
    name: 'family man woman girl girl',
    keywords: ['family', 'man', 'woman', 'girls'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👨‍👦',
    name: 'family man man boy',
    keywords: ['family', 'gay', 'parents', 'boy'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👨‍👧',
    name: 'family man man girl',
    keywords: ['family', 'gay', 'parents', 'girl'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👨‍👧‍👦',
    name: 'family man man girl boy',
    keywords: ['family', 'gay', 'parents', 'children'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👨‍👦‍👦',
    name: 'family man man boy boy',
    keywords: ['family', 'gay', 'parents', 'boys'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👨‍👧‍👧',
    name: 'family man man girl girl',
    keywords: ['family', 'gay', 'parents', 'girls'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👩‍👩‍👦',
    name: 'family woman woman boy',
    keywords: ['family', 'lesbian', 'parents', 'boy'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👩‍👩‍👧',
    name: 'family woman woman girl',
    keywords: ['family', 'lesbian', 'parents', 'girl'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👩‍👩‍👧‍👦',
    name: 'family woman woman girl boy',
    keywords: ['family', 'lesbian', 'parents', 'children'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👩‍👩‍👦‍👦',
    name: 'family woman woman boy boy',
    keywords: ['family', 'lesbian', 'parents', 'boys'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👩‍👩‍👧‍👧',
    name: 'family woman woman girl girl',
    keywords: ['family', 'lesbian', 'parents', 'girls'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👦',
    name: 'family man boy',
    keywords: ['family', 'father', 'son'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👦‍👦',
    name: 'family man boy boy',
    keywords: ['family', 'father', 'sons'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👧',
    name: 'family man girl',
    keywords: ['family', 'father', 'daughter'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👧‍👦',
    name: 'family man girl boy',
    keywords: ['family', 'father', 'children'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👨‍👧‍👧',
    name: 'family man girl girl',
    keywords: ['family', 'father', 'daughters'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👩‍👦',
    name: 'family woman boy',
    keywords: ['family', 'mother', 'son'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👩‍👦‍👦',
    name: 'family woman boy boy',
    keywords: ['family', 'mother', 'sons'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👩‍👧',
    name: 'family woman girl',
    keywords: ['family', 'mother', 'daughter'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👩‍👧‍👦',
    name: 'family woman girl boy',
    keywords: ['family', 'mother', 'children'],
    category: 'people',
    color: '#FFD700',
  },
  {
    emoji: '👩‍👧‍👧',
    name: 'family woman girl girl',
    keywords: ['family', 'mother', 'daughters'],
    category: 'people',
    color: '#FFD700',
  },

  // Speech bubble
  {
    emoji: '🗣️',
    name: 'speaking head',
    keywords: ['user', 'person', 'silhouette'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '👤',
    name: 'bust in silhouette',
    keywords: ['user', 'person', 'silhouette'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '👥',
    name: 'busts in silhouette',
    keywords: ['users', 'people', 'silhouette'],
    category: 'people',
    color: '#696969',
  },
  {
    emoji: '🫂',
    name: 'people hugging',
    keywords: ['hug', 'embrace', 'support'],
    category: 'people',
    color: '#87CEEB',
  },
  {
    emoji: '👣',
    name: 'footprints',
    keywords: ['feet', 'footprints', 'tracks'],
    category: 'people',
    color: '#8B4513',
  },
] as const satisfies readonly Emoji[];
