import type { Emoji } from '../../schema';

// Generated from OpenMoji dataset - 169 emojis
// Unicode versions up to 15.1 + OpenMoji extras
export const smileysEmojisAll: Emoji[] = [
  {
    emoji: '😀',
    name: 'grinning face',
    keywords: [
      'cheerful',
      'cheery',
      'face',
      'grin',
      'grinning',
      'happy',
      'laugh',
      'nice',
      'smile',
      'smiling',
      'teeth',
    ],
    category: 'smileys',
    subcategory: 'face-smiling',
    unicode: '1F600',
    version: '1',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😃',
    name: 'grinning face with big eyes',
    keywords: [
      'awesome',
      'big',
      'eyes',
      'face',
      'grin',
      'grinning',
      'happy',
      'mouth',
      'open',
      'smile',
      'smiling',
      'teeth',
      'yay',
    ],
    category: 'smileys',
    subcategory: 'face-smiling',
    unicode: '1F603',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😄',
    name: 'grinning face with smiling eyes',
    keywords: [
      'eye',
      'eyes',
      'face',
      'grin',
      'grinning',
      'happy',
      'laugh',
      'lol',
      'mouth',
      'open',
      'smile',
      'smiling',
    ],
    category: 'smileys',
    subcategory: 'face-smiling',
    unicode: '1F604',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😁',
    name: 'beaming face with smiling eyes',
    keywords: [
      'beaming',
      'eye',
      'eyes',
      'face',
      'grin',
      'grinning',
      'happy',
      'nice',
      'smile',
      'smiling',
      'teeth',
    ],
    category: 'smileys',
    subcategory: 'face-smiling',
    unicode: '1F601',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😆',
    name: 'grinning squinting face',
    keywords: [
      'closed',
      'eyes',
      'face',
      'grinning',
      'haha',
      'hahaha',
      'happy',
      'laugh',
      'lol',
      'mouth',
      'open',
      'rofl',
      'smile',
      'smiling',
      'squinting',
    ],
    category: 'smileys',
    subcategory: 'face-smiling',
    unicode: '1F606',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😅',
    name: 'grinning face with sweat',
    keywords: [
      'cold',
      'dejected',
      'excited',
      'face',
      'grinning',
      'mouth',
      'nervous',
      'open',
      'smile',
      'smiling',
      'stress',
      'stressed',
      'sweat',
    ],
    category: 'smileys',
    subcategory: 'face-smiling',
    unicode: '1F605',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🤣',
    name: 'rolling on the floor laughing',
    keywords: [
      'crying',
      'face',
      'floor',
      'funny',
      'haha',
      'happy',
      'hehe',
      'hilarious',
      'joy',
      'laugh',
      'lmao',
      'lol',
      'rofl',
      'roflmao',
      'rolling',
      'tear',
    ],
    category: 'smileys',
    subcategory: 'face-smiling',
    unicode: '1F923',
    version: '3',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😂',
    name: 'face with tears of joy',
    keywords: [
      'crying',
      'face',
      'feels',
      'funny',
      'haha',
      'happy',
      'hehe',
      'hilarious',
      'joy',
      'laugh',
      'lmao',
      'lol',
      'rofl',
      'roflmao',
      'tear',
    ],
    category: 'smileys',
    subcategory: 'face-smiling',
    unicode: '1F602',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🙂',
    name: 'slightly smiling face',
    keywords: ['face', 'happy', 'slightly', 'smile', 'smiling'],
    category: 'smileys',
    subcategory: 'face-smiling',
    unicode: '1F642',
    version: '1',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🙃',
    name: 'upside-down face',
    keywords: ['face', 'hehe', 'smile', 'upside-down'],
    category: 'smileys',
    subcategory: 'face-smiling',
    unicode: '1F643',
    version: '1',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🫠',
    name: 'melting face',
    keywords: [
      'disappear',
      'dissolve',
      'embarrassed',
      'face',
      'haha',
      'heat',
      'hot',
      'liquid',
      'lol',
      'melt',
      'melting',
      'sarcasm',
      'sarcastic',
    ],
    category: 'smileys',
    subcategory: 'face-smiling',
    unicode: '1FAE0',
    version: '14',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😉',
    name: 'winking face',
    keywords: [
      'face',
      'flirt',
      'heartbreaker',
      'sexy',
      'slide',
      'tease',
      'wink',
      'winking',
      'winks',
    ],
    category: 'smileys',
    subcategory: 'face-smiling',
    unicode: '1F609',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😊',
    name: 'smiling face with smiling eyes',
    keywords: [
      'blush',
      'eye',
      'eyes',
      'face',
      'glad',
      'satisfied',
      'smile',
      'smiling',
    ],
    category: 'smileys',
    subcategory: 'face-smiling',
    unicode: '1F60A',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😇',
    name: 'smiling face with halo',
    keywords: [
      'angel',
      'angelic',
      'angels',
      'blessed',
      'face',
      'fairy',
      'fairytale',
      'fantasy',
      'halo',
      'happy',
      'innocent',
      'peaceful',
      'smile',
      'smiling',
      'spirit',
      'tale',
    ],
    category: 'smileys',
    subcategory: 'face-smiling',
    unicode: '1F607',
    version: '1',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🥰',
    name: 'smiling face with hearts',
    keywords: [
      '3',
      'adore',
      'crush',
      'face',
      'heart',
      'hearts',
      'ily',
      'love',
      'romance',
      'smile',
      'smiling',
      'you',
    ],
    category: 'smileys',
    subcategory: 'face-affection',
    unicode: '1F970',
    version: '11',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😍',
    name: 'smiling face with heart-eyes',
    keywords: [
      '143',
      'bae',
      'eye',
      'face',
      'feels',
      'heart-eyes',
      'hearts',
      'ily',
      'kisses',
      'love',
      'romance',
      'romantic',
      'smile',
      'xoxo',
    ],
    category: 'smileys',
    subcategory: 'face-affection',
    unicode: '1F60D',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🤩',
    name: 'star-struck',
    keywords: [
      'excited',
      'eyes',
      'face',
      'grinning',
      'smile',
      'star',
      'starry-eyed',
      'wow',
    ],
    category: 'smileys',
    subcategory: 'face-affection',
    unicode: '1F929',
    version: '5',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😘',
    name: 'face blowing a kiss',
    keywords: [
      'adorbs',
      'bae',
      'blowing',
      'face',
      'flirt',
      'heart',
      'ily',
      'kiss',
      'love',
      'lover',
      'miss',
      'muah',
      'romantic',
      'smooch',
      'xoxo',
      'you',
    ],
    category: 'smileys',
    subcategory: 'face-affection',
    unicode: '1F618',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😗',
    name: 'kissing face',
    keywords: [
      '143',
      'date',
      'dating',
      'face',
      'flirt',
      'ily',
      'kiss',
      'love',
      'smooch',
      'smooches',
      'xoxo',
      'you',
    ],
    category: 'smileys',
    subcategory: 'face-affection',
    unicode: '1F617',
    version: '1',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '☺️',
    name: 'smiling face',
    keywords: ['face', 'happy', 'outlined', 'relaxed', 'smile', 'smiling'],
    category: 'smileys',
    subcategory: 'face-affection',
    unicode: '263A',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😚',
    name: 'kissing face with closed eyes',
    keywords: [
      '143',
      'bae',
      'blush',
      'closed',
      'date',
      'dating',
      'eye',
      'eyes',
      'face',
      'flirt',
      'ily',
      'kisses',
      'kissing',
      'smooches',
      'xoxo',
    ],
    category: 'smileys',
    subcategory: 'face-affection',
    unicode: '1F61A',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😙',
    name: 'kissing face with smiling eyes',
    keywords: [
      '143',
      'closed',
      'date',
      'dating',
      'eye',
      'eyes',
      'face',
      'flirt',
      'ily',
      'kiss',
      'kisses',
      'kissing',
      'love',
      'night',
      'smile',
      'smiling',
    ],
    category: 'smileys',
    subcategory: 'face-affection',
    unicode: '1F619',
    version: '1',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🥲',
    name: 'smiling face with tear',
    keywords: [
      'face',
      'glad',
      'grateful',
      'happy',
      'joy',
      'pain',
      'proud',
      'relieved',
      'smile',
      'smiley',
      'smiling',
      'tear',
      'touched',
    ],
    category: 'smileys',
    subcategory: 'face-affection',
    unicode: '1F972',
    version: '13',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😋',
    name: 'face savoring food',
    keywords: [
      'delicious',
      'eat',
      'face',
      'food',
      'full',
      'hungry',
      'savor',
      'smile',
      'smiling',
      'tasty',
      'um',
      'yum',
      'yummy',
    ],
    category: 'smileys',
    subcategory: 'face-tongue',
    unicode: '1F60B',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😛',
    name: 'face with tongue',
    keywords: [
      'awesome',
      'cool',
      'face',
      'nice',
      'party',
      'stuck-out',
      'sweet',
      'tongue',
    ],
    category: 'smileys',
    subcategory: 'face-tongue',
    unicode: '1F61B',
    version: '1',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😜',
    name: 'winking face with tongue',
    keywords: [
      'crazy',
      'epic',
      'eye',
      'face',
      'funny',
      'joke',
      'loopy',
      'nutty',
      'party',
      'stuck-out',
      'tongue',
      'wacky',
      'weirdo',
      'wink',
      'winking',
      'yolo',
    ],
    category: 'smileys',
    subcategory: 'face-tongue',
    unicode: '1F61C',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🤪',
    name: 'zany face',
    keywords: [
      'crazy',
      'eye',
      'eyes',
      'face',
      'goofy',
      'large',
      'small',
      'zany',
    ],
    category: 'smileys',
    subcategory: 'face-tongue',
    unicode: '1F92A',
    version: '5',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😝',
    name: 'squinting face with tongue',
    keywords: [
      'closed',
      'eye',
      'eyes',
      'face',
      'gross',
      'horrible',
      'omg',
      'squinting',
      'stuck-out',
      'taste',
      'tongue',
      'whatever',
      'yolo',
    ],
    category: 'smileys',
    subcategory: 'face-tongue',
    unicode: '1F61D',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🤑',
    name: 'money-mouth face',
    keywords: ['face', 'money', 'money-mouth', 'mouth', 'paid'],
    category: 'smileys',
    subcategory: 'face-tongue',
    unicode: '1F911',
    version: '1',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🤗',
    name: 'smiling face with open hands',
    keywords: ['face', 'hands', 'hug', 'hugging', 'open', 'smiling'],
    category: 'smileys',
    subcategory: 'face-hand',
    unicode: '1F917',
    version: '1',
    color: '#DDA0DD',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🤭',
    name: 'face with hand over mouth',
    keywords: [
      'face',
      'giggle',
      'giggling',
      'hand',
      'mouth',
      'oops',
      'realization',
      'secret',
      'shock',
      'sudden',
      'surprise',
      'whoops',
    ],
    category: 'smileys',
    subcategory: 'face-hand',
    unicode: '1F92D',
    version: '5',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫢',
    name: 'face with open eyes and hand over mouth',
    keywords: [
      'amazement',
      'awe',
      'disbelief',
      'embarrass',
      'eyes',
      'face',
      'gasp',
      'hand',
      'mouth',
      'omg',
      'open',
      'over',
      'quiet',
      'scared',
      'shock',
      'surprise',
    ],
    category: 'smileys',
    subcategory: 'face-hand',
    unicode: '1FAE2',
    version: '14',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫣',
    name: 'face with peeking eye',
    keywords: [
      'captivated',
      'embarrass',
      'eye',
      'face',
      'hide',
      'hiding',
      'peek',
      'peeking',
      'peep',
      'scared',
      'shy',
      'stare',
    ],
    category: 'smileys',
    subcategory: 'face-hand',
    unicode: '1FAE3',
    version: '14',
    color: '#DDA0DD',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🤫',
    name: 'shushing face',
    keywords: ['face', 'quiet', 'shh', 'shush', 'shushing'],
    category: 'smileys',
    subcategory: 'face-hand',
    unicode: '1F92B',
    version: '5',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🤔',
    name: 'thinking face',
    keywords: [
      'chin',
      'consider',
      'face',
      'hmm',
      'ponder',
      'pondering',
      'thinking',
      'wondering',
    ],
    category: 'smileys',
    subcategory: 'face-hand',
    unicode: '1F914',
    version: '1',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫡',
    name: 'saluting face',
    keywords: [
      'face',
      'good',
      'luck',
      'ma’am',
      'ok',
      'respect',
      'salute',
      'saluting',
      'sir',
      'troops',
      'yes',
    ],
    category: 'smileys',
    subcategory: 'face-hand',
    unicode: '1FAE1',
    version: '14',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🤐',
    name: 'zipper-mouth face',
    keywords: [
      'face',
      'keep',
      'mouth',
      'quiet',
      'secret',
      'shut',
      'zip',
      'zipper',
      'zipper-mouth',
    ],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1F910',
    version: '1',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🤨',
    name: 'face with raised eyebrow',
    keywords: [
      'disapproval',
      'disbelief',
      'distrust',
      'emoji',
      'eyebrow',
      'face',
      'hmm',
      'mild',
      'raised',
      'skeptic',
      'skeptical',
      'skepticism',
      'surprise',
      'what',
    ],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1F928',
    version: '5',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😐️',
    name: 'neutral face',
    keywords: [
      'awkward',
      'blank',
      'deadpan',
      'expressionless',
      'face',
      'fine',
      'jealous',
      'meh',
      'neutral',
      'oh',
      'shade',
      'straight',
      'unamused',
      'unhappy',
      'unimpressed',
      'whatever',
    ],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1F610',
    version: '0.7',
    color: '#C0C0C0',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😑',
    name: 'expressionless face',
    keywords: [
      'awkward',
      'dead',
      'expressionless',
      'face',
      'fine',
      'inexpressive',
      'jealous',
      'meh',
      'not',
      'oh',
      'omg',
      'straight',
      'uh',
      'unhappy',
      'unimpressed',
      'whatever',
    ],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1F611',
    version: '1',
    color: '#C0C0C0',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😶',
    name: 'face without mouth',
    keywords: [
      'awkward',
      'blank',
      'expressionless',
      'face',
      'mouth',
      'mouthless',
      'mute',
      'quiet',
      'secret',
      'silence',
      'silent',
      'speechless',
    ],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1F636',
    version: '1',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫥',
    name: 'dotted line face',
    keywords: [
      'depressed',
      'disappear',
      'dotted',
      'face',
      'hidden',
      'hide',
      'introvert',
      'invisible',
      'line',
      'meh',
      'whatever',
      'wtv',
    ],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1FAE5',
    version: '14',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😶‍🌫️',
    name: 'face in clouds',
    keywords: ['absentminded', 'clouds', 'face', 'fog', 'head'],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1F636 200D 1F32B FE0F',
    version: '13.1',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😏',
    name: 'smirking face',
    keywords: [
      'boss',
      'dapper',
      'face',
      'flirt',
      'homie',
      'kidding',
      'leer',
      'shade',
      'slick',
      'sly',
      'smirk',
      'smug',
      'snicker',
      'suave',
      'suspicious',
      'swag',
    ],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1F60F',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😒',
    name: 'unamused face',
    keywords: [
      '...',
      'bored',
      'face',
      'fine',
      'jealous',
      'jel',
      'jelly',
      'pissed',
      'smh',
      'ugh',
      'uhh',
      'unamused',
      'unhappy',
      'weird',
      'whatever',
    ],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1F612',
    version: '0.6',
    color: '#C0C0C0',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🙄',
    name: 'face with rolling eyes',
    keywords: [
      'eyeroll',
      'eyes',
      'face',
      'rolling',
      'shade',
      'ugh',
      'whatever',
    ],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1F644',
    version: '1',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😬',
    name: 'grimacing face',
    keywords: [
      'awk',
      'awkward',
      'dentist',
      'face',
      'grimace',
      'grimacing',
      'grinning',
      'smile',
      'smiling',
    ],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1F62C',
    version: '1',
    color: '#C0C0C0',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😮‍💨',
    name: 'face exhaling',
    keywords: [
      'blow',
      'blowing',
      'exhale',
      'exhaling',
      'exhausted',
      'face',
      'gasp',
      'groan',
      'relief',
      'sigh',
      'smiley',
      'smoke',
      'whisper',
      'whistle',
    ],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1F62E 200D 1F4A8',
    version: '13.1',
    color: '#C0C0C0',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🤥',
    name: 'lying face',
    keywords: ['face', 'liar', 'lie', 'lying', 'pinocchio'],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1F925',
    version: '3',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫨',
    name: 'shaking face',
    keywords: [
      'crazy',
      'daze',
      'earthquake',
      'face',
      'omg',
      'panic',
      'shaking',
      'shock',
      'surprise',
      'vibrate',
      'whoa',
      'wow',
    ],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1FAE8',
    version: '15',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🙂‍↔️',
    name: 'head shaking horizontally',
    keywords: ['head', 'horizontally', 'no', 'shake', 'shaking'],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1F642 200D 2194 FE0F',
    version: '15.1',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🙂‍↕️',
    name: 'head shaking vertically',
    keywords: ['head', 'nod', 'shaking', 'vertically', 'yes'],
    category: 'smileys',
    subcategory: 'face-neutral-skeptical',
    unicode: '1F642 200D 2195 FE0F',
    version: '15.1',
    color: '#C0C0C0',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😌',
    name: 'relieved face',
    keywords: ['calm', 'face', 'peace', 'relief', 'relieved', 'zen'],
    category: 'smileys',
    subcategory: 'face-sleepy',
    unicode: '1F60C',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😔',
    name: 'pensive face',
    keywords: [
      'awful',
      'bored',
      'dejected',
      'died',
      'disappointed',
      'face',
      'losing',
      'lost',
      'pensive',
      'sad',
      'sucks',
    ],
    category: 'smileys',
    subcategory: 'face-sleepy',
    unicode: '1F614',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'negative' as const,
  },
  {
    emoji: '😪',
    name: 'sleepy face',
    keywords: [
      'crying',
      'face',
      'good',
      'night',
      'sad',
      'sleep',
      'sleeping',
      'sleepy',
      'tired',
    ],
    category: 'smileys',
    subcategory: 'face-sleepy',
    unicode: '1F62A',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🤤',
    name: 'drooling face',
    keywords: ['drooling', 'face'],
    category: 'smileys',
    subcategory: 'face-sleepy',
    unicode: '1F924',
    version: '3',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😴',
    name: 'sleeping face',
    keywords: [
      'bed',
      'bedtime',
      'face',
      'good',
      'goodnight',
      'nap',
      'night',
      'sleep',
      'sleeping',
      'tired',
      'whatever',
      'yawn',
      'zzz',
    ],
    category: 'smileys',
    subcategory: 'face-sleepy',
    unicode: '1F634',
    version: '1',
    color: '#87CEEB',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🫩',
    name: 'face with bags under eyes',
    keywords: [
      'bags',
      'bored',
      'exhausted',
      'eyes',
      'face',
      'fatigued',
      'late',
      'sleepy',
      'tired',
      'weary',
    ],
    category: 'smileys',
    subcategory: 'face-sleepy',
    unicode: '1FAE9',
    version: '16',
    color: '#87CEEB',
    sentiment: 'negative' as const,
  },
  {
    emoji: '😷',
    name: 'face with medical mask',
    keywords: [
      'cold',
      'dentist',
      'dermatologist',
      'doctor',
      'dr',
      'face',
      'germs',
      'mask',
      'medical',
      'medicine',
      'sick',
    ],
    category: 'smileys',
    subcategory: 'face-unwell',
    unicode: '1F637',
    version: '0.6',
    color: '#90EE90',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🤒',
    name: 'face with thermometer',
    keywords: ['face', 'ill', 'sick', 'thermometer'],
    category: 'smileys',
    subcategory: 'face-unwell',
    unicode: '1F912',
    version: '1',
    color: '#90EE90',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🤕',
    name: 'face with head-bandage',
    keywords: ['bandage', 'face', 'head-bandage', 'hurt', 'injury', 'ouch'],
    category: 'smileys',
    subcategory: 'face-unwell',
    unicode: '1F915',
    version: '1',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🤢',
    name: 'nauseated face',
    keywords: ['face', 'gross', 'nasty', 'nauseated', 'sick', 'vomit'],
    category: 'smileys',
    subcategory: 'face-unwell',
    unicode: '1F922',
    version: '3',
    color: '#90EE90',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🤮',
    name: 'face vomiting',
    keywords: [
      'barf',
      'ew',
      'face',
      'gross',
      'puke',
      'sick',
      'spew',
      'throw',
      'up',
      'vomit',
      'vomiting',
    ],
    category: 'smileys',
    subcategory: 'face-unwell',
    unicode: '1F92E',
    version: '5',
    color: '#90EE90',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🤧',
    name: 'sneezing face',
    keywords: [
      'face',
      'fever',
      'flu',
      'gesundheit',
      'sick',
      'sneeze',
      'sneezing',
    ],
    category: 'smileys',
    subcategory: 'face-unwell',
    unicode: '1F927',
    version: '3',
    color: '#90EE90',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🥵',
    name: 'hot face',
    keywords: [
      'dying',
      'face',
      'feverish',
      'heat',
      'hot',
      'panting',
      'red-faced',
      'stroke',
      'sweating',
      'tongue',
    ],
    category: 'smileys',
    subcategory: 'face-unwell',
    unicode: '1F975',
    version: '11',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥶',
    name: 'cold face',
    keywords: [
      'blue',
      'blue-faced',
      'cold',
      'face',
      'freezing',
      'frostbite',
      'icicles',
      'subzero',
      'teeth',
    ],
    category: 'smileys',
    subcategory: 'face-unwell',
    unicode: '1F976',
    version: '11',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥴',
    name: 'woozy face',
    keywords: [
      'dizzy',
      'drunk',
      'eyes',
      'face',
      'intoxicated',
      'mouth',
      'tipsy',
      'uneven',
      'wavy',
      'woozy',
    ],
    category: 'smileys',
    subcategory: 'face-unwell',
    unicode: '1F974',
    version: '11',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😵',
    name: 'face with crossed-out eyes',
    keywords: [
      'crossed-out',
      'dead',
      'dizzy',
      'eyes',
      'face',
      'feels',
      'knocked',
      'out',
      'sick',
      'tired',
    ],
    category: 'smileys',
    subcategory: 'face-unwell',
    unicode: '1F635',
    version: '0.6',
    color: '#90EE90',
    sentiment: 'negative' as const,
  },
  {
    emoji: '😵‍💫',
    name: 'face with spiral eyes',
    keywords: [
      'confused',
      'dizzy',
      'eyes',
      'face',
      'hypnotized',
      'omg',
      'smiley',
      'spiral',
      'trouble',
      'whoa',
      'woah',
      'woozy',
    ],
    category: 'smileys',
    subcategory: 'face-unwell',
    unicode: '1F635 200D 1F4AB',
    version: '13.1',
    color: '#90EE90',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🤯',
    name: 'exploding head',
    keywords: [
      'blown',
      'explode',
      'exploding',
      'head',
      'mind',
      'mindblown',
      'no',
      'shocked',
      'way',
    ],
    category: 'smileys',
    subcategory: 'face-unwell',
    unicode: '1F92F',
    version: '5',
    color: '#90EE90',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🤠',
    name: 'cowboy hat face',
    keywords: ['cowboy', 'cowgirl', 'face', 'hat'],
    category: 'smileys',
    subcategory: 'face-hat',
    unicode: '1F920',
    version: '3',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🥳',
    name: 'partying face',
    keywords: [
      'bday',
      'birthday',
      'celebrate',
      'celebration',
      'excited',
      'face',
      'happy',
      'hat',
      'hooray',
      'horn',
      'party',
      'partying',
    ],
    category: 'smileys',
    subcategory: 'face-hat',
    unicode: '1F973',
    version: '11',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🥸',
    name: 'disguised face',
    keywords: [
      'disguise',
      'eyebrow',
      'face',
      'glasses',
      'incognito',
      'moustache',
      'mustache',
      'nose',
      'person',
      'spy',
      'tache',
      'tash',
    ],
    category: 'smileys',
    subcategory: 'face-hat',
    unicode: '1F978',
    version: '13',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😎',
    name: 'smiling face with sunglasses',
    keywords: [
      'awesome',
      'beach',
      'bright',
      'bro',
      'chilling',
      'cool',
      'face',
      'rad',
      'relaxed',
      'shades',
      'slay',
      'smile',
      'style',
      'sunglasses',
      'swag',
      'win',
    ],
    category: 'smileys',
    subcategory: 'face-glasses',
    unicode: '1F60E',
    version: '1',
    color: '#4169E1',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🤓',
    name: 'nerd face',
    keywords: [
      'brainy',
      'clever',
      'expert',
      'face',
      'geek',
      'gifted',
      'glasses',
      'intelligent',
      'nerd',
      'smart',
    ],
    category: 'smileys',
    subcategory: 'face-glasses',
    unicode: '1F913',
    version: '1',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧐',
    name: 'face with monocle',
    keywords: [
      'classy',
      'face',
      'fancy',
      'monocle',
      'rich',
      'stuffy',
      'wealthy',
    ],
    category: 'smileys',
    subcategory: 'face-glasses',
    unicode: '1F9D0',
    version: '5',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😕',
    name: 'confused face',
    keywords: [
      'befuddled',
      'confused',
      'confusing',
      'dunno',
      'face',
      'frown',
      'hm',
      'meh',
      'not',
      'sad',
      'sorry',
      'sure',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F615',
    version: '1',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🫤',
    name: 'face with diagonal mouth',
    keywords: [
      'confused',
      'confusion',
      'diagonal',
      'disappointed',
      'doubt',
      'doubtful',
      'face',
      'frustrated',
      'frustration',
      'meh',
      'mouth',
      'skeptical',
      'unsure',
      'whatever',
      'wtv',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1FAE4',
    version: '14',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '😟',
    name: 'worried face',
    keywords: [
      'anxious',
      'butterflies',
      'face',
      'nerves',
      'nervous',
      'sad',
      'stress',
      'stressed',
      'surprised',
      'worried',
      'worry',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F61F',
    version: '1',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🙁',
    name: 'slightly frowning face',
    keywords: ['face', 'frown', 'frowning', 'sad', 'slightly'],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F641',
    version: '1',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '☹️',
    name: 'frowning face',
    keywords: ['face', 'frown', 'frowning', 'sad'],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '2639',
    version: '0.7',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '😮',
    name: 'face with open mouth',
    keywords: [
      'believe',
      'face',
      'forgot',
      'mouth',
      'omg',
      'open',
      'shocked',
      'surprised',
      'sympathy',
      'unbelievable',
      'unreal',
      'whoa',
      'wow',
      'you',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F62E',
    version: '1',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😯',
    name: 'hushed face',
    keywords: [
      'epic',
      'face',
      'hushed',
      'omg',
      'stunned',
      'surprised',
      'whoa',
      'woah',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F62F',
    version: '1',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😲',
    name: 'astonished face',
    keywords: [
      'astonished',
      'cost',
      'face',
      'no',
      'omg',
      'shocked',
      'totally',
      'way',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F632',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😳',
    name: 'flushed face',
    keywords: [
      'amazed',
      'awkward',
      'crazy',
      'dazed',
      'dead',
      'disbelief',
      'embarrassed',
      'face',
      'flushed',
      'geez',
      'heat',
      'hot',
      'impressed',
      'jeez',
      'what',
      'wow',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F633',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🥺',
    name: 'pleading face',
    keywords: [
      'begging',
      'big',
      'eyes',
      'face',
      'mercy',
      'not',
      'pleading',
      'please',
      'pretty',
      'puppy',
      'sad',
      'why',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F97A',
    version: '11',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🥹',
    name: 'face holding back tears',
    keywords: [
      'admiration',
      'aww',
      'back',
      'cry',
      'embarrassed',
      'face',
      'feelings',
      'grateful',
      'gratitude',
      'holding',
      'joy',
      'please',
      'proud',
      'resist',
      'sad',
      'tears',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F979',
    version: '14',
    color: '#4682B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😦',
    name: 'frowning face with open mouth',
    keywords: [
      'caught',
      'face',
      'frown',
      'frowning',
      'guard',
      'mouth',
      'open',
      'scared',
      'scary',
      'surprise',
      'what',
      'wow',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F626',
    version: '1',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '😧',
    name: 'anguished face',
    keywords: [
      'anguished',
      'face',
      'forgot',
      'scared',
      'scary',
      'stressed',
      'surprise',
      'unhappy',
      'what',
      'wow',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F627',
    version: '1',
    color: '#4682B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😨',
    name: 'fearful face',
    keywords: [
      'afraid',
      'anxious',
      'blame',
      'face',
      'fear',
      'fearful',
      'scared',
      'worried',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F628',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '😰',
    name: 'anxious face with sweat',
    keywords: [
      'anxious',
      'blue',
      'cold',
      'eek',
      'face',
      'mouth',
      'nervous',
      'open',
      'rushed',
      'scared',
      'sweat',
      'yikes',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F630',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '😥',
    name: 'sad but relieved face',
    keywords: [
      'anxious',
      'call',
      'close',
      'complicated',
      'disappointed',
      'face',
      'not',
      'relieved',
      'sad',
      'sweat',
      'time',
      'whew',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F625',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '😢',
    name: 'crying face',
    keywords: [
      'awful',
      'cry',
      'crying',
      'face',
      'feels',
      'miss',
      'sad',
      'tear',
      'triste',
      'unhappy',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F622',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😭',
    name: 'loudly crying face',
    keywords: [
      'bawling',
      'cry',
      'crying',
      'face',
      'loudly',
      'sad',
      'sob',
      'tear',
      'tears',
      'unhappy',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F62D',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😱',
    name: 'face screaming in fear',
    keywords: [
      'epic',
      'face',
      'fear',
      'fearful',
      'munch',
      'scared',
      'scream',
      'screamer',
      'screaming',
      'shocked',
      'surprised',
      'woah',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F631',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '😖',
    name: 'confounded face',
    keywords: [
      'annoyed',
      'confounded',
      'confused',
      'cringe',
      'distraught',
      'face',
      'feels',
      'frustrated',
      'mad',
      'sad',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F616',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '😣',
    name: 'persevering face',
    keywords: [
      'concentrate',
      'concentration',
      'face',
      'focus',
      'headache',
      'persevere',
      'persevering',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F623',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😞',
    name: 'disappointed face',
    keywords: [
      'awful',
      'blame',
      'dejected',
      'disappointed',
      'face',
      'fail',
      'losing',
      'sad',
      'unhappy',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F61E',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😓',
    name: 'downcast face with sweat',
    keywords: [
      'close',
      'cold',
      'downcast',
      'face',
      'feels',
      'headache',
      'nervous',
      'sad',
      'scared',
      'sweat',
      'yikes',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F613',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '😩',
    name: 'weary face',
    keywords: [
      'crying',
      'face',
      'fail',
      'feels',
      'hungry',
      'mad',
      'nooo',
      'sad',
      'sleepy',
      'tired',
      'unhappy',
      'weary',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F629',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😫',
    name: 'tired face',
    keywords: ['cost', 'face', 'feels', 'nap', 'sad', 'sneeze', 'tired'],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F62B',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🥱',
    name: 'yawning face',
    keywords: [
      'bedtime',
      'bored',
      'face',
      'goodnight',
      'nap',
      'night',
      'sleep',
      'sleepy',
      'tired',
      'whatever',
      'yawn',
      'yawning',
      'zzz',
    ],
    category: 'smileys',
    subcategory: 'face-concerned',
    unicode: '1F971',
    version: '12',
    color: '#4682B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '😤',
    name: 'face with steam from nose',
    keywords: [
      'anger',
      'angry',
      'face',
      'feels',
      'fume',
      'fuming',
      'furious',
      'fury',
      'mad',
      'nose',
      'steam',
      'triumph',
      'unhappy',
      'won',
    ],
    category: 'smileys',
    subcategory: 'face-negative',
    unicode: '1F624',
    version: '0.6',
    color: '#DC143C',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😡',
    name: 'enraged face',
    keywords: [
      'anger',
      'angry',
      'enraged',
      'face',
      'feels',
      'mad',
      'maddening',
      'pouting',
      'rage',
      'red',
      'shade',
      'unhappy',
      'upset',
    ],
    category: 'smileys',
    subcategory: 'face-negative',
    unicode: '1F621',
    version: '0.6',
    color: '#DC143C',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😠',
    name: 'angry face',
    keywords: [
      'anger',
      'angry',
      'blame',
      'face',
      'feels',
      'frustrated',
      'mad',
      'maddening',
      'rage',
      'shade',
      'unhappy',
      'upset',
    ],
    category: 'smileys',
    subcategory: 'face-negative',
    unicode: '1F620',
    version: '0.6',
    color: '#DC143C',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🤬',
    name: 'face with symbols on mouth',
    keywords: [
      'censor',
      'cursing',
      'cussing',
      'face',
      'mad',
      'mouth',
      'pissed',
      'swearing',
      'symbols',
    ],
    category: 'smileys',
    subcategory: 'face-negative',
    unicode: '1F92C',
    version: '5',
    color: '#DC143C',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😈',
    name: 'smiling face with horns',
    keywords: [
      'demon',
      'devil',
      'evil',
      'face',
      'fairy',
      'fairytale',
      'fantasy',
      'horns',
      'purple',
      'shade',
      'smile',
      'smiling',
      'tale',
    ],
    category: 'smileys',
    subcategory: 'face-negative',
    unicode: '1F608',
    version: '1',
    color: '#DC143C',
    sentiment: 'positive' as const,
  },
  {
    emoji: '👿',
    name: 'angry face with horns',
    keywords: [
      'angry',
      'demon',
      'devil',
      'evil',
      'face',
      'fairy',
      'fairytale',
      'fantasy',
      'horns',
      'imp',
      'mischievous',
      'purple',
      'shade',
      'tale',
    ],
    category: 'smileys',
    subcategory: 'face-negative',
    unicode: '1F47F',
    version: '0.6',
    color: '#DC143C',
    sentiment: 'negative' as const,
  },
  {
    emoji: '💀',
    name: 'skull',
    keywords: [
      'body',
      'dead',
      'death',
      'face',
      'fairy',
      'fairytale',
      'i’m',
      'lmao',
      'monster',
      'tale',
      'yolo',
    ],
    category: 'smileys',
    subcategory: 'face-negative',
    unicode: '1F480',
    version: '0.6',
    color: '#DC143C',
    sentiment: 'negative' as const,
  },
  {
    emoji: '☠️',
    name: 'skull and crossbones',
    keywords: [
      'bone',
      'crossbones',
      'dead',
      'death',
      'face',
      'monster',
      'skull',
    ],
    category: 'smileys',
    subcategory: 'face-negative',
    unicode: '2620',
    version: '1',
    color: '#DC143C',
    sentiment: 'negative' as const,
  },
  {
    emoji: '💩',
    name: 'pile of poo',
    keywords: [
      'bs',
      'comic',
      'doo',
      'dung',
      'face',
      'fml',
      'monster',
      'pile',
      'poo',
      'poop',
      'smelly',
      'smh',
      'stink',
      'stinks',
      'stinky',
      'turd',
    ],
    category: 'smileys',
    subcategory: 'face-costume',
    unicode: '1F4A9',
    version: '0.6',
    color: '#8B0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🤡',
    name: 'clown face',
    keywords: ['clown', 'face'],
    category: 'smileys',
    subcategory: 'face-costume',
    unicode: '1F921',
    version: '3',
    color: '#8B0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👹',
    name: 'ogre',
    keywords: [
      'creature',
      'devil',
      'face',
      'fairy',
      'fairytale',
      'fantasy',
      'mask',
      'monster',
      'scary',
      'tale',
    ],
    category: 'smileys',
    subcategory: 'face-costume',
    unicode: '1F479',
    version: '0.6',
    color: '#8B0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👺',
    name: 'goblin',
    keywords: [
      'angry',
      'creature',
      'face',
      'fairy',
      'fairytale',
      'fantasy',
      'mask',
      'mean',
      'monster',
      'tale',
    ],
    category: 'smileys',
    subcategory: 'face-costume',
    unicode: '1F47A',
    version: '0.6',
    color: '#8B0000',
    sentiment: 'negative' as const,
  },
  {
    emoji: '👻',
    name: 'ghost',
    keywords: [
      'boo',
      'creature',
      'excited',
      'face',
      'fairy',
      'fairytale',
      'fantasy',
      'halloween',
      'haunting',
      'monster',
      'scary',
      'silly',
      'tale',
    ],
    category: 'smileys',
    subcategory: 'face-costume',
    unicode: '1F47B',
    version: '0.6',
    color: '#8B0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👽️',
    name: 'alien',
    keywords: [
      'creature',
      'extraterrestrial',
      'face',
      'fairy',
      'fairytale',
      'fantasy',
      'monster',
      'space',
      'tale',
      'ufo',
    ],
    category: 'smileys',
    subcategory: 'face-costume',
    unicode: '1F47D',
    version: '0.6',
    color: '#8B0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👾',
    name: 'alien monster',
    keywords: [
      'alien',
      'creature',
      'extraterrestrial',
      'face',
      'fairy',
      'fairytale',
      'fantasy',
      'game',
      'gamer',
      'games',
      'monster',
      'pixelated',
      'space',
      'tale',
      'ufo',
    ],
    category: 'smileys',
    subcategory: 'face-costume',
    unicode: '1F47E',
    version: '0.6',
    color: '#8B0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🤖',
    name: 'robot',
    keywords: ['face', 'monster'],
    category: 'smileys',
    subcategory: 'face-costume',
    unicode: '1F916',
    version: '1',
    color: '#8B0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😺',
    name: 'grinning cat',
    keywords: [
      'animal',
      'cat',
      'face',
      'grinning',
      'mouth',
      'open',
      'smile',
      'smiling',
    ],
    category: 'smileys',
    subcategory: 'cat-face',
    unicode: '1F63A',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😸',
    name: 'grinning cat with smiling eyes',
    keywords: [
      'animal',
      'cat',
      'eye',
      'eyes',
      'face',
      'grin',
      'grinning',
      'smile',
      'smiling',
    ],
    category: 'smileys',
    subcategory: 'cat-face',
    unicode: '1F638',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😹',
    name: 'cat with tears of joy',
    keywords: [
      'animal',
      'cat',
      'face',
      'joy',
      'laugh',
      'laughing',
      'lol',
      'tear',
      'tears',
    ],
    category: 'smileys',
    subcategory: 'cat-face',
    unicode: '1F639',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😻',
    name: 'smiling cat with heart-eyes',
    keywords: [
      'animal',
      'cat',
      'eye',
      'face',
      'heart',
      'heart-eyes',
      'love',
      'smile',
      'smiling',
    ],
    category: 'smileys',
    subcategory: 'cat-face',
    unicode: '1F63B',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😼',
    name: 'cat with wry smile',
    keywords: ['animal', 'cat', 'face', 'ironic', 'smile', 'wry'],
    category: 'smileys',
    subcategory: 'cat-face',
    unicode: '1F63C',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '😽',
    name: 'kissing cat',
    keywords: [
      'animal',
      'cat',
      'closed',
      'eye',
      'eyes',
      'face',
      'kiss',
      'kissing',
    ],
    category: 'smileys',
    subcategory: 'cat-face',
    unicode: '1F63D',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🙀',
    name: 'weary cat',
    keywords: ['animal', 'cat', 'face', 'oh', 'surprised', 'weary'],
    category: 'smileys',
    subcategory: 'cat-face',
    unicode: '1F640',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '😿',
    name: 'crying cat',
    keywords: ['animal', 'cat', 'cry', 'crying', 'face', 'sad', 'tear'],
    category: 'smileys',
    subcategory: 'cat-face',
    unicode: '1F63F',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'negative' as const,
  },
  {
    emoji: '😾',
    name: 'pouting cat',
    keywords: ['animal', 'cat', 'face', 'pouting'],
    category: 'smileys',
    subcategory: 'cat-face',
    unicode: '1F63E',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🙈',
    name: 'see-no-evil monkey',
    keywords: [
      'embarrassed',
      'evil',
      'face',
      'forbidden',
      'forgot',
      'gesture',
      'hide',
      'monkey',
      'no',
      'omg',
      'prohibited',
      'scared',
      'secret',
      'smh',
      'watch',
    ],
    category: 'smileys',
    subcategory: 'monkey-face',
    unicode: '1F648',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🙉',
    name: 'hear-no-evil monkey',
    keywords: [
      'animal',
      'ears',
      'evil',
      'face',
      'forbidden',
      'gesture',
      'hear',
      'listen',
      'monkey',
      'no',
      'not',
      'prohibited',
      'secret',
      'shh',
      'tmi',
    ],
    category: 'smileys',
    subcategory: 'monkey-face',
    unicode: '1F649',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🙊',
    name: 'speak-no-evil monkey',
    keywords: [
      'animal',
      'evil',
      'face',
      'forbidden',
      'gesture',
      'monkey',
      'no',
      'not',
      'oops',
      'prohibited',
      'quiet',
      'secret',
      'speak',
      'stealth',
    ],
    category: 'smileys',
    subcategory: 'monkey-face',
    unicode: '1F64A',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💌',
    name: 'love letter',
    keywords: ['heart', 'letter', 'love', 'mail', 'romance', 'valentine'],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F48C',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💘',
    name: 'heart with arrow',
    keywords: [
      '143',
      'adorbs',
      'arrow',
      'cupid',
      'date',
      'emotion',
      'heart',
      'ily',
      'love',
      'romance',
      'valentine',
    ],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F498',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💝',
    name: 'heart with ribbon',
    keywords: [
      '143',
      'anniversary',
      'emotion',
      'heart',
      'ily',
      'kisses',
      'ribbon',
      'valentine',
      'xoxo',
    ],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F49D',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💖',
    name: 'sparkling heart',
    keywords: [
      '143',
      'emotion',
      'excited',
      'good',
      'heart',
      'ily',
      'kisses',
      'morning',
      'night',
      'sparkle',
      'sparkling',
      'xoxo',
    ],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F496',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💗',
    name: 'growing heart',
    keywords: [
      '143',
      'emotion',
      'excited',
      'growing',
      'heart',
      'heartpulse',
      'ily',
      'kisses',
      'muah',
      'nervous',
      'pulse',
      'xoxo',
    ],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F497',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💓',
    name: 'beating heart',
    keywords: [
      '143',
      'beating',
      'cardio',
      'emotion',
      'heart',
      'heartbeat',
      'ily',
      'love',
      'pulsating',
      'pulse',
    ],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F493',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💞',
    name: 'revolving hearts',
    keywords: [
      '143',
      'adorbs',
      'anniversary',
      'emotion',
      'heart',
      'hearts',
      'revolving',
    ],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F49E',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💕',
    name: 'two hearts',
    keywords: [
      '143',
      'anniversary',
      'date',
      'dating',
      'emotion',
      'heart',
      'hearts',
      'ily',
      'kisses',
      'love',
      'loving',
      'two',
      'xoxo',
    ],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F495',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💟',
    name: 'heart decoration',
    keywords: [
      '143',
      'decoration',
      'emotion',
      'heart',
      'hearth',
      'purple',
      'white',
    ],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F49F',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '❣️',
    name: 'heart exclamation',
    keywords: ['exclamation', 'heart', 'heavy', 'mark', 'punctuation'],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '2763',
    version: '1',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💔',
    name: 'broken heart',
    keywords: [
      'break',
      'broken',
      'crushed',
      'emotion',
      'heart',
      'heartbroken',
      'lonely',
      'sad',
    ],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F494',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '❤️‍🔥',
    name: 'heart on fire',
    keywords: ['burn', 'fire', 'heart', 'love', 'lust', 'sacred'],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '2764 FE0F 200D 1F525',
    version: '13.1',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '❤️‍🩹',
    name: 'mending heart',
    keywords: [
      'healthier',
      'heart',
      'improving',
      'mending',
      'recovering',
      'recuperating',
      'well',
    ],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '2764 FE0F 200D 1FA79',
    version: '13.1',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '❤️',
    name: 'red heart',
    keywords: ['emotion', 'heart', 'love', 'red'],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '2764',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🩷',
    name: 'pink heart',
    keywords: [
      '143',
      'adorable',
      'cute',
      'emotion',
      'heart',
      'ily',
      'like',
      'love',
      'pink',
      'special',
      'sweet',
    ],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1FA77',
    version: '15',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🧡',
    name: 'orange heart',
    keywords: ['143', 'heart', 'orange'],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F9E1',
    version: '5',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💛',
    name: 'yellow heart',
    keywords: ['143', 'cardiac', 'emotion', 'heart', 'ily', 'love', 'yellow'],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F49B',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💚',
    name: 'green heart',
    keywords: ['143', 'emotion', 'green', 'heart', 'ily', 'love', 'romantic'],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F49A',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💙',
    name: 'blue heart',
    keywords: ['143', 'blue', 'emotion', 'heart', 'ily', 'love', 'romance'],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F499',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🩵',
    name: 'light blue heart',
    keywords: [
      '143',
      'blue',
      'cute',
      'cyan',
      'emotion',
      'heart',
      'ily',
      'light',
      'like',
      'love',
      'sky',
      'special',
      'teal',
    ],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1FA75',
    version: '15',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💜',
    name: 'purple heart',
    keywords: ['143', 'bestest', 'emotion', 'heart', 'ily', 'love', 'purple'],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F49C',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🤎',
    name: 'brown heart',
    keywords: ['143', 'brown', 'heart'],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F90E',
    version: '12',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🖤',
    name: 'black heart',
    keywords: ['black', 'evil', 'heart', 'wicked'],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F5A4',
    version: '3',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🩶',
    name: 'grey heart',
    keywords: [
      '143',
      'emotion',
      'gray',
      'grey',
      'heart',
      'ily',
      'love',
      'silver',
      'slate',
      'special',
    ],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1FA76',
    version: '15',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🤍',
    name: 'white heart',
    keywords: ['143', 'heart', 'white'],
    category: 'smileys',
    subcategory: 'heart',
    unicode: '1F90D',
    version: '12',
    color: '#FFD700',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💋',
    name: 'kiss mark',
    keywords: [
      'dating',
      'emotion',
      'heart',
      'kiss',
      'kissing',
      'lips',
      'mark',
      'romance',
      'sexy',
    ],
    category: 'smileys',
    subcategory: 'emotion',
    unicode: '1F48B',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💯',
    name: 'hundred points',
    keywords: [
      '100',
      'a+',
      'agree',
      'clearly',
      'definitely',
      'faithful',
      'fleek',
      'full',
      'hundred',
      'keep',
      'perfect',
      'point',
      'score',
      'true',
      'truth',
      'yup',
    ],
    category: 'smileys',
    subcategory: 'emotion',
    unicode: '1F4AF',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💢',
    name: 'anger symbol',
    keywords: ['anger', 'angry', 'comic', 'mad', 'symbol', 'upset'],
    category: 'smileys',
    subcategory: 'emotion',
    unicode: '1F4A2',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '💥',
    name: 'collision',
    keywords: ['bomb', 'boom', 'collide', 'comic', 'explode'],
    category: 'smileys',
    subcategory: 'emotion',
    unicode: '1F4A5',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💫',
    name: 'dizzy',
    keywords: ['comic', 'shining', 'shooting', 'star', 'stars'],
    category: 'smileys',
    subcategory: 'emotion',
    unicode: '1F4AB',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'positive' as const,
  },
  {
    emoji: '💦',
    name: 'sweat droplets',
    keywords: [
      'comic',
      'drip',
      'droplet',
      'droplets',
      'drops',
      'splashing',
      'squirt',
      'sweat',
      'water',
      'wet',
      'work',
      'workout',
    ],
    category: 'smileys',
    subcategory: 'emotion',
    unicode: '1F4A6',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💨',
    name: 'dashing away',
    keywords: [
      'away',
      'cloud',
      'comic',
      'dash',
      'dashing',
      'fart',
      'fast',
      'go',
      'gone',
      'gotta',
      'running',
      'smoke',
    ],
    category: 'smileys',
    subcategory: 'emotion',
    unicode: '1F4A8',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕳️',
    name: 'hole',
    keywords: ['hole'],
    category: 'smileys',
    subcategory: 'emotion',
    unicode: '1F573',
    version: '0.7',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💬',
    name: 'speech balloon',
    keywords: [
      'balloon',
      'bubble',
      'comic',
      'dialog',
      'message',
      'sms',
      'speech',
      'talk',
      'text',
      'typing',
    ],
    category: 'smileys',
    subcategory: 'emotion',
    unicode: '1F4AC',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '👁️‍🗨️',
    name: 'eye in speech bubble',
    keywords: ['balloon', 'bubble', 'eye', 'speech', 'witness'],
    category: 'smileys',
    subcategory: 'emotion',
    unicode: '1F441 FE0F 200D 1F5E8 FE0F',
    version: '2',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗨️',
    name: 'left speech bubble',
    keywords: ['balloon', 'bubble', 'dialog', 'left', 'speech'],
    category: 'smileys',
    subcategory: 'emotion',
    unicode: '1F5E8',
    version: '2',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗯️',
    name: 'right anger bubble',
    keywords: ['anger', 'angry', 'balloon', 'bubble', 'mad', 'right'],
    category: 'smileys',
    subcategory: 'emotion',
    unicode: '1F5EF',
    version: '0.7',
    color: '#FF69B4',
    sentiment: 'negative' as const,
  },
  {
    emoji: '💭',
    name: 'thought balloon',
    keywords: [
      'balloon',
      'bubble',
      'cartoon',
      'cloud',
      'comic',
      'daydream',
      'decisions',
      'dream',
      'idea',
      'invent',
      'invention',
      'realize',
      'think',
      'thoughts',
      'wonder',
    ],
    category: 'smileys',
    subcategory: 'emotion',
    unicode: '1F4AD',
    version: '1',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💤',
    name: 'zzz',
    keywords: [
      'comic',
      'good',
      'goodnight',
      'night',
      'sleep',
      'sleeping',
      'sleepy',
      'tired',
      'zzz',
    ],
    category: 'smileys',
    subcategory: 'emotion',
    unicode: '1F4A4',
    version: '0.6',
    color: '#FF69B4',
    sentiment: 'negative' as const,
  },
];
