import type { Emoji } from '../../schema';

export const smileyEmojis: Emoji[] = [
  // Positive emotions
  {
    emoji: '😀',
    name: 'grinning face',
    keywords: ['happy', 'smile', 'grin', 'joy', 'cheerful'],
    category: 'smileys',
    color: '#FFD700',
  },
  {
    emoji: '😃',
    name: 'grinning face with big eyes',
    keywords: ['happy', 'smile', 'grin', 'joy', 'excited'],
    category: 'smileys',
    color: '#FFD700',
  },
  {
    emoji: '😄',
    name: 'grinning face with smiling eyes',
    keywords: ['happy', 'smile', 'joy', 'pleased'],
    category: 'smileys',
    color: '#FFD700',
  },
  {
    emoji: '😁',
    name: 'beaming face with smiling eyes',
    keywords: ['happy', 'smile', 'joy', 'beam'],
    category: 'smileys',
    color: '#FFD700',
  },
  {
    emoji: '😆',
    name: 'grinning squinting face',
    keywords: ['happy', 'laugh', 'lol', 'satisfied'],
    category: 'smileys',
    color: '#FFD700',
  },
  {
    emoji: '😅',
    name: 'grinning face with sweat',
    keywords: ['hot', 'happy', 'laugh', 'sweat', 'smile', 'relief'],
    category: 'smileys',
    color: '#87CEEB',
  },
  {
    emoji: '🤣',
    name: 'rolling on the floor laughing',
    keywords: ['lol', 'laughing', 'rofl', 'haha', 'lmao'],
    category: 'smileys',
    color: '#FFD700',
  },
  {
    emoji: '😂',
    name: 'face with tears of joy',
    keywords: ['tears', 'happy', 'laughing', 'lol', 'haha', 'joy'],
    category: 'smileys',
    color: '#87CEEB',
  },
  {
    emoji: '🙂',
    name: 'slightly smiling face',
    keywords: ['smile', 'happy', 'slight'],
    category: 'smileys',
    color: '#FFD700',
  },
  {
    emoji: '🙃',
    name: 'upside-down face',
    keywords: ['upside down', 'silly', 'sarcasm'],
    category: 'smileys',
    color: '#DDA0DD',
  },
  {
    emoji: '😉',
    name: 'winking face',
    keywords: ['wink', 'happy', 'flirt'],
    category: 'smileys',
    color: '#FFB6C1',
  },
  {
    emoji: '😊',
    name: 'smiling face with smiling eyes',
    keywords: ['happy', 'smile', 'blush', 'pleased'],
    category: 'smileys',
    color: '#FFB6C1',
  },
  {
    emoji: '😇',
    name: 'smiling face with halo',
    keywords: ['angel', 'innocent', 'halo'],
    category: 'smileys',
    color: '#87CEEB',
  },

  // Love and affection
  {
    emoji: '🥰',
    name: 'smiling face with hearts',
    keywords: ['love', 'hearts', 'adore', 'crush'],
    category: 'smileys',
    color: '#FF69B4',
  },
  {
    emoji: '😍',
    name: 'smiling face with heart-eyes',
    keywords: ['love', 'heart eyes', 'crush', 'adore'],
    category: 'smileys',
    color: '#FF1493',
  },
  {
    emoji: '🤩',
    name: 'star-struck',
    keywords: ['star', 'eyes', 'excited', 'amazed'],
    category: 'smileys',
    color: '#FFD700',
  },
  {
    emoji: '😘',
    name: 'face blowing a kiss',
    keywords: ['kiss', 'love', 'flirt'],
    category: 'smileys',
    color: '#FF69B4',
  },
  {
    emoji: '😗',
    name: 'kissing face',
    keywords: ['kiss', 'pucker'],
    category: 'smileys',
    color: '#FFB6C1',
  },
  {
    emoji: '☺️',
    name: 'smiling face',
    keywords: ['smile', 'happy', 'pleased'],
    category: 'smileys',
    color: '#FFD700',
  },
  {
    emoji: '😚',
    name: 'kissing face with closed eyes',
    keywords: ['kiss', 'love', 'blush'],
    category: 'smileys',
    color: '#FFB6C1',
  },
  {
    emoji: '😙',
    name: 'kissing face with smiling eyes',
    keywords: ['kiss', 'smile', 'happy'],
    category: 'smileys',
    color: '#FFB6C1',
  },

  // Playful and silly
  {
    emoji: '😋',
    name: 'face savoring food',
    keywords: ['yum', 'tasty', 'delicious', 'tongue'],
    category: 'smileys',
    color: '#FF6347',
  },
  {
    emoji: '😛',
    name: 'face with tongue',
    keywords: ['tongue', 'playful', 'prank'],
    category: 'smileys',
    color: '#FF69B4',
  },
  {
    emoji: '😜',
    name: 'winking face with tongue',
    keywords: ['wink', 'tongue', 'joke', 'playful'],
    category: 'smileys',
    color: '#FF69B4',
  },
  {
    emoji: '🤪',
    name: 'zany face',
    keywords: ['crazy', 'wild', 'silly', 'goofy'],
    category: 'smileys',
    color: '#9370DB',
  },
  {
    emoji: '😝',
    name: 'squinting face with tongue',
    keywords: ['tongue', 'squint', 'prank', 'playful'],
    category: 'smileys',
    color: '#FF69B4',
  },
  {
    emoji: '🤑',
    name: 'money-mouth face',
    keywords: ['money', 'dollar', 'rich'],
    category: 'smileys',
    color: '#228B22',
  },

  // Neutral emotions
  {
    emoji: '🤗',
    name: 'hugging face',
    keywords: ['hug', 'embrace', 'warm'],
    category: 'smileys',
    color: '#FFB6C1',
  },
  {
    emoji: '🤭',
    name: 'face with hand over mouth',
    keywords: ['giggle', 'oops', 'shocked', 'surprised'],
    category: 'smileys',
    color: '#DDA0DD',
  },
  {
    emoji: '🤫',
    name: 'shushing face',
    keywords: ['shh', 'quiet', 'silence'],
    category: 'smileys',
    color: '#B0C4DE',
  },
  {
    emoji: '🤔',
    name: 'thinking face',
    keywords: ['think', 'consider', 'ponder', 'hmm'],
    category: 'smileys',
    color: '#DDA0DD',
  },
  {
    emoji: '🤐',
    name: 'zipper-mouth face',
    keywords: ['zip', 'sealed', 'lips', 'secret'],
    category: 'smileys',
    color: '#C0C0C0',
  },
  {
    emoji: '🤨',
    name: 'face with raised eyebrow',
    keywords: ['suspicious', 'skeptical', 'disapprove'],
    category: 'smileys',
    color: '#DEB887',
  },
  {
    emoji: '😐',
    name: 'neutral face',
    keywords: ['neutral', 'meh', 'deadpan'],
    category: 'smileys',
    color: '#C0C0C0',
  },
  {
    emoji: '😑',
    name: 'expressionless face',
    keywords: ['expressionless', 'meh', 'blank'],
    category: 'smileys',
    color: '#C0C0C0',
  },
  {
    emoji: '😶',
    name: 'face without mouth',
    keywords: ['mouthless', 'silent', 'mute'],
    category: 'smileys',
    color: '#C0C0C0',
  },
  {
    emoji: '😏',
    name: 'smirking face',
    keywords: ['smirk', 'smug', 'sly'],
    category: 'smileys',
    color: '#DDA0DD',
  },
  {
    emoji: '😒',
    name: 'unamused face',
    keywords: ['unamused', 'meh', 'skeptical'],
    category: 'smileys',
    color: '#A9A9A9',
  },
  {
    emoji: '🙄',
    name: 'face with rolling eyes',
    keywords: ['eyeroll', 'frustrated'],
    category: 'smileys',
    color: '#A9A9A9',
  },
  {
    emoji: '😬',
    name: 'grimacing face',
    keywords: ['grimace', 'awkward', 'teeth'],
    category: 'smileys',
    color: '#D3D3D3',
  },

  // Negative emotions
  {
    emoji: '😮‍💨',
    name: 'face exhaling',
    keywords: ['exhale', 'sigh', 'relief', 'tired'],
    category: 'smileys',
    color: '#87CEEB',
  },
  {
    emoji: '🤥',
    name: 'lying face',
    keywords: ['lie', 'pinocchio', 'dishonest'],
    category: 'smileys',
    color: '#CD853F',
  },
  {
    emoji: '😌',
    name: 'relieved face',
    keywords: ['relieved', 'calm', 'peace'],
    category: 'smileys',
    color: '#87CEEB',
  },
  {
    emoji: '😔',
    name: 'pensive face',
    keywords: ['pensive', 'sad', 'depressed'],
    category: 'smileys',
    color: '#4682B4',
  },
  {
    emoji: '😪',
    name: 'sleepy face',
    keywords: ['sleepy', 'tired', 'snot'],
    category: 'smileys',
    color: '#87CEEB',
  },
  {
    emoji: '🤤',
    name: 'drooling face',
    keywords: ['drool', 'hungry'],
    category: 'smileys',
    color: '#87CEEB',
  },
  {
    emoji: '😴',
    name: 'sleeping face',
    keywords: ['sleep', 'zzz', 'tired'],
    category: 'smileys',
    color: '#4169E1',
  },
  {
    emoji: '😷',
    name: 'face with medical mask',
    keywords: ['sick', 'mask', 'covid', 'coronavirus'],
    category: 'smileys',
    color: '#90EE90',
  },
  {
    emoji: '🤒',
    name: 'face with thermometer',
    keywords: ['sick', 'fever', 'thermometer'],
    category: 'smileys',
    color: '#FF6347',
  },
  {
    emoji: '🤕',
    name: 'face with head-bandage',
    keywords: ['hurt', 'bandage', 'injured'],
    category: 'smileys',
    color: '#F0E68C',
  },
  {
    emoji: '🤢',
    name: 'nauseated face',
    keywords: ['sick', 'nausea', 'green'],
    category: 'smileys',
    color: '#90EE90',
  },
  {
    emoji: '🤮',
    name: 'face vomiting',
    keywords: ['vomit', 'sick', 'puke'],
    category: 'smileys',
    color: '#90EE90',
  },
  {
    emoji: '🤧',
    name: 'sneezing face',
    keywords: ['sneeze', 'achoo', 'sick'],
    category: 'smileys',
    color: '#87CEEB',
  },
  {
    emoji: '🥵',
    name: 'hot face',
    keywords: ['hot', 'sweating', 'heat'],
    category: 'smileys',
    color: '#FF4500',
  },
  {
    emoji: '🥶',
    name: 'cold face',
    keywords: ['cold', 'freezing', 'ice'],
    category: 'smileys',
    color: '#87CEEB',
  },
  {
    emoji: '🥴',
    name: 'woozy face',
    keywords: ['dizzy', 'drunk', 'woozy'],
    category: 'smileys',
    color: '#DDA0DD',
  },
  {
    emoji: '😵',
    name: 'dizzy face',
    keywords: ['dizzy', 'spiral', 'dead'],
    category: 'smileys',
    color: '#DDA0DD',
  },
  {
    emoji: '😵‍💫',
    name: 'face with spiral eyes',
    keywords: ['dizzy', 'hypnotized', 'spiral'],
    category: 'smileys',
    color: '#DDA0DD',
  },
  {
    emoji: '🤯',
    name: 'exploding head',
    keywords: ['mind blown', 'explode', 'shocked'],
    category: 'smileys',
    color: '#FF4500',
  },

  // More emotions
  {
    emoji: '🤠',
    name: 'cowboy hat face',
    keywords: ['cowboy', 'hat', 'western'],
    category: 'smileys',
    color: '#8B4513',
  },
  {
    emoji: '🥳',
    name: 'partying face',
    keywords: ['party', 'celebration', 'hat'],
    category: 'smileys',
    color: '#FF69B4',
  },
  {
    emoji: '😎',
    name: 'smiling face with sunglasses',
    keywords: ['cool', 'sunglasses', 'confident'],
    category: 'smileys',
    color: '#000000',
  },
  {
    emoji: '🤓',
    name: 'nerd face',
    keywords: ['nerd', 'geek', 'glasses'],
    category: 'smileys',
    color: '#4169E1',
  },
  {
    emoji: '🧐',
    name: 'face with monocle',
    keywords: ['monocle', 'fancy', 'stuffy'],
    category: 'smileys',
    color: '#DAA520',
  },

  // Concerned emotions
  {
    emoji: '😕',
    name: 'confused face',
    keywords: ['confused', 'puzzled', 'huh'],
    category: 'smileys',
    color: '#DEB887',
  },
  {
    emoji: '😟',
    name: 'worried face',
    keywords: ['worried', 'nervous', 'anxious'],
    category: 'smileys',
    color: '#4682B4',
  },
  {
    emoji: '🙁',
    name: 'slightly frowning face',
    keywords: ['frown', 'sad', 'disappointed'],
    category: 'smileys',
    color: '#4682B4',
  },
  {
    emoji: '☹️',
    name: 'frowning face',
    keywords: ['frown', 'sad', 'megafrown'],
    category: 'smileys',
    color: '#4682B4',
  },
  {
    emoji: '😮',
    name: 'face with open mouth',
    keywords: ['open', 'mouth', 'surprised'],
    category: 'smileys',
    color: '#FFB6C1',
  },
  {
    emoji: '😯',
    name: 'hushed face',
    keywords: ['hushed', 'surprised', 'wow'],
    category: 'smileys',
    color: '#FFB6C1',
  },
  {
    emoji: '😲',
    name: 'astonished face',
    keywords: ['astonished', 'shocked', 'amazed'],
    category: 'smileys',
    color: '#FFB6C1',
  },
  {
    emoji: '😳',
    name: 'flushed face',
    keywords: ['flushed', 'embarrassed', 'blush'],
    category: 'smileys',
    color: '#FF69B4',
  },
  {
    emoji: '🥺',
    name: 'pleading face',
    keywords: ['please', 'puppy eyes', 'beg'],
    category: 'smileys',
    color: '#87CEEB',
  },
  {
    emoji: '😦',
    name: 'frowning face with open mouth',
    keywords: ['frown', 'open', 'surprised'],
    category: 'smileys',
    color: '#4682B4',
  },
  {
    emoji: '😧',
    name: 'anguished face',
    keywords: ['anguished', 'shocked', 'surprised'],
    category: 'smileys',
    color: '#4682B4',
  },
  {
    emoji: '😨',
    name: 'fearful face',
    keywords: ['fear', 'scared', 'nervous'],
    category: 'smileys',
    color: '#9370DB',
  },
  {
    emoji: '😰',
    name: 'anxious face with sweat',
    keywords: ['anxious', 'sweat', 'nervous'],
    category: 'smileys',
    color: '#87CEEB',
  },
  {
    emoji: '😥',
    name: 'sad but relieved face',
    keywords: ['sad', 'relieved', 'disappointed'],
    category: 'smileys',
    color: '#87CEEB',
  },
  {
    emoji: '😢',
    name: 'crying face',
    keywords: ['cry', 'sad', 'tears'],
    category: 'smileys',
    color: '#4682B4',
  },
  {
    emoji: '😭',
    name: 'loudly crying face',
    keywords: ['cry', 'sad', 'bawl', 'sob'],
    category: 'smileys',
    color: '#4682B4',
  },
  {
    emoji: '😱',
    name: 'face screaming in fear',
    keywords: ['scream', 'fear', 'omg'],
    category: 'smileys',
    color: '#9370DB',
  },
  {
    emoji: '😖',
    name: 'confounded face',
    keywords: ['confounded', 'confused', 'frustrated'],
    category: 'smileys',
    color: '#DEB887',
  },
  {
    emoji: '😣',
    name: 'persevering face',
    keywords: ['persevere', 'struggling', 'no'],
    category: 'smileys',
    color: '#DEB887',
  },
  {
    emoji: '😞',
    name: 'disappointed face',
    keywords: ['disappointed', 'sad', 'depressed'],
    category: 'smileys',
    color: '#4682B4',
  },
  {
    emoji: '😓',
    name: 'downcast face with sweat',
    keywords: ['sweat', 'sad', 'hard work'],
    category: 'smileys',
    color: '#87CEEB',
  },
  {
    emoji: '😩',
    name: 'weary face',
    keywords: ['weary', 'tired', 'groaning'],
    category: 'smileys',
    color: '#DEB887',
  },
  {
    emoji: '😫',
    name: 'tired face',
    keywords: ['tired', 'exhausted', 'fed up'],
    category: 'smileys',
    color: '#DEB887',
  },
  {
    emoji: '🥱',
    name: 'yawning face',
    keywords: ['yawn', 'tired', 'bored'],
    category: 'smileys',
    color: '#DEB887',
  },

  // Angry emotions
  {
    emoji: '😤',
    name: 'face with steam from nose',
    keywords: ['triumph', 'steam', 'proud'],
    category: 'smileys',
    color: '#FF6347',
  },
  {
    emoji: '😡',
    name: 'pouting face',
    keywords: ['angry', 'mad', 'rage'],
    category: 'smileys',
    color: '#DC143C',
  },
  {
    emoji: '😠',
    name: 'angry face',
    keywords: ['angry', 'mad', 'annoyed'],
    category: 'smileys',
    color: '#DC143C',
  },
  {
    emoji: '🤬',
    name: 'face with symbols on mouth',
    keywords: ['curse', 'swear', 'angry'],
    category: 'smileys',
    color: '#DC143C',
  },

  // Evil/mischievous
  {
    emoji: '😈',
    name: 'smiling face with horns',
    keywords: ['devil', 'evil', 'horns'],
    category: 'smileys',
    color: '#8B0000',
  },
  {
    emoji: '👿',
    name: 'angry face with horns',
    keywords: ['devil', 'angry', 'imp'],
    category: 'smileys',
    color: '#8B0000',
  },

  // Skulls and ghosts
  {
    emoji: '💀',
    name: 'skull',
    keywords: ['dead', 'skull', 'death'],
    category: 'smileys',
    color: '#F5F5F5',
  },
  {
    emoji: '☠️',
    name: 'skull and crossbones',
    keywords: ['dead', 'danger', 'pirate'],
    category: 'smileys',
    color: '#F5F5F5',
  },

  // Other faces
  {
    emoji: '💩',
    name: 'pile of poo',
    keywords: ['poop', 'shit', 'crap'],
    category: 'smileys',
    color: '#8B4513',
  },
  {
    emoji: '🤡',
    name: 'clown face',
    keywords: ['clown', 'circus', 'joker'],
    category: 'smileys',
    color: '#FF0000',
  },
  {
    emoji: '👹',
    name: 'ogre',
    keywords: ['monster', 'ogre', 'scary'],
    category: 'smileys',
    color: '#DC143C',
  },
  {
    emoji: '👺',
    name: 'goblin',
    keywords: ['goblin', 'monster', 'scary'],
    category: 'smileys',
    color: '#DC143C',
  },
  {
    emoji: '👻',
    name: 'ghost',
    keywords: ['ghost', 'boo', 'halloween'],
    category: 'smileys',
    color: '#F5F5F5',
  },
  {
    emoji: '👽',
    name: 'alien',
    keywords: ['alien', 'ufo', 'space'],
    category: 'smileys',
    color: '#90EE90',
  },
  {
    emoji: '👾',
    name: 'alien monster',
    keywords: ['alien', 'monster', 'game'],
    category: 'smileys',
    color: '#9370DB',
  },
  {
    emoji: '🤖',
    name: 'robot',
    keywords: ['robot', 'ai', 'machine'],
    category: 'smileys',
    color: '#C0C0C0',
  },
];

// Helper function to determine sentiment based on emoji
export function getEmojiSentiment(
  emoji: string
): 'positive' | 'negative' | 'neutral' {
  const positiveEmojis = [
    '😀',
    '😃',
    '😄',
    '😁',
    '😆',
    '😊',
    '😇',
    '🥰',
    '😍',
    '🤩',
    '😘',
    '😗',
    '☺️',
    '😚',
    '😙',
    '😋',
    '😌',
    '🤗',
    '😎',
    '🥳',
  ];
  const negativeEmojis = [
    '😔',
    '😕',
    '😟',
    '🙁',
    '☹️',
    '😣',
    '😞',
    '😓',
    '😩',
    '😫',
    '😤',
    '😡',
    '😠',
    '🤬',
    '😈',
    '👿',
    '😰',
    '😥',
    '😢',
    '😭',
    '😱',
    '😖',
    '😣',
    '😞',
    '😓',
    '😩',
    '😫',
  ];

  if (positiveEmojis.includes(emoji)) return 'positive';
  if (negativeEmojis.includes(emoji)) return 'negative';
  return 'neutral';
}
