import type { Emoji } from '../../schema';

export const symbolEmojis: Emoji[] = [
  // Hearts
  {
    emoji: '💋',
    name: 'kiss mark',
    keywords: ['face', 'lips', 'love'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '💌',
    name: 'love letter',
    keywords: ['email', 'like', 'affection'],
    category: 'symbols',
    color: '#FFB6C1',
  },
  {
    emoji: '💘',
    name: 'heart with arrow',
    keywords: ['love', 'like', 'heart'],
    category: 'symbols',
    color: '#FF69B4',
  },
  {
    emoji: '💝',
    name: 'heart with ribbon',
    keywords: ['love', 'valentines', 'gift'],
    category: 'symbols',
    color: '#FF69B4',
  },
  {
    emoji: '💖',
    name: 'sparkling heart',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#FF69B4',
  },
  {
    emoji: '💗',
    name: 'growing heart',
    keywords: ['like', 'love', 'affection'],
    category: 'symbols',
    color: '#FF69B4',
  },
  {
    emoji: '💓',
    name: 'beating heart',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#FF69B4',
  },
  {
    emoji: '💞',
    name: 'revolving hearts',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#FF69B4',
  },
  {
    emoji: '💕',
    name: 'two hearts',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#FF69B4',
  },
  {
    emoji: '💟',
    name: 'heart decoration',
    keywords: ['purple-square', 'love', 'like'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '❣️',
    name: 'heart exclamation',
    keywords: ['decoration', 'love', 'exclamation'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '💔',
    name: 'broken heart',
    keywords: ['sad', 'sorry', 'break'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '❤️‍🔥',
    name: 'heart on fire',
    keywords: ['passionate', 'ardent', 'burning'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '❤️‍🩹',
    name: 'mending heart',
    keywords: ['broken heart', 'bandage', 'wounded'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '❤️',
    name: 'red heart',
    keywords: ['love', 'like', 'valentines'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🧡',
    name: 'orange heart',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#FF8C00',
  },
  {
    emoji: '💛',
    name: 'yellow heart',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#FFD700',
  },
  {
    emoji: '💚',
    name: 'green heart',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#90EE90',
  },
  {
    emoji: '💙',
    name: 'blue heart',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '💜',
    name: 'purple heart',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '🤎',
    name: 'brown heart',
    keywords: ['coffee', 'love', 'like'],
    category: 'symbols',
    color: '#8B4513',
  },
  {
    emoji: '🖤',
    name: 'black heart',
    keywords: ['evil', 'dark', 'love'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '🤍',
    name: 'white heart',
    keywords: ['pure', 'love', 'like'],
    category: 'symbols',
    color: '#FFFFFF',
  },

  // Emotion symbols
  {
    emoji: '💯',
    name: 'hundred points',
    keywords: ['score', 'perfect', 'numbers'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '💢',
    name: 'anger symbol',
    keywords: ['angry', 'violence', 'red'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '💥',
    name: 'collision',
    keywords: ['bomb', 'explode', 'explosion'],
    category: 'symbols',
    color: '#FF8C00',
  },
  {
    emoji: '💫',
    name: 'dizzy',
    keywords: ['star', 'sparkle', 'shoot'],
    category: 'symbols',
    color: '#FFD700',
  },
  {
    emoji: '💦',
    name: 'sweat droplets',
    keywords: ['water', 'drip', 'oops'],
    category: 'symbols',
    color: '#87CEEB',
  },
  {
    emoji: '💨',
    name: 'dashing away',
    keywords: ['wind', 'air', 'fast'],
    category: 'symbols',
    color: '#87CEEB',
  },
  {
    emoji: '🕳️',
    name: 'hole',
    keywords: ['embarrassing', 'hole', 'pit'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '💣',
    name: 'bomb',
    keywords: ['boom', 'explode', 'explosion'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '💬',
    name: 'speech balloon',
    keywords: ['bubble', 'words', 'message'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '👁️‍🗨️',
    name: 'eye in speech bubble',
    keywords: ['info', 'feedback', 'witness'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🗨️',
    name: 'left speech bubble',
    keywords: ['words', 'message', 'talk'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '🗯️',
    name: 'right anger bubble',
    keywords: ['caption', 'speech', 'thinking'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '💭',
    name: 'thought balloon',
    keywords: ['bubble', 'cloud', 'speech'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '💤',
    name: 'zzz',
    keywords: ['sleepy', 'tired', 'dream'],
    category: 'symbols',
    color: '#4169E1',
  },

  // Cards
  {
    emoji: '♠️',
    name: 'spade suit',
    keywords: ['poker', 'cards', 'suits'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '♥️',
    name: 'heart suit',
    keywords: ['poker', 'cards', 'suits'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '♦️',
    name: 'diamond suit',
    keywords: ['poker', 'cards', 'suits'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '♣️',
    name: 'club suit',
    keywords: ['poker', 'cards', 'suits'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '🃏',
    name: 'joker',
    keywords: ['poker', 'cards', 'game'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '🎴',
    name: 'flower playing cards',
    keywords: ['game', 'sunset', 'red'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🀄',
    name: 'mahjong red dragon',
    keywords: ['game', 'play', 'chinese'],
    category: 'symbols',
    color: '#DC143C',
  },

  // Time and cycles
  {
    emoji: '🕐',
    name: `clock face one o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '🕑',
    name: `clock face two o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '🕒',
    name: `clock face three o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '🕓',
    name: `clock face four o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '🕔',
    name: `clock face five o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '🕕',
    name: `clock face six o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '🕖',
    name: `clock face seven o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '🕗',
    name: `clock face eight o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '🕘',
    name: `clock face nine o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '🕙',
    name: `clock face ten o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '🕚',
    name: `clock face eleven o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '🕛',
    name: `clock face twelve o'clock`,
    keywords: ['time', 'noon', 'midnight'],
    category: 'symbols',
    color: '#F5F5F5',
  },

  // Geometric shapes
  {
    emoji: '🔴',
    name: 'red circle',
    keywords: ['shape', 'error', 'danger'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🟠',
    name: 'orange circle',
    keywords: ['round', 'orange', 'circle'],
    category: 'symbols',
    color: '#FF8C00',
  },
  {
    emoji: '🟡',
    name: 'yellow circle',
    keywords: ['round', 'yellow', 'circle'],
    category: 'symbols',
    color: '#FFD700',
  },
  {
    emoji: '🟢',
    name: 'green circle',
    keywords: ['round', 'green', 'circle'],
    category: 'symbols',
    color: '#90EE90',
  },
  {
    emoji: '🔵',
    name: 'blue circle',
    keywords: ['shape', 'icon', 'button'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🟣',
    name: 'purple circle',
    keywords: ['round', 'purple', 'circle'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '🟤',
    name: 'brown circle',
    keywords: ['round', 'brown', 'circle'],
    category: 'symbols',
    color: '#8B4513',
  },
  {
    emoji: '⚫',
    name: 'black circle',
    keywords: ['shape', 'button', 'round'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '⚪',
    name: 'white circle',
    keywords: ['shape', 'round', 'circle'],
    category: 'symbols',
    color: '#FFFFFF',
  },
  {
    emoji: '🟥',
    name: 'red square',
    keywords: ['shape', 'red', 'square'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🟧',
    name: 'orange square',
    keywords: ['shape', 'orange', 'square'],
    category: 'symbols',
    color: '#FF8C00',
  },
  {
    emoji: '🟨',
    name: 'yellow square',
    keywords: ['shape', 'yellow', 'square'],
    category: 'symbols',
    color: '#FFD700',
  },
  {
    emoji: '🟩',
    name: 'green square',
    keywords: ['shape', 'green', 'square'],
    category: 'symbols',
    color: '#90EE90',
  },
  {
    emoji: '🟦',
    name: 'blue square',
    keywords: ['shape', 'blue', 'square'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🟪',
    name: 'purple square',
    keywords: ['shape', 'purple', 'square'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '🟫',
    name: 'brown square',
    keywords: ['shape', 'brown', 'square'],
    category: 'symbols',
    color: '#8B4513',
  },
  {
    emoji: '⬛',
    name: 'black large square',
    keywords: ['shape', 'icon', 'button'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '⬜',
    name: 'white large square',
    keywords: ['shape', 'icon', 'button'],
    category: 'symbols',
    color: '#FFFFFF',
  },
  {
    emoji: '◼️',
    name: 'black medium square',
    keywords: ['shape', 'button', 'icon'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '◻️',
    name: 'white medium square',
    keywords: ['shape', 'stone', 'icon'],
    category: 'symbols',
    color: '#FFFFFF',
  },
  {
    emoji: '◾',
    name: 'black medium-small square',
    keywords: ['icon', 'shape', 'button'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '◽',
    name: 'white medium-small square',
    keywords: ['shape', 'stone', 'icon'],
    category: 'symbols',
    color: '#FFFFFF',
  },
  {
    emoji: '▪️',
    name: 'black small square',
    keywords: ['shape', 'icon', 'button'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '▫️',
    name: 'white small square',
    keywords: ['shape', 'icon', 'button'],
    category: 'symbols',
    color: '#FFFFFF',
  },
  {
    emoji: '🔶',
    name: 'large orange diamond',
    keywords: ['shape', 'jewel', 'gem'],
    category: 'symbols',
    color: '#FF8C00',
  },
  {
    emoji: '🔷',
    name: 'large blue diamond',
    keywords: ['shape', 'jewel', 'gem'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔸',
    name: 'small orange diamond',
    keywords: ['shape', 'jewel', 'gem'],
    category: 'symbols',
    color: '#FF8C00',
  },
  {
    emoji: '🔹',
    name: 'small blue diamond',
    keywords: ['shape', 'jewel', 'gem'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔺',
    name: 'red triangle pointed up',
    keywords: ['shape', 'direction', 'up'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🔻',
    name: 'red triangle pointed down',
    keywords: ['shape', 'direction', 'bottom'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '💠',
    name: 'diamond with a dot',
    keywords: ['jewel', 'blue', 'gem'],
    category: 'symbols',
    color: '#87CEEB',
  },
  {
    emoji: '🔘',
    name: 'radio button',
    keywords: ['input', 'old', 'music'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔳',
    name: 'white square button',
    keywords: ['shape', 'input', 'button'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '🔲',
    name: 'black square button',
    keywords: ['shape', 'input', 'frame'],
    category: 'symbols',
    color: '#000000',
  },

  // UI symbols
  {
    emoji: '✅',
    name: 'check mark button',
    keywords: ['green-square', 'ok', 'yes'],
    category: 'symbols',
    color: '#90EE90',
  },
  {
    emoji: '☑️',
    name: 'check box with check',
    keywords: ['ok', 'agree', 'vote'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '✔️',
    name: 'check mark',
    keywords: ['ok', 'nike', 'answer'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '❌',
    name: 'cross mark',
    keywords: ['no', 'delete', 'remove'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '❎',
    name: 'cross mark button',
    keywords: ['x', 'green-square', 'no'],
    category: 'symbols',
    color: '#90EE90',
  },
  {
    emoji: '➕',
    name: 'plus',
    keywords: ['math', 'calculation', 'addition'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '➖',
    name: 'minus',
    keywords: ['math', 'calculation', 'subtract'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '➗',
    name: 'divide',
    keywords: ['math', 'calculation', 'divide'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '✖️',
    name: 'multiply',
    keywords: ['math', 'calculation', 'multiply'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '♾️',
    name: 'infinity',
    keywords: ['forever', 'unbounded', 'universal'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '💲',
    name: 'heavy dollar sign',
    keywords: ['money', 'sales', 'payment'],
    category: 'symbols',
    color: '#90EE90',
  },
  {
    emoji: '💱',
    name: 'currency exchange',
    keywords: ['money', 'sales', 'dollar'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '™️',
    name: 'trade mark',
    keywords: ['trademark', 'brand', 'law'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '©️',
    name: 'copyright',
    keywords: ['ip', 'license', 'circle'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '®️',
    name: 'registered',
    keywords: ['alphabet', 'circle', 'registered'],
    category: 'symbols',
    color: '#000000',
  },

  // Arrows
  {
    emoji: '⬆️',
    name: 'up arrow',
    keywords: ['blue-square', 'continue', 'top'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '↗️',
    name: 'up-right arrow',
    keywords: ['blue-square', 'direction', 'diagonal'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '➡️',
    name: 'right arrow',
    keywords: ['blue-square', 'next', 'forward'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '↘️',
    name: 'down-right arrow',
    keywords: ['blue-square', 'direction', 'diagonal'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '⬇️',
    name: 'down arrow',
    keywords: ['blue-square', 'direction', 'bottom'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '↙️',
    name: 'down-left arrow',
    keywords: ['blue-square', 'direction', 'diagonal'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '⬅️',
    name: 'left arrow',
    keywords: ['blue-square', 'previous', 'back'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '↖️',
    name: 'up-left arrow',
    keywords: ['blue-square', 'direction', 'diagonal'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '↕️',
    name: 'up-down arrow',
    keywords: ['blue-square', 'direction', 'vertical'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '↔️',
    name: 'left-right arrow',
    keywords: ['shape', 'direction', 'horizontal'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '↩️',
    name: 'right arrow curving left',
    keywords: ['back', 'return', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '↪️',
    name: 'left arrow curving right',
    keywords: ['blue-square', 'return', 'forward'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '⤴️',
    name: 'right arrow curving up',
    keywords: ['blue-square', 'direction', 'up'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '⤵️',
    name: 'right arrow curving down',
    keywords: ['blue-square', 'direction', 'bottom'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔃',
    name: 'clockwise vertical arrows',
    keywords: ['sync', 'cycle', 'round'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔄',
    name: 'counterclockwise arrows button',
    keywords: ['blue-square', 'sync', 'cycle'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔙',
    name: 'BACK arrow',
    keywords: ['arrow', 'words', 'return'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔚',
    name: 'END arrow',
    keywords: ['words', 'arrow', 'end'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔛',
    name: 'ON! arrow',
    keywords: ['arrow', 'words', 'on'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔜',
    name: 'SOON arrow',
    keywords: ['arrow', 'words', 'soon'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔝',
    name: 'TOP arrow',
    keywords: ['words', 'blue-square', 'top'],
    category: 'symbols',
    color: '#4169E1',
  },

  // Religious symbols
  {
    emoji: '🛐',
    name: 'place of worship',
    keywords: ['religion', 'church', 'temple'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '⚛️',
    name: 'atom symbol',
    keywords: ['science', 'physics', 'chemistry'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '🕉️',
    name: 'om',
    keywords: ['hinduism', 'buddhism', 'sikhism'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '✡️',
    name: 'star of david',
    keywords: ['judaism', 'jewish', 'star'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '☸️',
    name: 'wheel of dharma',
    keywords: ['hinduism', 'buddhism', 'sikhism'],
    category: 'symbols',
    color: '#DAA520',
  },
  {
    emoji: '☯️',
    name: 'yin yang',
    keywords: ['balance', 'opposites', 'harmony'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '✝️',
    name: 'latin cross',
    keywords: ['christianity', 'cross', 'religion'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '☦️',
    name: 'orthodox cross',
    keywords: ['suppedaneum', 'religion', 'cross'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '☪️',
    name: 'star and crescent',
    keywords: ['islam', 'muslim', 'religion'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '☮️',
    name: 'peace symbol',
    keywords: ['hippie', 'peace', 'sign'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '🕎',
    name: 'menorah',
    keywords: ['hanukkah', 'candles', 'jewish'],
    category: 'symbols',
    color: '#FFD700',
  },
  {
    emoji: '🔯',
    name: 'dotted six-pointed star',
    keywords: ['purple-square', 'religion', 'jewish'],
    category: 'symbols',
    color: '#9370DB',
  },

  // Zodiac
  {
    emoji: '♈',
    name: 'aries',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '♉',
    name: 'taurus',
    keywords: ['purple-square', 'sign', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '♊',
    name: 'gemini',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '♋',
    name: 'cancer',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '♌',
    name: 'leo',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '♍',
    name: 'virgo',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '♎',
    name: 'libra',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '♏',
    name: 'scorpio',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '♐',
    name: 'sagittarius',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '♑',
    name: 'capricorn',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '♒',
    name: 'aquarius',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '♓',
    name: 'pisces',
    keywords: ['purple-square', 'sign', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '⛎',
    name: 'ophiuchus',
    keywords: ['sign', 'purple-square', 'constellation'],
    category: 'symbols',
    color: '#9370DB',
  },

  // Audio/Video controls
  {
    emoji: '🔀',
    name: 'shuffle tracks button',
    keywords: ['blue-square', 'shuffle', 'music'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔁',
    name: 'repeat button',
    keywords: ['loop', 'record', 'repeat'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔂',
    name: 'repeat single button',
    keywords: ['blue-square', 'loop', 'repeat'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '▶️',
    name: 'play button',
    keywords: ['blue-square', 'right', 'direction'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '⏩',
    name: 'fast-forward button',
    keywords: ['blue-square', 'play', 'speed'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '⏭️',
    name: 'next track button',
    keywords: ['forward', 'next', 'blue-square'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '⏯️',
    name: 'play or pause button',
    keywords: ['blue-square', 'play', 'pause'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '◀️',
    name: 'reverse button',
    keywords: ['blue-square', 'left', 'direction'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '⏪',
    name: 'fast reverse button',
    keywords: ['play', 'blue-square', 'rewind'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '⏮️',
    name: 'last track button',
    keywords: ['backward', 'previous', 'blue-square'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '🔼',
    name: 'upwards button',
    keywords: ['blue-square', 'triangle', 'direction'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '⏫',
    name: 'fast up button',
    keywords: ['blue-square', 'direction', 'top'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '🔽',
    name: 'downwards button',
    keywords: ['blue-square', 'direction', 'bottom'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '⏬',
    name: 'fast down button',
    keywords: ['blue-square', 'direction', 'bottom'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '⏸️',
    name: 'pause button',
    keywords: ['pause', 'blue-square', 'stop'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '⏹️',
    name: 'stop button',
    keywords: ['blue-square', 'stop', 'square'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '⏺️',
    name: 'record button',
    keywords: ['blue-square', 'record', 'circle'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '⏏️',
    name: 'eject button',
    keywords: ['blue-square', 'eject', 'up'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '🎦',
    name: 'cinema',
    keywords: ['blue-square', 'record', 'film'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔅',
    name: 'dim button',
    keywords: ['sun', 'afternoon', 'warm'],
    category: 'symbols',
    color: '#FFD700',
  },
  {
    emoji: '🔆',
    name: 'bright button',
    keywords: ['sun', 'light', 'brightness'],
    category: 'symbols',
    color: '#FFD700',
  },
  {
    emoji: '📶',
    name: 'antenna bars',
    keywords: ['blue-square', 'reception', 'phone'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '📳',
    name: 'vibration mode',
    keywords: ['orange-square', 'phone', 'vibrate'],
    category: 'symbols',
    color: '#FF8C00',
  },
  {
    emoji: '📴',
    name: 'mobile phone off',
    keywords: ['mute', 'orange-square', 'silence'],
    category: 'symbols',
    color: '#FF8C00',
  },

  // Gender symbols
  {
    emoji: '♀️',
    name: 'female sign',
    keywords: ['woman', 'female', 'girl'],
    category: 'symbols',
    color: '#FF69B4',
  },
  {
    emoji: '♂️',
    name: 'male sign',
    keywords: ['man', 'boy', 'male'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '⚧️',
    name: 'transgender symbol',
    keywords: ['transgender', 'trans', 'gender'],
    category: 'symbols',
    color: '#87CEEB',
  },

  // Other symbols
  {
    emoji: '🟰',
    name: 'heavy equals sign',
    keywords: ['math', 'equality', 'equal'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '‼️',
    name: 'double exclamation mark',
    keywords: ['exclamation', 'surprise', 'bangbang'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '⁉️',
    name: 'exclamation question mark',
    keywords: ['wat', 'punctuation', 'surprise'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '❓',
    name: 'red question mark',
    keywords: ['doubt', 'confused', 'question'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '❔',
    name: 'white question mark',
    keywords: ['doubts', 'gray', 'huh'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '❕',
    name: 'white exclamation mark',
    keywords: ['surprise', 'punctuation', 'gray'],
    category: 'symbols',
    color: '#F5F5F5',
  },
  {
    emoji: '❗',
    name: 'red exclamation mark',
    keywords: ['heavy_exclamation_mark', 'danger', 'surprise'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '〰️',
    name: 'wavy dash',
    keywords: ['draw', 'line', 'moustache'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '⚕️',
    name: 'medical symbol',
    keywords: ['health', 'hospital', 'medical'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '♻️',
    name: 'recycling symbol',
    keywords: ['arrow', 'environment', 'garbage'],
    category: 'symbols',
    color: '#90EE90',
  },
  {
    emoji: '⚜️',
    name: 'fleur-de-lis',
    keywords: ['decorative', 'scout', 'french'],
    category: 'symbols',
    color: '#FFD700',
  },
  {
    emoji: '🔱',
    name: 'trident emblem',
    keywords: ['weapon', 'spear', 'poseidon'],
    category: 'symbols',
    color: '#FFD700',
  },
  {
    emoji: '📛',
    name: 'name badge',
    keywords: ['fire', 'forbid', 'tag'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🔰',
    name: 'japanese symbol for beginner',
    keywords: ['badge', 'shield', 'beginner'],
    category: 'symbols',
    color: '#FFFF00',
  },
  {
    emoji: '⭕',
    name: 'hollow red circle',
    keywords: ['circle', 'round', 'correct'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '➰',
    name: 'curly loop',
    keywords: ['scribble', 'draw', 'shape'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '➿',
    name: 'double curly loop',
    keywords: ['tape', 'cassette', 'loop'],
    category: 'symbols',
    color: '#000000',
  },
  {
    emoji: '〽️',
    name: 'part alternation mark',
    keywords: ['graph', 'presentation', 'stats'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '✳️',
    name: 'eight-spoked asterisk',
    keywords: ['star', 'sparkle', 'green-square'],
    category: 'symbols',
    color: '#90EE90',
  },
  {
    emoji: '✴️',
    name: 'eight-pointed star',
    keywords: ['orange-square', 'shape', 'polygon'],
    category: 'symbols',
    color: '#FF8C00',
  },
  {
    emoji: '❇️',
    name: 'sparkle',
    keywords: ['stars', 'green-square', 'awesome'],
    category: 'symbols',
    color: '#90EE90',
  },

  // Warning signs
  {
    emoji: '⚠️',
    name: 'warning',
    keywords: ['exclamation', 'wip', 'alert'],
    category: 'symbols',
    color: '#FFD700',
  },
  {
    emoji: '🚸',
    name: 'children crossing',
    keywords: ['school', 'warning', 'danger'],
    category: 'symbols',
    color: '#FFD700',
  },

  // Restriction signs
  {
    emoji: '🚫',
    name: 'prohibited',
    keywords: ['forbid', 'stop', 'limit'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🚳',
    name: 'no bicycles',
    keywords: ['cyclist', 'prohibited', 'circle'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🚭',
    name: 'no smoking',
    keywords: ['cigarette', 'blue-square', 'smell'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🚯',
    name: 'no littering',
    keywords: ['trash', 'bin', 'garbage'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🚱',
    name: 'non-potable water',
    keywords: ['drink', 'faucet', 'tap'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🚷',
    name: 'no pedestrians',
    keywords: ['rules', 'crossing', 'walking'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '📵',
    name: 'no mobile phones',
    keywords: ['iphone', 'mute', 'circle'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🔞',
    name: 'no one under eighteen',
    keywords: ['18', 'drink', 'pub'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '☢️',
    name: 'radioactive',
    keywords: ['nuclear', 'danger', 'radiation'],
    category: 'symbols',
    color: '#FFD700',
  },
  {
    emoji: '☣️',
    name: 'biohazard',
    keywords: ['danger', 'biological', 'virus'],
    category: 'symbols',
    color: '#FF8C00',
  },

  // Decorative symbols
  {
    emoji: '💮',
    name: 'white flower',
    keywords: ['japanese', 'spring', 'blossom'],
    category: 'symbols',
    color: '#FFB6C1',
  },
  {
    emoji: '🉐',
    name: 'japanese "bargain" button',
    keywords: ['chinese', 'kanji', 'obtain'],
    category: 'symbols',
    color: '#FF8C00',
  },
  {
    emoji: '㊙️',
    name: 'japanese "secret" button',
    keywords: ['privacy', 'chinese', 'sshh'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '㊗️',
    name: 'japanese "congratulations" button',
    keywords: ['chinese', 'kanji', 'japanese'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🈴',
    name: 'japanese "passing grade" button',
    keywords: ['japanese', 'chinese', 'pass'],
    category: 'symbols',
    color: '#FF8C00',
  },
  {
    emoji: '🈵',
    name: 'japanese "no vacancy" button',
    keywords: ['full', 'chinese', 'japanese'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🈹',
    name: 'japanese "discount" button',
    keywords: ['cut', 'divide', 'chinese'],
    category: 'symbols',
    color: '#FF8C00',
  },
  {
    emoji: '🈲',
    name: 'japanese "prohibited" button',
    keywords: ['kanji', 'japanese', 'chinese'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🅰️',
    name: 'A button (blood type)',
    keywords: ['red-square', 'alphabet', 'letter'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🅱️',
    name: 'B button (blood type)',
    keywords: ['red-square', 'alphabet', 'letter'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🆎',
    name: 'AB button (blood type)',
    keywords: ['red-square', 'alphabet', 'medical'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🆑',
    name: 'CL button',
    keywords: ['alphabet', 'words', 'red-square'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🅾️',
    name: 'O button (blood type)',
    keywords: ['alphabet', 'red-square', 'letter'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🆘',
    name: 'SOS button',
    keywords: ['help', 'red-square', 'words'],
    category: 'symbols',
    color: '#DC143C',
  },
  {
    emoji: '🚼',
    name: 'baby symbol',
    keywords: ['orange-square', 'child', 'baby'],
    category: 'symbols',
    color: '#FFD700',
  },
  {
    emoji: '🚾',
    name: 'water closet',
    keywords: ['toilet', 'restroom', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🅿️',
    name: 'P button',
    keywords: ['cars', 'blue-square', 'alphabet'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '♿',
    name: 'wheelchair symbol',
    keywords: ['blue-square', 'disabled', 'accessibility'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🚹',
    name: `men's room`,
    keywords: ['toilet', 'restroom', 'wc'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🚺',
    name: `women's room`,
    keywords: ['purple-square', 'woman', 'female'],
    category: 'symbols',
    color: '#9370DB',
  },
  {
    emoji: '🚻',
    name: 'restroom',
    keywords: ['blue-square', 'toilet', 'refresh'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🚮',
    name: 'litter in bin sign',
    keywords: ['blue-square', 'sign', 'human'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🈁',
    name: 'japanese "here" button',
    keywords: ['blue-square', 'here', 'katakana'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔣',
    name: 'input symbols',
    keywords: ['blue-square', 'music', 'note'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: 'ℹ️',
    name: 'information',
    keywords: ['blue-square', 'alphabet', 'letter'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔤',
    name: 'input latin letters',
    keywords: ['blue-square', 'alphabet', 'abc'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔡',
    name: 'input latin lowercase',
    keywords: ['blue-square', 'alphabet', 'abc'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔠',
    name: 'input latin uppercase',
    keywords: ['alphabet', 'words', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🆖',
    name: 'NG button',
    keywords: ['blue-square', 'words', 'shape'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🆗',
    name: 'OK button',
    keywords: ['good', 'agree', 'yes'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🆙',
    name: 'UP! button',
    keywords: ['blue-square', 'above', 'high'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🆒',
    name: 'COOL button',
    keywords: ['words', 'blue-square', 'awesome'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🆕',
    name: 'NEW button',
    keywords: ['blue-square', 'words', 'start'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🆓',
    name: 'FREE button',
    keywords: ['blue-square', 'words', 'gratis'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '0️⃣',
    name: 'keycap: 0',
    keywords: ['numbers', 'blue-square', 'null'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '1️⃣',
    name: 'keycap: 1',
    keywords: ['blue-square', 'numbers', 'one'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '2️⃣',
    name: 'keycap: 2',
    keywords: ['numbers', 'prime', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '3️⃣',
    name: 'keycap: 3',
    keywords: ['three', 'numbers', 'prime'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '4️⃣',
    name: 'keycap: 4',
    keywords: ['four', 'numbers', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '5️⃣',
    name: 'keycap: 5',
    keywords: ['five', 'numbers', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '6️⃣',
    name: 'keycap: 6',
    keywords: ['six', 'numbers', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '7️⃣',
    name: 'keycap: 7',
    keywords: ['seven', 'numbers', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '8️⃣',
    name: 'keycap: 8',
    keywords: ['eight', 'blue-square', 'numbers'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '9️⃣',
    name: 'keycap: 9',
    keywords: ['blue-square', 'numbers', 'nine'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔟',
    name: 'keycap: 10',
    keywords: ['numbers', '10', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '🔢',
    name: 'input numbers',
    keywords: ['numbers', 'blue-square', '1234'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '#️⃣',
    name: 'keycap: #',
    keywords: ['symbol', 'blue-square', 'hash'],
    category: 'symbols',
    color: '#4169E1',
  },
  {
    emoji: '*️⃣',
    name: 'keycap: *',
    keywords: ['star', 'keycap', 'asterisk'],
    category: 'symbols',
    color: '#4169E1',
  },
];
