import type { Emoji } from '../../schema';

export const symbolEmojis: Omit<Emoji, 'sentiment'>[] = [
  // Hearts
  {
    emoji: '💋',
    name: 'kiss mark',
    keywords: ['face', 'lips', 'love'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['kiss', 'lips', 'lipstick'],
  },
  {
    emoji: '💌',
    name: 'love letter',
    keywords: ['email', 'like', 'affection'],
    category: 'symbols',
    color: '#FFB6C1',
    tags: ['love-letter', 'heart', 'envelope'],
  },
  {
    emoji: '💘',
    name: 'heart with arrow',
    keywords: ['love', 'like', 'heart'],
    category: 'symbols',
    color: '#FF69B4',
    tags: ['cupid', 'love', 'arrow'],
  },
  {
    emoji: '💝',
    name: 'heart with ribbon',
    keywords: ['love', 'valentines', 'gift'],
    category: 'symbols',
    color: '#FF69B4',
    tags: ['gift', 'heart', 'ribbon'],
  },
  {
    emoji: '💖',
    name: 'sparkling heart',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#FF69B4',
    tags: ['sparkle', 'heart', 'shiny'],
  },
  {
    emoji: '💗',
    name: 'growing heart',
    keywords: ['like', 'love', 'affection'],
    category: 'symbols',
    color: '#FF69B4',
    tags: ['growing', 'heart', 'pulse'],
  },
  {
    emoji: '💓',
    name: 'beating heart',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#FF69B4',
    tags: ['beating', 'heart', 'pulse'],
  },
  {
    emoji: '💞',
    name: 'revolving hearts',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#FF69B4',
    tags: ['revolving', 'hearts', 'spinning'],
  },
  {
    emoji: '💕',
    name: 'two hearts',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#FF69B4',
    tags: ['two-hearts', 'love', 'couple'],
  },
  {
    emoji: '💟',
    name: 'heart decoration',
    keywords: ['purple-square', 'love', 'like'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['heart', 'decoration', 'ornament'],
  },
  {
    emoji: '❣️',
    name: 'heart exclamation',
    keywords: ['decoration', 'love', 'exclamation'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['heart', 'exclamation', 'emphasis'],
  },
  {
    emoji: '💔',
    name: 'broken heart',
    keywords: ['sad', 'sorry', 'break'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['broken-heart', 'sad', 'heartbreak'],
  },
  {
    emoji: '❤️‍🔥',
    name: 'heart on fire',
    keywords: ['passionate', 'ardent', 'burning'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['heart', 'fire', 'passionate'],
  },
  {
    emoji: '❤️‍🩹',
    name: 'mending heart',
    keywords: ['broken heart', 'bandage', 'wounded'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['heart', 'healing', 'mending'],
  },
  {
    emoji: '❤️',
    name: 'red heart',
    keywords: ['love', 'like', 'valentines'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['heart', 'love', 'red'],
  },
  {
    emoji: '🧡',
    name: 'orange heart',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#FF8C00',
    tags: ['heart', 'orange', 'warm'],
  },
  {
    emoji: '💛',
    name: 'yellow heart',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['heart', 'yellow', 'friendship'],
  },
  {
    emoji: '💚',
    name: 'green heart',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#90EE90',
    tags: ['heart', 'green', 'nature'],
  },
  {
    emoji: '💙',
    name: 'blue heart',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['heart', 'blue', 'trust'],
  },
  {
    emoji: '💜',
    name: 'purple heart',
    keywords: ['love', 'like', 'affection'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['heart', 'purple', 'bts'],
  },
  {
    emoji: '🤎',
    name: 'brown heart',
    keywords: ['coffee', 'love', 'like'],
    category: 'symbols',
    color: '#8B4513',
    tags: ['heart', 'brown', 'chocolate'],
  },
  {
    emoji: '🖤',
    name: 'black heart',
    keywords: ['evil', 'dark', 'love'],
    category: 'symbols',
    color: '#000000',
    tags: ['heart', 'black', 'dark'],
  },
  {
    emoji: '🤍',
    name: 'white heart',
    keywords: ['pure', 'love', 'like'],
    category: 'symbols',
    color: '#FFFFFF',
    tags: ['heart', 'white', 'pure'],
  },

  // Emotion symbols
  {
    emoji: '💯',
    name: 'hundred points',
    keywords: ['score', 'perfect', 'numbers'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['100', 'perfect', 'score'],
  },
  {
    emoji: '💢',
    name: 'anger symbol',
    keywords: ['angry', 'violence', 'red'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['anger', 'mad', 'comic'],
  },
  {
    emoji: '💥',
    name: 'collision',
    keywords: ['bomb', 'explode', 'explosion'],
    category: 'symbols',
    color: '#FF8C00',
    tags: ['explosion', 'boom', 'collision'],
  },
  {
    emoji: '💫',
    name: 'dizzy',
    keywords: ['star', 'sparkle', 'shoot'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['dizzy', 'stars', 'spinning'],
  },
  {
    emoji: '💦',
    name: 'sweat droplets',
    keywords: ['water', 'drip', 'oops'],
    category: 'symbols',
    color: '#87CEEB',
    tags: ['sweat', 'water', 'droplets'],
  },
  {
    emoji: '💨',
    name: 'dashing away',
    keywords: ['wind', 'air', 'fast'],
    category: 'symbols',
    color: '#87CEEB',
    tags: ['dash', 'wind', 'speed'],
  },
  {
    emoji: '🕳️',
    name: 'hole',
    keywords: ['embarrassing', 'hole', 'pit'],
    category: 'symbols',
    color: '#000000',
    tags: ['hole', 'pit', 'void'],
  },
  {
    emoji: '💣',
    name: 'bomb',
    keywords: ['boom', 'explode', 'explosion'],
    category: 'symbols',
    color: '#000000',
    tags: ['bomb', 'explosive', 'danger'],
  },
  {
    emoji: '💬',
    name: 'speech balloon',
    keywords: ['bubble', 'words', 'message'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['speech', 'bubble', 'chat'],
  },
  {
    emoji: '👁️‍🗨️',
    name: 'eye in speech bubble',
    keywords: ['info', 'feedback', 'witness'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['witness', 'anti-bullying', 'feedback'],
  },
  {
    emoji: '🗨️',
    name: 'left speech bubble',
    keywords: ['words', 'message', 'talk'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['speech', 'left', 'bubble'],
  },
  {
    emoji: '🗯️',
    name: 'right anger bubble',
    keywords: ['caption', 'speech', 'thinking'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['anger', 'bubble', 'comic'],
  },
  {
    emoji: '💭',
    name: 'thought balloon',
    keywords: ['bubble', 'cloud', 'speech'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['thought', 'thinking', 'bubble'],
  },
  {
    emoji: '💤',
    name: 'zzz',
    keywords: ['sleepy', 'tired', 'dream'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['sleep', 'zzz', 'tired'],
  },

  // Cards
  {
    emoji: '♠️',
    name: 'spade suit',
    keywords: ['poker', 'cards', 'suits'],
    category: 'symbols',
    color: '#000000',
    tags: ['spades', 'cards', 'suit'],
  },
  {
    emoji: '♥️',
    name: 'heart suit',
    keywords: ['poker', 'cards', 'suits'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['hearts', 'cards', 'suit'],
  },
  {
    emoji: '♦️',
    name: 'diamond suit',
    keywords: ['poker', 'cards', 'suits'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['diamonds', 'cards', 'suit'],
  },
  {
    emoji: '♣️',
    name: 'club suit',
    keywords: ['poker', 'cards', 'suits'],
    category: 'symbols',
    color: '#000000',
    tags: ['clubs', 'cards', 'suit'],
  },
  {
    emoji: '🃏',
    name: 'joker',
    keywords: ['poker', 'cards', 'game'],
    category: 'symbols',
    color: '#000000',
    tags: ['joker', 'cards', 'wild'],
  },
  {
    emoji: '🎴',
    name: 'flower playing cards',
    keywords: ['game', 'sunset', 'red'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['hanafuda', 'cards', 'japanese'],
  },
  {
    emoji: '🀄',
    name: 'mahjong red dragon',
    keywords: ['game', 'play', 'chinese'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['mahjong', 'dragon', 'tile'],
  },

  // Time and cycles
  {
    emoji: '🕐',
    name: `clock face one o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['clock', '1:00', 'time'],
  },
  {
    emoji: '🕑',
    name: `clock face two o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['clock', '2:00', 'time'],
  },
  {
    emoji: '🕒',
    name: `clock face three o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['clock', '3:00', 'time'],
  },
  {
    emoji: '🕓',
    name: `clock face four o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['clock', '4:00', 'time'],
  },
  {
    emoji: '🕔',
    name: `clock face five o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['clock', '5:00', 'time'],
  },
  {
    emoji: '🕕',
    name: `clock face six o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['clock', '6:00', 'time'],
  },
  {
    emoji: '🕖',
    name: `clock face seven o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['clock', '7:00', 'time'],
  },
  {
    emoji: '🕗',
    name: `clock face eight o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['clock', '8:00', 'time'],
  },
  {
    emoji: '🕘',
    name: `clock face nine o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['clock', '9:00', 'time'],
  },
  {
    emoji: '🕙',
    name: `clock face ten o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['clock', '10:00', 'time'],
  },
  {
    emoji: '🕚',
    name: `clock face eleven o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['clock', '11:00', 'time'],
  },
  {
    emoji: '🕛',
    name: `clock face twelve o'clock`,
    keywords: ['time', 'noon', 'midnight'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['clock', '12:00', 'time'],
  },

  // Geometric shapes
  {
    emoji: '🔴',
    name: 'red circle',
    keywords: ['shape', 'error', 'danger'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['circle', 'red', 'stop'],
  },
  {
    emoji: '🟠',
    name: 'orange circle',
    keywords: ['round', 'orange', 'circle'],
    category: 'symbols',
    color: '#FF8C00',
    tags: ['circle', 'orange', 'round'],
  },
  {
    emoji: '🟡',
    name: 'yellow circle',
    keywords: ['round', 'yellow', 'circle'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['circle', 'yellow', 'round'],
  },
  {
    emoji: '🟢',
    name: 'green circle',
    keywords: ['round', 'green', 'circle'],
    category: 'symbols',
    color: '#90EE90',
    tags: ['circle', 'green', 'go'],
  },
  {
    emoji: '🔵',
    name: 'blue circle',
    keywords: ['shape', 'icon', 'button'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['circle', 'blue', 'round'],
  },
  {
    emoji: '🟣',
    name: 'purple circle',
    keywords: ['round', 'purple', 'circle'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['circle', 'purple', 'round'],
  },
  {
    emoji: '🟤',
    name: 'brown circle',
    keywords: ['round', 'brown', 'circle'],
    category: 'symbols',
    color: '#8B4513',
    tags: ['circle', 'brown', 'round'],
  },
  {
    emoji: '⚫',
    name: 'black circle',
    keywords: ['shape', 'button', 'round'],
    category: 'symbols',
    color: '#000000',
    tags: ['circle', 'black', 'round'],
  },
  {
    emoji: '⚪',
    name: 'white circle',
    keywords: ['shape', 'round', 'circle'],
    category: 'symbols',
    color: '#FFFFFF',
    tags: ['circle', 'white', 'round'],
  },
  {
    emoji: '🟥',
    name: 'red square',
    keywords: ['shape', 'red', 'square'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['square', 'red', 'box'],
  },
  {
    emoji: '🟧',
    name: 'orange square',
    keywords: ['shape', 'orange', 'square'],
    category: 'symbols',
    color: '#FF8C00',
    tags: ['square', 'orange', 'box'],
  },
  {
    emoji: '🟨',
    name: 'yellow square',
    keywords: ['shape', 'yellow', 'square'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['square', 'yellow', 'box'],
  },
  {
    emoji: '🟩',
    name: 'green square',
    keywords: ['shape', 'green', 'square'],
    category: 'symbols',
    color: '#90EE90',
    tags: ['square', 'green', 'box'],
  },
  {
    emoji: '🟦',
    name: 'blue square',
    keywords: ['shape', 'blue', 'square'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['square', 'blue', 'box'],
  },
  {
    emoji: '🟪',
    name: 'purple square',
    keywords: ['shape', 'purple', 'square'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['square', 'purple', 'box'],
  },
  {
    emoji: '🟫',
    name: 'brown square',
    keywords: ['shape', 'brown', 'square'],
    category: 'symbols',
    color: '#8B4513',
    tags: ['square', 'brown', 'box'],
  },
  {
    emoji: '⬛',
    name: 'black large square',
    keywords: ['shape', 'icon', 'button'],
    category: 'symbols',
    color: '#000000',
    tags: ['square', 'black', 'large'],
  },
  {
    emoji: '⬜',
    name: 'white large square',
    keywords: ['shape', 'icon', 'button'],
    category: 'symbols',
    color: '#FFFFFF',
    tags: ['square', 'white', 'large'],
  },
  {
    emoji: '◼️',
    name: 'black medium square',
    keywords: ['shape', 'button', 'icon'],
    category: 'symbols',
    color: '#000000',
    tags: ['square', 'black', 'medium'],
  },
  {
    emoji: '◻️',
    name: 'white medium square',
    keywords: ['shape', 'stone', 'icon'],
    category: 'symbols',
    color: '#FFFFFF',
    tags: ['square', 'white', 'medium'],
  },
  {
    emoji: '◾',
    name: 'black medium-small square',
    keywords: ['icon', 'shape', 'button'],
    category: 'symbols',
    color: '#000000',
    tags: ['square', 'black', 'small'],
  },
  {
    emoji: '◽',
    name: 'white medium-small square',
    keywords: ['shape', 'stone', 'icon'],
    category: 'symbols',
    color: '#FFFFFF',
    tags: ['square', 'white', 'small'],
  },
  {
    emoji: '▪️',
    name: 'black small square',
    keywords: ['shape', 'icon', 'button'],
    category: 'symbols',
    color: '#000000',
    tags: ['square', 'black', 'tiny'],
  },
  {
    emoji: '▫️',
    name: 'white small square',
    keywords: ['shape', 'icon', 'button'],
    category: 'symbols',
    color: '#FFFFFF',
    tags: ['square', 'white', 'tiny'],
  },
  {
    emoji: '🔶',
    name: 'large orange diamond',
    keywords: ['shape', 'jewel', 'gem'],
    category: 'symbols',
    color: '#FF8C00',
    tags: ['diamond', 'orange', 'large'],
  },
  {
    emoji: '🔷',
    name: 'large blue diamond',
    keywords: ['shape', 'jewel', 'gem'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['diamond', 'blue', 'large'],
  },
  {
    emoji: '🔸',
    name: 'small orange diamond',
    keywords: ['shape', 'jewel', 'gem'],
    category: 'symbols',
    color: '#FF8C00',
    tags: ['diamond', 'orange', 'small'],
  },
  {
    emoji: '🔹',
    name: 'small blue diamond',
    keywords: ['shape', 'jewel', 'gem'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['diamond', 'blue', 'small'],
  },
  {
    emoji: '🔺',
    name: 'red triangle pointed up',
    keywords: ['shape', 'direction', 'up'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['triangle', 'red', 'up'],
  },
  {
    emoji: '🔻',
    name: 'red triangle pointed down',
    keywords: ['shape', 'direction', 'bottom'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['triangle', 'red', 'down'],
  },
  {
    emoji: '💠',
    name: 'diamond with a dot',
    keywords: ['jewel', 'blue', 'gem'],
    category: 'symbols',
    color: '#87CEEB',
    tags: ['diamond', 'dot', 'kawaii'],
  },
  {
    emoji: '🔘',
    name: 'radio button',
    keywords: ['input', 'old', 'music'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['radio', 'button', 'selected'],
  },
  {
    emoji: '🔳',
    name: 'white square button',
    keywords: ['shape', 'input', 'button'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['button', 'square', 'white'],
  },
  {
    emoji: '🔲',
    name: 'black square button',
    keywords: ['shape', 'input', 'frame'],
    category: 'symbols',
    color: '#000000',
    tags: ['button', 'square', 'black'],
  },

  // UI symbols
  {
    emoji: '✅',
    name: 'check mark button',
    keywords: ['green-square', 'ok', 'yes'],
    category: 'symbols',
    color: '#90EE90',
    tags: ['check', 'done', 'complete'],
  },
  {
    emoji: '☑️',
    name: 'check box with check',
    keywords: ['ok', 'agree', 'vote'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['checkbox', 'checked', 'done'],
  },
  {
    emoji: '✔️',
    name: 'check mark',
    keywords: ['ok', 'nike', 'answer'],
    category: 'symbols',
    color: '#000000',
    tags: ['check', 'mark', 'done'],
  },
  {
    emoji: '❌',
    name: 'cross mark',
    keywords: ['no', 'delete', 'remove'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['x', 'wrong', 'no'],
  },
  {
    emoji: '❎',
    name: 'cross mark button',
    keywords: ['x', 'green-square', 'no'],
    category: 'symbols',
    color: '#90EE90',
    tags: ['x', 'button', 'negative'],
  },
  {
    emoji: '➕',
    name: 'plus',
    keywords: ['math', 'calculation', 'addition'],
    category: 'symbols',
    color: '#000000',
    tags: ['plus', 'add', 'positive'],
  },
  {
    emoji: '➖',
    name: 'minus',
    keywords: ['math', 'calculation', 'subtract'],
    category: 'symbols',
    color: '#000000',
    tags: ['minus', 'subtract', 'negative'],
  },
  {
    emoji: '➗',
    name: 'divide',
    keywords: ['math', 'calculation', 'divide'],
    category: 'symbols',
    color: '#000000',
    tags: ['divide', 'division', 'math'],
  },
  {
    emoji: '✖️',
    name: 'multiply',
    keywords: ['math', 'calculation', 'multiply'],
    category: 'symbols',
    color: '#000000',
    tags: ['multiply', 'x', 'times'],
  },
  {
    emoji: '♾️',
    name: 'infinity',
    keywords: ['forever', 'unbounded', 'universal'],
    category: 'symbols',
    color: '#000000',
    tags: ['infinity', 'forever', 'endless'],
  },
  {
    emoji: '💲',
    name: 'heavy dollar sign',
    keywords: ['money', 'sales', 'payment'],
    category: 'symbols',
    color: '#90EE90',
    tags: ['dollar', 'money', 'currency'],
  },
  {
    emoji: '💱',
    name: 'currency exchange',
    keywords: ['money', 'sales', 'dollar'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['exchange', 'currency', 'money'],
  },
  {
    emoji: '™️',
    name: 'trade mark',
    keywords: ['trademark', 'brand', 'law'],
    category: 'symbols',
    color: '#000000',
    tags: ['trademark', 'tm', 'brand'],
  },
  {
    emoji: '©️',
    name: 'copyright',
    keywords: ['ip', 'license', 'circle'],
    category: 'symbols',
    color: '#000000',
    tags: ['copyright', 'c', 'rights'],
  },
  {
    emoji: '®️',
    name: 'registered',
    keywords: ['alphabet', 'circle', 'registered'],
    category: 'symbols',
    color: '#000000',
    tags: ['registered', 'r', 'trademark'],
  },

  // Arrows
  {
    emoji: '⬆️',
    name: 'up arrow',
    keywords: ['blue-square', 'continue', 'top'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['arrow', 'up', 'north'],
  },
  {
    emoji: '↗️',
    name: 'up-right arrow',
    keywords: ['blue-square', 'direction', 'diagonal'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['arrow', 'northeast', 'diagonal'],
  },
  {
    emoji: '➡️',
    name: 'right arrow',
    keywords: ['blue-square', 'next', 'forward'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['arrow', 'right', 'east'],
  },
  {
    emoji: '↘️',
    name: 'down-right arrow',
    keywords: ['blue-square', 'direction', 'diagonal'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['arrow', 'southeast', 'diagonal'],
  },
  {
    emoji: '⬇️',
    name: 'down arrow',
    keywords: ['blue-square', 'direction', 'bottom'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['arrow', 'down', 'south'],
  },
  {
    emoji: '↙️',
    name: 'down-left arrow',
    keywords: ['blue-square', 'direction', 'diagonal'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['arrow', 'southwest', 'diagonal'],
  },
  {
    emoji: '⬅️',
    name: 'left arrow',
    keywords: ['blue-square', 'previous', 'back'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['arrow', 'left', 'west'],
  },
  {
    emoji: '↖️',
    name: 'up-left arrow',
    keywords: ['blue-square', 'direction', 'diagonal'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['arrow', 'northwest', 'diagonal'],
  },
  {
    emoji: '↕️',
    name: 'up-down arrow',
    keywords: ['blue-square', 'direction', 'vertical'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['arrow', 'vertical', 'up-down'],
  },
  {
    emoji: '↔️',
    name: 'left-right arrow',
    keywords: ['shape', 'direction', 'horizontal'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['arrow', 'horizontal', 'left-right'],
  },
  {
    emoji: '↩️',
    name: 'right arrow curving left',
    keywords: ['back', 'return', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['arrow', 'return', 'back'],
  },
  {
    emoji: '↪️',
    name: 'left arrow curving right',
    keywords: ['blue-square', 'return', 'forward'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['arrow', 'forward', 'enter'],
  },
  {
    emoji: '⤴️',
    name: 'right arrow curving up',
    keywords: ['blue-square', 'direction', 'up'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['arrow', 'up', 'curve'],
  },
  {
    emoji: '⤵️',
    name: 'right arrow curving down',
    keywords: ['blue-square', 'direction', 'bottom'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['arrow', 'down', 'curve'],
  },
  {
    emoji: '🔃',
    name: 'clockwise vertical arrows',
    keywords: ['sync', 'cycle', 'round'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['refresh', 'clockwise', 'sync'],
  },
  {
    emoji: '🔄',
    name: 'counterclockwise arrows button',
    keywords: ['blue-square', 'sync', 'cycle'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['refresh', 'counter', 'sync'],
  },
  {
    emoji: '🔙',
    name: 'BACK arrow',
    keywords: ['arrow', 'words', 'return'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['back', 'arrow', 'return'],
  },
  {
    emoji: '🔚',
    name: 'END arrow',
    keywords: ['words', 'arrow', 'end'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['end', 'arrow', 'finish'],
  },
  {
    emoji: '🔛',
    name: 'ON! arrow',
    keywords: ['arrow', 'words', 'on'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['on', 'arrow', 'exclamation'],
  },
  {
    emoji: '🔜',
    name: 'SOON arrow',
    keywords: ['arrow', 'words', 'soon'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['soon', 'arrow', 'coming'],
  },
  {
    emoji: '🔝',
    name: 'TOP arrow',
    keywords: ['words', 'blue-square', 'top'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['top', 'arrow', 'up'],
  },

  // Religious symbols
  {
    emoji: '🛐',
    name: 'place of worship',
    keywords: ['religion', 'church', 'temple'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['worship', 'pray', 'religion'],
  },
  {
    emoji: '⚛️',
    name: 'atom symbol',
    keywords: ['science', 'physics', 'chemistry'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['atom', 'science', 'nuclear'],
  },
  {
    emoji: '🕉️',
    name: 'om',
    keywords: ['hinduism', 'buddhism', 'sikhism'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['om', 'hindu', 'sacred'],
  },
  {
    emoji: '✡️',
    name: 'star of david',
    keywords: ['judaism', 'jewish', 'star'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['jewish', 'star', 'david'],
  },
  {
    emoji: '☸️',
    name: 'wheel of dharma',
    keywords: ['hinduism', 'buddhism', 'sikhism'],
    category: 'symbols',
    color: '#DAA520',
    tags: ['dharma', 'buddhist', 'wheel'],
  },
  {
    emoji: '☯️',
    name: 'yin yang',
    keywords: ['balance', 'opposites', 'harmony'],
    category: 'symbols',
    color: '#000000',
    tags: ['yin-yang', 'balance', 'tao'],
  },
  {
    emoji: '✝️',
    name: 'latin cross',
    keywords: ['christianity', 'cross', 'religion'],
    category: 'symbols',
    color: '#000000',
    tags: ['cross', 'christian', 'latin'],
  },
  {
    emoji: '☦️',
    name: 'orthodox cross',
    keywords: ['suppedaneum', 'religion', 'cross'],
    category: 'symbols',
    color: '#000000',
    tags: ['cross', 'orthodox', 'christian'],
  },
  {
    emoji: '☪️',
    name: 'star and crescent',
    keywords: ['islam', 'muslim', 'religion'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['islam', 'muslim', 'crescent'],
  },
  {
    emoji: '☮️',
    name: 'peace symbol',
    keywords: ['hippie', 'peace', 'sign'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['peace', 'symbol', 'hippie'],
  },
  {
    emoji: '🕎',
    name: 'menorah',
    keywords: ['hanukkah', 'candles', 'jewish'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['menorah', 'jewish', 'hanukkah'],
  },
  {
    emoji: '🔯',
    name: 'dotted six-pointed star',
    keywords: ['purple-square', 'religion', 'jewish'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['star', 'six-pointed', 'hexagram'],
  },

  // Zodiac
  {
    emoji: '♈',
    name: 'aries',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['aries', 'zodiac', 'ram'],
  },
  {
    emoji: '♉',
    name: 'taurus',
    keywords: ['purple-square', 'sign', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['taurus', 'zodiac', 'bull'],
  },
  {
    emoji: '♊',
    name: 'gemini',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['gemini', 'zodiac', 'twins'],
  },
  {
    emoji: '♋',
    name: 'cancer',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['cancer', 'zodiac', 'crab'],
  },
  {
    emoji: '♌',
    name: 'leo',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['leo', 'zodiac', 'lion'],
  },
  {
    emoji: '♍',
    name: 'virgo',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['virgo', 'zodiac', 'maiden'],
  },
  {
    emoji: '♎',
    name: 'libra',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['libra', 'zodiac', 'scales'],
  },
  {
    emoji: '♏',
    name: 'scorpio',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['scorpio', 'zodiac', 'scorpion'],
  },
  {
    emoji: '♐',
    name: 'sagittarius',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['sagittarius', 'zodiac', 'archer'],
  },
  {
    emoji: '♑',
    name: 'capricorn',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['capricorn', 'zodiac', 'goat'],
  },
  {
    emoji: '♒',
    name: 'aquarius',
    keywords: ['sign', 'purple-square', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['aquarius', 'zodiac', 'water'],
  },
  {
    emoji: '♓',
    name: 'pisces',
    keywords: ['purple-square', 'sign', 'zodiac'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['pisces', 'zodiac', 'fish'],
  },
  {
    emoji: '⛎',
    name: 'ophiuchus',
    keywords: ['sign', 'purple-square', 'constellation'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['ophiuchus', 'zodiac', 'serpent'],
  },

  // Audio/Video controls
  {
    emoji: '🔀',
    name: 'shuffle tracks button',
    keywords: ['blue-square', 'shuffle', 'music'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['shuffle', 'random', 'music'],
  },
  {
    emoji: '🔁',
    name: 'repeat button',
    keywords: ['loop', 'record', 'repeat'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['repeat', 'loop', 'music'],
  },
  {
    emoji: '🔂',
    name: 'repeat single button',
    keywords: ['blue-square', 'loop', 'repeat'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['repeat-one', 'loop', 'single'],
  },
  {
    emoji: '▶️',
    name: 'play button',
    keywords: ['blue-square', 'right', 'direction'],
    category: 'symbols',
    color: '#000000',
    tags: ['play', 'start', 'arrow'],
  },
  {
    emoji: '⏩',
    name: 'fast-forward button',
    keywords: ['blue-square', 'play', 'speed'],
    category: 'symbols',
    color: '#000000',
    tags: ['fast-forward', 'speed', 'skip'],
  },
  {
    emoji: '⏭️',
    name: 'next track button',
    keywords: ['forward', 'next', 'blue-square'],
    category: 'symbols',
    color: '#000000',
    tags: ['next', 'skip', 'track'],
  },
  {
    emoji: '⏯️',
    name: 'play or pause button',
    keywords: ['blue-square', 'play', 'pause'],
    category: 'symbols',
    color: '#000000',
    tags: ['play-pause', 'toggle', 'media'],
  },
  {
    emoji: '◀️',
    name: 'reverse button',
    keywords: ['blue-square', 'left', 'direction'],
    category: 'symbols',
    color: '#000000',
    tags: ['reverse', 'back', 'arrow'],
  },
  {
    emoji: '⏪',
    name: 'fast reverse button',
    keywords: ['play', 'blue-square', 'rewind'],
    category: 'symbols',
    color: '#000000',
    tags: ['rewind', 'fast', 'back'],
  },
  {
    emoji: '⏮️',
    name: 'last track button',
    keywords: ['backward', 'previous', 'blue-square'],
    category: 'symbols',
    color: '#000000',
    tags: ['previous', 'back', 'track'],
  },
  {
    emoji: '🔼',
    name: 'upwards button',
    keywords: ['blue-square', 'triangle', 'direction'],
    category: 'symbols',
    color: '#000000',
    tags: ['up', 'triangle', 'button'],
  },
  {
    emoji: '⏫',
    name: 'fast up button',
    keywords: ['blue-square', 'direction', 'top'],
    category: 'symbols',
    color: '#000000',
    tags: ['fast-up', 'double', 'arrow'],
  },
  {
    emoji: '🔽',
    name: 'downwards button',
    keywords: ['blue-square', 'direction', 'bottom'],
    category: 'symbols',
    color: '#000000',
    tags: ['down', 'triangle', 'button'],
  },
  {
    emoji: '⏬',
    name: 'fast down button',
    keywords: ['blue-square', 'direction', 'bottom'],
    category: 'symbols',
    color: '#000000',
    tags: ['fast-down', 'double', 'arrow'],
  },
  {
    emoji: '⏸️',
    name: 'pause button',
    keywords: ['pause', 'blue-square', 'stop'],
    category: 'symbols',
    color: '#000000',
    tags: ['pause', 'stop', 'media'],
  },
  {
    emoji: '⏹️',
    name: 'stop button',
    keywords: ['blue-square', 'stop', 'square'],
    category: 'symbols',
    color: '#000000',
    tags: ['stop', 'square', 'end'],
  },
  {
    emoji: '⏺️',
    name: 'record button',
    keywords: ['blue-square', 'record', 'circle'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['record', 'circle', 'capture'],
  },
  {
    emoji: '⏏️',
    name: 'eject button',
    keywords: ['blue-square', 'eject', 'up'],
    category: 'symbols',
    color: '#000000',
    tags: ['eject', 'remove', 'out'],
  },
  {
    emoji: '🎦',
    name: 'cinema',
    keywords: ['blue-square', 'record', 'film'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['cinema', 'movie', 'film'],
  },
  {
    emoji: '🔅',
    name: 'dim button',
    keywords: ['sun', 'afternoon', 'warm'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['brightness', 'dim', 'low'],
  },
  {
    emoji: '🔆',
    name: 'bright button',
    keywords: ['sun', 'light', 'brightness'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['brightness', 'bright', 'high'],
  },
  {
    emoji: '📶',
    name: 'antenna bars',
    keywords: ['blue-square', 'reception', 'phone'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['signal', 'bars', 'reception'],
  },
  {
    emoji: '📳',
    name: 'vibration mode',
    keywords: ['orange-square', 'phone', 'vibrate'],
    category: 'symbols',
    color: '#FF8C00',
    tags: ['vibrate', 'phone', 'mode'],
  },
  {
    emoji: '📴',
    name: 'mobile phone off',
    keywords: ['mute', 'orange-square', 'silence'],
    category: 'symbols',
    color: '#FF8C00',
    tags: ['phone-off', 'mute', 'airplane'],
  },

  // Gender symbols
  {
    emoji: '♀️',
    name: 'female sign',
    keywords: ['woman', 'female', 'girl'],
    category: 'symbols',
    color: '#FF69B4',
    tags: ['female', 'venus', 'woman'],
  },
  {
    emoji: '♂️',
    name: 'male sign',
    keywords: ['man', 'boy', 'male'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['male', 'mars', 'man'],
  },
  {
    emoji: '⚧️',
    name: 'transgender symbol',
    keywords: ['transgender', 'trans', 'gender'],
    category: 'symbols',
    color: '#87CEEB',
    tags: ['transgender', 'trans', 'gender'],
  },

  // Other symbols
  {
    emoji: '✖️',
    name: 'multiply',
    keywords: ['math', 'calculation', 'multiply'],
    category: 'symbols',
    color: '#000000',
    tags: ['multiply', 'x', 'times'],
  },
  {
    emoji: '➕',
    name: 'plus',
    keywords: ['math', 'calculation', 'addition'],
    category: 'symbols',
    color: '#000000',
    tags: ['plus', 'add', 'positive'],
  },
  {
    emoji: '➖',
    name: 'minus',
    keywords: ['math', 'calculation', 'subtract'],
    category: 'symbols',
    color: '#000000',
    tags: ['minus', 'subtract', 'negative'],
  },
  {
    emoji: '➗',
    name: 'divide',
    keywords: ['math', 'calculation', 'divide'],
    category: 'symbols',
    color: '#000000',
    tags: ['divide', 'division', 'math'],
  },
  {
    emoji: '🟰',
    name: 'heavy equals sign',
    keywords: ['math', 'equality', 'equal'],
    category: 'symbols',
    color: '#000000',
    tags: ['equals', 'equal', 'math'],
  },
  {
    emoji: '♾️',
    name: 'infinity',
    keywords: ['forever', 'unbounded', 'universal'],
    category: 'symbols',
    color: '#000000',
    tags: ['infinity', 'forever', 'endless'],
  },
  {
    emoji: '‼️',
    name: 'double exclamation mark',
    keywords: ['exclamation', 'surprise', 'bangbang'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['exclamation', 'double', 'emphasis'],
  },
  {
    emoji: '⁉️',
    name: 'exclamation question mark',
    keywords: ['wat', 'punctuation', 'surprise'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['interrobang', 'question', 'exclamation'],
  },
  {
    emoji: '❓',
    name: 'red question mark',
    keywords: ['doubt', 'confused', 'question'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['question', 'confused', 'ask'],
  },
  {
    emoji: '❔',
    name: 'white question mark',
    keywords: ['doubts', 'gray', 'huh'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['question', 'white', 'confused'],
  },
  {
    emoji: '❕',
    name: 'white exclamation mark',
    keywords: ['surprise', 'punctuation', 'gray'],
    category: 'symbols',
    color: '#F5F5F5',
    tags: ['exclamation', 'white', 'mild'],
  },
  {
    emoji: '❗',
    name: 'red exclamation mark',
    keywords: ['heavy_exclamation_mark', 'danger', 'surprise'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['exclamation', 'danger', 'alert'],
  },
  {
    emoji: '〰️',
    name: 'wavy dash',
    keywords: ['draw', 'line', 'moustache'],
    category: 'symbols',
    color: '#000000',
    tags: ['wavy', 'line', 'dash'],
  },
  {
    emoji: '💱',
    name: 'currency exchange',
    keywords: ['money', 'sales', 'dollar'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['exchange', 'currency', 'money'],
  },
  {
    emoji: '💲',
    name: 'heavy dollar sign',
    keywords: ['money', 'sales', 'payment'],
    category: 'symbols',
    color: '#90EE90',
    tags: ['dollar', 'money', 'currency'],
  },
  {
    emoji: '⚕️',
    name: 'medical symbol',
    keywords: ['health', 'hospital', 'medical'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['medical', 'health', 'caduceus'],
  },
  {
    emoji: '♻️',
    name: 'recycling symbol',
    keywords: ['arrow', 'environment', 'garbage'],
    category: 'symbols',
    color: '#90EE90',
    tags: ['recycle', 'environment', 'green'],
  },
  {
    emoji: '⚜️',
    name: 'fleur-de-lis',
    keywords: ['decorative', 'scout', 'french'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['fleur-de-lis', 'french', 'royal'],
  },
  {
    emoji: '🔱',
    name: 'trident emblem',
    keywords: ['weapon', 'spear', 'poseidon'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['trident', 'poseidon', 'weapon'],
  },
  {
    emoji: '📛',
    name: 'name badge',
    keywords: ['fire', 'forbid', 'tag'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['name-badge', 'tag', 'identification'],
  },
  {
    emoji: '🔰',
    name: 'japanese symbol for beginner',
    keywords: ['badge', 'shield', 'beginner'],
    category: 'symbols',
    color: '#FFFF00',
    tags: ['beginner', 'japanese', 'new'],
  },
  {
    emoji: '⭕',
    name: 'hollow red circle',
    keywords: ['circle', 'round', 'correct'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['circle', 'correct', 'hollow'],
  },
  {
    emoji: '✅',
    name: 'check mark button',
    keywords: ['green-square', 'ok', 'yes'],
    category: 'symbols',
    color: '#90EE90',
    tags: ['check', 'done', 'complete'],
  },
  {
    emoji: '☑️',
    name: 'check box with check',
    keywords: ['ok', 'agree', 'vote'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['checkbox', 'checked', 'done'],
  },
  {
    emoji: '✔️',
    name: 'check mark',
    keywords: ['ok', 'nike', 'answer'],
    category: 'symbols',
    color: '#000000',
    tags: ['check', 'mark', 'done'],
  },
  {
    emoji: '❌',
    name: 'cross mark',
    keywords: ['no', 'delete', 'remove'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['x', 'wrong', 'no'],
  },
  {
    emoji: '❎',
    name: 'cross mark button',
    keywords: ['x', 'green-square', 'no'],
    category: 'symbols',
    color: '#90EE90',
    tags: ['x', 'button', 'negative'],
  },
  {
    emoji: '➰',
    name: 'curly loop',
    keywords: ['scribble', 'draw', 'shape'],
    category: 'symbols',
    color: '#000000',
    tags: ['loop', 'curly', 'squiggle'],
  },
  {
    emoji: '➿',
    name: 'double curly loop',
    keywords: ['tape', 'cassette', 'loop'],
    category: 'symbols',
    color: '#000000',
    tags: ['loop', 'double', 'voicemail'],
  },
  {
    emoji: '〽️',
    name: 'part alternation mark',
    keywords: ['graph', 'presentation', 'stats'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['alternation', 'mark', 'chart'],
  },
  {
    emoji: '✳️',
    name: 'eight-spoked asterisk',
    keywords: ['star', 'sparkle', 'green-square'],
    category: 'symbols',
    color: '#90EE90',
    tags: ['asterisk', 'star', 'eight'],
  },
  {
    emoji: '✴️',
    name: 'eight-pointed star',
    keywords: ['orange-square', 'shape', 'polygon'],
    category: 'symbols',
    color: '#FF8C00',
    tags: ['star', 'eight-pointed', 'shape'],
  },
  {
    emoji: '❇️',
    name: 'sparkle',
    keywords: ['stars', 'green-square', 'awesome'],
    category: 'symbols',
    color: '#90EE90',
    tags: ['sparkle', 'star', 'shine'],
  },

  // Warning signs
  {
    emoji: '⚠️',
    name: 'warning',
    keywords: ['exclamation', 'wip', 'alert'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['warning', 'caution', 'alert'],
  },
  {
    emoji: '🚸',
    name: 'children crossing',
    keywords: ['school', 'warning', 'danger'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['children', 'crossing', 'school'],
  },
  {
    emoji: '🔱',
    name: 'trident emblem',
    keywords: ['weapon', 'spear', 'poseidon'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['trident', 'neptune', 'weapon'],
  },
  {
    emoji: '⚜️',
    name: 'fleur-de-lis',
    keywords: ['decorative', 'scout', 'french'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['fleur-de-lis', 'french', 'scouts'],
  },
  {
    emoji: '🔆',
    name: 'bright button',
    keywords: ['sun', 'light', 'brightness'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['brightness', 'high', 'sun'],
  },
  {
    emoji: '🔅',
    name: 'dim button',
    keywords: ['sun', 'afternoon', 'warm'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['brightness', 'low', 'dim'],
  },

  // Restriction signs
  {
    emoji: '🚫',
    name: 'prohibited',
    keywords: ['forbid', 'stop', 'limit'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['prohibited', 'no', 'forbidden'],
  },
  {
    emoji: '🚳',
    name: 'no bicycles',
    keywords: ['cyclist', 'prohibited', 'circle'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['no-bicycles', 'prohibited', 'bikes'],
  },
  {
    emoji: '🚭',
    name: 'no smoking',
    keywords: ['cigarette', 'blue-square', 'smell'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['no-smoking', 'prohibited', 'cigarette'],
  },
  {
    emoji: '🚯',
    name: 'no littering',
    keywords: ['trash', 'bin', 'garbage'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['no-littering', 'trash', 'prohibited'],
  },
  {
    emoji: '🚱',
    name: 'non-potable water',
    keywords: ['drink', 'faucet', 'tap'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['non-potable', 'water', 'no-drinking'],
  },
  {
    emoji: '🚷',
    name: 'no pedestrians',
    keywords: ['rules', 'crossing', 'walking'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['no-pedestrians', 'prohibited', 'walking'],
  },
  {
    emoji: '📵',
    name: 'no mobile phones',
    keywords: ['iphone', 'mute', 'circle'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['no-phones', 'prohibited', 'mobile'],
  },
  {
    emoji: '🔞',
    name: 'no one under eighteen',
    keywords: ['18', 'drink', 'pub'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['18+', 'adult', 'restricted'],
  },
  {
    emoji: '☢️',
    name: 'radioactive',
    keywords: ['nuclear', 'danger', 'radiation'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['radioactive', 'nuclear', 'danger'],
  },
  {
    emoji: '☣️',
    name: 'biohazard',
    keywords: ['danger', 'biological', 'virus'],
    category: 'symbols',
    color: '#FF8C00',
    tags: ['biohazard', 'danger', 'biological'],
  },

  // Decorative symbols
  {
    emoji: '💮',
    name: 'white flower',
    keywords: ['japanese', 'spring', 'blossom'],
    category: 'symbols',
    color: '#FFB6C1',
    tags: ['flower', 'white', 'stamp'],
  },
  {
    emoji: '🉐',
    name: 'japanese "bargain" button',
    keywords: ['chinese', 'kanji', 'obtain'],
    category: 'symbols',
    color: '#FF8C00',
    tags: ['bargain', 'japanese', 'deal'],
  },
  {
    emoji: '㊙️',
    name: 'japanese "secret" button',
    keywords: ['privacy', 'chinese', 'sshh'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['secret', 'japanese', 'confidential'],
  },
  {
    emoji: '㊗️',
    name: 'japanese "congratulations" button',
    keywords: ['chinese', 'kanji', 'japanese'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['congratulations', 'japanese', 'celebration'],
  },
  {
    emoji: '🈴',
    name: 'japanese "passing grade" button',
    keywords: ['japanese', 'chinese', 'pass'],
    category: 'symbols',
    color: '#FF8C00',
    tags: ['pass', 'japanese', 'grade'],
  },
  {
    emoji: '🈵',
    name: 'japanese "no vacancy" button',
    keywords: ['full', 'chinese', 'japanese'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['full', 'japanese', 'no-vacancy'],
  },
  {
    emoji: '🈹',
    name: 'japanese "discount" button',
    keywords: ['cut', 'divide', 'chinese'],
    category: 'symbols',
    color: '#FF8C00',
    tags: ['discount', 'japanese', 'sale'],
  },
  {
    emoji: '🈲',
    name: 'japanese "prohibited" button',
    keywords: ['kanji', 'japanese', 'chinese'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['prohibited', 'japanese', 'forbidden'],
  },
  {
    emoji: '🅰️',
    name: 'A button (blood type)',
    keywords: ['red-square', 'alphabet', 'letter'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['a', 'blood-type', 'letter'],
  },
  {
    emoji: '🅱️',
    name: 'B button (blood type)',
    keywords: ['red-square', 'alphabet', 'letter'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['b', 'blood-type', 'letter'],
  },
  {
    emoji: '🆎',
    name: 'AB button (blood type)',
    keywords: ['red-square', 'alphabet', 'medical'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['ab', 'blood-type', 'medical'],
  },
  {
    emoji: '🆑',
    name: 'CL button',
    keywords: ['alphabet', 'words', 'red-square'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['cl', 'clear', 'button'],
  },
  {
    emoji: '🅾️',
    name: 'O button (blood type)',
    keywords: ['alphabet', 'red-square', 'letter'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['o', 'blood-type', 'letter'],
  },
  {
    emoji: '🆘',
    name: 'SOS button',
    keywords: ['help', 'red-square', 'words'],
    category: 'symbols',
    color: '#DC143C',
    tags: ['sos', 'help', 'emergency'],
  },
  {
    emoji: '🚼',
    name: 'baby symbol',
    keywords: ['orange-square', 'child', 'baby'],
    category: 'symbols',
    color: '#FFD700',
    tags: ['baby', 'changing', 'symbol'],
  },
  {
    emoji: '🚾',
    name: 'water closet',
    keywords: ['toilet', 'restroom', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['wc', 'toilet', 'restroom'],
  },
  {
    emoji: '🅿️',
    name: 'P button',
    keywords: ['cars', 'blue-square', 'alphabet'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['parking', 'p', 'car'],
  },
  {
    emoji: '♿',
    name: 'wheelchair symbol',
    keywords: ['blue-square', 'disabled', 'accessibility'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['wheelchair', 'accessible', 'disability'],
  },
  {
    emoji: '🚹',
    name: `men's room`,
    keywords: ['toilet', 'restroom', 'wc'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['mens', 'restroom', 'male'],
  },
  {
    emoji: '🚺',
    name: `women's room`,
    keywords: ['purple-square', 'woman', 'female'],
    category: 'symbols',
    color: '#9370DB',
    tags: ['womens', 'restroom', 'female'],
  },
  {
    emoji: '🚻',
    name: 'restroom',
    keywords: ['blue-square', 'toilet', 'refresh'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['restroom', 'bathroom', 'toilet'],
  },
  {
    emoji: '🚮',
    name: 'litter in bin sign',
    keywords: ['blue-square', 'sign', 'human'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['litter', 'trash', 'bin'],
  },
  {
    emoji: '🎦',
    name: 'cinema',
    keywords: ['blue-square', 'record', 'film'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['cinema', 'movie', 'film'],
  },
  {
    emoji: '📶',
    name: 'antenna bars',
    keywords: ['blue-square', 'reception', 'phone'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['signal', 'bars', 'reception'],
  },
  {
    emoji: '🈁',
    name: 'japanese "here" button',
    keywords: ['blue-square', 'here', 'katakana'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['here', 'japanese', 'koko'],
  },
  {
    emoji: '🔣',
    name: 'input symbols',
    keywords: ['blue-square', 'music', 'note'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['symbols', 'input', 'characters'],
  },
  {
    emoji: 'ℹ️',
    name: 'information',
    keywords: ['blue-square', 'alphabet', 'letter'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['info', 'information', 'i'],
  },
  {
    emoji: '🔤',
    name: 'input latin letters',
    keywords: ['blue-square', 'alphabet', 'abc'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['abc', 'letters', 'alphabet'],
  },
  {
    emoji: '🔡',
    name: 'input latin lowercase',
    keywords: ['blue-square', 'alphabet', 'abc'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['abc', 'lowercase', 'letters'],
  },
  {
    emoji: '🔠',
    name: 'input latin uppercase',
    keywords: ['alphabet', 'words', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['ABC', 'uppercase', 'letters'],
  },
  {
    emoji: '🆖',
    name: 'NG button',
    keywords: ['blue-square', 'words', 'shape'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['ng', 'no-good', 'button'],
  },
  {
    emoji: '🆗',
    name: 'OK button',
    keywords: ['good', 'agree', 'yes'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['ok', 'okay', 'button'],
  },
  {
    emoji: '🆙',
    name: 'UP! button',
    keywords: ['blue-square', 'above', 'high'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['up', 'level-up', 'button'],
  },
  {
    emoji: '🆒',
    name: 'COOL button',
    keywords: ['words', 'blue-square', 'awesome'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['cool', 'awesome', 'button'],
  },
  {
    emoji: '🆕',
    name: 'NEW button',
    keywords: ['blue-square', 'words', 'start'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['new', 'fresh', 'button'],
  },
  {
    emoji: '🆓',
    name: 'FREE button',
    keywords: ['blue-square', 'words', 'gratis'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['free', 'gratis', 'button'],
  },
  {
    emoji: '0️⃣',
    name: 'keycap: 0',
    keywords: ['numbers', 'blue-square', 'null'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['zero', '0', 'number'],
  },
  {
    emoji: '1️⃣',
    name: 'keycap: 1',
    keywords: ['blue-square', 'numbers', 'one'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['one', '1', 'number'],
  },
  {
    emoji: '2️⃣',
    name: 'keycap: 2',
    keywords: ['numbers', 'prime', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['two', '2', 'number'],
  },
  {
    emoji: '3️⃣',
    name: 'keycap: 3',
    keywords: ['three', 'numbers', 'prime'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['three', '3', 'number'],
  },
  {
    emoji: '4️⃣',
    name: 'keycap: 4',
    keywords: ['four', 'numbers', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['four', '4', 'number'],
  },
  {
    emoji: '5️⃣',
    name: 'keycap: 5',
    keywords: ['five', 'numbers', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['five', '5', 'number'],
  },
  {
    emoji: '6️⃣',
    name: 'keycap: 6',
    keywords: ['six', 'numbers', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['six', '6', 'number'],
  },
  {
    emoji: '7️⃣',
    name: 'keycap: 7',
    keywords: ['seven', 'numbers', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['seven', '7', 'number'],
  },
  {
    emoji: '8️⃣',
    name: 'keycap: 8',
    keywords: ['eight', 'blue-square', 'numbers'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['eight', '8', 'number'],
  },
  {
    emoji: '9️⃣',
    name: 'keycap: 9',
    keywords: ['blue-square', 'numbers', 'nine'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['nine', '9', 'number'],
  },
  {
    emoji: '🔟',
    name: 'keycap: 10',
    keywords: ['numbers', '10', 'blue-square'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['ten', '10', 'number'],
  },
  {
    emoji: '🔢',
    name: 'input numbers',
    keywords: ['numbers', 'blue-square', '1234'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['numbers', '1234', 'input'],
  },
  {
    emoji: '#️⃣',
    name: 'keycap: #',
    keywords: ['symbol', 'blue-square', 'hash'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['hash', 'pound', 'number'],
  },
  {
    emoji: '*️⃣',
    name: 'keycap: *',
    keywords: ['star', 'keycap', 'asterisk'],
    category: 'symbols',
    color: '#4169E1',
    tags: ['asterisk', 'star', 'keycap'],
  },
  {
    emoji: '⏏️',
    name: 'eject button',
    keywords: ['blue-square', 'eject', 'up'],
    category: 'symbols',
    color: '#000000',
    tags: ['eject', 'remove', 'button'],
  },
];
