import type { Emoji } from '../../schema';

// Generated from OpenMoji dataset - 224 emojis
// Unicode versions up to 15.1 + OpenMoji extras
export const symbolsEmojisAll: Omit<Emoji, 'sentiment'>[] = [
  {
    emoji: '🏧',
    name: 'atm sign',
    keywords: ['atm', 'automated', 'bank', 'cash', 'money', 'sign', 'teller'],
    category: 'symbols',
    subcategory: 'transport-sign',
    unicode: '1F3E7',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚮',
    name: 'litter in bin sign',
    keywords: ['bin', 'litter', 'litterbin', 'sign'],
    category: 'symbols',
    subcategory: 'transport-sign',
    unicode: '1F6AE',
    version: '1',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚰',
    name: 'potable water',
    keywords: ['drinking', 'potable', 'water'],
    category: 'symbols',
    subcategory: 'transport-sign',
    unicode: '1F6B0',
    version: '1',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♿️',
    name: 'wheelchair symbol',
    keywords: ['access', 'handicap', 'symbol', 'wheelchair'],
    category: 'symbols',
    subcategory: 'transport-sign',
    unicode: '267F',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚹️',
    name: 'men’s room',
    keywords: ['bathroom', 'lavatory', 'man', 'men’s', 'restroom', 'room', 'toilet', 'wc'],
    category: 'symbols',
    subcategory: 'transport-sign',
    unicode: '1F6B9',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚺️',
    name: 'women’s room',
    keywords: ['bathroom', 'lavatory', 'restroom', 'room', 'toilet', 'wc', 'woman', 'women’s'],
    category: 'symbols',
    subcategory: 'transport-sign',
    unicode: '1F6BA',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚻',
    name: 'restroom',
    keywords: ['bathroom', 'lavatory', 'toilet', 'wc'],
    category: 'symbols',
    subcategory: 'transport-sign',
    unicode: '1F6BB',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚼️',
    name: 'baby symbol',
    keywords: ['baby', 'changing', 'symbol'],
    category: 'symbols',
    subcategory: 'transport-sign',
    unicode: '1F6BC',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚾',
    name: 'water closet',
    keywords: ['bathroom', 'closet', 'lavatory', 'restroom', 'toilet', 'water', 'wc'],
    category: 'symbols',
    subcategory: 'transport-sign',
    unicode: '1F6BE',
    version: '0.6',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛂',
    name: 'passport control',
    keywords: ['control', 'passport'],
    category: 'symbols',
    subcategory: 'transport-sign',
    unicode: '1F6C2',
    version: '1',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛃',
    name: 'customs',
    keywords: ['packing'],
    category: 'symbols',
    subcategory: 'transport-sign',
    unicode: '1F6C3',
    version: '1',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛄',
    name: 'baggage claim',
    keywords: ['arrived', 'baggage', 'bags', 'case', 'checked', 'claim', 'journey', 'packing', 'plane', 'ready', 'travel', 'trip'],
    category: 'symbols',
    subcategory: 'transport-sign',
    unicode: '1F6C4',
    version: '1',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛅',
    name: 'left luggage',
    keywords: ['baggage', 'case', 'left', 'locker', 'luggage'],
    category: 'symbols',
    subcategory: 'transport-sign',
    unicode: '1F6C5',
    version: '1',
    color: '#0000FF',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚠️',
    name: 'warning',
    keywords: ['caution'],
    category: 'symbols',
    subcategory: 'warning',
    unicode: '26A0',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚸',
    name: 'children crossing',
    keywords: ['child', 'children', 'crossing', 'pedestrian', 'traffic'],
    category: 'symbols',
    subcategory: 'warning',
    unicode: '1F6B8',
    version: '1',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛔️',
    name: 'no entry',
    keywords: ['do', 'entry', 'fail', 'forbidden', 'no', 'not', 'pass', 'prohibited', 'traffic'],
    category: 'symbols',
    subcategory: 'warning',
    unicode: '26D4',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚫',
    name: 'prohibited',
    keywords: ['entry', 'forbidden', 'no', 'not', 'smoke'],
    category: 'symbols',
    subcategory: 'warning',
    unicode: '1F6AB',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚳',
    name: 'no bicycles',
    keywords: ['bicycle', 'bicycles', 'bike', 'forbidden', 'no', 'not', 'prohibited'],
    category: 'symbols',
    subcategory: 'warning',
    unicode: '1F6B3',
    version: '1',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚭️',
    name: 'no smoking',
    keywords: ['forbidden', 'no', 'not', 'prohibited', 'smoke', 'smoking'],
    category: 'symbols',
    subcategory: 'warning',
    unicode: '1F6AD',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚯',
    name: 'no littering',
    keywords: ['forbidden', 'litter', 'littering', 'no', 'not', 'prohibited'],
    category: 'symbols',
    subcategory: 'warning',
    unicode: '1F6AF',
    version: '1',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚱',
    name: 'non-potable water',
    keywords: ['dry', 'non-drinking', 'non-potable', 'prohibited', 'water'],
    category: 'symbols',
    subcategory: 'warning',
    unicode: '1F6B1',
    version: '1',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚷',
    name: 'no pedestrians',
    keywords: ['forbidden', 'no', 'not', 'pedestrian', 'pedestrians', 'prohibited'],
    category: 'symbols',
    subcategory: 'warning',
    unicode: '1F6B7',
    version: '1',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📵',
    name: 'no mobile phones',
    keywords: ['cell', 'forbidden', 'mobile', 'no', 'not', 'phone', 'phones', 'prohibited', 'telephone'],
    category: 'symbols',
    subcategory: 'warning',
    unicode: '1F4F5',
    version: '1',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔞',
    name: 'no one under eighteen',
    keywords: ['18', 'age', 'eighteen', 'forbidden', 'no', 'not', 'one', 'prohibited', 'restriction', 'underage'],
    category: 'symbols',
    subcategory: 'warning',
    unicode: '1F51E',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'negative' as const,
  },
  {
    emoji: '☢️',
    name: 'radioactive',
    keywords: ['sign'],
    category: 'symbols',
    subcategory: 'warning',
    unicode: '2622',
    version: '1',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '☣️',
    name: 'biohazard',
    keywords: ['sign'],
    category: 'symbols',
    subcategory: 'warning',
    unicode: '2623',
    version: '1',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⬆️',
    name: 'up arrow',
    keywords: ['arrow', 'cardinal', 'direction', 'north', 'up'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '2B06',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '↗️',
    name: 'up-right arrow',
    keywords: ['arrow', 'direction', 'intercardinal', 'northeast', 'up-right'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '2197',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '➡️',
    name: 'right arrow',
    keywords: ['arrow', 'cardinal', 'direction', 'east', 'right'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '27A1',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '↘️',
    name: 'down-right arrow',
    keywords: ['arrow', 'direction', 'down-right', 'intercardinal', 'southeast'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '2198',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⬇️',
    name: 'down arrow',
    keywords: ['arrow', 'cardinal', 'direction', 'down', 'south'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '2B07',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '↙️',
    name: 'down-left arrow',
    keywords: ['arrow', 'direction', 'down-left', 'intercardinal', 'southwest'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '2199',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⬅️',
    name: 'left arrow',
    keywords: ['arrow', 'cardinal', 'direction', 'left', 'west'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '2B05',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '↖️',
    name: 'up-left arrow',
    keywords: ['arrow', 'direction', 'intercardinal', 'northwest', 'up-left'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '2196',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '↕️',
    name: 'up-down arrow',
    keywords: ['arrow', 'up-down'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '2195',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '↔️',
    name: 'left-right arrow',
    keywords: ['arrow', 'left-right'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '2194',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '↩️',
    name: 'right arrow curving left',
    keywords: ['arrow', 'curving', 'left', 'right'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '21A9',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '↪️',
    name: 'left arrow curving right',
    keywords: ['arrow', 'curving', 'left', 'right'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '21AA',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⤴️',
    name: 'right arrow curving up',
    keywords: ['arrow', 'curving', 'right', 'up'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '2934',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⤵️',
    name: 'right arrow curving down',
    keywords: ['arrow', 'curving', 'down', 'right'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '2935',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔃',
    name: 'clockwise vertical arrows',
    keywords: ['arrow', 'arrows', 'clockwise', 'refresh', 'reload', 'vertical'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '1F503',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔄',
    name: 'counterclockwise arrows button',
    keywords: ['again', 'anticlockwise', 'arrow', 'arrows', 'button', 'counterclockwise', 'deja', 'refresh', 'rewindershins', 'vu'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '1F504',
    version: '1',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔙',
    name: 'back arrow',
    keywords: ['arrow', 'back'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '1F519',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔚',
    name: 'end arrow',
    keywords: ['arrow', 'end'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '1F51A',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔛',
    name: 'on! arrow',
    keywords: ['arrow', 'mark', 'on!'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '1F51B',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔜',
    name: 'soon arrow',
    keywords: ['arrow', 'brb', 'omw', 'soon'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '1F51C',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔝',
    name: 'top arrow',
    keywords: ['arrow', 'homie', 'top', 'up'],
    category: 'symbols',
    subcategory: 'arrow',
    unicode: '1F51D',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛐',
    name: 'place of worship',
    keywords: ['place', 'pray', 'religion', 'worship'],
    category: 'symbols',
    subcategory: 'religion',
    unicode: '1F6D0',
    version: '1',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚛️',
    name: 'atom symbol',
    keywords: ['atheist', 'atom', 'symbol'],
    category: 'symbols',
    subcategory: 'religion',
    unicode: '269B',
    version: '1',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕉️',
    name: 'om',
    keywords: ['hindu', 'religion'],
    category: 'symbols',
    subcategory: 'religion',
    unicode: '1F549',
    version: '0.7',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '✡️',
    name: 'star of david',
    keywords: ['david', 'jew', 'jewish', 'judaism', 'religion', 'star'],
    category: 'symbols',
    subcategory: 'religion',
    unicode: '2721',
    version: '0.7',
    color: '#DAA520',
    sentiment: 'positive' as const,
  },
  {
    emoji: '☸️',
    name: 'wheel of dharma',
    keywords: ['buddhist', 'dharma', 'religion', 'wheel'],
    category: 'symbols',
    subcategory: 'religion',
    unicode: '2638',
    version: '0.7',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '☯️',
    name: 'yin yang',
    keywords: ['difficult', 'lives', 'religion', 'tao', 'taoist', 'total', 'yang', 'yin', 'yinyang'],
    category: 'symbols',
    subcategory: 'religion',
    unicode: '262F',
    version: '0.7',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '✝️',
    name: 'latin cross',
    keywords: ['christ', 'christian', 'cross', 'latin', 'religion'],
    category: 'symbols',
    subcategory: 'religion',
    unicode: '271D',
    version: '0.7',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '☦️',
    name: 'orthodox cross',
    keywords: ['christian', 'cross', 'orthodox', 'religion'],
    category: 'symbols',
    subcategory: 'religion',
    unicode: '2626',
    version: '1',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '☪️',
    name: 'star and crescent',
    keywords: ['crescent', 'islam', 'muslim', 'ramadan', 'religion', 'star'],
    category: 'symbols',
    subcategory: 'religion',
    unicode: '262A',
    version: '0.7',
    color: '#DAA520',
    sentiment: 'positive' as const,
  },
  {
    emoji: '☮️',
    name: 'peace symbol',
    keywords: ['healing', 'peace', 'peaceful', 'symbol'],
    category: 'symbols',
    subcategory: 'religion',
    unicode: '262E',
    version: '1',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕎',
    name: 'menorah',
    keywords: ['candelabrum', 'candlestick', 'hanukkah', 'jewish', 'judaism', 'religion'],
    category: 'symbols',
    subcategory: 'religion',
    unicode: '1F54E',
    version: '1',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔯',
    name: 'dotted six-pointed star',
    keywords: ['dotted', 'fortune', 'jewish', 'judaism', 'six-pointed', 'star'],
    category: 'symbols',
    subcategory: 'religion',
    unicode: '1F52F',
    version: '0.6',
    color: '#DAA520',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🪯',
    name: 'khanda',
    keywords: ['deg', 'fateh', 'khalsa', 'religion', 'sikh', 'sikhism', 'tegh'],
    category: 'symbols',
    subcategory: 'religion',
    unicode: '1FAAF',
    version: '15',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♈️',
    name: 'aries',
    keywords: ['aries', 'horoscope', 'ram', 'zodiac'],
    category: 'symbols',
    subcategory: 'zodiac',
    unicode: '2648',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♉️',
    name: 'taurus',
    keywords: ['bull', 'horoscope', 'ox', 'taurus', 'zodiac'],
    category: 'symbols',
    subcategory: 'zodiac',
    unicode: '2649',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♊️',
    name: 'gemini',
    keywords: ['gemini', 'horoscope', 'twins', 'zodiac'],
    category: 'symbols',
    subcategory: 'zodiac',
    unicode: '264A',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♋️',
    name: 'cancer',
    keywords: ['cancer', 'crab', 'horoscope', 'zodiac'],
    category: 'symbols',
    subcategory: 'zodiac',
    unicode: '264B',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♌️',
    name: 'leo',
    keywords: ['horoscope', 'leo', 'lion', 'zodiac'],
    category: 'symbols',
    subcategory: 'zodiac',
    unicode: '264C',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♍️',
    name: 'virgo',
    keywords: ['horoscope', 'virgo', 'zodiac'],
    category: 'symbols',
    subcategory: 'zodiac',
    unicode: '264D',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♎️',
    name: 'libra',
    keywords: ['balance', 'horoscope', 'justice', 'libra', 'scales', 'zodiac'],
    category: 'symbols',
    subcategory: 'zodiac',
    unicode: '264E',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♏️',
    name: 'scorpio',
    keywords: ['horoscope', 'scorpio', 'scorpion', 'scorpius', 'zodiac'],
    category: 'symbols',
    subcategory: 'zodiac',
    unicode: '264F',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♐️',
    name: 'sagittarius',
    keywords: ['archer', 'horoscope', 'sagittarius', 'zodiac'],
    category: 'symbols',
    subcategory: 'zodiac',
    unicode: '2650',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♑️',
    name: 'capricorn',
    keywords: ['capricorn', 'goat', 'horoscope', 'zodiac'],
    category: 'symbols',
    subcategory: 'zodiac',
    unicode: '2651',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♒️',
    name: 'aquarius',
    keywords: ['aquarius', 'bearer', 'horoscope', 'water', 'zodiac'],
    category: 'symbols',
    subcategory: 'zodiac',
    unicode: '2652',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♓️',
    name: 'pisces',
    keywords: ['fish', 'horoscope', 'pisces', 'zodiac'],
    category: 'symbols',
    subcategory: 'zodiac',
    unicode: '2653',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛎️',
    name: 'ophiuchus',
    keywords: ['bearer', 'ophiuchus', 'serpent', 'snake', 'zodiac'],
    category: 'symbols',
    subcategory: 'zodiac',
    unicode: '26CE',
    version: '0.6',
    color: '#9370DB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔀',
    name: 'shuffle tracks button',
    keywords: ['arrow', 'button', 'crossed', 'shuffle', 'tracks'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '1F500',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔁',
    name: 'repeat button',
    keywords: ['arrow', 'button', 'clockwise', 'repeat'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '1F501',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔂',
    name: 'repeat single button',
    keywords: ['arrow', 'button', 'clockwise', 'once', 'repeat', 'single'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '1F502',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '▶️',
    name: 'play button',
    keywords: ['arrow', 'button', 'play', 'right', 'triangle'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '25B6',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏩️',
    name: 'fast-forward button',
    keywords: ['arrow', 'button', 'double', 'fast', 'fast-forward', 'forward'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '23E9',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏭️',
    name: 'next track button',
    keywords: ['arrow', 'button', 'next', 'scene', 'track', 'triangle'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '23ED',
    version: '0.7',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏯️',
    name: 'play or pause button',
    keywords: ['arrow', 'button', 'pause', 'play', 'right', 'triangle'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '23EF',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '◀️',
    name: 'reverse button',
    keywords: ['arrow', 'button', 'left', 'reverse', 'triangle'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '25C0',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏪️',
    name: 'fast reverse button',
    keywords: ['arrow', 'button', 'double', 'fast', 'reverse', 'rewind'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '23EA',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏮️',
    name: 'last track button',
    keywords: ['arrow', 'button', 'last', 'previous', 'scene', 'track', 'triangle'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '23EE',
    version: '0.7',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔼',
    name: 'upwards button',
    keywords: ['arrow', 'button', 'red', 'up', 'upwards'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '1F53C',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏫️',
    name: 'fast up button',
    keywords: ['arrow', 'button', 'double', 'fast', 'up'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '23EB',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔽',
    name: 'downwards button',
    keywords: ['arrow', 'button', 'down', 'downwards', 'red'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '1F53D',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏬️',
    name: 'fast down button',
    keywords: ['arrow', 'button', 'double', 'down', 'fast'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '23EC',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏸️',
    name: 'pause button',
    keywords: ['bar', 'button', 'double', 'pause', 'vertical'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '23F8',
    version: '0.7',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏹️',
    name: 'stop button',
    keywords: ['button', 'square', 'stop'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '23F9',
    version: '0.7',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏺️',
    name: 'record button',
    keywords: ['button', 'circle', 'record'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '23FA',
    version: '0.7',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏏️',
    name: 'eject button',
    keywords: ['button', 'eject'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '23CF',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎦',
    name: 'cinema',
    keywords: ['camera', 'film', 'movie'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '1F3A6',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔅',
    name: 'dim button',
    keywords: ['brightness', 'button', 'dim', 'low'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '1F505',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔆',
    name: 'bright button',
    keywords: ['bright', 'brightness', 'button', 'light'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '1F506',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📶',
    name: 'antenna bars',
    keywords: ['antenna', 'bar', 'bars', 'cell', 'communication', 'mobile', 'phone', 'signal', 'telephone'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '1F4F6',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛜',
    name: 'wireless',
    keywords: ['broadband', 'computer', 'connectivity', 'hotspot', 'internet', 'network', 'router', 'smartphone', 'wi-fi', 'wifi', 'wlan'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '1F6DC',
    version: '15',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📳',
    name: 'vibration mode',
    keywords: ['cell', 'communication', 'mobile', 'mode', 'phone', 'telephone', 'vibration'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '1F4F3',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📴',
    name: 'mobile phone off',
    keywords: ['cell', 'mobile', 'off', 'phone', 'telephone'],
    category: 'symbols',
    subcategory: 'av-symbol',
    unicode: '1F4F4',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♀️',
    name: 'female sign',
    keywords: ['female', 'sign', 'woman'],
    category: 'symbols',
    subcategory: 'gender',
    unicode: '2640',
    version: '4',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♂️',
    name: 'male sign',
    keywords: ['male', 'man', 'sign'],
    category: 'symbols',
    subcategory: 'gender',
    unicode: '2642',
    version: '4',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚧️',
    name: 'transgender symbol',
    keywords: ['symbol', 'transgender'],
    category: 'symbols',
    subcategory: 'gender',
    unicode: '26A7',
    version: '13',
    color: '#FF69B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '✖️',
    name: 'multiply',
    keywords: ['cancel', 'multiplication', 'sign', 'x', '×'],
    category: 'symbols',
    subcategory: 'math',
    unicode: '2716',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '➕️',
    name: 'plus',
    keywords: ['+'],
    category: 'symbols',
    subcategory: 'math',
    unicode: '2795',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '➖️',
    name: 'minus',
    keywords: ['-', 'heavy', 'math', 'sign', '−'],
    category: 'symbols',
    subcategory: 'math',
    unicode: '2796',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '➗️',
    name: 'divide',
    keywords: ['division', 'heavy', 'math', 'sign', '÷'],
    category: 'symbols',
    subcategory: 'math',
    unicode: '2797',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🟰',
    name: 'heavy equals sign',
    keywords: ['answer', 'equal', 'equality', 'equals', 'heavy', 'math', 'sign'],
    category: 'symbols',
    subcategory: 'math',
    unicode: '1F7F0',
    version: '14',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♾️',
    name: 'infinity',
    keywords: ['forever', 'unbounded', 'universal'],
    category: 'symbols',
    subcategory: 'math',
    unicode: '267E',
    version: '11',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '‼️',
    name: 'double exclamation mark',
    keywords: ['!', '!!', 'bangbang', 'double', 'exclamation', 'mark', 'punctuation'],
    category: 'symbols',
    subcategory: 'punctuation',
    unicode: '203C',
    version: '0.6',
    color: '#000000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⁉️',
    name: 'exclamation question mark',
    keywords: ['!', '!?', '?', 'exclamation', 'interrobang', 'mark', 'punctuation', 'question'],
    category: 'symbols',
    subcategory: 'punctuation',
    unicode: '2049',
    version: '0.6',
    color: '#000000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '❓️',
    name: 'red question mark',
    keywords: ['?', 'mark', 'punctuation', 'question', 'red'],
    category: 'symbols',
    subcategory: 'punctuation',
    unicode: '2753',
    version: '0.6',
    color: '#000000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '❔️',
    name: 'white question mark',
    keywords: ['?', 'mark', 'outlined', 'punctuation', 'question', 'white'],
    category: 'symbols',
    subcategory: 'punctuation',
    unicode: '2754',
    version: '0.6',
    color: '#000000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '❕️',
    name: 'white exclamation mark',
    keywords: ['!', 'exclamation', 'mark', 'outlined', 'punctuation', 'white'],
    category: 'symbols',
    subcategory: 'punctuation',
    unicode: '2755',
    version: '0.6',
    color: '#000000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '❗️',
    name: 'red exclamation mark',
    keywords: ['!', 'exclamation', 'mark', 'punctuation', 'red'],
    category: 'symbols',
    subcategory: 'punctuation',
    unicode: '2757',
    version: '0.6',
    color: '#000000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '〰️',
    name: 'wavy dash',
    keywords: ['dash', 'punctuation', 'wavy'],
    category: 'symbols',
    subcategory: 'punctuation',
    unicode: '3030',
    version: '0.6',
    color: '#000000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💱',
    name: 'currency exchange',
    keywords: ['bank', 'currency', 'exchange', 'money'],
    category: 'symbols',
    subcategory: 'currency',
    unicode: '1F4B1',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💲',
    name: 'heavy dollar sign',
    keywords: ['billion', 'cash', 'charge', 'currency', 'dollar', 'heavy', 'million', 'money', 'pay', 'sign'],
    category: 'symbols',
    subcategory: 'currency',
    unicode: '1F4B2',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚕️',
    name: 'medical symbol',
    keywords: ['aesculapius', 'medical', 'medicine', 'staff', 'symbol'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '2695',
    version: '4',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♻️',
    name: 'recycling symbol',
    keywords: ['recycle', 'recycling', 'symbol'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '267B',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚜️',
    name: 'fleur-de-lis',
    keywords: ['knights'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '269C',
    version: '1',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔱',
    name: 'trident emblem',
    keywords: ['anchor', 'emblem', 'poseidon', 'ship', 'tool', 'trident'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '1F531',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '📛',
    name: 'name badge',
    keywords: ['badge', 'name'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '1F4DB',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔰',
    name: 'japanese symbol for beginner',
    keywords: ['beginner', 'chevron', 'green', 'japanese', 'leaf', 'symbol', 'tool', 'yellow'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '1F530',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⭕️',
    name: 'hollow red circle',
    keywords: ['circle', 'heavy', 'hollow', 'large', 'o', 'red'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '2B55',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '✅️',
    name: 'check mark button',
    keywords: ['button', 'check', 'checked', 'checkmark', 'complete', 'completed', 'done', 'fixed', 'mark', 'tick', '✓'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '2705',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '☑️',
    name: 'check box with check',
    keywords: ['ballot', 'box', 'check', 'checked', 'done', 'off', 'tick', '✓'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '2611',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '✔️',
    name: 'check mark',
    keywords: ['check', 'checked', 'checkmark', 'done', 'heavy', 'mark', 'tick', '✓'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '2714',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '❌️',
    name: 'cross mark',
    keywords: ['cancel', 'cross', 'mark', 'multiplication', 'multiply', 'x', '×'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '274C',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '❎️',
    name: 'cross mark button',
    keywords: ['button', 'cross', 'mark', 'multiplication', 'multiply', 'square', 'x', '×'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '274E',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '➰️',
    name: 'curly loop',
    keywords: ['curl', 'curly', 'loop'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '27B0',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '➿️',
    name: 'double curly loop',
    keywords: ['curl', 'curly', 'double', 'loop'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '27BF',
    version: '1',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '〽️',
    name: 'part alternation mark',
    keywords: ['alternation', 'mark', 'part'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '303D',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '✳️',
    name: 'eight-spoked asterisk',
    keywords: ['*', 'asterisk', 'eight-spoked'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '2733',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '✴️',
    name: 'eight-pointed star',
    keywords: ['*', 'eight-pointed', 'star'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '2734',
    version: '0.6',
    color: '#808080',
    sentiment: 'positive' as const,
  },
  {
    emoji: '❇️',
    name: 'sparkle',
    keywords: ['*'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '2747',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '©️',
    name: 'copyright',
    keywords: ['c'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '00A9',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '®️',
    name: 'registered',
    keywords: ['r'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '00AE',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '™️',
    name: 'trade mark',
    keywords: ['mark', 'tm', 'trade', 'trademark'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '2122',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🫟',
    name: 'splatter',
    keywords: ['drip', 'holi', 'ink', 'liquid', 'mess', 'paint', 'spill', 'stain'],
    category: 'symbols',
    subcategory: 'other-symbol',
    unicode: '1FADF',
    version: '16',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '#️⃣',
    name: 'keycap: #',
    keywords: ['keycap'],
    category: 'symbols',
    subcategory: 'keycap',
    unicode: '0023 FE0F 20E3',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '*️⃣',
    name: 'keycap: *',
    keywords: ['keycap'],
    category: 'symbols',
    subcategory: 'keycap',
    unicode: '002A FE0F 20E3',
    version: '2',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '0️⃣',
    name: 'keycap: 0',
    keywords: ['keycap'],
    category: 'symbols',
    subcategory: 'keycap',
    unicode: '0030 FE0F 20E3',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '1️⃣',
    name: 'keycap: 1',
    keywords: ['keycap'],
    category: 'symbols',
    subcategory: 'keycap',
    unicode: '0031 FE0F 20E3',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '2️⃣',
    name: 'keycap: 2',
    keywords: ['keycap'],
    category: 'symbols',
    subcategory: 'keycap',
    unicode: '0032 FE0F 20E3',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '3️⃣',
    name: 'keycap: 3',
    keywords: ['keycap'],
    category: 'symbols',
    subcategory: 'keycap',
    unicode: '0033 FE0F 20E3',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '4️⃣',
    name: 'keycap: 4',
    keywords: ['keycap'],
    category: 'symbols',
    subcategory: 'keycap',
    unicode: '0034 FE0F 20E3',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '5️⃣',
    name: 'keycap: 5',
    keywords: ['keycap'],
    category: 'symbols',
    subcategory: 'keycap',
    unicode: '0035 FE0F 20E3',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '6️⃣',
    name: 'keycap: 6',
    keywords: ['keycap'],
    category: 'symbols',
    subcategory: 'keycap',
    unicode: '0036 FE0F 20E3',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '7️⃣',
    name: 'keycap: 7',
    keywords: ['keycap'],
    category: 'symbols',
    subcategory: 'keycap',
    unicode: '0037 FE0F 20E3',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '8️⃣',
    name: 'keycap: 8',
    keywords: ['keycap'],
    category: 'symbols',
    subcategory: 'keycap',
    unicode: '0038 FE0F 20E3',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '9️⃣',
    name: 'keycap: 9',
    keywords: ['keycap'],
    category: 'symbols',
    subcategory: 'keycap',
    unicode: '0039 FE0F 20E3',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔟',
    name: 'keycap: 10',
    keywords: ['keycap'],
    category: 'symbols',
    subcategory: 'keycap',
    unicode: '1F51F',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔠',
    name: 'input latin uppercase',
    keywords: ['abcd', 'input', 'latin', 'letters', 'uppercase'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F520',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔡',
    name: 'input latin lowercase',
    keywords: ['abcd', 'input', 'latin', 'letters', 'lowercase'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F521',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔢',
    name: 'input numbers',
    keywords: ['1234', 'input', 'numbers'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F522',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔣',
    name: 'input symbols',
    keywords: ['%', '&', 'input', 'symbols', '♪', '〒'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F523',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔤',
    name: 'input latin letters',
    keywords: ['abc', 'alphabet', 'input', 'latin', 'letters'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F524',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🅰️',
    name: 'a button (blood type)',
    keywords: ['blood', 'button', 'type'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F170',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🆎',
    name: 'ab button (blood type)',
    keywords: ['ab', 'blood', 'button', 'type'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F18E',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🅱️',
    name: 'b button (blood type)',
    keywords: ['b', 'blood', 'button', 'type'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F171',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🆑',
    name: 'cl button',
    keywords: ['button', 'cl'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F191',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🆒',
    name: 'cool button',
    keywords: ['button', 'cool'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F192',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🆓',
    name: 'free button',
    keywords: ['button', 'free'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F193',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: 'ℹ️',
    name: 'information',
    keywords: ['i'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '2139',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🆔',
    name: 'id button',
    keywords: ['button', 'id', 'identity'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F194',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: 'Ⓜ️',
    name: 'circled m',
    keywords: ['circle', 'circled', 'm'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '24C2',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🆕',
    name: 'new button',
    keywords: ['button', 'new'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F195',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🆖',
    name: 'ng button',
    keywords: ['button', 'ng'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F196',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🅾️',
    name: 'o button (blood type)',
    keywords: ['blood', 'button', 'o', 'type'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F17E',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🆗',
    name: 'ok button',
    keywords: ['button', 'ok', 'okay'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F197',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🅿️',
    name: 'p button',
    keywords: ['button', 'p', 'parking'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F17F',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🆘',
    name: 'sos button',
    keywords: ['button', 'help', 'sos'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F198',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🆙',
    name: 'up! button',
    keywords: ['button', 'mark', 'up', 'up!'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F199',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🆚',
    name: 'vs button',
    keywords: ['button', 'versus', 'vs'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F19A',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🈁',
    name: 'japanese “here” button',
    keywords: ['button', 'here', 'japanese', 'katakana'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F201',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🈂️',
    name: 'japanese “service charge” button',
    keywords: ['button', 'charge', 'japanese', 'katakana', 'service'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F202',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🈷️',
    name: 'japanese “monthly amount” button',
    keywords: ['amount', 'button', 'ideograph', 'japanese', 'monthly'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F237',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🈶',
    name: 'japanese “not free of charge” button',
    keywords: ['button', 'charge', 'free', 'ideograph', 'japanese', 'not'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F236',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🈯️',
    name: 'japanese “reserved” button',
    keywords: ['button', 'ideograph', 'japanese', 'reserved'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F22F',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🉐',
    name: 'japanese “bargain” button',
    keywords: ['bargain', 'button', 'ideograph', 'japanese'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F250',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🈹',
    name: 'japanese “discount” button',
    keywords: ['button', 'discount', 'ideograph', 'japanese'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F239',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🈚️',
    name: 'japanese “free of charge” button',
    keywords: ['button', 'charge', 'free', 'ideograph', 'japanese'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F21A',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🈲',
    name: 'japanese “prohibited” button',
    keywords: ['button', 'ideograph', 'japanese', 'prohibited'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F232',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🉑',
    name: 'japanese “acceptable” button',
    keywords: ['acceptable', 'button', 'ideograph', 'japanese'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F251',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🈸',
    name: 'japanese “application” button',
    keywords: ['application', 'button', 'ideograph', 'japanese'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F238',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🈴',
    name: 'japanese “passing grade” button',
    keywords: ['button', 'grade', 'ideograph', 'japanese', 'passing'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F234',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🈳',
    name: 'japanese “vacancy” button',
    keywords: ['button', 'ideograph', 'japanese', 'vacancy'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F233',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '㊗️',
    name: 'japanese “congratulations” button',
    keywords: ['button', 'congratulations', 'ideograph', 'japanese'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '3297',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '㊙️',
    name: 'japanese “secret” button',
    keywords: ['button', 'ideograph', 'japanese', 'secret'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '3299',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🈺',
    name: 'japanese “open for business” button',
    keywords: ['business', 'button', 'ideograph', 'japanese', 'open'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F23A',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🈵',
    name: 'japanese “no vacancy” button',
    keywords: ['button', 'ideograph', 'japanese', 'no', 'vacancy'],
    category: 'symbols',
    subcategory: 'alphanum',
    unicode: '1F235',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔴',
    name: 'red circle',
    keywords: ['circle', 'geometric', 'red'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F534',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🟠',
    name: 'orange circle',
    keywords: ['circle', 'orange'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F7E0',
    version: '12',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🟡',
    name: 'yellow circle',
    keywords: ['circle', 'yellow'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F7E1',
    version: '12',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🟢',
    name: 'green circle',
    keywords: ['circle', 'green'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F7E2',
    version: '12',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔵',
    name: 'blue circle',
    keywords: ['blue', 'circle', 'geometric'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F535',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🟣',
    name: 'purple circle',
    keywords: ['circle', 'purple'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F7E3',
    version: '12',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🟤',
    name: 'brown circle',
    keywords: ['brown', 'circle'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F7E4',
    version: '12',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚫️',
    name: 'black circle',
    keywords: ['black', 'circle', 'geometric'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '26AB',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚪️',
    name: 'white circle',
    keywords: ['circle', 'geometric', 'white'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '26AA',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🟥',
    name: 'red square',
    keywords: ['card', 'penalty', 'red', 'square'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F7E5',
    version: '12',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🟧',
    name: 'orange square',
    keywords: ['orange', 'square'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F7E7',
    version: '12',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🟨',
    name: 'yellow square',
    keywords: ['card', 'penalty', 'square', 'yellow'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F7E8',
    version: '12',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🟩',
    name: 'green square',
    keywords: ['green', 'square'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F7E9',
    version: '12',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🟦',
    name: 'blue square',
    keywords: ['blue', 'square'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F7E6',
    version: '12',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🟪',
    name: 'purple square',
    keywords: ['purple', 'square'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F7EA',
    version: '12',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🟫',
    name: 'brown square',
    keywords: ['brown', 'square'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F7EB',
    version: '12',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⬛️',
    name: 'black large square',
    keywords: ['black', 'geometric', 'large', 'square'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '2B1B',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⬜️',
    name: 'white large square',
    keywords: ['geometric', 'large', 'square', 'white'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '2B1C',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '◼️',
    name: 'black medium square',
    keywords: ['black', 'geometric', 'medium', 'square'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '25FC',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '◻️',
    name: 'white medium square',
    keywords: ['geometric', 'medium', 'square', 'white'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '25FB',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '◾️',
    name: 'black medium-small square',
    keywords: ['black', 'geometric', 'medium-small', 'square'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '25FE',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '◽️',
    name: 'white medium-small square',
    keywords: ['geometric', 'medium-small', 'square', 'white'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '25FD',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '▪️',
    name: 'black small square',
    keywords: ['black', 'geometric', 'small', 'square'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '25AA',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '▫️',
    name: 'white small square',
    keywords: ['geometric', 'small', 'square', 'white'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '25AB',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔶',
    name: 'large orange diamond',
    keywords: ['diamond', 'geometric', 'large', 'orange'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F536',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔷',
    name: 'large blue diamond',
    keywords: ['blue', 'diamond', 'geometric', 'large'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F537',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔸',
    name: 'small orange diamond',
    keywords: ['diamond', 'geometric', 'orange', 'small'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F538',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔹',
    name: 'small blue diamond',
    keywords: ['blue', 'diamond', 'geometric', 'small'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F539',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔺',
    name: 'red triangle pointed up',
    keywords: ['geometric', 'pointed', 'red', 'triangle', 'up'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F53A',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔻',
    name: 'red triangle pointed down',
    keywords: ['down', 'geometric', 'pointed', 'red', 'triangle'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F53B',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💠',
    name: 'diamond with a dot',
    keywords: ['comic', 'diamond', 'dot', 'geometric'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F4A0',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔘',
    name: 'radio button',
    keywords: ['button', 'geometric', 'radio'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F518',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔳',
    name: 'white square button',
    keywords: ['button', 'geometric', 'outlined', 'square', 'white'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F533',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔲',
    name: 'black square button',
    keywords: ['black', 'button', 'geometric', 'square'],
    category: 'symbols',
    subcategory: 'geometric',
    unicode: '1F532',
    version: '0.6',
    color: '#FF6347',
    sentiment: 'neutral' as const,
  }
];