import type { Emoji } from '../../schema';

export const travelEmojis: Omit<Emoji, 'sentiment'>[] = [
  // Places - Maps
  {
    emoji: '🗾',
    name: 'map of japan',
    keywords: ['nation', 'country', 'japanese'],
    category: 'travel',
    color: '#90EE90',
    tags: ['japan', 'map', 'island'],
  },
  {
    emoji: '🏔️',
    name: 'snow-capped mountain',
    keywords: ['photo', 'nature', 'environment'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['mountain', 'snow', 'peak'],
  },
  {
    emoji: '⛰️',
    name: 'mountain',
    keywords: ['photo', 'nature', 'environment'],
    category: 'travel',
    color: '#8B4513',
    tags: ['mountain', 'hiking', 'nature'],
  },
  {
    emoji: '🌋',
    name: 'volcano',
    keywords: ['photo', 'nature', 'disaster'],
    category: 'travel',
    color: '#DC143C',
    tags: ['volcano', 'eruption', 'lava'],
  },
  {
    emoji: '🗻',
    name: 'mount fuji',
    keywords: ['photo', 'mountain', 'nature'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['fuji', 'japan', 'mountain'],
  },
  {
    emoji: '🏕️',
    name: 'camping',
    keywords: ['photo', 'outdoors', 'tent'],
    category: 'travel',
    color: '#228B22',
    tags: ['camping', 'tent', 'outdoors'],
  },
  {
    emoji: '🏖️',
    name: 'beach with umbrella',
    keywords: ['weather', 'summer', 'sunny'],
    category: 'travel',
    color: '#FFD700',
    tags: ['beach', 'vacation', 'umbrella'],
  },
  {
    emoji: '🏜️',
    name: 'desert',
    keywords: ['photo', 'warm', 'saharah'],
    category: 'travel',
    color: '#DEB887',
    tags: ['desert', 'dry', 'cactus'],
  },
  {
    emoji: '🏝️',
    name: 'desert island',
    keywords: ['photo', 'tropical', 'mojito'],
    category: 'travel',
    color: '#90EE90',
    tags: ['island', 'tropical', 'palm'],
  },
  {
    emoji: '🏞️',
    name: 'national park',
    keywords: ['photo', 'environment', 'nature'],
    category: 'travel',
    color: '#228B22',
    tags: ['park', 'nature', 'landscape'],
  },

  // Buildings
  {
    emoji: '🏟️',
    name: 'stadium',
    keywords: ['photo', 'place', 'sports'],
    category: 'travel',
    color: '#696969',
    tags: ['stadium', 'sports', 'arena'],
  },
  {
    emoji: '🏛️',
    name: 'classical building',
    keywords: ['art', 'culture', 'history'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['building', 'classical', 'museum'],
  },
  {
    emoji: '🏗️',
    name: 'building construction',
    keywords: ['wip', 'working', 'progress'],
    category: 'travel',
    color: '#FFD700',
    tags: ['construction', 'building', 'crane'],
  },
  {
    emoji: '🧱',
    name: 'brick',
    keywords: ['bricks', 'wall', 'construction'],
    category: 'travel',
    color: '#DC143C',
    tags: ['brick', 'wall', 'building'],
  },
  {
    emoji: '🪨',
    name: 'rock',
    keywords: ['stone', 'boulder', 'heavy'],
    category: 'travel',
    color: '#696969',
    tags: ['rock', 'stone', 'boulder'],
  },
  {
    emoji: '🪵',
    name: 'wood',
    keywords: ['log', 'timber', 'lumber'],
    category: 'travel',
    color: '#8B4513',
    tags: ['wood', 'log', 'timber'],
  },
  {
    emoji: '🛖',
    name: 'hut',
    keywords: ['house', 'structure', 'roundhouse'],
    category: 'travel',
    color: '#8B4513',
    tags: ['hut', 'shelter', 'primitive'],
  },
  {
    emoji: '🏘️',
    name: 'houses',
    keywords: ['buildings', 'photo', 'neighborhood'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['houses', 'neighborhood', 'suburb'],
  },
  {
    emoji: '🏚️',
    name: 'derelict house',
    keywords: ['abandon', 'evict', 'broken'],
    category: 'travel',
    color: '#8B4513',
    tags: ['abandoned', 'house', 'derelict'],
  },
  {
    emoji: '🏠',
    name: 'house',
    keywords: ['building', 'home', 'house'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['house', 'home', 'building'],
  },
  {
    emoji: '🏡',
    name: 'house with garden',
    keywords: ['home', 'plant', 'nature'],
    category: 'travel',
    color: '#90EE90',
    tags: ['house', 'garden', 'home'],
  },
  {
    emoji: '🏢',
    name: 'office building',
    keywords: ['building', 'work', 'enterprise'],
    category: 'travel',
    color: '#696969',
    tags: ['office', 'building', 'work'],
  },
  {
    emoji: '🏣',
    name: 'japanese post office',
    keywords: ['building', 'envelope', 'communication'],
    category: 'travel',
    color: '#DC143C',
    tags: ['post-office', 'japanese', 'mail'],
  },
  {
    emoji: '🏤',
    name: 'post office',
    keywords: ['building', 'email', 'communication'],
    category: 'travel',
    color: '#4169E1',
    tags: ['post-office', 'mail', 'building'],
  },
  {
    emoji: '🏥',
    name: 'hospital',
    keywords: ['building', 'health', 'surgery'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['hospital', 'medical', 'health'],
  },
  {
    emoji: '🏦',
    name: 'bank',
    keywords: ['building', 'money', 'sales'],
    category: 'travel',
    color: '#696969',
    tags: ['bank', 'money', 'building'],
  },
  {
    emoji: '🏨',
    name: 'hotel',
    keywords: ['building', 'accommodation', 'checkin'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['hotel', 'accommodation', 'building'],
  },
  {
    emoji: '🏩',
    name: 'love hotel',
    keywords: ['like', 'affection', 'dating'],
    category: 'travel',
    color: '#FF69B4',
    tags: ['love-hotel', 'romance', 'heart'],
  },
  {
    emoji: '🏪',
    name: 'convenience store',
    keywords: ['building', 'shopping', 'groceries'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['store', 'convenience', '24-7'],
  },
  {
    emoji: '🏫',
    name: 'school',
    keywords: ['building', 'student', 'education'],
    category: 'travel',
    color: '#8B4513',
    tags: ['school', 'education', 'building'],
  },
  {
    emoji: '🏬',
    name: 'department store',
    keywords: ['building', 'shopping', 'mall'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['store', 'department', 'shopping'],
  },
  {
    emoji: '🏭',
    name: 'factory',
    keywords: ['building', 'industry', 'pollution'],
    category: 'travel',
    color: '#696969',
    tags: ['factory', 'industrial', 'smoke'],
  },
  {
    emoji: '🏯',
    name: 'japanese castle',
    keywords: ['photo', 'building', 'castle'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['castle', 'japanese', 'building'],
  },
  {
    emoji: '🏰',
    name: 'castle',
    keywords: ['building', 'royalty', 'history'],
    category: 'travel',
    color: '#D3D3D3',
    tags: ['castle', 'european', 'fairytale'],
  },
  {
    emoji: '💒',
    name: 'wedding',
    keywords: ['love', 'like', 'affection'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['wedding', 'chapel', 'marriage'],
  },
  {
    emoji: '🗼',
    name: 'tokyo tower',
    keywords: ['photo', 'japanese', 'tokyo'],
    category: 'travel',
    color: '#DC143C',
    tags: ['tokyo-tower', 'japan', 'landmark'],
  },
  {
    emoji: '🗽',
    name: 'statue of liberty',
    keywords: ['american', 'newyork', 'liberty'],
    category: 'travel',
    color: '#90EE90',
    tags: ['liberty', 'statue', 'america'],
  },

  // Religious buildings
  {
    emoji: '⛪',
    name: 'church',
    keywords: ['building', 'religion', 'christ'],
    category: 'travel',
    color: '#8B4513',
    tags: ['church', 'christian', 'religion'],
  },
  {
    emoji: '🕌',
    name: 'mosque',
    keywords: ['islam', 'worship', 'minaret'],
    category: 'travel',
    color: '#4169E1',
    tags: ['mosque', 'islam', 'religion'],
  },
  {
    emoji: '🛕',
    name: 'hindu temple',
    keywords: ['temple', 'hindu', 'worship'],
    category: 'travel',
    color: '#FF8C00',
    tags: ['temple', 'hindu', 'religion'],
  },
  {
    emoji: '🕍',
    name: 'synagogue',
    keywords: ['judaism', 'worship', 'temple'],
    category: 'travel',
    color: '#4169E1',
    tags: ['synagogue', 'jewish', 'religion'],
  },
  {
    emoji: '⛩️',
    name: 'shinto shrine',
    keywords: ['temple', 'japan', 'kyoto'],
    category: 'travel',
    color: '#DC143C',
    tags: ['shrine', 'shinto', 'japanese'],
  },
  {
    emoji: '🕋',
    name: 'kaaba',
    keywords: ['mecca', 'mosque', 'islam'],
    category: 'travel',
    color: '#000000',
    tags: ['kaaba', 'mecca', 'islam'],
  },

  // Other structures
  {
    emoji: '⛲',
    name: 'fountain',
    keywords: ['photo', 'summer', 'water'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['fountain', 'water', 'park'],
  },
  {
    emoji: '⛺',
    name: 'tent',
    keywords: ['photo', 'camping', 'outdoors'],
    category: 'travel',
    color: '#FF8C00',
    tags: ['tent', 'camping', 'outdoors'],
  },
  {
    emoji: '🌁',
    name: 'foggy',
    keywords: ['photo', 'mountain', 'bridge'],
    category: 'travel',
    color: '#B0C4DE',
    tags: ['fog', 'bridge', 'misty'],
  },
  {
    emoji: '🌃',
    name: 'night with stars',
    keywords: ['evening', 'city', 'downtown'],
    category: 'travel',
    color: '#191970',
    tags: ['night', 'city', 'stars'],
  },
  {
    emoji: '🏙️',
    name: 'cityscape',
    keywords: ['photo', 'night life', 'urban'],
    category: 'travel',
    color: '#696969',
    tags: ['city', 'skyline', 'urban'],
  },
  {
    emoji: '🌄',
    name: 'sunrise over mountains',
    keywords: ['view', 'vacation', 'photo'],
    category: 'travel',
    color: '#FFD700',
    tags: ['sunrise', 'mountains', 'morning'],
  },
  {
    emoji: '🌅',
    name: 'sunrise',
    keywords: ['morning', 'view', 'vacation'],
    category: 'travel',
    color: '#FF8C00',
    tags: ['sunrise', 'morning', 'sun'],
  },
  {
    emoji: '🌆',
    name: 'cityscape at dusk',
    keywords: ['photo', 'evening', 'sky'],
    category: 'travel',
    color: '#FF69B4',
    tags: ['dusk', 'city', 'evening'],
  },
  {
    emoji: '🌇',
    name: 'sunset',
    keywords: ['photo', 'good morning', 'dawn'],
    category: 'travel',
    color: '#FF8C00',
    tags: ['sunset', 'evening', 'sun'],
  },
  {
    emoji: '🌉',
    name: 'bridge at night',
    keywords: ['photo', 'sanfrancisco', 'bridge'],
    category: 'travel',
    color: '#4169E1',
    tags: ['bridge', 'night', 'lights'],
  },
  {
    emoji: '♨️',
    name: 'hot springs',
    keywords: ['bath', 'warm', 'relax'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['hot-springs', 'onsen', 'steam'],
  },
  {
    emoji: '🎠',
    name: 'carousel horse',
    keywords: ['photo', 'carnival', 'ride'],
    category: 'travel',
    color: '#FF69B4',
    tags: ['carousel', 'horse', 'carnival'],
  },
  {
    emoji: '🎡',
    name: 'ferris wheel',
    keywords: ['photo', 'carnival', 'londoneye'],
    category: 'travel',
    color: '#9370DB',
    tags: ['ferris-wheel', 'carnival', 'ride'],
  },
  {
    emoji: '🎢',
    name: 'roller coaster',
    keywords: ['carnival', 'playground', 'photo'],
    category: 'travel',
    color: '#DC143C',
    tags: ['roller-coaster', 'amusement', 'ride'],
  },
  {
    emoji: '💈',
    name: 'barber pole',
    keywords: ['hair', 'salon', 'style'],
    category: 'travel',
    color: '#DC143C',
    tags: ['barber', 'pole', 'haircut'],
  },
  {
    emoji: '🎪',
    name: 'circus tent',
    keywords: ['festival', 'carnival', 'party'],
    category: 'travel',
    color: '#DC143C',
    tags: ['circus', 'tent', 'carnival'],
  },

  // Transportation - Ground
  {
    emoji: '🚂',
    name: 'locomotive',
    keywords: ['transportation', 'vehicle', 'train'],
    category: 'travel',
    color: '#696969',
    tags: ['train', 'locomotive', 'steam'],
  },
  {
    emoji: '🚃',
    name: 'railway car',
    keywords: ['transportation', 'vehicle', 'train'],
    category: 'travel',
    color: '#4169E1',
    tags: ['train', 'car', 'railway'],
  },
  {
    emoji: '🚄',
    name: 'high-speed train',
    keywords: ['transportation', 'vehicle', 'speed'],
    category: 'travel',
    color: '#4169E1',
    tags: ['train', 'bullet', 'fast'],
  },
  {
    emoji: '🚅',
    name: 'bullet train',
    keywords: ['transportation', 'vehicle', 'speed'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['train', 'shinkansen', 'fast'],
  },
  {
    emoji: '🚆',
    name: 'train',
    keywords: ['transportation', 'vehicle', 'train'],
    category: 'travel',
    color: '#4169E1',
    tags: ['train', 'railway', 'transport'],
  },
  {
    emoji: '🚇',
    name: 'metro',
    keywords: ['transportation', 'blue-square', 'mrt'],
    category: 'travel',
    color: '#4169E1',
    tags: ['metro', 'subway', 'underground'],
  },
  {
    emoji: '🚈',
    name: 'light rail',
    keywords: ['transportation', 'vehicle', 'train'],
    category: 'travel',
    color: '#90EE90',
    tags: ['rail', 'light', 'tram'],
  },
  {
    emoji: '🚉',
    name: 'station',
    keywords: ['transportation', 'vehicle', 'building'],
    category: 'travel',
    color: '#8B4513',
    tags: ['station', 'train', 'platform'],
  },
  {
    emoji: '🚊',
    name: 'tram',
    keywords: ['transportation', 'vehicle', 'trolley'],
    category: 'travel',
    color: '#90EE90',
    tags: ['tram', 'trolley', 'streetcar'],
  },
  {
    emoji: '🚝',
    name: 'monorail',
    keywords: ['transportation', 'vehicle', 'train'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['monorail', 'train', 'elevated'],
  },
  {
    emoji: '🚞',
    name: 'mountain railway',
    keywords: ['transportation', 'vehicle', 'train'],
    category: 'travel',
    color: '#DC143C',
    tags: ['railway', 'mountain', 'cable-car'],
  },
  {
    emoji: '🚋',
    name: 'tram car',
    keywords: ['transportation', 'vehicle', 'carriage'],
    category: 'travel',
    color: '#DC143C',
    tags: ['tram', 'car', 'trolley'],
  },
  {
    emoji: '🚌',
    name: 'bus',
    keywords: ['car', 'vehicle', 'transportation'],
    category: 'travel',
    color: '#4169E1',
    tags: ['bus', 'transport', 'public'],
  },
  {
    emoji: '🚍',
    name: 'oncoming bus',
    keywords: ['vehicle', 'transportation', 'bus'],
    category: 'travel',
    color: '#FFD700',
    tags: ['bus', 'oncoming', 'front'],
  },
  {
    emoji: '🚎',
    name: 'trolleybus',
    keywords: ['bart', 'transportation', 'vehicle'],
    category: 'travel',
    color: '#4169E1',
    tags: ['trolleybus', 'electric', 'bus'],
  },
  {
    emoji: '🚐',
    name: 'minibus',
    keywords: ['vehicle', 'car', 'transportation'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['minibus', 'van', 'shuttle'],
  },
  {
    emoji: '🚑',
    name: 'ambulance',
    keywords: ['health', '911', 'hospital'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['ambulance', 'emergency', 'medical'],
  },
  {
    emoji: '🚒',
    name: 'fire engine',
    keywords: ['transportation', 'cars', 'vehicle'],
    category: 'travel',
    color: '#DC143C',
    tags: ['fire-truck', 'emergency', 'rescue'],
  },
  {
    emoji: '🚓',
    name: 'police car',
    keywords: ['vehicle', 'cars', 'transportation'],
    category: 'travel',
    color: '#000000',
    tags: ['police', 'car', 'cop'],
  },
  {
    emoji: '🚔',
    name: 'oncoming police car',
    keywords: ['vehicle', 'law', 'legal'],
    category: 'travel',
    color: '#000000',
    tags: ['police', 'oncoming', 'lights'],
  },
  {
    emoji: '🚕',
    name: 'taxi',
    keywords: ['uber', 'vehicle', 'cars'],
    category: 'travel',
    color: '#FFD700',
    tags: ['taxi', 'cab', 'transport'],
  },
  {
    emoji: '🚖',
    name: 'oncoming taxi',
    keywords: ['vehicle', 'cars', 'uber'],
    category: 'travel',
    color: '#FFD700',
    tags: ['taxi', 'oncoming', 'cab'],
  },
  {
    emoji: '🚗',
    name: 'automobile',
    keywords: ['red', 'transportation', 'vehicle'],
    category: 'travel',
    color: '#DC143C',
    tags: ['car', 'automobile', 'vehicle'],
  },
  {
    emoji: '🚘',
    name: 'oncoming automobile',
    keywords: ['car', 'vehicle', 'transportation'],
    category: 'travel',
    color: '#4169E1',
    tags: ['car', 'oncoming', 'driving'],
  },
  {
    emoji: '🚙',
    name: 'sport utility vehicle',
    keywords: ['transportation', 'vehicle', 'suv'],
    category: 'travel',
    color: '#4169E1',
    tags: ['suv', 'car', 'vehicle'],
  },
  {
    emoji: '🛻',
    name: 'pickup truck',
    keywords: ['car', 'transportation', 'pick-up'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['truck', 'pickup', 'vehicle'],
  },
  {
    emoji: '🚚',
    name: 'delivery truck',
    keywords: ['cars', 'transportation', 'truck'],
    category: 'travel',
    color: '#90EE90',
    tags: ['truck', 'delivery', 'transport'],
  },
  {
    emoji: '🚛',
    name: 'articulated lorry',
    keywords: ['vehicle', 'cars', 'transportation'],
    category: 'travel',
    color: '#90EE90',
    tags: ['truck', 'lorry', 'semi'],
  },
  {
    emoji: '🚜',
    name: 'tractor',
    keywords: ['vehicle', 'car', 'farming'],
    category: 'travel',
    color: '#228B22',
    tags: ['tractor', 'farm', 'agriculture'],
  },
  {
    emoji: '🏎️',
    name: 'racing car',
    keywords: ['sports', 'race', 'fast'],
    category: 'travel',
    color: '#DC143C',
    tags: ['race-car', 'f1', 'fast'],
  },
  {
    emoji: '🏍️',
    name: 'motorcycle',
    keywords: ['race', 'sports', 'fast'],
    category: 'travel',
    color: '#000000',
    tags: ['motorcycle', 'bike', 'motorbike'],
  },
  {
    emoji: '🛵',
    name: 'motor scooter',
    keywords: ['vehicle', 'vespa', 'sasha'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['scooter', 'vespa', 'moped'],
  },
  {
    emoji: '🦽',
    name: 'manual wheelchair',
    keywords: ['accessibility', 'wheelchair', 'manual'],
    category: 'travel',
    color: '#696969',
    tags: ['wheelchair', 'manual', 'accessibility'],
  },
  {
    emoji: '🦼',
    name: 'motorized wheelchair',
    keywords: ['accessibility', 'wheelchair', 'electric'],
    category: 'travel',
    color: '#4169E1',
    tags: ['wheelchair', 'electric', 'accessibility'],
  },
  {
    emoji: '🛺',
    name: 'auto rickshaw',
    keywords: ['move', 'transportation', 'tuk tuk'],
    category: 'travel',
    color: '#FFD700',
    tags: ['rickshaw', 'tuk-tuk', 'transport'],
  },
  {
    emoji: '🚲',
    name: 'bicycle',
    keywords: ['sports', 'bicycle', 'exercise'],
    category: 'travel',
    color: '#4169E1',
    tags: ['bicycle', 'bike', 'cycling'],
  },
  {
    emoji: '🛴',
    name: 'kick scooter',
    keywords: ['vehicle', 'kick', 'razor'],
    category: 'travel',
    color: '#C0C0C0',
    tags: ['scooter', 'kick', 'ride'],
  },
  {
    emoji: '🛹',
    name: 'skateboard',
    keywords: ['board', 'skateboard', 'sport'],
    category: 'travel',
    color: '#8B4513',
    tags: ['skateboard', 'skating', 'board'],
  },
  {
    emoji: '🛼',
    name: 'roller skate',
    keywords: ['footwear', 'sports', 'skate'],
    category: 'travel',
    color: '#FF69B4',
    tags: ['roller-skate', 'skating', 'retro'],
  },
  {
    emoji: '🚏',
    name: 'bus stop',
    keywords: ['transportation', 'wait', 'stop'],
    category: 'travel',
    color: '#4169E1',
    tags: ['bus-stop', 'waiting', 'public'],
  },
  {
    emoji: '🛣️',
    name: 'motorway',
    keywords: ['road', 'cupertino', 'interstate'],
    category: 'travel',
    color: '#696969',
    tags: ['highway', 'road', 'motorway'],
  },
  {
    emoji: '🛤️',
    name: 'railway track',
    keywords: ['train', 'transportation', 'track'],
    category: 'travel',
    color: '#8B4513',
    tags: ['tracks', 'railway', 'railroad'],
  },
  {
    emoji: '🛢️',
    name: 'oil drum',
    keywords: ['barrell', 'oil', 'petroleum'],
    category: 'travel',
    color: '#DC143C',
    tags: ['oil', 'drum', 'barrel'],
  },
  {
    emoji: '⛽',
    name: 'fuel pump',
    keywords: ['gas station', 'petroleum', 'fuel'],
    category: 'travel',
    color: '#DC143C',
    tags: ['gas', 'fuel', 'pump'],
  },
  {
    emoji: '🚨',
    name: 'police car light',
    keywords: ['police', 'ambulance', '911'],
    category: 'travel',
    color: '#DC143C',
    tags: ['siren', 'emergency', 'light'],
  },
  {
    emoji: '🚥',
    name: 'horizontal traffic light',
    keywords: ['transportation', 'signal', 'traffic'],
    category: 'travel',
    color: '#FFD700',
    tags: ['traffic-light', 'horizontal', 'signal'],
  },
  {
    emoji: '🚦',
    name: 'vertical traffic light',
    keywords: ['transportation', 'driving', 'signal'],
    category: 'travel',
    color: '#90EE90',
    tags: ['traffic-light', 'vertical', 'signal'],
  },
  {
    emoji: '🛑',
    name: 'stop sign',
    keywords: ['stop', 'sign', 'octagonal'],
    category: 'travel',
    color: '#DC143C',
    tags: ['stop', 'sign', 'traffic'],
  },
  {
    emoji: '🚧',
    name: 'construction',
    keywords: ['wip', 'progress', 'caution'],
    category: 'travel',
    color: '#FF8C00',
    tags: ['construction', 'warning', 'barrier'],
  },

  // Transportation - Sea
  {
    emoji: '⚓',
    name: 'anchor',
    keywords: ['ship', 'ferry', 'sea'],
    category: 'travel',
    color: '#696969',
    tags: ['anchor', 'ship', 'nautical'],
  },
  {
    emoji: '⛵',
    name: 'sailboat',
    keywords: ['ship', 'summer', 'transportation'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['sailboat', 'sailing', 'yacht'],
  },
  {
    emoji: '🛶',
    name: 'canoe',
    keywords: ['boat', 'paddle', 'water'],
    category: 'travel',
    color: '#8B4513',
    tags: ['canoe', 'paddle', 'boat'],
  },
  {
    emoji: '🚤',
    name: 'speedboat',
    keywords: ['ship', 'transportation', 'vehicle'],
    category: 'travel',
    color: '#4169E1',
    tags: ['speedboat', 'fast', 'boat'],
  },
  {
    emoji: '🛳️',
    name: 'passenger ship',
    keywords: ['yacht', 'cruise', 'ferry'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['cruise', 'ship', 'passenger'],
  },
  {
    emoji: '⛴️',
    name: 'ferry',
    keywords: ['ship', 'transport', 'boat'],
    category: 'travel',
    color: '#4169E1',
    tags: ['ferry', 'boat', 'transport'],
  },
  {
    emoji: '🛥️',
    name: 'motor boat',
    keywords: ['ship', 'motorboat', 'boat'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['motorboat', 'boat', 'speed'],
  },
  {
    emoji: '🚢',
    name: 'ship',
    keywords: ['transportation', 'titanic', 'deploy'],
    category: 'travel',
    color: '#696969',
    tags: ['ship', 'vessel', 'ocean'],
  },

  // Transportation - Air
  {
    emoji: '✈️',
    name: 'airplane',
    keywords: ['vehicle', 'transportation', 'flight'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['airplane', 'flight', 'travel'],
  },
  {
    emoji: '🛩️',
    name: 'small airplane',
    keywords: ['flight', 'transportation', 'fly'],
    category: 'travel',
    color: '#DC143C',
    tags: ['airplane', 'small', 'private'],
  },
  {
    emoji: '🛫',
    name: 'airplane departure',
    keywords: ['airport', 'flight', 'landing'],
    category: 'travel',
    color: '#4169E1',
    tags: ['takeoff', 'departure', 'airplane'],
  },
  {
    emoji: '🛬',
    name: 'airplane arrival',
    keywords: ['airport', 'flight', 'boarding'],
    category: 'travel',
    color: '#4169E1',
    tags: ['landing', 'arrival', 'airplane'],
  },
  {
    emoji: '🪂',
    name: 'parachute',
    keywords: ['fly', 'glide', 'parasail'],
    category: 'travel',
    color: '#DC143C',
    tags: ['parachute', 'skydiving', 'flying'],
  },
  {
    emoji: '💺',
    name: 'seat',
    keywords: ['sit', 'airplane', 'transport'],
    category: 'travel',
    color: '#4169E1',
    tags: ['seat', 'chair', 'airplane'],
  },
  {
    emoji: '🚁',
    name: 'helicopter',
    keywords: ['transportation', 'vehicle', 'fly'],
    category: 'travel',
    color: '#696969',
    tags: ['helicopter', 'chopper', 'flying'],
  },
  {
    emoji: '🚟',
    name: 'suspension railway',
    keywords: ['vehicle', 'transportation', 'railway'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['railway', 'suspension', 'cable'],
  },
  {
    emoji: '🚠',
    name: 'mountain cableway',
    keywords: ['transportation', 'vehicle', 'ski'],
    category: 'travel',
    color: '#DC143C',
    tags: ['cable-car', 'mountain', 'gondola'],
  },
  {
    emoji: '🚡',
    name: 'aerial tramway',
    keywords: ['transportation', 'vehicle', 'ski'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['tramway', 'aerial', 'cable'],
  },
  {
    emoji: '🛰️',
    name: 'satellite',
    keywords: ['communication', 'gps', 'orbit'],
    category: 'travel',
    color: '#C0C0C0',
    tags: ['satellite', 'space', 'orbit'],
  },
  {
    emoji: '🚀',
    name: 'rocket',
    keywords: ['launch', 'ship', 'staffmode'],
    category: 'travel',
    color: '#DC143C',
    tags: ['rocket', 'space', 'launch'],
  },
  {
    emoji: '🛸',
    name: 'flying saucer',
    keywords: ['transportation', 'vehicle', 'ufo'],
    category: 'travel',
    color: '#C0C0C0',
    tags: ['ufo', 'alien', 'spaceship'],
  },

  // Hotel and tourism
  {
    emoji: '🛎️',
    name: 'bellhop bell',
    keywords: ['service', 'hotel', 'bell'],
    category: 'travel',
    color: '#FFD700',
    tags: ['bell', 'hotel', 'service'],
  },
  {
    emoji: '🧳',
    name: 'luggage',
    keywords: ['packing', 'travel', 'suitcase'],
    category: 'travel',
    color: '#8B4513',
    tags: ['luggage', 'suitcase', 'travel'],
  },

  // Time
  {
    emoji: '⌛',
    name: 'hourglass done',
    keywords: ['time', 'clock', 'oldschool'],
    category: 'travel',
    color: '#DEB887',
    tags: ['hourglass', 'time', 'done'],
  },
  {
    emoji: '⏳',
    name: 'hourglass not done',
    keywords: ['oldschool', 'time', 'countdown'],
    category: 'travel',
    color: '#DEB887',
    tags: ['hourglass', 'time', 'waiting'],
  },
  {
    emoji: '⌚',
    name: 'watch',
    keywords: ['time', 'accessories', 'apple'],
    category: 'travel',
    color: '#C0C0C0',
    tags: ['watch', 'time', 'wrist'],
  },
  {
    emoji: '⏰',
    name: 'alarm clock',
    keywords: ['time', 'wake', 'morning'],
    category: 'travel',
    color: '#DC143C',
    tags: ['alarm', 'clock', 'wake'],
  },
  {
    emoji: '⏱️',
    name: 'stopwatch',
    keywords: ['time', 'deadline', 'racing'],
    category: 'travel',
    color: '#C0C0C0',
    tags: ['stopwatch', 'timer', 'sports'],
  },
  {
    emoji: '⏲️',
    name: 'timer clock',
    keywords: ['alarm', 'kitchen', 'timer'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['timer', 'clock', 'kitchen'],
  },
  {
    emoji: '🕰️',
    name: 'mantelpiece clock',
    keywords: ['time', 'clock', 'antique'],
    category: 'travel',
    color: '#8B4513',
    tags: ['clock', 'mantel', 'antique'],
  },
  {
    emoji: '🕐',
    name: `one o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '1:00', 'time'],
  },
  {
    emoji: '🕜',
    name: 'one-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '1:30', 'time'],
  },
  {
    emoji: '🕑',
    name: `two o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '2:00', 'time'],
  },
  {
    emoji: '🕝',
    name: 'two-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '2:30', 'time'],
  },
  {
    emoji: '🕒',
    name: `three o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '3:00', 'time'],
  },
  {
    emoji: '🕞',
    name: 'three-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '3:30', 'time'],
  },
  {
    emoji: '🕓',
    name: `four o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '4:00', 'time'],
  },
  {
    emoji: '🕟',
    name: 'four-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '4:30', 'time'],
  },
  {
    emoji: '🕔',
    name: `five o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '5:00', 'time'],
  },
  {
    emoji: '🕠',
    name: 'five-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '5:30', 'time'],
  },
  {
    emoji: '🕕',
    name: `six o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '6:00', 'time'],
  },
  {
    emoji: '🕡',
    name: 'six-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '6:30', 'time'],
  },
  {
    emoji: '🕖',
    name: `seven o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '7:00', 'time'],
  },
  {
    emoji: '🕢',
    name: 'seven-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '7:30', 'time'],
  },
  {
    emoji: '🕗',
    name: `eight o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '8:00', 'time'],
  },
  {
    emoji: '🕣',
    name: 'eight-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '8:30', 'time'],
  },
  {
    emoji: '🕘',
    name: `nine o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '9:00', 'time'],
  },
  {
    emoji: '🕤',
    name: 'nine-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '9:30', 'time'],
  },
  {
    emoji: '🕙',
    name: `ten o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '10:00', 'time'],
  },
  {
    emoji: '🕥',
    name: 'ten-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '10:30', 'time'],
  },
  {
    emoji: '🕚',
    name: `eleven o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '11:00', 'time'],
  },
  {
    emoji: '🕦',
    name: 'eleven-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '11:30', 'time'],
  },
  {
    emoji: '🕛',
    name: `twelve o'clock`,
    keywords: ['time', 'noon', 'midnight'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '12:00', 'time'],
  },
  {
    emoji: '🕧',
    name: 'twelve-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['clock', '12:30', 'time'],
  },

  // Sky and weather
  {
    emoji: '🌍',
    name: 'earth globe europe-africa',
    keywords: ['globe', 'world', 'international'],
    category: 'travel',
    color: '#4169E1',
    tags: ['earth', 'globe', 'europe-africa'],
  },
  {
    emoji: '🌎',
    name: 'earth globe americas',
    keywords: ['globe', 'world', 'usa'],
    category: 'travel',
    color: '#4169E1',
    tags: ['earth', 'globe', 'americas'],
  },
  {
    emoji: '🌏',
    name: 'earth globe asia-australia',
    keywords: ['globe', 'world', 'east'],
    category: 'travel',
    color: '#4169E1',
    tags: ['earth', 'globe', 'asia'],
  },
  {
    emoji: '🌐',
    name: 'globe with meridians',
    keywords: ['earth', 'international', 'world'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['globe', 'world', 'meridians'],
  },
  {
    emoji: '🗺️',
    name: 'world map',
    keywords: ['location', 'direction', 'map'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['map', 'world', 'geography'],
  },
  {
    emoji: '🗿',
    name: 'moai',
    keywords: ['stone', 'easter island', 'statue'],
    category: 'travel',
    color: '#696969',
    tags: ['moai', 'easter-island', 'statue'],
  },
  {
    emoji: '🧭',
    name: 'compass',
    keywords: ['magnetic', 'navigation', 'orienteering'],
    category: 'travel',
    color: '#DC143C',
    tags: ['compass', 'navigation', 'direction'],
  },

  // Weather phenomena
  {
    emoji: '🌞',
    name: 'sun with face',
    keywords: ['nature', 'morning', 'sky'],
    category: 'travel',
    color: '#FFD700',
    tags: ['sun', 'face', 'sunny'],
  },
  {
    emoji: '☀️',
    name: 'sun',
    keywords: ['weather', 'nature', 'brightness'],
    category: 'travel',
    color: '#FFD700',
    tags: ['sun', 'sunny', 'weather'],
  },
  {
    emoji: '🌝',
    name: 'full moon face',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
    tags: ['moon', 'face', 'full'],
  },
  {
    emoji: '🌛',
    name: 'first quarter moon face',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
    tags: ['moon', 'face', 'quarter'],
  },
  {
    emoji: '🌜',
    name: 'last quarter moon face',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
    tags: ['moon', 'face', 'quarter'],
  },
  {
    emoji: '🌚',
    name: 'new moon face',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#696969',
    tags: ['moon', 'face', 'new'],
  },
  {
    emoji: '🌕',
    name: 'full moon',
    keywords: ['nature', 'yellow', 'twilight'],
    category: 'travel',
    color: '#F0E68C',
    tags: ['moon', 'full', 'night'],
  },
  {
    emoji: '🌖',
    name: 'waning gibbous moon',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
    tags: ['moon', 'waning', 'gibbous'],
  },
  {
    emoji: '🌗',
    name: 'last quarter moon',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
    tags: ['moon', 'quarter', 'last'],
  },
  {
    emoji: '🌘',
    name: 'waning crescent moon',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
    tags: ['moon', 'waning', 'crescent'],
  },
  {
    emoji: '🌑',
    name: 'new moon',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#696969',
    tags: ['moon', 'new', 'dark'],
  },
  {
    emoji: '🌒',
    name: 'waxing crescent moon',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
    tags: ['moon', 'waxing', 'crescent'],
  },
  {
    emoji: '🌓',
    name: 'first quarter moon',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
    tags: ['moon', 'quarter', 'first'],
  },
  {
    emoji: '🌔',
    name: 'waxing gibbous moon',
    keywords: ['nature', 'night', 'sky'],
    category: 'travel',
    color: '#F0E68C',
    tags: ['moon', 'waxing', 'gibbous'],
  },
  {
    emoji: '🌙',
    name: 'crescent moon',
    keywords: ['night', 'sleep', 'sky'],
    category: 'travel',
    color: '#F0E68C',
    tags: ['moon', 'crescent', 'night'],
  },
  {
    emoji: '🌡️',
    name: 'thermometer',
    keywords: ['weather', 'temperature', 'hot'],
    category: 'travel',
    color: '#DC143C',
    tags: ['thermometer', 'temperature', 'weather'],
  },
  {
    emoji: '☁️',
    name: 'cloud',
    keywords: ['weather', 'nature', 'sky'],
    category: 'travel',
    color: '#D3D3D3',
    tags: ['cloud', 'weather', 'sky'],
  },
  {
    emoji: '⛅',
    name: 'sun behind cloud',
    keywords: ['weather', 'nature', 'cloudy'],
    category: 'travel',
    color: '#FFD700',
    tags: ['partly-cloudy', 'sun', 'cloud'],
  },
  {
    emoji: '⛈️',
    name: 'cloud with lightning and rain',
    keywords: ['weather', 'lightning', 'thunder'],
    category: 'travel',
    color: '#696969',
    tags: ['storm', 'thunder', 'lightning'],
  },
  {
    emoji: '🌤️',
    name: 'sun behind small cloud',
    keywords: ['weather', 'nature', 'cloudy'],
    category: 'travel',
    color: '#FFD700',
    tags: ['mostly-sunny', 'weather', 'cloud'],
  },
  {
    emoji: '🌥️',
    name: 'sun behind large cloud',
    keywords: ['weather', 'nature', 'cloudy'],
    category: 'travel',
    color: '#D3D3D3',
    tags: ['mostly-cloudy', 'weather', 'sun'],
  },
  {
    emoji: '🌦️',
    name: 'sun behind rain cloud',
    keywords: ['weather', 'nature', 'cloudy'],
    category: 'travel',
    color: '#4682B4',
    tags: ['sun-shower', 'rain', 'weather'],
  },
  {
    emoji: '🌧️',
    name: 'cloud with rain',
    keywords: ['weather', 'rain', 'cloud'],
    category: 'travel',
    color: '#4682B4',
    tags: ['rain', 'weather', 'cloud'],
  },
  {
    emoji: '🌨️',
    name: 'cloud with snow',
    keywords: ['weather', 'cold', 'winter'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['snow', 'weather', 'winter'],
  },
  {
    emoji: '🌩️',
    name: 'cloud with lightning',
    keywords: ['weather', 'thunder', 'lightning'],
    category: 'travel',
    color: '#FFD700',
    tags: ['lightning', 'thunder', 'storm'],
  },
  {
    emoji: '🌪️',
    name: 'tornado',
    keywords: ['weather', 'cyclone', 'twister'],
    category: 'travel',
    color: '#696969',
    tags: ['tornado', 'cyclone', 'twister'],
  },
  {
    emoji: '🌫️',
    name: 'fog',
    keywords: ['weather', 'fog', 'mist'],
    category: 'travel',
    color: '#D3D3D3',
    tags: ['fog', 'mist', 'weather'],
  },
  {
    emoji: '🌬️',
    name: 'wind face',
    keywords: ['face', 'weather', 'blow'],
    category: 'travel',
    color: '#87CEEB',
    tags: ['wind', 'blowing', 'face'],
  },
  {
    emoji: '🌀',
    name: 'cyclone',
    keywords: ['weather', 'swirl', 'blue'],
    category: 'travel',
    color: '#4169E1',
    tags: ['cyclone', 'spiral', 'hurricane'],
  },
  {
    emoji: '🌈',
    name: 'rainbow',
    keywords: ['nature', 'happy', 'unicorn'],
    category: 'travel',
    color: '#FF0000',
    tags: ['rainbow', 'colorful', 'weather'],
  },
  {
    emoji: '⚡',
    name: 'high voltage',
    keywords: ['thunder', 'weather', 'lightning'],
    category: 'travel',
    color: '#FFD700',
    tags: ['lightning', 'electric', 'voltage'],
  },
  {
    emoji: '❄️',
    name: 'snowflake',
    keywords: ['winter', 'season', 'cold'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['snowflake', 'winter', 'cold'],
  },
  {
    emoji: '☃️',
    name: 'snowman',
    keywords: ['winter', 'season', 'cold'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['snowman', 'winter', 'snow'],
  },
  {
    emoji: '⛄',
    name: 'snowman without snow',
    keywords: ['winter', 'season', 'cold'],
    category: 'travel',
    color: '#F5F5F5',
    tags: ['snowman', 'winter', 'simple'],
  },
  {
    emoji: '☄️',
    name: 'comet',
    keywords: ['space', 'meteor', 'asteroid'],
    category: 'travel',
    color: '#FF8C00',
    tags: ['comet', 'space', 'meteor'],
  },
  {
    emoji: '🔥',
    name: 'fire',
    keywords: ['hot', 'cook', 'flame'],
    category: 'travel',
    color: '#FF4500',
    tags: ['fire', 'hot', 'flame'],
  },
  {
    emoji: '💧',
    name: 'droplet',
    keywords: ['water', 'drip', 'faucet'],
    category: 'travel',
    color: '#4682B4',
    tags: ['droplet', 'water', 'drop'],
  },
  {
    emoji: '🌊',
    name: 'water wave',
    keywords: ['sea', 'water', 'wave'],
    category: 'travel',
    color: '#4682B4',
    tags: ['wave', 'ocean', 'water'],
  },

  // Space
  {
    emoji: '⭐',
    name: 'star',
    keywords: ['night', 'yellow', 'star'],
    category: 'travel',
    color: '#FFD700',
    tags: ['star', 'night', 'sky'],
  },
  {
    emoji: '🌟',
    name: 'glowing star',
    keywords: ['night', 'awesome', 'good'],
    category: 'travel',
    color: '#FFD700',
    tags: ['star', 'glowing', 'bright'],
  },
  {
    emoji: '🌠',
    name: 'shooting star',
    keywords: ['night', 'photo', 'wish'],
    category: 'travel',
    color: '#FFD700',
    tags: ['shooting-star', 'wish', 'meteor'],
  },
  {
    emoji: '🌌',
    name: 'milky way',
    keywords: ['photo', 'space', 'stars'],
    category: 'travel',
    color: '#4B0082',
    tags: ['galaxy', 'milky-way', 'space'],
  },
  {
    emoji: '☄️',
    name: 'comet',
    keywords: ['space', 'meteor', 'asteroid'],
    category: 'travel',
    color: '#FF8C00',
    tags: ['comet', 'space', 'shooting'],
  },
];

