import type { Emoji } from '../../schema';

// Generated from OpenMoji dataset - 218 emojis
// Unicode versions up to 15.1 + OpenMoji extras
export const travelEmojisAll: Omit<Emoji, 'sentiment'>[] = [
  {
    emoji: '🌍️',
    name: 'globe showing europe-africa',
    keywords: ['africa', 'earth', 'europe', 'europe-africa', 'globe', 'showing', 'world'],
    category: 'travel',
    subcategory: 'place-map',
    unicode: '1F30D',
    version: '0.7',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌎️',
    name: 'globe showing americas',
    keywords: ['americas', 'earth', 'globe', 'showing', 'world'],
    category: 'travel',
    subcategory: 'place-map',
    unicode: '1F30E',
    version: '0.7',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌏️',
    name: 'globe showing asia-australia',
    keywords: ['asia', 'asia-australia', 'australia', 'earth', 'globe', 'showing', 'world'],
    category: 'travel',
    subcategory: 'place-map',
    unicode: '1F30F',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌐',
    name: 'globe with meridians',
    keywords: ['earth', 'globe', 'internet', 'meridians', 'web', 'world', 'worldwide'],
    category: 'travel',
    subcategory: 'place-map',
    unicode: '1F310',
    version: '1',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗺️',
    name: 'world map',
    keywords: ['map', 'world'],
    category: 'travel',
    subcategory: 'place-map',
    unicode: '1F5FA',
    version: '0.7',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗾',
    name: 'map of japan',
    keywords: ['japan', 'map'],
    category: 'travel',
    subcategory: 'place-map',
    unicode: '1F5FE',
    version: '0.6',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧭',
    name: 'compass',
    keywords: ['direction', 'magnetic', 'navigation', 'orienteering'],
    category: 'travel',
    subcategory: 'place-map',
    unicode: '1F9ED',
    version: '11',
    color: '#4169E1',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏔️',
    name: 'snow-capped mountain',
    keywords: ['cold', 'mountain', 'snow', 'snow-capped'],
    category: 'travel',
    subcategory: 'place-geographic',
    unicode: '1F3D4',
    version: '0.7',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛰️',
    name: 'mountain',
    keywords: ['mountain'],
    category: 'travel',
    subcategory: 'place-geographic',
    unicode: '26F0',
    version: '0.7',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌋',
    name: 'volcano',
    keywords: ['eruption', 'mountain', 'nature'],
    category: 'travel',
    subcategory: 'place-geographic',
    unicode: '1F30B',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗻',
    name: 'mount fuji',
    keywords: ['fuji', 'mount', 'mountain', 'nature'],
    category: 'travel',
    subcategory: 'place-geographic',
    unicode: '1F5FB',
    version: '0.6',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏕️',
    name: 'camping',
    keywords: ['camping'],
    category: 'travel',
    subcategory: 'place-geographic',
    unicode: '1F3D5',
    version: '0.7',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏖️',
    name: 'beach with umbrella',
    keywords: ['beach', 'umbrella'],
    category: 'travel',
    subcategory: 'place-geographic',
    unicode: '1F3D6',
    version: '0.7',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏜️',
    name: 'desert',
    keywords: ['desert'],
    category: 'travel',
    subcategory: 'place-geographic',
    unicode: '1F3DC',
    version: '0.7',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏝️',
    name: 'desert island',
    keywords: ['desert', 'island'],
    category: 'travel',
    subcategory: 'place-geographic',
    unicode: '1F3DD',
    version: '0.7',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏞️',
    name: 'national park',
    keywords: ['national', 'park'],
    category: 'travel',
    subcategory: 'place-geographic',
    unicode: '1F3DE',
    version: '0.7',
    color: '#228B22',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏟️',
    name: 'stadium',
    keywords: ['stadium'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3DF',
    version: '0.7',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏛️',
    name: 'classical building',
    keywords: ['building', 'classical'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3DB',
    version: '0.7',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏗️',
    name: 'building construction',
    keywords: ['building', 'construction', 'crane'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3D7',
    version: '0.7',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧱',
    name: 'brick',
    keywords: ['bricks', 'clay', 'mortar', 'wall'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F9F1',
    version: '11',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪨',
    name: 'rock',
    keywords: ['boulder', 'heavy', 'solid', 'stone', 'tough'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1FAA8',
    version: '13',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪵',
    name: 'wood',
    keywords: ['log', 'lumber', 'timber'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1FAB5',
    version: '13',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛖',
    name: 'hut',
    keywords: ['home', 'house', 'roundhouse', 'shelter', 'yurt'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F6D6',
    version: '13',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏘️',
    name: 'houses',
    keywords: ['house'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3D8',
    version: '0.7',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏚️',
    name: 'derelict house',
    keywords: ['derelict', 'home', 'house'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3DA',
    version: '0.7',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏠️',
    name: 'house',
    keywords: ['building', 'country', 'heart', 'home', 'ranch', 'settle', 'simple', 'suburban', 'suburbia', 'where'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3E0',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🏡',
    name: 'house with garden',
    keywords: ['building', 'country', 'garden', 'heart', 'home', 'house', 'ranch', 'settle', 'simple', 'suburban', 'suburbia', 'where'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3E1',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🏢',
    name: 'office building',
    keywords: ['building', 'city', 'cubical', 'job', 'office'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3E2',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏣',
    name: 'japanese post office',
    keywords: ['building', 'japanese', 'office', 'post'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3E3',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏤',
    name: 'post office',
    keywords: ['building', 'european', 'office', 'post'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3E4',
    version: '1',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏥',
    name: 'hospital',
    keywords: ['building', 'doctor', 'medicine'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3E5',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏦',
    name: 'bank',
    keywords: ['building'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3E6',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏨',
    name: 'hotel',
    keywords: ['building'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3E8',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏩',
    name: 'love hotel',
    keywords: ['building', 'hotel', 'love'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3E9',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🏪',
    name: 'convenience store',
    keywords: ['24', 'building', 'convenience', 'hours', 'store'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3EA',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏫',
    name: 'school',
    keywords: ['building'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3EB',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏬',
    name: 'department store',
    keywords: ['building', 'department', 'store'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3EC',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏭️',
    name: 'factory',
    keywords: ['building'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3ED',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏯',
    name: 'japanese castle',
    keywords: ['building', 'castle', 'japanese'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3EF',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏰',
    name: 'castle',
    keywords: ['building', 'european'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F3F0',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💒',
    name: 'wedding',
    keywords: ['chapel', 'hitched', 'nuptials', 'romance'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F492',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗼',
    name: 'tokyo tower',
    keywords: ['tokyo', 'tower'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F5FC',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🗽',
    name: 'statue of liberty',
    keywords: ['liberty', 'new', 'ny', 'nyc', 'statue', 'york'],
    category: 'travel',
    subcategory: 'place-building',
    unicode: '1F5FD',
    version: '0.6',
    color: '#A0522D',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛪️',
    name: 'church',
    keywords: ['bless', 'chapel', 'christian', 'cross', 'religion'],
    category: 'travel',
    subcategory: 'place-religious',
    unicode: '26EA',
    version: '0.6',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕌',
    name: 'mosque',
    keywords: ['islam', 'masjid', 'muslim', 'religion'],
    category: 'travel',
    subcategory: 'place-religious',
    unicode: '1F54C',
    version: '1',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛕',
    name: 'hindu temple',
    keywords: ['hindu', 'temple'],
    category: 'travel',
    subcategory: 'place-religious',
    unicode: '1F6D5',
    version: '12',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕍',
    name: 'synagogue',
    keywords: ['jew', 'jewish', 'judaism', 'religion', 'temple'],
    category: 'travel',
    subcategory: 'place-religious',
    unicode: '1F54D',
    version: '1',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛩️',
    name: 'shinto shrine',
    keywords: ['religion', 'shinto', 'shrine'],
    category: 'travel',
    subcategory: 'place-religious',
    unicode: '26E9',
    version: '0.7',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕋',
    name: 'kaaba',
    keywords: ['hajj', 'islam', 'muslim', 'religion', 'umrah'],
    category: 'travel',
    subcategory: 'place-religious',
    unicode: '1F54B',
    version: '1',
    color: '#DAA520',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛲️',
    name: 'fountain',
    keywords: ['fountain'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '26F2',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛺️',
    name: 'tent',
    keywords: ['camping'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '26FA',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌁',
    name: 'foggy',
    keywords: ['fog'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '1F301',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌃',
    name: 'night with stars',
    keywords: ['night', 'star', 'stars'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '1F303',
    version: '0.6',
    color: '#808080',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🏙️',
    name: 'cityscape',
    keywords: ['city'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '1F3D9',
    version: '0.7',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌄',
    name: 'sunrise over mountains',
    keywords: ['morning', 'mountains', 'over', 'sun', 'sunrise'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '1F304',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌅',
    name: 'sunrise',
    keywords: ['morning', 'nature', 'sun'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '1F305',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌆',
    name: 'cityscape at dusk',
    keywords: ['at', 'building', 'city', 'cityscape', 'dusk', 'evening', 'landscape', 'sun', 'sunset'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '1F306',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌇',
    name: 'sunset',
    keywords: ['building', 'dusk', 'sun'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '1F307',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌉',
    name: 'bridge at night',
    keywords: ['at', 'bridge', 'night'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '1F309',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '♨️',
    name: 'hot springs',
    keywords: ['hot', 'hotsprings', 'springs', 'steaming'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '2668',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎠',
    name: 'carousel horse',
    keywords: ['carousel', 'entertainment', 'horse'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '1F3A0',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛝',
    name: 'playground slide',
    keywords: ['amusement', 'park', 'play', 'playground', 'playing', 'slide', 'sliding', 'theme'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '1F6DD',
    version: '14',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎡',
    name: 'ferris wheel',
    keywords: ['amusement', 'ferris', 'park', 'theme', 'wheel'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '1F3A1',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎢',
    name: 'roller coaster',
    keywords: ['amusement', 'coaster', 'park', 'roller', 'theme'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '1F3A2',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💈',
    name: 'barber pole',
    keywords: ['barber', 'cut', 'fresh', 'haircut', 'pole', 'shave'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '1F488',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🎪',
    name: 'circus tent',
    keywords: ['circus', 'tent'],
    category: 'travel',
    subcategory: 'place-other',
    unicode: '1F3AA',
    version: '0.6',
    color: '#808080',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚂',
    name: 'locomotive',
    keywords: ['caboose', 'engine', 'railway', 'steam', 'train', 'trains', 'travel'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F682',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚃',
    name: 'railway car',
    keywords: ['car', 'electric', 'railway', 'train', 'tram', 'travel', 'trolleybus'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F683',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚄',
    name: 'high-speed train',
    keywords: ['high-speed', 'railway', 'shinkansen', 'speed', 'train'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F684',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚅',
    name: 'bullet train',
    keywords: ['bullet', 'high-speed', 'nose', 'railway', 'shinkansen', 'speed', 'train', 'travel'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F685',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚆',
    name: 'train',
    keywords: ['arrived', 'choo', 'railway'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F686',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚇️',
    name: 'metro',
    keywords: ['subway', 'travel'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F687',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚈',
    name: 'light rail',
    keywords: ['arrived', 'light', 'monorail', 'rail', 'railway'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F688',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚉',
    name: 'station',
    keywords: ['railway', 'train'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F689',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚊',
    name: 'tram',
    keywords: ['trolleybus'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F68A',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚝',
    name: 'monorail',
    keywords: ['vehicle'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F69D',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚞',
    name: 'mountain railway',
    keywords: ['car', 'mountain', 'railway', 'trip'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F69E',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚋',
    name: 'tram car',
    keywords: ['bus', 'car', 'tram', 'trolley', 'trolleybus'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F68B',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚌',
    name: 'bus',
    keywords: ['school', 'vehicle'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F68C',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚍️',
    name: 'oncoming bus',
    keywords: ['bus', 'cars', 'oncoming'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F68D',
    version: '0.7',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚎',
    name: 'trolleybus',
    keywords: ['bus', 'tram', 'trolley'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F68E',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚐',
    name: 'minibus',
    keywords: ['bus', 'drive', 'van', 'vehicle'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F690',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚑️',
    name: 'ambulance',
    keywords: ['emergency', 'vehicle'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F691',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚒',
    name: 'fire engine',
    keywords: ['engine', 'fire', 'truck'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F692',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚓',
    name: 'police car',
    keywords: ['5–0', 'car', 'cops', 'patrol', 'police'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F693',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚔️',
    name: 'oncoming police car',
    keywords: ['car', 'oncoming', 'police'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F694',
    version: '0.7',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚕',
    name: 'taxi',
    keywords: ['cab', 'cabbie', 'car', 'drive', 'vehicle', 'yellow'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F695',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚖',
    name: 'oncoming taxi',
    keywords: ['cab', 'cabbie', 'cars', 'drove', 'hail', 'oncoming', 'taxi', 'yellow'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F696',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚗',
    name: 'automobile',
    keywords: ['car', 'driving', 'vehicle'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F697',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚘️',
    name: 'oncoming automobile',
    keywords: ['automobile', 'car', 'cars', 'drove', 'oncoming', 'vehicle'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F698',
    version: '0.7',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚙',
    name: 'sport utility vehicle',
    keywords: ['car', 'drive', 'recreational', 'sport', 'sportutility', 'utility', 'vehicle'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F699',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛻',
    name: 'pickup truck',
    keywords: ['automobile', 'car', 'flatbed', 'pick-up', 'pickup', 'transportation', 'truck'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6FB',
    version: '13',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚚',
    name: 'delivery truck',
    keywords: ['car', 'delivery', 'drive', 'truck', 'vehicle'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F69A',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚛',
    name: 'articulated lorry',
    keywords: ['articulated', 'car', 'drive', 'lorry', 'move', 'semi', 'truck', 'vehicle'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F69B',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚜',
    name: 'tractor',
    keywords: ['vehicle'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F69C',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏎️',
    name: 'racing car',
    keywords: ['car', 'racing', 'zoom'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F3CE',
    version: '0.7',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🏍️',
    name: 'motorcycle',
    keywords: ['racing'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F3CD',
    version: '0.7',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛵',
    name: 'motor scooter',
    keywords: ['motor', 'scooter'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6F5',
    version: '3',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦽',
    name: 'manual wheelchair',
    keywords: ['accessibility', 'manual', 'wheelchair'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F9BD',
    version: '12',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🦼',
    name: 'motorized wheelchair',
    keywords: ['accessibility', 'motorized', 'wheelchair'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F9BC',
    version: '12',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛺',
    name: 'auto rickshaw',
    keywords: ['auto', 'rickshaw', 'tuk'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6FA',
    version: '12',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚲️',
    name: 'bicycle',
    keywords: ['bike', 'class', 'cycle', 'cycling', 'cyclist', 'gang', 'ride', 'spin', 'spinning'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6B2',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛴',
    name: 'kick scooter',
    keywords: ['kick', 'scooter'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6F4',
    version: '3',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛹',
    name: 'skateboard',
    keywords: ['board', 'skate', 'skater', 'wheels'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6F9',
    version: '11',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛼',
    name: 'roller skate',
    keywords: ['blades', 'roller', 'skate', 'skates', 'sport'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6FC',
    version: '13',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚏',
    name: 'bus stop',
    keywords: ['bus', 'busstop', 'stop'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F68F',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛣️',
    name: 'motorway',
    keywords: ['highway', 'road'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6E3',
    version: '0.7',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛤️',
    name: 'railway track',
    keywords: ['railway', 'track', 'train'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6E4',
    version: '0.7',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛢️',
    name: 'oil drum',
    keywords: ['drum', 'oil'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6E2',
    version: '0.7',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛽️',
    name: 'fuel pump',
    keywords: ['diesel', 'fuel', 'fuelpump', 'gas', 'gasoline', 'pump', 'station'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '26FD',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛞',
    name: 'wheel',
    keywords: ['car', 'circle', 'tire', 'turn', 'vehicle'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6DE',
    version: '14',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚨',
    name: 'police car light',
    keywords: ['alarm', 'alert', 'beacon', 'car', 'emergency', 'light', 'police', 'revolving', 'siren'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6A8',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚥',
    name: 'horizontal traffic light',
    keywords: ['horizontal', 'intersection', 'light', 'signal', 'stop', 'stoplight', 'traffic'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6A5',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚦',
    name: 'vertical traffic light',
    keywords: ['drove', 'intersection', 'light', 'signal', 'stop', 'stoplight', 'traffic', 'vertical'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6A6',
    version: '1',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛑',
    name: 'stop sign',
    keywords: ['octagonal', 'sign', 'stop'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6D1',
    version: '3',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚧',
    name: 'construction',
    keywords: ['barrier'],
    category: 'travel',
    subcategory: 'transport-ground',
    unicode: '1F6A7',
    version: '0.6',
    color: '#FF0000',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚓️',
    name: 'anchor',
    keywords: ['ship', 'tool'],
    category: 'travel',
    subcategory: 'transport-water',
    unicode: '2693',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛟',
    name: 'ring buoy',
    keywords: ['buoy', 'float', 'life', 'lifesaver', 'preserver', 'rescue', 'ring', 'safety', 'save', 'saver', 'swim'],
    category: 'travel',
    subcategory: 'transport-water',
    unicode: '1F6DF',
    version: '14',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛵️',
    name: 'sailboat',
    keywords: ['boat', 'resort', 'sailing', 'sea', 'yacht'],
    category: 'travel',
    subcategory: 'transport-water',
    unicode: '26F5',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛶',
    name: 'canoe',
    keywords: ['boat'],
    category: 'travel',
    subcategory: 'transport-water',
    unicode: '1F6F6',
    version: '3',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚤',
    name: 'speedboat',
    keywords: ['billionaire', 'boat', 'lake', 'luxury', 'millionaire', 'summer', 'travel'],
    category: 'travel',
    subcategory: 'transport-water',
    unicode: '1F6A4',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛳️',
    name: 'passenger ship',
    keywords: ['passenger', 'ship'],
    category: 'travel',
    subcategory: 'transport-water',
    unicode: '1F6F3',
    version: '0.7',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛴️',
    name: 'ferry',
    keywords: ['boat', 'passenger'],
    category: 'travel',
    subcategory: 'transport-water',
    unicode: '26F4',
    version: '0.7',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛥️',
    name: 'motor boat',
    keywords: ['boat', 'motor', 'motorboat'],
    category: 'travel',
    subcategory: 'transport-water',
    unicode: '1F6E5',
    version: '0.7',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚢',
    name: 'ship',
    keywords: ['boat', 'passenger', 'travel'],
    category: 'travel',
    subcategory: 'transport-water',
    unicode: '1F6A2',
    version: '0.6',
    color: '#4682B4',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '✈️',
    name: 'airplane',
    keywords: ['aeroplane', 'fly', 'flying', 'jet', 'plane', 'travel'],
    category: 'travel',
    subcategory: 'transport-air',
    unicode: '2708',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛩️',
    name: 'small airplane',
    keywords: ['aeroplane', 'airplane', 'plane', 'small'],
    category: 'travel',
    subcategory: 'transport-air',
    unicode: '1F6E9',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛫',
    name: 'airplane departure',
    keywords: ['aeroplane', 'airplane', 'check-in', 'departure', 'departures', 'plane'],
    category: 'travel',
    subcategory: 'transport-air',
    unicode: '1F6EB',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛬',
    name: 'airplane arrival',
    keywords: ['aeroplane', 'airplane', 'arrival', 'arrivals', 'arriving', 'landing', 'plane'],
    category: 'travel',
    subcategory: 'transport-air',
    unicode: '1F6EC',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪂',
    name: 'parachute',
    keywords: ['hang-glide', 'parasail', 'skydive'],
    category: 'travel',
    subcategory: 'transport-air',
    unicode: '1FA82',
    version: '12',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💺',
    name: 'seat',
    keywords: ['chair'],
    category: 'travel',
    subcategory: 'transport-air',
    unicode: '1F4BA',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚁',
    name: 'helicopter',
    keywords: ['copter', 'roflcopter', 'travel', 'vehicle'],
    category: 'travel',
    subcategory: 'transport-air',
    unicode: '1F681',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚟',
    name: 'suspension railway',
    keywords: ['railway', 'suspension'],
    category: 'travel',
    subcategory: 'transport-air',
    unicode: '1F69F',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚠',
    name: 'mountain cableway',
    keywords: ['cable', 'cableway', 'gondola', 'lift', 'mountain', 'ski'],
    category: 'travel',
    subcategory: 'transport-air',
    unicode: '1F6A0',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚡',
    name: 'aerial tramway',
    keywords: ['aerial', 'cable', 'car', 'gondola', 'ropeway', 'tramway'],
    category: 'travel',
    subcategory: 'transport-air',
    unicode: '1F6A1',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛰️',
    name: 'satellite',
    keywords: ['space'],
    category: 'travel',
    subcategory: 'transport-air',
    unicode: '1F6F0',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🚀',
    name: 'rocket',
    keywords: ['launch', 'rockets', 'space', 'travel'],
    category: 'travel',
    subcategory: 'transport-air',
    unicode: '1F680',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛸',
    name: 'flying saucer',
    keywords: ['aliens', 'extra', 'flying', 'saucer', 'terrestrial', 'ufo'],
    category: 'travel',
    subcategory: 'transport-air',
    unicode: '1F6F8',
    version: '5',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🛎️',
    name: 'bellhop bell',
    keywords: ['bell', 'bellhop', 'hotel'],
    category: 'travel',
    subcategory: 'hotel',
    unicode: '1F6CE',
    version: '0.7',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🧳',
    name: 'luggage',
    keywords: ['bag', 'packing', 'roller', 'suitcase', 'travel'],
    category: 'travel',
    subcategory: 'hotel',
    unicode: '1F9F3',
    version: '11',
    color: '#DDA0DD',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⌛️',
    name: 'hourglass done',
    keywords: ['done', 'hourglass', 'sand', 'time', 'timer'],
    category: 'travel',
    subcategory: 'time',
    unicode: '231B',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏳️',
    name: 'hourglass not done',
    keywords: ['done', 'flowing', 'hourglass', 'hours', 'not', 'sand', 'timer', 'waiting', 'yolo'],
    category: 'travel',
    subcategory: 'time',
    unicode: '23F3',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⌚️',
    name: 'watch',
    keywords: ['clock', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '231A',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏰️',
    name: 'alarm clock',
    keywords: ['alarm', 'clock', 'hours', 'hrs', 'late', 'time', 'waiting'],
    category: 'travel',
    subcategory: 'time',
    unicode: '23F0',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏱️',
    name: 'stopwatch',
    keywords: ['clock', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '23F1',
    version: '1',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⏲️',
    name: 'timer clock',
    keywords: ['clock', 'timer'],
    category: 'travel',
    subcategory: 'time',
    unicode: '23F2',
    version: '1',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕰️',
    name: 'mantelpiece clock',
    keywords: ['clock', 'mantelpiece', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F570',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕛️',
    name: 'twelve o’clock',
    keywords: ['12', '12:00', 'clock', 'o’clock', 'time', 'twelve'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F55B',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕧️',
    name: 'twelve-thirty',
    keywords: ['12', '12:30', '30', 'clock', 'thirty', 'time', 'twelve'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F567',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕐️',
    name: 'one o’clock',
    keywords: ['1', '1:00', 'clock', 'one', 'o’clock', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F550',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕜️',
    name: 'one-thirty',
    keywords: ['1', '1:30', '30', 'clock', 'one', 'thirty', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F55C',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕑️',
    name: 'two o’clock',
    keywords: ['2', '2:00', 'clock', 'o’clock', 'time', 'two'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F551',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕝️',
    name: 'two-thirty',
    keywords: ['2', '2:30', '30', 'clock', 'thirty', 'time', 'two'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F55D',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕒️',
    name: 'three o’clock',
    keywords: ['3', '3:00', 'clock', 'o’clock', 'three', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F552',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕞️',
    name: 'three-thirty',
    keywords: ['3', '30', '3:30', 'clock', 'thirty', 'three', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F55E',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕓️',
    name: 'four o’clock',
    keywords: ['4', '4:00', 'clock', 'four', 'o’clock', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F553',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕟️',
    name: 'four-thirty',
    keywords: ['30', '4', '4:30', 'clock', 'four', 'thirty', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F55F',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕔️',
    name: 'five o’clock',
    keywords: ['5', '5:00', 'clock', 'five', 'o’clock', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F554',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕠️',
    name: 'five-thirty',
    keywords: ['30', '5', '5:30', 'clock', 'five', 'thirty', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F560',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕕️',
    name: 'six o’clock',
    keywords: ['6', '6:00', 'clock', 'o’clock', 'six', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F555',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕡️',
    name: 'six-thirty',
    keywords: ['30', '6', '6:30', 'clock', 'six', 'thirty'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F561',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕖️',
    name: 'seven o’clock',
    keywords: ['0', '7', '7:00', 'clock', 'o’clock', 'seven'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F556',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕢️',
    name: 'seven-thirty',
    keywords: ['30', '7', '7:30', 'clock', 'seven', 'thirty'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F562',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕗️',
    name: 'eight o’clock',
    keywords: ['8', '8:00', 'clock', 'eight', 'o’clock', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F557',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕣️',
    name: 'eight-thirty',
    keywords: ['30', '8', '8:30', 'clock', 'eight', 'thirty', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F563',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕘️',
    name: 'nine o’clock',
    keywords: ['9', '9:00', 'clock', 'nine', 'o’clock', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F558',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕤️',
    name: 'nine-thirty',
    keywords: ['30', '9', '9:30', 'clock', 'nine', 'thirty', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F564',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕙️',
    name: 'ten o’clock',
    keywords: ['0', '10', '10:00', 'clock', 'o’clock', 'ten'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F559',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕥️',
    name: 'ten-thirty',
    keywords: ['10', '10:30', '30', 'clock', 'ten', 'thirty', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F565',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕚️',
    name: 'eleven o’clock',
    keywords: ['11', '11:00', 'clock', 'eleven', 'o’clock', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F55A',
    version: '0.6',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🕦️',
    name: 'eleven-thirty',
    keywords: ['11', '11:30', '30', 'clock', 'eleven', 'thirty', 'time'],
    category: 'travel',
    subcategory: 'time',
    unicode: '1F566',
    version: '0.7',
    color: '#FFD700',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌑',
    name: 'new moon',
    keywords: ['dark', 'moon', 'new', 'space'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F311',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌒',
    name: 'waxing crescent moon',
    keywords: ['crescent', 'dreams', 'moon', 'space', 'waxing'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F312',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌓',
    name: 'first quarter moon',
    keywords: ['first', 'moon', 'quarter', 'space'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F313',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌔',
    name: 'waxing gibbous moon',
    keywords: ['gibbous', 'moon', 'space', 'waxing'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F314',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌕️',
    name: 'full moon',
    keywords: ['full', 'moon', 'space'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F315',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌖',
    name: 'waning gibbous moon',
    keywords: ['gibbous', 'moon', 'space', 'waning'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F316',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌗',
    name: 'last quarter moon',
    keywords: ['last', 'moon', 'quarter', 'space'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F317',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌘',
    name: 'waning crescent moon',
    keywords: ['crescent', 'moon', 'space', 'waning'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F318',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌙',
    name: 'crescent moon',
    keywords: ['crescent', 'moon', 'ramadan', 'space'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F319',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌚',
    name: 'new moon face',
    keywords: ['face', 'moon', 'new', 'space'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F31A',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌛',
    name: 'first quarter moon face',
    keywords: ['face', 'first', 'moon', 'quarter', 'space'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F31B',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌜️',
    name: 'last quarter moon face',
    keywords: ['dreams', 'face', 'last', 'moon', 'quarter'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F31C',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌡️',
    name: 'thermometer',
    keywords: ['weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F321',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '☀️',
    name: 'sun',
    keywords: ['bright', 'rays', 'space', 'sunny', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '2600',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌝',
    name: 'full moon face',
    keywords: ['bright', 'face', 'full', 'moon'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F31D',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌞',
    name: 'sun with face',
    keywords: ['beach', 'bright', 'day', 'face', 'heat', 'shine', 'sun', 'sunny', 'sunshine', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F31E',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🪐',
    name: 'ringed planet',
    keywords: ['planet', 'ringed', 'saturn', 'saturnine'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1FA90',
    version: '12',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⭐️',
    name: 'star',
    keywords: ['astronomy', 'medium', 'stars', 'white'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '2B50',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🌟',
    name: 'glowing star',
    keywords: ['glittery', 'glow', 'glowing', 'night', 'shining', 'sparkle', 'star', 'win'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F31F',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🌠',
    name: 'shooting star',
    keywords: ['falling', 'night', 'shooting', 'space', 'star'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F320',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'positive' as const,
  },
  {
    emoji: '🌌',
    name: 'milky way',
    keywords: ['milky', 'space', 'way'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F30C',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '☁️',
    name: 'cloud',
    keywords: ['weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '2601',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛅️',
    name: 'sun behind cloud',
    keywords: ['behind', 'cloud', 'cloudy', 'sun', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '26C5',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛈️',
    name: 'cloud with lightning and rain',
    keywords: ['cloud', 'lightning', 'rain', 'thunder', 'thunderstorm'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '26C8',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌤️',
    name: 'sun behind small cloud',
    keywords: ['behind', 'cloud', 'sun', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F324',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌥️',
    name: 'sun behind large cloud',
    keywords: ['behind', 'cloud', 'sun', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F325',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌦️',
    name: 'sun behind rain cloud',
    keywords: ['behind', 'cloud', 'rain', 'sun', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F326',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌧️',
    name: 'cloud with rain',
    keywords: ['cloud', 'rain', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F327',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌨️',
    name: 'cloud with snow',
    keywords: ['cloud', 'cold', 'snow', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F328',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌩️',
    name: 'cloud with lightning',
    keywords: ['cloud', 'lightning', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F329',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌪️',
    name: 'tornado',
    keywords: ['cloud', 'weather', 'whirlwind'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F32A',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌫️',
    name: 'fog',
    keywords: ['cloud', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F32B',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌬️',
    name: 'wind face',
    keywords: ['blow', 'cloud', 'face', 'wind'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F32C',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌀',
    name: 'cyclone',
    keywords: ['dizzy', 'hurricane', 'twister', 'typhoon', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F300',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌈',
    name: 'rainbow',
    keywords: ['gay', 'genderqueer', 'glbt', 'glbtq', 'lesbian', 'lgbt', 'lgbtq', 'lgbtqia', 'nature', 'pride', 'queer', 'rain', 'trans', 'transgender', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F308',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🌂',
    name: 'closed umbrella',
    keywords: ['closed', 'clothing', 'rain', 'umbrella'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F302',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '☂️',
    name: 'umbrella',
    keywords: ['clothing', 'rain'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '2602',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '☔️',
    name: 'umbrella with rain drops',
    keywords: ['clothing', 'drop', 'drops', 'rain', 'umbrella', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '2614',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛱️',
    name: 'umbrella on ground',
    keywords: ['ground', 'rain', 'sun', 'umbrella'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '26F1',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⚡️',
    name: 'high voltage',
    keywords: ['danger', 'electric', 'electricity', 'high', 'lightning', 'nature', 'thunder', 'thunderbolt', 'voltage', 'zap'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '26A1',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '❄️',
    name: 'snowflake',
    keywords: ['cold', 'snow', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '2744',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '☃️',
    name: 'snowman',
    keywords: ['cold', 'man', 'snow'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '2603',
    version: '0.7',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '⛄️',
    name: 'snowman without snow',
    keywords: ['cold', 'man', 'snow', 'snowman'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '26C4',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '☄️',
    name: 'comet',
    keywords: ['space'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '2604',
    version: '1',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '🔥',
    name: 'fire',
    keywords: ['af', 'burn', 'flame', 'hot', 'lit', 'litaf', 'tool'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F525',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  },
  {
    emoji: '💧',
    name: 'droplet',
    keywords: ['cold', 'comic', 'drop', 'nature', 'sad', 'sweat', 'tear', 'water', 'weather'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F4A7',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'negative' as const,
  },
  {
    emoji: '🌊',
    name: 'water wave',
    keywords: ['nature', 'ocean', 'surf', 'surfer', 'surfing', 'water', 'wave'],
    category: 'travel',
    subcategory: 'sky-weather',
    unicode: '1F30A',
    version: '0.6',
    color: '#87CEEB',
    sentiment: 'neutral' as const,
  }
];