import type { Emoji } from '../../schema';

export const travelEmojis: Omit<Emoji, 'sentiment'>[] = [
  // Places - Maps
  {
    emoji: '🗾',
    name: 'map of japan',
    keywords: ['nation', 'country', 'japanese'],
    category: 'travel',
    color: '#90EE90',
  },
  {
    emoji: '🏔️',
    name: 'snow-capped mountain',
    keywords: ['photo', 'nature', 'environment'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '⛰️',
    name: 'mountain',
    keywords: ['photo', 'nature', 'environment'],
    category: 'travel',
    color: '#8B4513',
  },
  {
    emoji: '🌋',
    name: 'volcano',
    keywords: ['photo', 'nature', 'disaster'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🗻',
    name: 'mount fuji',
    keywords: ['photo', 'mountain', 'nature'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🏕️',
    name: 'camping',
    keywords: ['photo', 'outdoors', 'tent'],
    category: 'travel',
    color: '#228B22',
  },
  {
    emoji: '🏖️',
    name: 'beach with umbrella',
    keywords: ['weather', 'summer', 'sunny'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🏜️',
    name: 'desert',
    keywords: ['photo', 'warm', 'saharah'],
    category: 'travel',
    color: '#DEB887',
  },
  {
    emoji: '🏝️',
    name: 'desert island',
    keywords: ['photo', 'tropical', 'mojito'],
    category: 'travel',
    color: '#90EE90',
  },
  {
    emoji: '🏞️',
    name: 'national park',
    keywords: ['photo', 'environment', 'nature'],
    category: 'travel',
    color: '#228B22',
  },

  // Buildings
  {
    emoji: '🏟️',
    name: 'stadium',
    keywords: ['photo', 'place', 'sports'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🏛️',
    name: 'classical building',
    keywords: ['art', 'culture', 'history'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🏗️',
    name: 'building construction',
    keywords: ['wip', 'working', 'progress'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🧱',
    name: 'brick',
    keywords: ['bricks', 'wall', 'construction'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🪨',
    name: 'rock',
    keywords: ['stone', 'boulder', 'heavy'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🪵',
    name: 'wood',
    keywords: ['log', 'timber', 'lumber'],
    category: 'travel',
    color: '#8B4513',
  },
  {
    emoji: '🛖',
    name: 'hut',
    keywords: ['house', 'structure', 'roundhouse'],
    category: 'travel',
    color: '#8B4513',
  },
  {
    emoji: '🏘️',
    name: 'houses',
    keywords: ['buildings', 'photo', 'neighborhood'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🏚️',
    name: 'derelict house',
    keywords: ['abandon', 'evict', 'broken'],
    category: 'travel',
    color: '#8B4513',
  },
  {
    emoji: '🏠',
    name: 'house',
    keywords: ['building', 'home', 'house'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🏡',
    name: 'house with garden',
    keywords: ['home', 'plant', 'nature'],
    category: 'travel',
    color: '#90EE90',
  },
  {
    emoji: '🏢',
    name: 'office building',
    keywords: ['building', 'work', 'enterprise'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🏣',
    name: 'japanese post office',
    keywords: ['building', 'envelope', 'communication'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🏤',
    name: 'post office',
    keywords: ['building', 'email', 'communication'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🏥',
    name: 'hospital',
    keywords: ['building', 'health', 'surgery'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🏦',
    name: 'bank',
    keywords: ['building', 'money', 'sales'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🏨',
    name: 'hotel',
    keywords: ['building', 'accommodation', 'checkin'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🏩',
    name: 'love hotel',
    keywords: ['like', 'affection', 'dating'],
    category: 'travel',
    color: '#FF69B4',
  },
  {
    emoji: '🏪',
    name: 'convenience store',
    keywords: ['building', 'shopping', 'groceries'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🏫',
    name: 'school',
    keywords: ['building', 'student', 'education'],
    category: 'travel',
    color: '#8B4513',
  },
  {
    emoji: '🏬',
    name: 'department store',
    keywords: ['building', 'shopping', 'mall'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🏭',
    name: 'factory',
    keywords: ['building', 'industry', 'pollution'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🏯',
    name: 'japanese castle',
    keywords: ['photo', 'building', 'castle'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🏰',
    name: 'castle',
    keywords: ['building', 'royalty', 'history'],
    category: 'travel',
    color: '#D3D3D3',
  },
  {
    emoji: '💒',
    name: 'wedding',
    keywords: ['love', 'like', 'affection'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🗼',
    name: 'tokyo tower',
    keywords: ['photo', 'japanese', 'tokyo'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🗽',
    name: 'statue of liberty',
    keywords: ['american', 'newyork', 'liberty'],
    category: 'travel',
    color: '#90EE90',
  },

  // Religious buildings
  {
    emoji: '⛪',
    name: 'church',
    keywords: ['building', 'religion', 'christ'],
    category: 'travel',
    color: '#8B4513',
  },
  {
    emoji: '🕌',
    name: 'mosque',
    keywords: ['islam', 'worship', 'minaret'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🛕',
    name: 'hindu temple',
    keywords: ['temple', 'hindu', 'worship'],
    category: 'travel',
    color: '#FF8C00',
  },
  {
    emoji: '🕍',
    name: 'synagogue',
    keywords: ['judaism', 'worship', 'temple'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '⛩️',
    name: 'shinto shrine',
    keywords: ['temple', 'japan', 'kyoto'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🕋',
    name: 'kaaba',
    keywords: ['mecca', 'mosque', 'islam'],
    category: 'travel',
    color: '#000000',
  },

  // Other structures
  {
    emoji: '⛲',
    name: 'fountain',
    keywords: ['photo', 'summer', 'water'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '⛺',
    name: 'tent',
    keywords: ['photo', 'camping', 'outdoors'],
    category: 'travel',
    color: '#FF8C00',
  },
  {
    emoji: '🌁',
    name: 'foggy',
    keywords: ['photo', 'mountain', 'bridge'],
    category: 'travel',
    color: '#B0C4DE',
  },
  {
    emoji: '🌃',
    name: 'night with stars',
    keywords: ['evening', 'city', 'downtown'],
    category: 'travel',
    color: '#191970',
  },
  {
    emoji: '🏙️',
    name: 'cityscape',
    keywords: ['photo', 'night life', 'urban'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🌄',
    name: 'sunrise over mountains',
    keywords: ['view', 'vacation', 'photo'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🌅',
    name: 'sunrise',
    keywords: ['morning', 'view', 'vacation'],
    category: 'travel',
    color: '#FF8C00',
  },
  {
    emoji: '🌆',
    name: 'cityscape at dusk',
    keywords: ['photo', 'evening', 'sky'],
    category: 'travel',
    color: '#FF69B4',
  },
  {
    emoji: '🌇',
    name: 'sunset',
    keywords: ['photo', 'good morning', 'dawn'],
    category: 'travel',
    color: '#FF8C00',
  },
  {
    emoji: '🌉',
    name: 'bridge at night',
    keywords: ['photo', 'sanfrancisco', 'bridge'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '♨️',
    name: 'hot springs',
    keywords: ['bath', 'warm', 'relax'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🎠',
    name: 'carousel horse',
    keywords: ['photo', 'carnival', 'ride'],
    category: 'travel',
    color: '#FF69B4',
  },
  {
    emoji: '🎡',
    name: 'ferris wheel',
    keywords: ['photo', 'carnival', 'londoneye'],
    category: 'travel',
    color: '#9370DB',
  },
  {
    emoji: '🎢',
    name: 'roller coaster',
    keywords: ['carnival', 'playground', 'photo'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '💈',
    name: 'barber pole',
    keywords: ['hair', 'salon', 'style'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🎪',
    name: 'circus tent',
    keywords: ['festival', 'carnival', 'party'],
    category: 'travel',
    color: '#DC143C',
  },

  // Transportation - Ground
  {
    emoji: '🚂',
    name: 'locomotive',
    keywords: ['transportation', 'vehicle', 'train'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🚃',
    name: 'railway car',
    keywords: ['transportation', 'vehicle', 'train'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🚄',
    name: 'high-speed train',
    keywords: ['transportation', 'vehicle', 'speed'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🚅',
    name: 'bullet train',
    keywords: ['transportation', 'vehicle', 'speed'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🚆',
    name: 'train',
    keywords: ['transportation', 'vehicle', 'train'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🚇',
    name: 'metro',
    keywords: ['transportation', 'blue-square', 'mrt'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🚈',
    name: 'light rail',
    keywords: ['transportation', 'vehicle', 'train'],
    category: 'travel',
    color: '#90EE90',
  },
  {
    emoji: '🚉',
    name: 'station',
    keywords: ['transportation', 'vehicle', 'building'],
    category: 'travel',
    color: '#8B4513',
  },
  {
    emoji: '🚊',
    name: 'tram',
    keywords: ['transportation', 'vehicle', 'trolley'],
    category: 'travel',
    color: '#90EE90',
  },
  {
    emoji: '🚝',
    name: 'monorail',
    keywords: ['transportation', 'vehicle', 'train'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🚞',
    name: 'mountain railway',
    keywords: ['transportation', 'vehicle', 'train'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🚋',
    name: 'tram car',
    keywords: ['transportation', 'vehicle', 'carriage'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🚌',
    name: 'bus',
    keywords: ['car', 'vehicle', 'transportation'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🚍',
    name: 'oncoming bus',
    keywords: ['vehicle', 'transportation', 'bus'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🚎',
    name: 'trolleybus',
    keywords: ['bart', 'transportation', 'vehicle'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🚐',
    name: 'minibus',
    keywords: ['vehicle', 'car', 'transportation'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🚑',
    name: 'ambulance',
    keywords: ['health', '911', 'hospital'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🚒',
    name: 'fire engine',
    keywords: ['transportation', 'cars', 'vehicle'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🚓',
    name: 'police car',
    keywords: ['vehicle', 'cars', 'transportation'],
    category: 'travel',
    color: '#000000',
  },
  {
    emoji: '🚔',
    name: 'oncoming police car',
    keywords: ['vehicle', 'law', 'legal'],
    category: 'travel',
    color: '#000000',
  },
  {
    emoji: '🚕',
    name: 'taxi',
    keywords: ['uber', 'vehicle', 'cars'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🚖',
    name: 'oncoming taxi',
    keywords: ['vehicle', 'cars', 'uber'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🚗',
    name: 'automobile',
    keywords: ['red', 'transportation', 'vehicle'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🚘',
    name: 'oncoming automobile',
    keywords: ['car', 'vehicle', 'transportation'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🚙',
    name: 'sport utility vehicle',
    keywords: ['transportation', 'vehicle', 'suv'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🛻',
    name: 'pickup truck',
    keywords: ['car', 'transportation', 'pick-up'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🚚',
    name: 'delivery truck',
    keywords: ['cars', 'transportation', 'truck'],
    category: 'travel',
    color: '#90EE90',
  },
  {
    emoji: '🚛',
    name: 'articulated lorry',
    keywords: ['vehicle', 'cars', 'transportation'],
    category: 'travel',
    color: '#90EE90',
  },
  {
    emoji: '🚜',
    name: 'tractor',
    keywords: ['vehicle', 'car', 'farming'],
    category: 'travel',
    color: '#228B22',
  },
  {
    emoji: '🏎️',
    name: 'racing car',
    keywords: ['sports', 'race', 'fast'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🏍️',
    name: 'motorcycle',
    keywords: ['race', 'sports', 'fast'],
    category: 'travel',
    color: '#000000',
  },
  {
    emoji: '🛵',
    name: 'motor scooter',
    keywords: ['vehicle', 'vespa', 'sasha'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🦽',
    name: 'manual wheelchair',
    keywords: ['accessibility', 'wheelchair', 'manual'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🦼',
    name: 'motorized wheelchair',
    keywords: ['accessibility', 'wheelchair', 'electric'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🛺',
    name: 'auto rickshaw',
    keywords: ['move', 'transportation', 'tuk tuk'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🚲',
    name: 'bicycle',
    keywords: ['sports', 'bicycle', 'exercise'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🛴',
    name: 'kick scooter',
    keywords: ['vehicle', 'kick', 'razor'],
    category: 'travel',
    color: '#C0C0C0',
  },
  {
    emoji: '🛹',
    name: 'skateboard',
    keywords: ['board', 'skateboard', 'sport'],
    category: 'travel',
    color: '#8B4513',
  },
  {
    emoji: '🛼',
    name: 'roller skate',
    keywords: ['footwear', 'sports', 'skate'],
    category: 'travel',
    color: '#FF69B4',
  },
  {
    emoji: '🚏',
    name: 'bus stop',
    keywords: ['transportation', 'wait', 'stop'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🛣️',
    name: 'motorway',
    keywords: ['road', 'cupertino', 'interstate'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🛤️',
    name: 'railway track',
    keywords: ['train', 'transportation', 'track'],
    category: 'travel',
    color: '#8B4513',
  },
  {
    emoji: '🛢️',
    name: 'oil drum',
    keywords: ['barrell', 'oil', 'petroleum'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '⛽',
    name: 'fuel pump',
    keywords: ['gas station', 'petroleum', 'fuel'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🚨',
    name: 'police car light',
    keywords: ['police', 'ambulance', '911'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🚥',
    name: 'horizontal traffic light',
    keywords: ['transportation', 'signal', 'traffic'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🚦',
    name: 'vertical traffic light',
    keywords: ['transportation', 'driving', 'signal'],
    category: 'travel',
    color: '#90EE90',
  },
  {
    emoji: '🛑',
    name: 'stop sign',
    keywords: ['stop', 'sign', 'octagonal'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🚧',
    name: 'construction',
    keywords: ['wip', 'progress', 'caution'],
    category: 'travel',
    color: '#FF8C00',
  },

  // Transportation - Sea
  {
    emoji: '⚓',
    name: 'anchor',
    keywords: ['ship', 'ferry', 'sea'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '⛵',
    name: 'sailboat',
    keywords: ['ship', 'summer', 'transportation'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🛶',
    name: 'canoe',
    keywords: ['boat', 'paddle', 'water'],
    category: 'travel',
    color: '#8B4513',
  },
  {
    emoji: '🚤',
    name: 'speedboat',
    keywords: ['ship', 'transportation', 'vehicle'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🛳️',
    name: 'passenger ship',
    keywords: ['yacht', 'cruise', 'ferry'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '⛴️',
    name: 'ferry',
    keywords: ['ship', 'transport', 'boat'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🛥️',
    name: 'motor boat',
    keywords: ['ship', 'motorboat', 'boat'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🚢',
    name: 'ship',
    keywords: ['transportation', 'titanic', 'deploy'],
    category: 'travel',
    color: '#696969',
  },

  // Transportation - Air
  {
    emoji: '✈️',
    name: 'airplane',
    keywords: ['vehicle', 'transportation', 'flight'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🛩️',
    name: 'small airplane',
    keywords: ['flight', 'transportation', 'fly'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🛫',
    name: 'airplane departure',
    keywords: ['airport', 'flight', 'landing'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🛬',
    name: 'airplane arrival',
    keywords: ['airport', 'flight', 'boarding'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🪂',
    name: 'parachute',
    keywords: ['fly', 'glide', 'parasail'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '💺',
    name: 'seat',
    keywords: ['sit', 'airplane', 'transport'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🚁',
    name: 'helicopter',
    keywords: ['transportation', 'vehicle', 'fly'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🚟',
    name: 'suspension railway',
    keywords: ['vehicle', 'transportation', 'railway'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🚠',
    name: 'mountain cableway',
    keywords: ['transportation', 'vehicle', 'ski'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🚡',
    name: 'aerial tramway',
    keywords: ['transportation', 'vehicle', 'ski'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🛰️',
    name: 'satellite',
    keywords: ['communication', 'gps', 'orbit'],
    category: 'travel',
    color: '#C0C0C0',
  },
  {
    emoji: '🚀',
    name: 'rocket',
    keywords: ['launch', 'ship', 'staffmode'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '🛸',
    name: 'flying saucer',
    keywords: ['transportation', 'vehicle', 'ufo'],
    category: 'travel',
    color: '#C0C0C0',
  },

  // Hotel and tourism
  {
    emoji: '🛎️',
    name: 'bellhop bell',
    keywords: ['service', 'hotel', 'bell'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🧳',
    name: 'luggage',
    keywords: ['packing', 'travel', 'suitcase'],
    category: 'travel',
    color: '#8B4513',
  },

  // Time
  {
    emoji: '⌛',
    name: 'hourglass done',
    keywords: ['time', 'clock', 'oldschool'],
    category: 'travel',
    color: '#DEB887',
  },
  {
    emoji: '⏳',
    name: 'hourglass not done',
    keywords: ['oldschool', 'time', 'countdown'],
    category: 'travel',
    color: '#DEB887',
  },
  {
    emoji: '⌚',
    name: 'watch',
    keywords: ['time', 'accessories', 'apple'],
    category: 'travel',
    color: '#C0C0C0',
  },
  {
    emoji: '⏰',
    name: 'alarm clock',
    keywords: ['time', 'wake', 'morning'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '⏱️',
    name: 'stopwatch',
    keywords: ['time', 'deadline', 'racing'],
    category: 'travel',
    color: '#C0C0C0',
  },
  {
    emoji: '⏲️',
    name: 'timer clock',
    keywords: ['alarm', 'kitchen', 'timer'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕰️',
    name: 'mantelpiece clock',
    keywords: ['time', 'clock', 'antique'],
    category: 'travel',
    color: '#8B4513',
  },
  {
    emoji: '🕐',
    name: `one o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕜',
    name: 'one-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕑',
    name: `two o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕝',
    name: 'two-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕒',
    name: `three o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕞',
    name: 'three-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕓',
    name: `four o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕟',
    name: 'four-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕔',
    name: `five o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕠',
    name: 'five-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕕',
    name: `six o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕡',
    name: 'six-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕖',
    name: `seven o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕢',
    name: 'seven-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕗',
    name: `eight o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕣',
    name: 'eight-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕘',
    name: `nine o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕤',
    name: 'nine-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕙',
    name: `ten o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕥',
    name: 'ten-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕚',
    name: `eleven o'clock`,
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕦',
    name: 'eleven-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕛',
    name: `twelve o'clock`,
    keywords: ['time', 'noon', 'midnight'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🕧',
    name: 'twelve-thirty',
    keywords: ['time', 'late', 'early'],
    category: 'travel',
    color: '#F5F5F5',
  },

  // Sky and weather
  {
    emoji: '🌍',
    name: 'earth globe europe-africa',
    keywords: ['globe', 'world', 'international'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🌎',
    name: 'earth globe americas',
    keywords: ['globe', 'world', 'usa'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🌏',
    name: 'earth globe asia-australia',
    keywords: ['globe', 'world', 'east'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🌐',
    name: 'globe with meridians',
    keywords: ['earth', 'international', 'world'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🗺️',
    name: 'world map',
    keywords: ['location', 'direction', 'map'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🗿',
    name: 'moai',
    keywords: ['stone', 'easter island', 'statue'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🧭',
    name: 'compass',
    keywords: ['magnetic', 'navigation', 'orienteering'],
    category: 'travel',
    color: '#DC143C',
  },

  // Weather phenomena
  {
    emoji: '🌞',
    name: 'sun with face',
    keywords: ['nature', 'morning', 'sky'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '☀️',
    name: 'sun',
    keywords: ['weather', 'nature', 'brightness'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🌝',
    name: 'full moon face',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
  },
  {
    emoji: '🌛',
    name: 'first quarter moon face',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
  },
  {
    emoji: '🌜',
    name: 'last quarter moon face',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
  },
  {
    emoji: '🌚',
    name: 'new moon face',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🌕',
    name: 'full moon',
    keywords: ['nature', 'yellow', 'twilight'],
    category: 'travel',
    color: '#F0E68C',
  },
  {
    emoji: '🌖',
    name: 'waning gibbous moon',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
  },
  {
    emoji: '🌗',
    name: 'last quarter moon',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
  },
  {
    emoji: '🌘',
    name: 'waning crescent moon',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
  },
  {
    emoji: '🌑',
    name: 'new moon',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🌒',
    name: 'waxing crescent moon',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
  },
  {
    emoji: '🌓',
    name: 'first quarter moon',
    keywords: ['nature', 'twilight', 'planet'],
    category: 'travel',
    color: '#F0E68C',
  },
  {
    emoji: '🌔',
    name: 'waxing gibbous moon',
    keywords: ['nature', 'night', 'sky'],
    category: 'travel',
    color: '#F0E68C',
  },
  {
    emoji: '🌙',
    name: 'crescent moon',
    keywords: ['night', 'sleep', 'sky'],
    category: 'travel',
    color: '#F0E68C',
  },
  {
    emoji: '🌡️',
    name: 'thermometer',
    keywords: ['weather', 'temperature', 'hot'],
    category: 'travel',
    color: '#DC143C',
  },
  {
    emoji: '☁️',
    name: 'cloud',
    keywords: ['weather', 'nature', 'sky'],
    category: 'travel',
    color: '#D3D3D3',
  },
  {
    emoji: '⛅',
    name: 'sun behind cloud',
    keywords: ['weather', 'nature', 'cloudy'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '⛈️',
    name: 'cloud with lightning and rain',
    keywords: ['weather', 'lightning', 'thunder'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🌤️',
    name: 'sun behind small cloud',
    keywords: ['weather', 'nature', 'cloudy'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🌥️',
    name: 'sun behind large cloud',
    keywords: ['weather', 'nature', 'cloudy'],
    category: 'travel',
    color: '#D3D3D3',
  },
  {
    emoji: '🌦️',
    name: 'sun behind rain cloud',
    keywords: ['weather', 'nature', 'cloudy'],
    category: 'travel',
    color: '#4682B4',
  },
  {
    emoji: '🌧️',
    name: 'cloud with rain',
    keywords: ['weather', 'rain', 'cloud'],
    category: 'travel',
    color: '#4682B4',
  },
  {
    emoji: '🌨️',
    name: 'cloud with snow',
    keywords: ['weather', 'cold', 'winter'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '🌩️',
    name: 'cloud with lightning',
    keywords: ['weather', 'thunder', 'lightning'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🌪️',
    name: 'tornado',
    keywords: ['weather', 'cyclone', 'twister'],
    category: 'travel',
    color: '#696969',
  },
  {
    emoji: '🌫️',
    name: 'fog',
    keywords: ['weather', 'fog', 'mist'],
    category: 'travel',
    color: '#D3D3D3',
  },
  {
    emoji: '🌬️',
    name: 'wind face',
    keywords: ['face', 'weather', 'blow'],
    category: 'travel',
    color: '#87CEEB',
  },
  {
    emoji: '🌀',
    name: 'cyclone',
    keywords: ['weather', 'swirl', 'blue'],
    category: 'travel',
    color: '#4169E1',
  },
  {
    emoji: '🌈',
    name: 'rainbow',
    keywords: ['nature', 'happy', 'unicorn'],
    category: 'travel',
    color: '#FF0000',
  },
  {
    emoji: '⚡',
    name: 'high voltage',
    keywords: ['thunder', 'weather', 'lightning'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '❄️',
    name: 'snowflake',
    keywords: ['winter', 'season', 'cold'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '☃️',
    name: 'snowman',
    keywords: ['winter', 'season', 'cold'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '⛄',
    name: 'snowman without snow',
    keywords: ['winter', 'season', 'cold'],
    category: 'travel',
    color: '#F5F5F5',
  },
  {
    emoji: '☄️',
    name: 'comet',
    keywords: ['space', 'meteor', 'asteroid'],
    category: 'travel',
    color: '#FF8C00',
  },
  {
    emoji: '🔥',
    name: 'fire',
    keywords: ['hot', 'cook', 'flame'],
    category: 'travel',
    color: '#FF4500',
  },
  {
    emoji: '💧',
    name: 'droplet',
    keywords: ['water', 'drip', 'faucet'],
    category: 'travel',
    color: '#4682B4',
  },
  {
    emoji: '🌊',
    name: 'water wave',
    keywords: ['sea', 'water', 'wave'],
    category: 'travel',
    color: '#4682B4',
  },

  // Space
  {
    emoji: '⭐',
    name: 'star',
    keywords: ['night', 'yellow', 'star'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🌟',
    name: 'glowing star',
    keywords: ['night', 'awesome', 'good'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🌠',
    name: 'shooting star',
    keywords: ['night', 'photo', 'wish'],
    category: 'travel',
    color: '#FFD700',
  },
  {
    emoji: '🌌',
    name: 'milky way',
    keywords: ['photo', 'space', 'stars'],
    category: 'travel',
    color: '#4B0082',
  },
  {
    emoji: '☄️',
    name: 'comet',
    keywords: ['space', 'meteor', 'asteroid'],
    category: 'travel',
    color: '#FF8C00',
  },
];
