# Top-level configuration
"$schema" = "../../../node_modules/wrangler/config-schema.json"
name = "vibechecc"
main = "./.output/server/index.mjs"
compatibility_date = "2025-07-01"
compatibility_flags = [ "nodejs_compat" ]

# TanStack Start static assets
[assets]
directory = "./.output/public"

[observability]
enabled = true

# Production Environment
[env.production]
name = "vibechecc-production-frontend"
# Secrets should be set via `npx wrangler secret put --env production`

# Development Environment
[env.development]
name = "vibechecc-development-frontend"
# Secrets should be set via `npx wrangler secret put --env development`