# .github/workflows/deploy-cloudflare.yml
name: Deploy vibechecc to Cloudflare

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    permissions:
      contents: read
      id-token: write # Required for OIDC if you use it

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine Environment
        id: get-env
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" == "dev" ]; then
            echo "environment=development" >> $GITHUB_OUTPUT
          fi

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Cache Bun dependencies
        uses: useblacksmith/cache@v5
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '3'
          # This tells wrangler which environment in wrangler.toml to use
          command: 'deploy --env ${{ steps.get-env.outputs.environment }}'
