name: Deploy Convex

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-convex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g bun
      - run: bun install
      - name: Deploy Convex
        run: |
          # This is a placeholder for the actual Convex deployment command
          echo "Deploying Convex..."
          # bunx convex deploy
