name: Deploy Convex

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-convex:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Cache Bun dependencies
        uses: useblacksmith/cache@v5
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Deploy Convex
        run: |
          # This is a placeholder for the actual Convex deployment command
          echo "Deploying Convex..."
          # bunx convex deploy
