name: PR Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  pr-cleanup:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Cache Terraform plugins
        uses: useblacksmith/cache@v5
        with:
          path: |
            ~/.terraform.d/plugin-cache
            terraform/environments/ephemeral/.terraform
          key: ${{ runner.os }}-terraform-ephemeral-${{ hashFiles('terraform/**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-ephemeral-
            ${{ runner.os }}-terraform-

      - name: Configure Cloudflare credentials for R2 state storage
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
        run: echo "Cloudflare credentials configured for Terraform state storage"

      - name: Terraform Destroy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
        run: |
          terraform -chdir=terraform/environments/ephemeral init
          terraform -chdir=terraform/environments/ephemeral destroy -auto-approve -var="pr_number=${{ github.event.number }}" -var="cloudflare_account_id=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" -var="cloudflare_zone_id=${{ secrets.CLOUDFLARE_ZONE_ID }}"
